var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.ch = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>接受浏览器请求将数据存储在本地，并刷新页面."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "装入配置文件出错."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "控制 '{0}' 没有 launch 方法。你确定它是 Ext.app.Controller 的扩充吗？"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "该数值格式错误:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "该值不是有效的邮件地址:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "该值不可接受:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "该值不在可接受的列表中:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "该值为错误的长度:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "此值必须呈现:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "添加"},
        {key1: "Common.control.Camera", key2: "Close", value: "关闭"},
        {key1: "Common.control.Camera", key2: "Photo", value: "照片"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "取消"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "清除"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "完成"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "正在加载..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "请纠正下面的错误:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "扫描出错"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "完成"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "无数据显示: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "应用"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "取消"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "取消"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "没有{0}可显示"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "请求"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "小时"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "分钟"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "取消"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "调入第 {0} 个，共 {1}个"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "大厦"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "大厦"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "联系人"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "名字"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "姓(L)"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "名称:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "联系人"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "联系人"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "部门"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "部门:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "部门"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "业务部"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "业务部:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "业务部"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "业务部"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "业务部:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "业务部"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "电子邮件"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "邮件:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "员工"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "员工"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "员工级别"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "设备"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "设备编码"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "设备规格"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "设备:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "设备规格"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "设备规格"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "大厦:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "楼层"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "楼层:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "大厦:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "楼层"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "楼层:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "楼层:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "楼层"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "取消"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "问题类型"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "不动产"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "不动产"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "不动产:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "大厦/楼层:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "房间"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "房间:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "房间"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "类别:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "房间类别"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "房间类别"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "大厦:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "楼层"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "楼层:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "楼层:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "房间"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "房间"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "房间:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "房间:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "房间"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "房间标准"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "标准"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "类别:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "房间类别"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "房间类型"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "房间类型"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "类型:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "街区"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "街区"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "街区:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "街区"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "没有前期的查找."},
        {key1: "Common.control.Signature", key2: "Clear", value: "清除"},
        {key1: "Common.control.Signature", key2: "Done", value: "完成"},
        {key1: "Common.control.Signature", key2: "Signature", value: "签字"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "当扩充 Common.controller.NavigationController 类时，需要提供一个 mainView ref config"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "取消"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "保存"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "你要继续？"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "推出连接设备出错. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "登出并不删除应用数据.<br>你需要重新注册设备从而再次使用该应用."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "注册"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "注册失败"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "设备注册服务不能使用，移动服务可能没有在网络中心激活"},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "模型 [{0}] 不存在."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "无法扫描条码"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "拒绝察看地点信息"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "没有位置"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "位置超时"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "未知位置错误"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "显示文档时出错"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "显示文档"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "下载文件"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "功能在桌面环境不可用."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "字段不存在"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "文件 {0} 无法显示在本设备."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "文件 {0} 在桌面模式无法显示."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "移除文档"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "字段变更，字段: {0} 新值: {1} 旧值: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "输入"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "字段 {0} 输入不能超过 {1} 字符"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "取消"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "清除"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "复制"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "完成"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "错误"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "否"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "粘贴"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "重新加载"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "房间名称"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "房间名字"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "保存图片"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "评价"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "是"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "装入更多…"},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "没有更多记录了"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "装入更多…"},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "没有更多记录了"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "该应用被升级到最新版. 正在重新装载应用."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "访问网络出错。可能网络连接慢或不可用。"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "没有连接到网络"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "没有从服务器收到数据"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "超时"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "未知错误"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "注册设备出错。"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "提取用户信息出错."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "设置进程语言出错."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "启动用户进程出错."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "登录错"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "获取表格定义出错。"},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "设备没有注册."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Workflow toJSON. Date objects 不允许用 Workflow Rules 来配置。"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "执行工作流规则"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Workflow rule 失败:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "应用预选项"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "大厦"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "原因类型"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "联系人"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "技工"},
        {key1: "Common.store.Departments", key2: "Departments", value: "部门"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "业务部"},
        {key1: "Common.store.Employees", key2: "Employees", value: "员工"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "员工级别"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "设备"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "设备规格"},
        {key1: "Common.store.Floors", key2: "Floors", value: "楼层"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "受伤区域"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "受伤类型"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "事故类型"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "平面图组"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "平面图类型"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "问题类型"},
        {key1: "Common.store.Projects", key2: "Projects", value: "项目"},
        {key1: "Common.store.Properties", key2: "Properties", value: "属性"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "数据库错误:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "没有数据库表变更. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "字段: [{0}] 缺省值没有更新"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "更新缺省值: 字段 [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Sqlite Proxy 出错"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "创建操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "销毁操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "读操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "更新操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "打开数据库出错: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "数据库错误 [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "数据库错误 SqliteView proxy 问题."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView 是只读的，不支持删除记录操作"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView 是只读的，不支持更新记录操作"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqlliteView是只读的，不支持创建新记录操作"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "数据库不包含所需要的Sqllite视图 {0} 的表定义"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "维修类型"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "房间类别"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "房间"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "房间标准"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "房间类型"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "房间用途"},
        {key1: "Common.store.Sites", key2: "Sites", value: "街区"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "文件找不到"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "同步"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "下载"},
        {key1: "Common.sync.Manager", key2: "Error", value: "错误"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "输入的值无法转换为 Common.type.Date 类型"},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "输入的值无法转换为 Common.type.Integer 类型"},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "输入的值无法转换为 Common.type.Time 类型"},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "输入的值无法转换为 Common.type.Timestamp 类型"},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "应用的偏好参数没有装入"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "运行在浏览器方式. 停止文件系统读取"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "运行于 Chrome 或 WebView. 停止文件系统读取"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "中止文件访问"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "此文件已存在"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "文件编码错误"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "文件错误"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "文件处于无效状态"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "不允许修改文件"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "文件超过配额"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "文件安全错误"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "文件类型不匹配错误"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "文件未找到"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "文件不可读"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "无效的文件修改错误"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "没有连接到网络"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "没有网络"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "下载背景数据"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "错误"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "App Preferences store 没有载入. 无法读取 preferences"},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "M"},
        {key1: "Common.util.Units", key2: "sq ft", value: "平方英尺"},
        {key1: "Common.util.Units", key2: "sq m", value: "平方米"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "用户基本情况信息得不到. 请点击同步获取用户基本状况信息."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "同步的时候删除"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "显示"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "文档"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "没有文档"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "第 {0} ，共 {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1/ x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "该视图相关的 Model class 名称应该在 model property 中提供"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "该视图相关的 Store class 的 store id 必须在storeId property 中提供"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "清除"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "筛选"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "返回"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "保存"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "字段"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "标识"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "长度(Bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "同步信息"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "表格"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "下列 Web Central 字段值没有写入客户数据库，因为数据大小超过数据库定义"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "设置查询条件"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Date Updated", value: "更新时间"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Edited By", value: "最近编辑被"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Inventoried", value: "最后盘点"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle", value: "走廊"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code:", value: "过道:"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisles", value: "走廊"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Name", value: "名称"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle/Cabinet/Shelf:", value: "过道/置物柜/货架:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code", value: "容器"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code:", value: "容器:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bins", value: "容器"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Cabinet Code", value: "置物柜"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Shelf Code", value: "货架编号"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code:", value: "过道:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinet Code", value: "置物柜"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "cabinet Code:", value: "置物柜:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinets", value: "置物柜"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building Code", value: "大厦"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building/Floor:", value: "大厦/楼层:"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Floor Code", value: "楼层"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code", value: "房间"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code:", value: "房间:"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Rooms", value: "房间"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle/Cabinet:", value: "过道/置物柜:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Cabinet Code", value: "置物柜"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code", value: "货架编号"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code:", value: "货架编号:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelves", value: "货架"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Loading...", value: "正在加载..."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No document available for selected location.", value: "选择的位置没有文档"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floor plans available.", value: "没有楼层平面图"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floors available.", value: "没有楼层"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Not all floor plans were downloaded.", value: "下载了部分楼层平面图"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Sync Material Locations", value: "同步药品地点"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "There are no buildings in the selected site.", value: "选择的街区没有大厦。"},
        {key1: "MaterialInventory.controller.Materials", key2: "Cancel", value: "取消"},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is not registered.", value: "未注册的容器"},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is registered multiple times.", value: "多次注册的容器"},
        {key1: "MaterialInventory.controller.Materials", key2: "Document unavailable", value: "无文档"},
        {key1: "MaterialInventory.controller.Materials", key2: "Downloading Document", value: "下载文件"},
        {key1: "MaterialInventory.controller.Materials", key2: "Error", value: "错误"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory", value: "清册"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory Start Date cannot be in the future", value: "库存开始日期不能是未来"},
        {key1: "MaterialInventory.controller.Materials", key2: "The container you have scanned is in a different location: {0}. Do you want to update its location as your current location: {1} or do you want to cancel the scan and navigate to a different location?", value: "你正在扫描的容器应该在另外一个地址: {0}. 你想将当前的地址更新为容器的新地址: {1} 抑或你想取消扫描并巡视其他地方?"},
        {key1: "MaterialInventory.controller.Materials", key2: "This action will save your changes on the server. If you reset the Inventory Start Date then the app will no longer highlight inventoried items. Are you sure you want to clear the Inventory Start Date?", value: "该操作将会将你的修改保存到服务器端. 如果你重置库存开始日期，程序将不再高亮库存内容。你确定要清除库存开始日期吗?"},
        {key1: "MaterialInventory.controller.Materials", key2: "Update location", value: "更新地址"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Aisle with code \\'{0}\\' not found.", value: "没找到过道 \\'{0}\\' ."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Bin with code \\'{0}\\' not found.", value: "没找到容器 \\'{0}\\' ."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Cabinet with code \\'{0}\\' not found.", value: "没找到置物柜 \\'{0}\\' ."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Close", value: "关闭"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Floor Plan", value: "加载楼层平面图"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Site Map", value: "加载街区地图"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Room with code \\'{0}\\' not found.", value: "编码为 \\'{0}\\' 的房间未找到。"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Selected building is not registered in the current site.", value: "所选大厦未注册到当前街区."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Shelf with code \\'{0}\\' not found.", value: "编码为 \\'{0}\\'的货架未找到."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Updating Lists", value: "正在更新列表"},
        {key1: "MaterialInventory.model.MaterialLocation", key2: "{0} cannot be greater than {1}.", value: "{0} 不能大于 {1}."},
        {key1: "MaterialInventory.store.Actions", key2: "Download Documents", value: "下载文档"},
        {key1: "MaterialInventory.store.MaterialData", key2: "Material Data", value: "物料数据"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Locations", value: "地点"},
        {key1: "MaterialInventory.store.MaterialMsds", key2: "Documents", value: "文档"},
        {key1: "MaterialInventory.store.prompt.ContainerCategories", key2: "Container Categories", value: "容器类别"},
        {key1: "MaterialInventory.store.prompt.ContainerTypes", key2: "Container Types", value: "容器类型"},
        {key1: "MaterialInventory.store.prompt.MaterialChemicals", key2: "Chemicals", value: "化学品"},
        {key1: "MaterialInventory.store.prompt.MaterialConstituents", key2: "Constituents", value: "委托人"},
        {key1: "MaterialInventory.store.MaterialEmployees", key2: "Employees", value: "员工"},
        {key1: "MaterialInventory.store.prompt.MaterialUnits", key2: "Material Units", value: "材料单位"},
        {key1: "MaterialInventory.store.prompt.PressureUnits", key2: "Pressure Units", value: "压力单位"},
        {key1: "MaterialInventory.store.MaterialAisles", key2: "Aisles", value: "走廊"},
        {key1: "MaterialInventory.store.MaterialBins", key2: "Bins", value: "容器"},
        {key1: "MaterialInventory.store.MaterialBuildings", key2: "Buildings", value: "大厦"},
        {key1: "MaterialInventory.store.MaterialCabinets", key2: "Cabinets", value: "置物柜"},
        {key1: "MaterialInventory.store.space.MaterialFloors", key2: "Floors", value: "楼层"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Rooms", value: "房间"},
        {key1: "MaterialInventory.store.MaterialShelves", key2: "Shelves", value: "货架"},
        {key1: "MaterialInventory.store.MaterialSites", key2: "Sites", value: "街区"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Cancel", value: "取消"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Inventory Start Date", value: "库存开始日期"},
        {key1: "MaterialInventory.view.Filter", key2: "All", value: "全部"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Category", value: "容器类别"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Type", value: "容器类型"},
        {key1: "MaterialInventory.view.Filter", key2: "Custodian", value: "管理人"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From", value: "日期 最后库存 从"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From should not be greater than Date Last Inventory To.", value: "日期 最后库存 从 不能大于日期 最后库存 到."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory To", value: "日期 最后库存 到"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From", value: "更新日期 从"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From should not be greater than Date Updated To.", value: "更新日期 从不能大于更新日期 到."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated To", value: "更新日期 到"},
        {key1: "MaterialInventory.view.Filter", key2: "Description", value: "说明"},
        {key1: "MaterialInventory.view.Filter", key2: "Display only items not inventoried", value: "仅显示未登记的项目"},
        {key1: "MaterialInventory.view.Filter", key2: "GHS Product Identifier", value: "GHS 产品检验人"},
        {key1: "MaterialInventory.view.Filter", key2: "Last Edited By", value: "最近编辑被"},
        {key1: "MaterialInventory.view.Filter", key2: "Manufacturer", value: "制造商"},
        {key1: "MaterialInventory.view.Filter", key2: "No", value: "否"},
        {key1: "MaterialInventory.view.Filter", key2: "Product Name", value: "产品名称"},
        {key1: "MaterialInventory.view.Filter", key2: "Set Filter", value: "设置查询条件"},
        {key1: "MaterialInventory.view.Filter", key2: "Yes", value: "是"},
        {key1: "MaterialInventory.view.Main", key2: "Apps", value: "移动应用"},
        {key1: "MaterialInventory.view.Main", key2: "Plan Types", value: "平面图类型"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Comments", value: "备注"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Category", value: "容器类别"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Type", value: "容器类型"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Custodian", value: "管理人"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Date Last Updated:", value: "日期 最后更新:"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Description", value: "说明"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Edit Material", value: "编辑物料"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "GHS Product Identifier", value: "GHS 产品检验人"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Manufacturer", value: "制造商"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Pressure", value: "压力"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Product Name", value: "产品名称"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Products", value: "产品"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Quantity", value: "数量"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Review Material", value: "查看材料"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Type", value: "类型"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Unit", value: "单位"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Add Material", value: "添加材料"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Hazmat", value: "有害物"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Inventory", value: "清册"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Location", value: "地点"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Materials", value: "材料"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Product Name", value: "产品名称"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Review", value: "检查"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Status", value: "状态"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle:", value: "走廊:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building Code", value: "大厦"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building:", value: "大厦:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor Code", value: "楼层"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor:", value: "楼层:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room Code", value: "房间"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room:", value: "房间:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Select Aisle Location", value: "选择过道位置"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle:", value: "走廊:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Bin:", value: "容器:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building Code", value: "大厦"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building:", value: "大厦:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet Code", value: "置物柜"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet:", value: "置物柜:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor Code", value: "楼层"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor:", value: "楼层:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room Code", value: "房间"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room:", value: "房间:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Select Bin Location", value: "选择盒子位置"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf Code", value: "货架编号"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf:", value: "货架:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle:", value: "走廊:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building Code", value: "大厦"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building:", value: "大厦:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet Code", value: "置物柜"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet:", value: "置物柜:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor Code", value: "楼层"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor:", value: "楼层:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room Code", value: "房间"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room:", value: "房间:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Select Cabinet Location", value: "选择置物柜位置"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building Code", value: "大厦"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building:", value: "大厦:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor Code", value: "楼层"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor:", value: "楼层:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room Code", value: "房间"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room:", value: "房间:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Select Room Location", value: "选择房间位置"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle Code", value: "过道:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle:", value: "走廊:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building Code", value: "大厦"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building:", value: "大厦:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet Code", value: "置物柜"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet:", value: "置物柜:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor Code", value: "楼层"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor:", value: "楼层:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room Code", value: "房间"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room:", value: "房间:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Select Shelf Location", value: "选择货架位置"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf Code", value: "货架编号"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf:", value: "货架:"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Aisles", value: "走廊"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Materials in Room", value: "屋里的物料"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "No aisles identified.", value: "未定义过道"},
        {key1: "MaterialInventory.view.space.BinList", key2: "Bins", value: "容器"},
        {key1: "MaterialInventory.view.space.BinList", key2: "Materials on Shelf", value: "架子上的物料"},
        {key1: "MaterialInventory.view.space.BinList", key2: "No bins identified.", value: "未定义箱子"},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "Materials at Site", value: "该地址物料"},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "No buildings identified.", value: "没有选中大厦"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Cabinets", value: "置物柜"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Materials in Aisle", value: "过道里的物料"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "No cabinets identified.", value: "没找到置物柜"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Floors", value: "楼层"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Materials in Building", value: "建筑物里的物料"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "No floors identified.", value: "没发现楼层."},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plan", value: "楼层图"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Room List", value: "房间列表"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "Materials on Floor", value: "该楼层的物料"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "No rooms identified.", value: "没有标识的房间"},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Materials in Cabinet", value: "置物柜里的药品"},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "No shelves identified.", value: "未定义的隔断."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Shelves", value: "货架"},
        {key1: "MaterialInventory.view.space.Site", key2: "Buildings", value: "大厦"},
        {key1: "MaterialInventory.view.space.Site", key2: "List View", value: "大厦列表"},
        {key1: "MaterialInventory.view.space.Site", key2: "Site Plan", value: "街区图"},
        {key1: "MaterialInventory.view.space.SiteList", key2: "No sites identified.", value: "没有指定街区"},
        {key1: "MaterialInventory.view.space.SiteList", key2: "Sites", value: "街区"},
        {key1: "MaterialInventory.view.space.SiteMap", key2: "Site Plan is not available", value: "街区图不可用"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "确定要删除该目标?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "请输入文字:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "没有楼层图"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "复制"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "粘贴"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "重新加载"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "保存图片"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "你确定要删除此项?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "编辑"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "没有楼层图来画红线"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "发布日期"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "街区地图"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "楼层图"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "红线"},
        {key1: "Space.model.SpaceSurvey", key2: " can only consist of alpha-numeric characters.", value: "只能包含阿拉伯数字."},
        {key1: "Space.SpaceDownload", key2: "Download Floor Plans", value: "下载楼层图"},
        {key1: "Space.SpaceDownload", key2: "Downloaded plans for {0} floors.", value: "{0}层下载示意图."},
        {key1: "Space.SpaceDownload", key2: "Downloading Site Maps", value: "街区图下载中"},
        {key1: "Space.SpaceDownload", key2: "Floor Plan download was cancelled.", value: "楼层平面图下载已经被取消."},
        {key1: "Space.SpaceDownload", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "Space.SpaceDownload", key2: "Loading Plans for Floor {0} of {1}", value: "加载{1}中的{0}层 楼层图"},
        {key1: "Space.SpaceDownload", key2: "No active plan types found.", value: "没有可用的图层类型."},
        {key1: "Space.SpaceDownload", key2: "No Floor Plans available to download", value: "没有楼层图下载"},
        {key1: "Space.SpaceDownload", key2: "No plan types found", value: "没有图层类型"},
        {key1: "Space.SpaceDownload", key2: "Not all {0} floors of the selected buildings have floor plans available.", value: "并不是所有选定建筑物的{0}楼层都有楼层平面图."},
        {key1: "Space.SpaceDownload", key2: "Use the {0} icon to download your list of floors and buildings before downloading floor plans.", value: "下载楼层图前，请使用 {0} 符号先下载大厦和楼层列表"},
        {key1: "Space.SpaceDownload", key2: "You are going to download plans for {0} floors and this action may take some time. Proceed?", value: "你要下载 {0} 楼层的图形, 需要些时间, 继续吗?"},
        {key1: "Space.SpaceFloorPlan", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "Space.SpaceFloorPlan", key2: "Rooms", value: "房间"},
        {key1: "Space.SpaceFloorPlan", key2: "The Plan Type data is not loaded.", value: "图形类型数据没有载入."},
        {key1: "Space.SpaceSurvey", key2: "There is no Room data available for the selected Room.<br>Tap the {0} icon and select \\'Add to Survey\\' to update the Room data.", value: "选择的房间没有房间数据。<br>点击 {0} 图标并选择 \\'加到检查\\' 来更新房间数据。"},
        {key1: "Space.SpaceSurvey", key2: "There is not an active survey for this floor.<br>To initiate a survey, tap the {0} icon and select \\'Start Survey\\'.", value: "该楼层没有正在进行的检查。<br>如果想开始一个新的检查, 请点击 {0} 图标并选择 \\'开始检查\\'."},
        {key1: "Space.store.Buildings", key2: "Buildings", value: "大厦"},
        {key1: "Space.store.DownloadActions", key2: "Download Floor Plans", value: "下载楼层图"},
        {key1: "Space.store.Floors", key2: "Floors", value: "楼层"},
        {key1: "Space.store.RoomSurveys", key2: "Rooms", value: "房间"},
        {key1: "Space.store.Sites", key2: "Buildings Without a Site Assigned", value: "没有加上街区的大厦"},
        {key1: "Space.store.Sites", key2: "Sites", value: "街区"},
        {key1: "Space.store.SpaceSurveys", key2: "Surveys", value: "调查"},
        {key1: "Space.store.SurveyActions", key2: "Add to Survey", value: "加到评价项目"},
        {key1: "Space.store.SurveyActions", key2: "Close Survey", value: "关闭评价"},
        {key1: "Space.store.SurveyActions", key2: "Complete Survey", value: "完成"},
        {key1: "Space.store.SurveyActions", key2: "Start Survey", value: "开始评价"},
        {key1: "Space.store.UserGroups", key2: "User Groups", value: "用户组"},
        {key1: "Space.view.BuildingList", key2: "No buildings identified.", value: "没有选中大厦"},
        {key1: "Space.view.FloorList", key2: "Floors", value: "楼层"},
        {key1: "Space.view.FloorList", key2: "No floors identified.", value: "没发现楼层."},
        {key1: "Space.view.FloorList", key2: "Search Floors", value: "查找楼层"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plan", value: "楼层图"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "Space.view.FloorPlan", key2: "Room List", value: "房间列表"},
        {key1: "Space.view.Main", key2: "Apps", value: "移动应用"},
        {key1: "Space.view.Main", key2: "Plan Types", value: "平面图类型"},
        {key1: "Space.view.report.Configuration", key2: "Address 1", value: "地址1"},
        {key1: "Space.view.report.Configuration", key2: "Address 2", value: "地址2"},
        {key1: "Space.view.report.Configuration", key2: "Building", value: "大厦"},
        {key1: "Space.view.report.Configuration", key2: "Building Code", value: "大厦"},
        {key1: "Space.view.report.Configuration", key2: "City", value: "城市"},
        {key1: "Space.view.report.Configuration", key2: "Country", value: "国家/地区"},
        {key1: "Space.view.report.Configuration", key2: "Department", value: "部门"},
        {key1: "Space.view.report.Configuration", key2: "Division", value: "业务部"},
        {key1: "Space.view.report.Configuration", key2: "Email", value: "电子邮件"},
        {key1: "Space.view.report.Configuration", key2: "Employee ID", value: "员工 ID"},
        {key1: "Space.view.report.Configuration", key2: "Employee Information", value: "职员信息"},
        {key1: "Space.view.report.Configuration", key2: "First Name", value: "名字"},
        {key1: "Space.view.report.Configuration", key2: "Floor", value: "楼层"},
        {key1: "Space.view.report.Configuration", key2: "Floor Name", value: "层名"},
        {key1: "Space.view.report.Configuration", key2: "Last Name", value: "姓(L)"},
        {key1: "Space.view.report.Configuration", key2: "Phone", value: "电话"},
        {key1: "Space.view.report.Configuration", key2: "Room", value: "房间"},
        {key1: "Space.view.report.Configuration", key2: "Room Area", value: "房间面积"},
        {key1: "Space.view.report.Configuration", key2: "Room Category", value: "房间类别"},
        {key1: "Space.view.report.Configuration", key2: "Room Information", value: "房间信息"},
        {key1: "Space.view.report.Configuration", key2: "Room Name", value: "房间名称"},
        {key1: "Space.view.report.Configuration", key2: "Room Phone", value: "房间电话"},
        {key1: "Space.view.report.Configuration", key2: "Room Standard", value: "房间标准"},
        {key1: "Space.view.report.Configuration", key2: "Room Type", value: "房间类型"},
        {key1: "Space.view.report.Configuration", key2: "Site Code", value: "街区"},
        {key1: "Space.view.report.Configuration", key2: "State", value: "省"},
        {key1: "Space.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} 选择的楼层没有检查项.<br> 点击 {1} 图标并选择 \\'开始检查\\' 或 \\'添加检查\\' 来为该楼层创建检查项.{2}"},
        {key1: "Space.view.Site", key2: "Buildings", value: "大厦"},
        {key1: "Space.view.Site", key2: "List View", value: "大厦列表"},
        {key1: "Space.view.Site", key2: "Site Plan", value: "街区图"},
        {key1: "Space.view.SiteList", key2: "No sites identified.", value: "没有指定街区"},
        {key1: "Space.view.SiteList", key2: "Sites", value: "街区"},
        {key1: "Space.view.StartSurvey", key2: "Start", value: "开始"},
        {key1: "Space.view.StartSurvey", key2: "Start Survey", value: "开始评价"},
        {key1: "Space.view.StartSurvey", key2: "Survey Code", value: "评价编号"},
        {key1: "Space.view.StartSurvey", key2: "Survey Name", value: "评价项目"},
        {key1: "Space.view.StartSurvey", key2: "Surveyor", value: "评价员"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "大厦"},
    ]
};
