var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.nl = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Accepteer het browserverzoek om gegevens op de lokale computer op te slaan en vernieuw de pagina."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fout tijdens laden van configuratiebestand."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "De controller '{0}' heeft geen startmethode. Weet u zeker dat dit een uitbreiding is van Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Deze waarde heeft de verkeerde notatie:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Dit is geen geldig e-mailadres:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Dit is geen geldige waarde:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Deze waarde is niet opgenomen in de lijst met acceptabele waarden:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Deze waarde heeft de verkeerde lengte:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Deze waarde moet aanwezig zijn:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Koppelen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Sluiten"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Gereed"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Bezig met laden..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Corrigeer het volgende:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scanfout"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Gereed"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Geen gegevens om weer te geven voor: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Toepassen"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Geen {0} om weer te geven."},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Aanvraag"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Uren"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Item {0} van {1} laden"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Voornaam"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Achternaam"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Naam:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contactpersoon"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Afdelingscode"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Afdeling:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Divisiecode:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Divisie"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Divisie:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisies"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Medewerker"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Personeelscode"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Personeelsstandaard"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Uitrusting:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type probleem"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code van vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Vastgoedobject:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebouw/verdieping:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Ruimtestandaard"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standaards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type ruimte"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Vestigingscode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Er zijn geen eerdere zoekopdrachten opgeslagen."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.Signature", key2: "Done", value: "Gereed"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Handtekening"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Er moet een mainView-referentieconfiguratie worden verstrekt bij het uitbreiden van de Common.controller.NavigationController-klasse"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Opslaan"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Doorgaan?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Fout bij het ongedaan maken van de apparaatregistratie. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Door uit te loggen worden uw toepassingsgegevens niet verwijderd.<br>U moet het apparaat opnieuw registreren om toegang tot de apps te krijgen."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registratie"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registratie is mislukt"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "De service voor apparaatregistratie is niet beschikbaar. De Mobiel-services zijn mogelijk niet ingeschakeld in Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Model met de naam [{0}] bestaat niet."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Scannen van barcodes is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Toestemming voor toegang tot locatiegegevens geweigerd"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Positie is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Time-out voor positie"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fout onbekende positie"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Er is een fout opgetreden tijdens het weergeven van het document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Documentweergave"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Document downloaden"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Functie niet beschikbaar in de desktopomgeving."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Bestand bestaat niet"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Bestand {0} kan niet op dit apparaat worden weergegeven."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Bestand {0} kan niet worden weergegeven in de Desktop-modus."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Document verwijderen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Veld met de naam Veld gewijzigd: {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Invoer"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Invoer voor veld {0} is beperkt tot {1} tekens"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Wissen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopiëren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Gereed"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fout"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nee"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Plakken"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Ruimtenaam"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Ruimtenamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Survey"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Deze toepassing is bijgewerkt naar de laatste versie. De toepassing wordt opnieuw geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fout bij laden van netwerkservices. De netwerkverbinding kan traag of niet beschikbaar zijn"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Geen gegevens ontvangen van server"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Time-out"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Onbekende fout"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fout bij registreren van apparaat"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fout tijdens ophalen van gebruikersinformatie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fout tijdens instellen van landinstellingen voor sessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fout tijdens opstarten van gebruikerssessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fout bij eenmalige aanmelding"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fout bij ophalen van TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Apparaat is niet geregistreerd"},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Werkstroom toJSON. Datumobjecten mogen niet worden gerangschikt aan de hand van Werkstroomregels."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Werkstroomregel uitgevoerd"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Werkstroomregel mislukt:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-voorkeuren"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types oorzaken"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contactpersonen"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisies"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Medewerkers"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Personeelsstandaarden"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Letsels"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Letselcategorieën"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Incidenttypen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantype Groepen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Type problemen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projecten"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Eigenschappen"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Databasefout:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Geen wijziging aan databasetabel toegepast. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Standaardwaarde niet bijgewerkt voor veld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standaardwaarde bijwerken: veld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Fout Sqlite-proxy"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Fout Sqlite-proxy tijdens aanmaken"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Fout Sqlite-proxy tijdens vernietigen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Fout Sqlite-proxy tijdens lezen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Fout Sqlite-proxy tijdens bijwerken"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fout bij openen van database: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Databasefout [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Databasefout in SqliteView-proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView is alleen-lezen; het verwijderen van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView is alleen-lezen; het bijwerken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView is alleen-lezen; het maken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "De database bevat niet de vereiste tabeldefinities voor Sqllite-weergave {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Type reparaties"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Ruimtestandaarden"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Ruimtefuncties"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "bestand_niet_beschikbaar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchroniseren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Downloaden"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fout"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "De applicatievoorkeuren zijn niet geladen"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Uitvoeren in browsermodus. Toegang tot bestandssysteem uitgeschakeld"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Uitvoeren in Chrome of in webweergave. Toegang tot bestandssysteem ingeschakeld"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Toegang tot bestanden werd afgebroken"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Bestand bestaat al"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fout bij bestandscodering"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Bestandsfout"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Bestand is in ongeldige toestand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Bestandswijziging is niet toegestaan"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Bestandsquotum is overschreden"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fout bij bestandsbeveiliging"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fout bij vergelijken bestandstype"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Bestand is niet gevonden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Bestand is niet leesbaar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fout: ongeldige bestandswijziging"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netwerk onbereikbaar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Basisgegevens downloaden"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fout"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Het toepassingsvoorkeurenarchief is niet geladen. Kan voorkeuren niet ophalen."},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "sq ft"},
        {key1: "Common.util.Units", key2: "sq m", value: "vierkante meter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "De gegevens van het gebruikersprofiel zijn niet beschikbaar. Synchroniseer om de gegevens van het gebruikersprofiel op te halen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Verwijderen tijdens synchroniseren"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Tonen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documenten"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Geen documenten beschikbaar"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} of {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 van x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "De naam van de Model-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de modeleigenschap"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "De opslag-id van de Opslag-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de storeId-eigenschap"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Wissen"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Terug"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Opslaan"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Veld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifier"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Grootte (in bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisatieberichten"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabel"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "De volgende Web Central-veldwaarden zijn niet naar de clientdatabase geschreven omdat de hoeveelheid gegevens de databaselimiet overschrijdt"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter instellen"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Date Updated", value: "Datum bijgewerkt"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Edited By", value: "Laatst bewerkt door"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Inventoried", value: "Laatst geïnventariseerd"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle", value: "Gang"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code:", value: "Gangcode:"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisles", value: "Gangen"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Name", value: "Naam"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle/Cabinet/Shelf:", value: "Gang/Kast/Plank:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code", value: "Bakcode"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code:", value: "Bakcode:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bins", value: "Bakken"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Cabinet Code", value: "Kastcode"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Shelf Code", value: "Plankcode"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code:", value: "Gangcode:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinet Code", value: "Kastcode"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "cabinet Code:", value: "Kastcode:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinets", value: "Kasten"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building Code", value: "Gebouwcode"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building/Floor:", value: "Gebouw/verdieping:"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Floor Code", value: "Code verdieping"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code", value: "Code ruimte"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Rooms", value: "Ruimtes"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle/Cabinet:", value: "Gang/Kast:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Cabinet Code", value: "Kastcode"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code", value: "Plankcode"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code:", value: "Plankcode:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelves", value: "Planken"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Loading...", value: "Bezig met laden..."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No document available for selected location.", value: "Geen document beschikbaar voor geselecteerde locatie."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floor plans available.", value: "Geen verdiepingsplattegronden beschikbaar."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floors available.", value: "Geen verdiepingen beschikbaar."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Not all floor plans were downloaded.", value: "Niet alle verdiepingplattegronden zijn gedownload."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Sync Material Locations", value: "Materiaallocaties synchroniseren"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "There are no buildings in the selected site.", value: "Er zijn geen gebouwen in de geselecteerde locatie."},
        {key1: "MaterialInventory.controller.Materials", key2: "Cancel", value: "Annuleren"},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is not registered.", value: "Container is niet geregistreerd."},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is registered multiple times.", value: "Container is meerdere keren geregistreerd."},
        {key1: "MaterialInventory.controller.Materials", key2: "Document unavailable", value: "Document niet beschikbaar"},
        {key1: "MaterialInventory.controller.Materials", key2: "Downloading Document", value: "Document downloaden"},
        {key1: "MaterialInventory.controller.Materials", key2: "Error", value: "Fout"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory", value: "Voorraad"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory Start Date cannot be in the future", value: "Begindatum inventarisatie kan niet in de toekomst zijn"},
        {key1: "MaterialInventory.controller.Materials", key2: "The container you have scanned is in a different location: {0}. Do you want to update its location as your current location: {1} or do you want to cancel the scan and navigate to a different location?", value: "De container die u hebt gescand, bevindt zich in een andere locatie: {0}. Wilt u de locatie bijwerken naar uw huidige locatie: {1} of wilt u het scannen annuleren en naar een andere locatie gaan?"},
        {key1: "MaterialInventory.controller.Materials", key2: "This action will save your changes on the server. If you reset the Inventory Start Date then the app will no longer highlight inventoried items. Are you sure you want to clear the Inventory Start Date?", value: "Met deze actie worden uw wijzigingen op de server opgeslagen. Als u de Begindatum inventarisatie reset, worden geïnventariseerde items eer gemarkeerd weergegeven. Weet u zeker dat u de Begindatum inventarisatie wilt wissen?"},
        {key1: "MaterialInventory.controller.Materials", key2: "Update location", value: "Locatie bijwerken"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Aisle with code \\'{0}\\' not found.", value: "Gang met code \\'{0}\\' niet gevonden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Bin with code \\'{0}\\' not found.", value: "Bak met code \\'{0}\\' niet gevonden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Cabinet with code \\'{0}\\' not found.", value: "Kast met code \\'{0}\\' niet gevonden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Close", value: "Sluiten"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Floor Plan", value: "Verdiepingplattegrond laden"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Site Map", value: "Locatieplattegrond laden"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Room with code \\'{0}\\' not found.", value: "Ruimte met code \\'{0}\\' niet gevonden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Selected building is not registered in the current site.", value: "Geselecteerd gebouw is niet in de huidige locatie geregistreerd."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Shelf with code \\'{0}\\' not found.", value: "Plank met code \\'{0}\\' niet gevonden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Updating Lists", value: "Lijsten bijwerken"},
        {key1: "MaterialInventory.model.MaterialLocation", key2: "{0} cannot be greater than {1}.", value: "{0} kan niet groter zijn dan {1}."},
        {key1: "MaterialInventory.store.Actions", key2: "Download Documents", value: "Documenten downloaden"},
        {key1: "MaterialInventory.store.MaterialData", key2: "Material Data", value: "Materiaalgegevens"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Locations", value: "Locaties"},
        {key1: "MaterialInventory.store.MaterialMsds", key2: "Documents", value: "Documenten"},
        {key1: "MaterialInventory.store.prompt.ContainerCategories", key2: "Container Categories", value: "Containercategorieën"},
        {key1: "MaterialInventory.store.prompt.ContainerTypes", key2: "Container Types", value: "Containertypen"},
        {key1: "MaterialInventory.store.prompt.MaterialChemicals", key2: "Chemicals", value: "Chemicaliën"},
        {key1: "MaterialInventory.store.prompt.MaterialConstituents", key2: "Constituents", value: "Bestanddelen"},
        {key1: "MaterialInventory.store.MaterialEmployees", key2: "Employees", value: "Medewerkers"},
        {key1: "MaterialInventory.store.prompt.MaterialUnits", key2: "Material Units", value: "Meeteenheden"},
        {key1: "MaterialInventory.store.prompt.PressureUnits", key2: "Pressure Units", value: "Drukeenheden"},
        {key1: "MaterialInventory.store.MaterialAisles", key2: "Aisles", value: "Gangen"},
        {key1: "MaterialInventory.store.MaterialBins", key2: "Bins", value: "Bakken"},
        {key1: "MaterialInventory.store.MaterialBuildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "MaterialInventory.store.MaterialCabinets", key2: "Cabinets", value: "Kasten"},
        {key1: "MaterialInventory.store.space.MaterialFloors", key2: "Floors", value: "Verdiepingen"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Rooms", value: "Ruimtes"},
        {key1: "MaterialInventory.store.MaterialShelves", key2: "Shelves", value: "Planken"},
        {key1: "MaterialInventory.store.MaterialSites", key2: "Sites", value: "Sites"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Cancel", value: "Annuleren"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Inventory Start Date", value: "Begindatum inventarisatie"},
        {key1: "MaterialInventory.view.Filter", key2: "All", value: "Alle"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Category", value: "Containercategorie"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Type", value: "Containertype"},
        {key1: "MaterialInventory.view.Filter", key2: "Custodian", value: "Beheerder"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From", value: "Datum laatste inventarisatie van"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From should not be greater than Date Last Inventory To.", value: "Datum laatste inventarisatie van mag niet groter zijn dan Datum laatste inventarisatie tot."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory To", value: "Datum laatste inventarisatie tot"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From", value: "Datum bijgewerkt vanaf"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From should not be greater than Date Updated To.", value: "Datum bijgewerkt vanaf mag niet groter zijn dan Datum bijgewerkt tot."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated To", value: "Datum bijgewerkt tot"},
        {key1: "MaterialInventory.view.Filter", key2: "Description", value: "Omschrijving"},
        {key1: "MaterialInventory.view.Filter", key2: "Display only items not inventoried", value: "Alleen niet-geïnventariseerde items weergeven"},
        {key1: "MaterialInventory.view.Filter", key2: "GHS Product Identifier", value: "GHS-product-ID"},
        {key1: "MaterialInventory.view.Filter", key2: "Last Edited By", value: "Laatst bewerkt door"},
        {key1: "MaterialInventory.view.Filter", key2: "Manufacturer", value: "Fabrikant"},
        {key1: "MaterialInventory.view.Filter", key2: "No", value: "Nee"},
        {key1: "MaterialInventory.view.Filter", key2: "Product Name", value: "Productnaam"},
        {key1: "MaterialInventory.view.Filter", key2: "Set Filter", value: "Filter instellen"},
        {key1: "MaterialInventory.view.Filter", key2: "Yes", value: "Ja"},
        {key1: "MaterialInventory.view.Main", key2: "Apps", value: "Apps"},
        {key1: "MaterialInventory.view.Main", key2: "Plan Types", value: "Plantypen"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Comments", value: "Opmerkingen"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Category", value: "Containercategorie"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Type", value: "Containertype"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Custodian", value: "Beheerder"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Date Last Updated:", value: "Datum laatst bijgewerkt:"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Description", value: "Omschrijving"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Edit Material", value: "Materiaal bewerken"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "GHS Product Identifier", value: "GHS-product-ID"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Manufacturer", value: "Fabrikant"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Pressure", value: "Druk"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Product Name", value: "Productnaam"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Products", value: "Producten"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Quantity", value: "Aantal"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Review Material", value: "Materiaal nakijken"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Type", value: "Type"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Unit", value: "Eenheid"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Add Material", value: "Materiaal toevoegen"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Hazmat", value: "gevsto"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Inventory", value: "Voorraad"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Location", value: "Locatie"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Materials", value: "Materiaal"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Product Name", value: "Productnaam"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Review", value: "Nakijken"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Status", value: "Status"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building Code", value: "Gebouwcode"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building:", value: "Gebouw:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor Code", value: "Code verdieping"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor:", value: "Verdieping:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room Code", value: "Code ruimte"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room:", value: "Ruimte:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Select Aisle Location", value: "Ganglocatie selecteren"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Bin:", value: "Bak:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building Code", value: "Gebouwcode"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building:", value: "Gebouw:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet Code", value: "Kastcode"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet:", value: "Kast:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor Code", value: "Code verdieping"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor:", value: "Verdieping:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room Code", value: "Code ruimte"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room:", value: "Ruimte:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Select Bin Location", value: "Baklocatie selecteren"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf Code", value: "Plankcode"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf:", value: "Plank:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building Code", value: "Gebouwcode"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building:", value: "Gebouw:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet Code", value: "Kastcode"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet:", value: "Kast:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor Code", value: "Code verdieping"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor:", value: "Verdieping:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room Code", value: "Code ruimte"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room:", value: "Ruimte:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Select Cabinet Location", value: "Kastlocatie selecteren"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building Code", value: "Gebouwcode"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building:", value: "Gebouw:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor Code", value: "Code verdieping"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor:", value: "Verdieping:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room Code", value: "Code ruimte"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room:", value: "Ruimte:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Select Room Location", value: "Ruimtelocatie selecteren"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle Code", value: "Gangcode"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building Code", value: "Gebouwcode"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building:", value: "Gebouw:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet Code", value: "Kastcode"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet:", value: "Kast:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor Code", value: "Code verdieping"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor:", value: "Verdieping:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room Code", value: "Code ruimte"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room:", value: "Ruimte:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Select Shelf Location", value: "Planklocatie selecteren"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf Code", value: "Plankcode"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf:", value: "Plank:"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Aisles", value: "Gangen"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Materials in Room", value: "Materialen in ruimte"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "No aisles identified.", value: "Geen gangen aangegeven."},
        {key1: "MaterialInventory.view.space.BinList", key2: "Bins", value: "Bakken"},
        {key1: "MaterialInventory.view.space.BinList", key2: "Materials on Shelf", value: "Materialen op plank"},
        {key1: "MaterialInventory.view.space.BinList", key2: "No bins identified.", value: "Geen bakken aangegeven."},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "Materials at Site", value: "Materialen op site"},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "No buildings identified.", value: "Geen gebouwen aangegeven."},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Cabinets", value: "Kasten"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Materials in Aisle", value: "Materialen in gang"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "No cabinets identified.", value: "Geen kasten aangegeven."},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Floors", value: "Verdiepingen"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Materials in Building", value: "Materialen in gebouw"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "No floors identified.", value: "Geen verdiepingen aangegeven."},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plan", value: "Verdiepingplattegrond"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Room List", value: "Ruimtelijst"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "Materials on Floor", value: "Materialen op verdieping"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "No rooms identified.", value: "Geen ruimtes aangegeven."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Materials in Cabinet", value: "Materialen in kast"},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "No shelves identified.", value: "Geen planken aangegeven."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Shelves", value: "Planken"},
        {key1: "MaterialInventory.view.space.Site", key2: "Buildings", value: "Gebouwen"},
        {key1: "MaterialInventory.view.space.Site", key2: "List View", value: "Lijstweergave"},
        {key1: "MaterialInventory.view.space.Site", key2: "Site Plan", value: "Locatieplattegrond"},
        {key1: "MaterialInventory.view.space.SiteList", key2: "No sites identified.", value: "Geen sites aangegeven."},
        {key1: "MaterialInventory.view.space.SiteList", key2: "Sites", value: "Sites"},
        {key1: "MaterialInventory.view.space.SiteMap", key2: "Site Plan is not available", value: "Locatieplattegrond is niet beschikbaar"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Weet u zeker dat u dit object wilt verwijderen?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Voer de inhoud voor het tekstvak in:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Plattegrond is niet beschikbaar"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Kopiëren"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Plakken"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Weet u zeker dat u dit item wilt verwijderen?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Bewerken"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Er is geen verdiepingplattegrond beschikbaar voor Rode lijn"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Datums publiceren"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Locatieplattegronden"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Verdiepingplattegrond"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Rode lijn"},
        {key1: "Space.model.SpaceSurvey", key2: " can only consist of alpha-numeric characters.", value: "kan alleen uit alfanumerieke tekens bestaan."},
        {key1: "Space.SpaceDownload", key2: "Download Floor Plans", value: "Verdiepingsplattegronden downloaden"},
        {key1: "Space.SpaceDownload", key2: "Downloaded plans for {0} floors.", value: "Gedownloade tekeningen voor {0} verdiepingen."},
        {key1: "Space.SpaceDownload", key2: "Downloading Site Maps", value: "Locatieplattegronden downloaden"},
        {key1: "Space.SpaceDownload", key2: "Floor Plan download was cancelled.", value: "Downloaden van verdiepingplattegrond is geannuleerd."},
        {key1: "Space.SpaceDownload", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "Space.SpaceDownload", key2: "Loading Plans for Floor {0} of {1}", value: "Verdiepingplattegrond {0} van {1} laden"},
        {key1: "Space.SpaceDownload", key2: "No active plan types found.", value: "Geen actieve plantypen gevonden."},
        {key1: "Space.SpaceDownload", key2: "No Floor Plans available to download", value: "Geen verdiepingsplattegronden beschikbaar om te downloaden"},
        {key1: "Space.SpaceDownload", key2: "No plan types found", value: "Geen plantypen gevonden"},
        {key1: "Space.SpaceDownload", key2: "Not all {0} floors of the selected buildings have floor plans available.", value: "Niet voor alle {0} verdiepingen van de geselecteerde gebouwen zijn verdiepingplattegronden beschikbaar."},
        {key1: "Space.SpaceDownload", key2: "Use the {0} icon to download your list of floors and buildings before downloading floor plans.", value: "Gebruik het pictogram {0} om uw lijst met verdiepingen en gebouwen te downloaden voordat u verdiepingsplattegronden downloadt."},
        {key1: "Space.SpaceDownload", key2: "You are going to download plans for {0} floors and this action may take some time. Proceed?", value: "U staat op het punt plattegronden voor {0} verdiepingen te downloaden, een actie die enige tijd kan duren. Wilt u doorgaan?"},
        {key1: "Space.SpaceFloorPlan", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "Space.SpaceFloorPlan", key2: "Rooms", value: "Ruimtes"},
        {key1: "Space.SpaceFloorPlan", key2: "The Plan Type data is not loaded.", value: "De gegevens voor het plantype zijn niet geladen."},
        {key1: "Space.SpaceSurvey", key2: "There is no Room data available for the selected Room.<br>Tap the {0} icon and select \\'Add to Survey\\' to update the Room data.", value: "Er zijn geen ruimtegegevens beschikbaar voor de geselecteerde ruimte.<br>Tik op het pictogram {0} en selecteer \\'Toevoegen aan survey\\' om de ruimtegegevens bij te werken."},
        {key1: "Space.SpaceSurvey", key2: "There is not an active survey for this floor.<br>To initiate a survey, tap the {0} icon and select \\'Start Survey\\'.", value: "Er is geen actieve survey voor deze verdieping.<br>Start een survey door op het pictogram {0} te tikken en \\'Survey starten\\' te selecteren."},
        {key1: "Space.store.Buildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "Space.store.DownloadActions", key2: "Download Floor Plans", value: "Verdiepingsplattegronden downloaden"},
        {key1: "Space.store.Floors", key2: "Floors", value: "Verdiepingen"},
        {key1: "Space.store.RoomSurveys", key2: "Rooms", value: "Ruimtes"},
        {key1: "Space.store.Sites", key2: "Buildings Without a Site Assigned", value: "Gebouwen zonder toegewezen vestiging"},
        {key1: "Space.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Space.store.SpaceSurveys", key2: "Surveys", value: "Surveys"},
        {key1: "Space.store.SurveyActions", key2: "Add to Survey", value: "Toevoegen aan survey"},
        {key1: "Space.store.SurveyActions", key2: "Close Survey", value: "survey sluiten"},
        {key1: "Space.store.SurveyActions", key2: "Complete Survey", value: "Survey voltooien"},
        {key1: "Space.store.SurveyActions", key2: "Start Survey", value: "Survey starten"},
        {key1: "Space.store.UserGroups", key2: "User Groups", value: "Gebruikersgroepen"},
        {key1: "Space.view.BuildingList", key2: "No buildings identified.", value: "Geen gebouwen aangegeven."},
        {key1: "Space.view.FloorList", key2: "Floors", value: "Verdiepingen"},
        {key1: "Space.view.FloorList", key2: "No floors identified.", value: "Geen verdiepingen aangegeven."},
        {key1: "Space.view.FloorList", key2: "Search Floors", value: "Verdiepingen zoeken"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plan", value: "Verdiepingplattegrond"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "Space.view.FloorPlan", key2: "Room List", value: "Ruimtelijst"},
        {key1: "Space.view.Main", key2: "Apps", value: "Apps"},
        {key1: "Space.view.Main", key2: "Plan Types", value: "Plantypen"},
        {key1: "Space.view.report.Configuration", key2: "Address 1", value: "Adres 1"},
        {key1: "Space.view.report.Configuration", key2: "Address 2", value: "Adres 2"},
        {key1: "Space.view.report.Configuration", key2: "Building", value: "Gebouw"},
        {key1: "Space.view.report.Configuration", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Space.view.report.Configuration", key2: "City", value: "Plaats"},
        {key1: "Space.view.report.Configuration", key2: "Country", value: "Land"},
        {key1: "Space.view.report.Configuration", key2: "Department", value: "Afdeling"},
        {key1: "Space.view.report.Configuration", key2: "Division", value: "Divisie"},
        {key1: "Space.view.report.Configuration", key2: "Email", value: "E-mail"},
        {key1: "Space.view.report.Configuration", key2: "Employee ID", value: "Personeels-ID"},
        {key1: "Space.view.report.Configuration", key2: "Employee Information", value: "Personeelsgegevens"},
        {key1: "Space.view.report.Configuration", key2: "First Name", value: "Voornaam"},
        {key1: "Space.view.report.Configuration", key2: "Floor", value: "Verdieping"},
        {key1: "Space.view.report.Configuration", key2: "Floor Name", value: "Naam van verdieping"},
        {key1: "Space.view.report.Configuration", key2: "Last Name", value: "Achternaam"},
        {key1: "Space.view.report.Configuration", key2: "Phone", value: "Telefoon"},
        {key1: "Space.view.report.Configuration", key2: "Room", value: "Ruimte"},
        {key1: "Space.view.report.Configuration", key2: "Room Area", value: "Oppervl. per ruimte"},
        {key1: "Space.view.report.Configuration", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Space.view.report.Configuration", key2: "Room Information", value: "Ruimtegegevens"},
        {key1: "Space.view.report.Configuration", key2: "Room Name", value: "Ruimtenaam"},
        {key1: "Space.view.report.Configuration", key2: "Room Phone", value: "Telefoon in ruimte"},
        {key1: "Space.view.report.Configuration", key2: "Room Standard", value: "Ruimtestandaard"},
        {key1: "Space.view.report.Configuration", key2: "Room Type", value: "Type ruimte"},
        {key1: "Space.view.report.Configuration", key2: "Site Code", value: "Vestigingscode"},
        {key1: "Space.view.report.Configuration", key2: "State", value: "Provincie"},
        {key1: "Space.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} Er zijn geen survey-items voor de geselecteerde verdieping.<br> Tik op het pictogram {1} en selecteer \\'Survey starten\\' of \\'Toevoegen aan survey\\' om survey-items voor deze verdieping te genereren.{2}"},
        {key1: "Space.view.Site", key2: "Buildings", value: "Gebouwen"},
        {key1: "Space.view.Site", key2: "List View", value: "Lijstweergave"},
        {key1: "Space.view.Site", key2: "Site Plan", value: "Locatieplattegrond"},
        {key1: "Space.view.SiteList", key2: "No sites identified.", value: "Geen sites aangegeven."},
        {key1: "Space.view.SiteList", key2: "Sites", value: "Sites"},
        {key1: "Space.view.StartSurvey", key2: "Start", value: "Start"},
        {key1: "Space.view.StartSurvey", key2: "Start Survey", value: "Survey starten"},
        {key1: "Space.view.StartSurvey", key2: "Survey Code", value: "Surveycode"},
        {key1: "Space.view.StartSurvey", key2: "Survey Name", value: "Surveynaam"},
        {key1: "Space.view.StartSurvey", key2: "Surveyor", value: "Opzichter"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Gebouwcodes"},
    ]
};
