package com.archibus.app.common.finanal.impl;

import com.archibus.context.ContextStore;
import com.archibus.eventhandler.EventHandlerBase;

/**
 * Contains translatable messages used in SFA.
 *
 * <p>
 *
 *
 * @author Ioan Draghici
 * @since 23.1
 *
 */
public final class Messages {
    /**
     * Aggregate operating cost description.
     */
    // @translatable
    public static final String AGGREGATE_OPERATING_COSTS_DESCRIPTION =
            "Auto-generated by the SFA Aggregate Operating Expenses Action";

    /**
     * Aggregate operating cost description.
     */
    // @translatable
    public static final String ACTUAL_COST_AGGREGATE_OPERATING_COSTS_DESCRIPTION =
            "ACTUAL Costs for Completed tasks - Auto-generated by the SFA Aggregate Operating Expenses Action";

    /**
     * Aggregate operating cost description.
     */
    // @translatable
    public static final String ESTIMATED_COST_AGGREGATE_OPERATING_COSTS_DESCRIPTION =
            "ESTIMATED Costs for planned or in process tasks - Auto-generated by the SFA Aggregate Operating Expenses Action";

    /**
     * Aggregate operating cost description.
     */
    // @translatable
    public static final String SCHEDULED_JOB_PROCESSING_METRICS =
            "Processing &apos;%s&apos; metric";

    /**
     * Aggregate operating cost description.
     */
    // @translatable
    public static final String SCHEDULED_JOB_UPDATE_ANALYSIS_METRICS = "Update Analysis Metrics";

    /**
     * Class name.
     */
    public static final String CLASS_NAME = "com.archibus.app.common.finanal.impl.Messages";

    /**
     * Private constructor.
     */
    private Messages() {

    }

    /**
     * Returns localized string.
     *
     * @param message message name
     * @return string
     */
    public static String getLocalizedMessage(final String message) {
        return EventHandlerBase.localizeString(ContextStore.get().getEventHandlerContext(), message,
            CLASS_NAME);
    }
}
