var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.de = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Akzeptieren Sie die Browseranforderung, Daten auf Ihrem lokalen Computer zu speichern und die Seite zu aktualisieren."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fehler beim Laden der Konfigurationsdatei."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Der Controller '{0}' verfügt über keine Startmethode. Sind Sie sicher, dass der Controller eine Erweiterung von Ext.app.Controller ist?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Der Wert hat ein falsches Format:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Der Wert ist keine gültige E-Mail:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Der Wert ist kein zulässiger Wert:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Der Wert ist in der Liste zulässiger Werte nicht enthalten:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Der Wert hat eine falsche Länge:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Der folgende Wert muss vorhanden sein:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Anhängen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Schließen"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Fertig"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Ladevorgang wird ausgeführt..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Korrigieren Sie Folgendes:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scan-Fehler"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Fertig"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Keine Datenanzeige für: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Anwenden"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Kein(e) {0} zum Anzeigen"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Anforderung"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Stunden"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Objekt {0} von {1} wird geladen"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Vorname"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nachname"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Name:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Ansprechpartner"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Bezeichnung der Abteilung"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Abteilung:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Bereich"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-Mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-Mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Mitarbeiter"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Kurzzeichen Mitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standardmitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Geräte"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Gerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Geräte:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Geschosse"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Bezeichnung der Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Liegenschaft:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebäude/Geschoss:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Räume"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standardraum"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Raumtyp"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Typ:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Standort"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Standortcode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Standort:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Standorte"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Es wurden keine vorherigen Suchen gespeichert."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.Signature", key2: "Done", value: "Fertig"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Unterschrift"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Bei Erweiterung der Klasse Common.controller.NavigationController muss eine mainView-Ref.-Konfiguration bereitgestellt werden."},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Speichern"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Möchten Sie fortfahren?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Beim Aufheben der Geräteregistrierung ist ein Fehler aufgetreten. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Beim Abmelden werden Ihre Anwendungsdaten nicht entfernt.<br>Sie müssen das Gerät erneut registrieren, um auf die Apps zugreifen zu können."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registrierung"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registrierung fehlgeschlagen"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Der Gerätregistrierungsservice ist nicht verfügbar. Die Mobildienste sind in Web Central möglicherweise nicht aktiviert."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Modell mit dem Namen [{0}] ist nicht vorhanden."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Einlesen des Barcodes ist nicht möglich"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Berechtigung zum Zugriff auf Standortinformationen verweigert"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Position ist nicht verfügbar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Zeitüberschreitung der Position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fehler: Unbekannte Position"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Beim Anzeigen des Dokuments und der Finanzierungsquelle"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Dokumentanzeige"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Dokument wird heruntergeladen"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Funktion in Desktop-Umgebung nicht verfügbar."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Datei existiert nicht"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Datei {0} kann auf diesem Gerät nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Datei {0} kann im Desktop-Modus nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Dokument entfernen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Feld 'Feld geändert': {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Eingabe"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Eingabe für Feld {0} ist auf {1} Zeichen begrenzt"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Leeren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopieren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Fertig"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fehler"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nein"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Einfügen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Neu laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Raumname"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Raumnamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Bild speichern"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Umfrage"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Die Anwendung wurde auf die neueste Version aktualisiert. Die Anwendung wird neu geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fehler beim Laden von Netzwerkdiensten. Die Netzwerkverbindung ist möglicherweise langsam oder nicht verfügbar."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Keine Daten vom Server erhalten"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Zeitüberschreitung"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Unbekannter Fehler"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fehler beim Registrieren des Geräts."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fehler beim Abrufen von Benutzerinformationen."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fehler beim Festlegen des Sitzungsgebiets."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fehler beim Starten der Benutzersitzung."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fehler bei Einzelanmeldung"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fehler beim Abrufen von TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Gerät ist nicht registriert."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Workflow nach JSON. Datenobjekte dürfen nicht mithilfe von Workflow-Regeln gemarshallt werden."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Workflow-Regel ausgeführt"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Workflow-Regel fehlgeschlagen:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-Einstellungen"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Ursachentypen"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Ansprechpartner"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Personal"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standardpersonal"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Geräte"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Geschosse"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Verletzte Körperteile"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Verletzungskategorien"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Arbeitsunfall - Typen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantypgruppen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Problemtypen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projekte"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Liegenschaften"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Datenbankfehler:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Keine Änderung an Datenbanktabelle übernommen. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Keine Standardwertaktualisierung für Feld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standardwert aktualisieren: Feld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Sqlite-Proxy-Fehler"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Sqlite-Proxy-Fehler während Erstellungsvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Sqlite-Proxy-Fehler während Löschvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Sqlite-Proxy-Fehler während Lesevorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Sqlite-Proxy-Fehler während Aktualisierungsvorgang"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fehler beim Öffnen der Datenbank: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Datenbankfehler [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Datenbankfehler bei SqliteView-Proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Löschen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Aktualisieren von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Erstellen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "Die Datenbank enthält nicht die erforderlichen Tabellendefinitionen für die Sqlite-Ansicht {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Reparaturtypen"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Räume"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standardräume"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Raumnutzungsarten"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Standorte"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "datei_nicht_verfügbar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisieren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Herunterladen wird ausgeführt:"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fehler"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Date-Typ konvertiert werden."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Integer konvertiert werden."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Time konvertiert werden."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Timestamp konvertiert werden."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Die Anwendungseinstellungen wurden nicht geladen."},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Ausführung im Browser-Modus. Zugriff auf Dateisystem deaktiviert"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Ausführung in Chrome oder in WebView. Zugriff auf Dateisystem aktiviert"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Dateizugriff wurde abgebrochen"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Datei ist bereits vorhanden"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fehler bei Dateiverschlüsselung"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Dateifehler"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Datei befindet sich in einem ungültigen Zustand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Dateiänderung ist nicht zulässig"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Dateiquoten überschritten"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fehler bei Dateisicherheit"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fehler wegen Dateitypkonflikt"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Datei wurde nicht gefunden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Datei war nicht lesbar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fehler aufgrund ungültiger Dateiänderung"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netzwerk nicht erreichbar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Stammdaten werden heruntergeladen"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fehler"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Der App-Einstellungsspeicher ist nicht geladen. Einstellungen können nicht abgerufen werden."},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "m"},
        {key1: "Common.util.Units", key2: "sq ft", value: "Quadratmeter"},
        {key1: "Common.util.Units", key2: "sq m", value: "Quadratmeter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Die Benutzerprofilinformationen sind nicht verfügbar. Führen Sie eine Synchronisierung durch, um die Benutzerprofildaten abzurufen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Bei Synchronisierung löschen"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Anzeigen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Dokumente"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Keine Dokumente verfügbar."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} von {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 von x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Der Name der Modellklasse, die dieser Ansicht zugeordnet ist, muss in der Modelleigenschaft angegeben werden."},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "Die Speicher-ID der Speicherklasse, die dieser Ansicht zugeordnet ist, muss in der Eigenschaft -storeId- angegeben werden."},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Leeren"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Zurück"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Speichern"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Feld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Kennung"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Größe (Bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisierungsmeldungen"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabelle"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Die folgenden Web Central-Feldwerte wurden nicht in die Client-Datenbank übertragen, da die Datengröße die Kapazität der Datenbank überschreitet."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Möchten Sie dieses Objekt wirklich löschen?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Geben Sie den Textfeldinhalt ein:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Grundriss nicht verfügbar"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Kopieren"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Einfügen"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Neu laden"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Bild speichern"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Möchten Sie dieses Objekt wirklich löschen?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Bearbeiten"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Für Redline ist kein Geschossplan verfügbar."},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Datum veröffentlichen"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Standortkarten"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Redline"},
        {key1: "Space.model.SpaceSurvey", key2: " can only consist of alpha-numeric characters.", value: "kann nur aus alphanumerischen Zeichen bestehen."},
        {key1: "Space.SpaceDownload", key2: "Download Floor Plans", value: "Grundrisse herunterladen"},
        {key1: "Space.SpaceDownload", key2: "Downloaded plans for {0} floors.", value: "Heruntergeladene Grundrisse für {0} Geschosse."},
        {key1: "Space.SpaceDownload", key2: "Downloading Site Maps", value: "Standortkarten werden heruntergeladen"},
        {key1: "Space.SpaceDownload", key2: "Floor Plan download was cancelled.", value: "Herunterladen des Grundrisses wurde abgebrochen."},
        {key1: "Space.SpaceDownload", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Space.SpaceDownload", key2: "Loading Plans for Floor {0} of {1}", value: "Pläne für Geschoss {0} von {1} laden"},
        {key1: "Space.SpaceDownload", key2: "No active plan types found.", value: "Keine aktiven Plantypen gefunden."},
        {key1: "Space.SpaceDownload", key2: "No Floor Plans available to download", value: "Kein Grundrissplan zum Download verfügbar"},
        {key1: "Space.SpaceDownload", key2: "No plan types found", value: "Keine Plantypen gefunden"},
        {key1: "Space.SpaceDownload", key2: "Not all {0} floors of the selected buildings have floor plans available.", value: "Für nicht alle {0} Geschosse der ausgewählten Gebäude sind Grundrisse verfügbar."},
        {key1: "Space.SpaceDownload", key2: "Use the {0} icon to download your list of floors and buildings before downloading floor plans.", value: "Verwenden Sie das Symbol {0}, um Ihre Geschoss- und Gebäudeliste herunterzuladen, bevor Sie Grundrisse herunterladen."},
        {key1: "Space.SpaceDownload", key2: "You are going to download plans for {0} floors and this action may take some time. Proceed?", value: "Sie beginnen mit dem Download von {0} Grundrissen. Diese Aktion kann einige Zeit in Anspruch nehmen. Fortfahren?"},
        {key1: "Space.SpaceFloorPlan", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Space.SpaceFloorPlan", key2: "Rooms", value: "Räume"},
        {key1: "Space.SpaceFloorPlan", key2: "The Plan Type data is not loaded.", value: "Die Plantypdaten wurden nicht geladen."},
        {key1: "Space.SpaceSurvey", key2: "There is no Room data available for the selected Room.<br>Tap the {0} icon and select \\'Add to Survey\\' to update the Room data.", value: "Für den ausgewählten Raum sind keine Raumdaten verfügbar.<br>Tippen Sie auf das {0}-Symbol und wählen Sie \\'Zu Erfassung hinzufügen\\' aus, um die Raumdaten zu aktualisieren."},
        {key1: "Space.SpaceSurvey", key2: "There is not an active survey for this floor.<br>To initiate a survey, tap the {0} icon and select \\'Start Survey\\'.", value: "Für dieses Geschoss gibt es keine aktive Erfassung.<br>Um eine Erfassung einzuleiten, tippen Sie auf das {0}-Symbol und wählen Sie \\'Erfassen\\' aus."},
        {key1: "Space.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Space.store.DownloadActions", key2: "Download Floor Plans", value: "Grundrisse herunterladen"},
        {key1: "Space.store.Floors", key2: "Floors", value: "Geschosse"},
        {key1: "Space.store.RoomSurveys", key2: "Rooms", value: "Räume"},
        {key1: "Space.store.Sites", key2: "Buildings Without a Site Assigned", value: "Gebäude ohne zugewiesenen Standort"},
        {key1: "Space.store.Sites", key2: "Sites", value: "Standorte"},
        {key1: "Space.store.SpaceSurveys", key2: "Surveys", value: "Inventaraufnahmen"},
        {key1: "Space.store.SurveyActions", key2: "Add to Survey", value: "Zu Erfassung hinzufügen"},
        {key1: "Space.store.SurveyActions", key2: "Close Survey", value: "Erfassung schließen"},
        {key1: "Space.store.SurveyActions", key2: "Complete Survey", value: "Erfassung abschließen"},
        {key1: "Space.store.SurveyActions", key2: "Start Survey", value: "Erfassung starten"},
        {key1: "Space.store.UserGroups", key2: "User Groups", value: "Benutzergruppen"},
        {key1: "Space.view.BuildingList", key2: "No buildings identified.", value: "Keine Gebäude ermittelt."},
        {key1: "Space.view.FloorList", key2: "Floors", value: "Geschosse"},
        {key1: "Space.view.FloorList", key2: "No floors identified.", value: "Keine Geschosse ermittelt."},
        {key1: "Space.view.FloorList", key2: "Search Floors", value: "Geschosse suchen"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Space.view.FloorPlan", key2: "Room List", value: "Raumliste"},
        {key1: "Space.view.Main", key2: "Apps", value: "Apps"},
        {key1: "Space.view.Main", key2: "Plan Types", value: "Plantypen"},
        {key1: "Space.view.report.Configuration", key2: "Address 1", value: "Adresse 1"},
        {key1: "Space.view.report.Configuration", key2: "Address 2", value: "Adresse 2"},
        {key1: "Space.view.report.Configuration", key2: "Building", value: "Gebäude"},
        {key1: "Space.view.report.Configuration", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Space.view.report.Configuration", key2: "City", value: "Stadt"},
        {key1: "Space.view.report.Configuration", key2: "Country", value: "Land"},
        {key1: "Space.view.report.Configuration", key2: "Department", value: "Abteilung"},
        {key1: "Space.view.report.Configuration", key2: "Division", value: "Bereich"},
        {key1: "Space.view.report.Configuration", key2: "Email", value: "E-Mail"},
        {key1: "Space.view.report.Configuration", key2: "Employee ID", value: "Mitarbeiter-ID"},
        {key1: "Space.view.report.Configuration", key2: "Employee Information", value: "Personaldaten"},
        {key1: "Space.view.report.Configuration", key2: "First Name", value: "Vorname"},
        {key1: "Space.view.report.Configuration", key2: "Floor", value: "Geschoss"},
        {key1: "Space.view.report.Configuration", key2: "Floor Name", value: "Geschossname"},
        {key1: "Space.view.report.Configuration", key2: "Last Name", value: "Nachname"},
        {key1: "Space.view.report.Configuration", key2: "Phone", value: "Telefon"},
        {key1: "Space.view.report.Configuration", key2: "Room", value: "Raum"},
        {key1: "Space.view.report.Configuration", key2: "Room Area", value: "Raumfläche"},
        {key1: "Space.view.report.Configuration", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Space.view.report.Configuration", key2: "Room Information", value: "Raumdaten"},
        {key1: "Space.view.report.Configuration", key2: "Room Name", value: "Raumname"},
        {key1: "Space.view.report.Configuration", key2: "Room Phone", value: "Raumtelefon"},
        {key1: "Space.view.report.Configuration", key2: "Room Standard", value: "Standardraum"},
        {key1: "Space.view.report.Configuration", key2: "Room Type", value: "Raumtyp"},
        {key1: "Space.view.report.Configuration", key2: "Site Code", value: "Standortcode"},
        {key1: "Space.view.report.Configuration", key2: "State", value: "Bundesland/Kanton"},
        {key1: "Space.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} Für das ausgewählte Geschoss sind keine Erfassungselemente verfügbar.<br> Tippen Sie auf das {1}-Symbol und wählen Sie \\'Erfassung starten\\' oder \\'Zu Erfassung hinzufügen\\', um Erfassungselemente für dieses Geschoss zu generieren.{2}"},
        {key1: "Space.view.Site", key2: "Buildings", value: "Gebäude"},
        {key1: "Space.view.Site", key2: "List View", value: "Listenansicht"},
        {key1: "Space.view.Site", key2: "Site Plan", value: "Standortplan"},
        {key1: "Space.view.SiteList", key2: "No sites identified.", value: "Keine Standorte ermittelt."},
        {key1: "Space.view.SiteList", key2: "Sites", value: "Standorte"},
        {key1: "Space.view.StartSurvey", key2: "Start", value: "Start"},
        {key1: "Space.view.StartSurvey", key2: "Start Survey", value: "Erfassung starten"},
        {key1: "Space.view.StartSurvey", key2: "Survey Code", value: "Kurzzeichen Erfassung"},
        {key1: "Space.view.StartSurvey", key2: "Survey Name", value: "Erfassungsname"},
        {key1: "Space.view.StartSurvey", key2: "Surveyor", value: "Prüfer"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Bezeichnung des Gebäudes"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Address 1", value: "Adresse 1"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Address 1:", value: "Adresse 1:"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Address 2", value: "Adresse 2"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Address 2:", value: "Adresse 2:"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Buildings", value: "Gebäude"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Code", value: "Kurzzeichen"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Name", value: "Name"},
        {key1: "WorkplacePortal.control.prompt.BuildingAddressPrompt", key2: "Name:", value: "Name:"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Building/Floor:", value: "Gebäude/Geschoss:"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Floor Code", value: "Geschoss"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Room Code", value: "Raum"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Room Code:", value: "Raum:"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Room Name", value: "Raumname"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Room Name:", value: "Raumname:"},
        {key1: "WorkplacePortal.control.prompt.RoomNamePrompt", key2: "Room Names", value: "Raumnamen"},
        {key1: "WorkplacePortal.controller.Documents", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "Alle Felder für Arbeitsanforderungsdokumente sind in Gebrauch.<br>Das Foto kann nicht an die Arbeitsanforderung angehängt werden"},
        {key1: "WorkplacePortal.controller.Documents", key2: "Documents", value: "Dokumente"},
        {key1: "WorkplacePortal.controller.Documents", key2: "This action will remove the document. Do you want to proceed?", value: "Diese Maßnahme entfernt das Dokument. Möchten Sie fortfahren?"},
        {key1: "WorkplacePortal.controller.Navigation", key2: "Locate Employee", value: "Personal lokalisieren"},
        {key1: "WorkplacePortal.controller.Navigation", key2: "No rooms available", value: "Keine Räume verfügbar"},
        {key1: "WorkplacePortal.controller.Navigation", key2: "No rooms available for selected building", value: "Keine Räume verfügbar für das ausgewählte Gebäude"},
        {key1: "WorkplacePortal.controller.Navigation", key2: "Please fill in at least one field.", value: "Füllen Sie mindestens ein Feld aus."},
        {key1: "WorkplacePortal.controller.Navigation", key2: "Request", value: "Anforderung"},
        {key1: "WorkplacePortal.controller.Navigation", key2: "The selected employee is not assigned to a room.", value: "Der ausgewählte Mitarbeiter ist keinem Raum zugewiesen."},
        {key1: "WorkplacePortal.controller.Navigation", key2: "There is no employee assigned to this room", value: "Diesem Raum ist kein Mitarbeiter zugewiesen"},
        {key1: "WorkplacePortal.store.FacilityServicesMenus", key2: "Facility Menu", value: "Anlagenmenü"},
        {key1: "WorkplacePortal.store.HotelingRequests", key2: "Hoteling Requests", value: "Hoteling-Anforderungen"},
        {key1: "WorkplacePortal.store.MobileMenus", key2: "Mobile Menus", value: "Mobile-Menüs"},
        {key1: "WorkplacePortal.store.ReservationEmployee", key2: "Reservation Employees", value: "Mitarbeiterreservierung"},
        {key1: "WorkplacePortal.store.ReservationRooms", key2: "Room Reservations", value: "Raumreservierungen"},
        {key1: "WorkplacePortal.store.Reservations", key2: "Reservations", value: "Reservierungen"},
        {key1: "WorkplacePortal.store.RoomArrangeTypes", key2: "Room Arrange Types", value: "Raumanordnungstypen"},
        {key1: "WorkplacePortal.store.RoomResource", key2: "Room Resources", value: "Raumressourcen"},
        {key1: "WorkplacePortal.store.ServiceDeskRequests", key2: "Service Desk Requests", value: "Anforderungen an den Service Desk"},
        {key1: "WorkplacePortal.store.UserReservationRooms", key2: "Current Reservations", value: "Aktuelle Reservierungen"},
        {key1: "WorkplacePortal.store.UserReservationRooms", key2: "Future Reservations", value: "Zukünftige Reservierungen"},
        {key1: "WorkplacePortal.store.UserReservationRooms", key2: "Past Reservations", value: "Frühere Reservierungen"},
        {key1: "WorkplacePortal.store.WorkspaceTransactions", key2: "Hoteling Bookings", value: "Hotelbuchungen"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Booking", value: "Buchung"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Cancel the Booking", value: "Buchung stornieren"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Cancel the Booking Occurrence?", value: "Vorkommen der Buchung stornieren?"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Canceling", value: "Stornieren"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Check In", value: "Einchecken"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Checking in", value: "Einchecken"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Do you want to check into the space now and claim your reservation?  You may lose your reservation if you do not.", value: "Möchten Sie den Raum jetzt überprüfen und Ihre Reservierung anfordern?  Andernfalls geht Ihre Reservierung möglicherweise verloren."},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Error", value: "Fehler"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "No rooms match the search criteria", value: "Keine Räume entsprechen den Suchkriterien"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Search", value: "Suche"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "Searching", value: "Sucht"},
        {key1: "WorkplacePortal.util.Hoteling", key2: "The reservation is already verified", value: "Die Reservierung wurde bereits geprüft"},
        {key1: "WorkplacePortal.util.Reservation", key2: "A reservation cannot end before its start time", value: "Eine Reservierung darf nicht vor ihrer Anfangszeit enden."},
        {key1: "WorkplacePortal.util.Reservation", key2: "A reservation cannot start in the past", value: "Eine Reservierung darf nicht in der Vergangenheit beginnen."},
        {key1: "WorkplacePortal.util.Reservation", key2: "All", value: "Alle"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Attendee", value: "Teilnehmer"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Attendee has been already added.", value: "Teilnehmer wurde bereits hinzugefügt."},
        {key1: "WorkplacePortal.util.Reservation", key2: "Cancel the Reservation", value: "Reservierung stornieren"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Canceling", value: "Stornieren"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Close", value: "Schließen"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Contact", value: "Ansprechpartner"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Contact Name", value: "A nsprechpartnername"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Do you want to cancel all occurrences of the recurring reservation or just this one?", value: "Möchten Sie alle Vorkommen der wiederkehrenden Reservierung oder nur diese Reservierung stornieren?"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Do you want to cancel this reservation?", value: "Möchten Sie diese Reservierung stornieren?"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Do you want to verify your reservation now? You may lose your reservation if you do not.", value: "Möchten Sie Ihre Reservierung jetzt prüfen? Andernfalls geht Ihre Reservierung möglicherweise verloren."},
        {key1: "WorkplacePortal.util.Reservation", key2: "Done", value: "Fertig"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Email", value: "E-Mail"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Employee", value: "Mitarbeiter"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Employee Code", value: "Kurzzeichen Mitarbeiter"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Error", value: "Fehler"},
        {key1: "WorkplacePortal.util.Reservation", key2: "No rooms match the search criteria", value: "Keine Räume entsprechen den Suchkriterien"},
        {key1: "WorkplacePortal.util.Reservation", key2: "No {0} to Display", value: "Kein(e) {0} zum Anzeigen"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Phone", value: "Telefon"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Please add a subject.", value: "Fügen Sie einen Betreff hinzu."},
        {key1: "WorkplacePortal.util.Reservation", key2: "Reserving", value: "Reservierung wird durchgeführt"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Search", value: "Suche"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Search {0}", value: "{0} suchen"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Searching", value: "Sucht"},
        {key1: "WorkplacePortal.util.Reservation", key2: "The Reservation can only be verified within 30 min of the reservation start time.", value: "Die Reservierung kann nur innerhalb von 30 Minuten nach der Reservierungsstartzeit überprüft werden."},
        {key1: "WorkplacePortal.util.Reservation", key2: "The reservation is already cancelled", value: "Die Reservierung wurde bereits storniert."},
        {key1: "WorkplacePortal.util.Reservation", key2: "The reservation is already verified", value: "Die Reservierung wurde bereits geprüft"},
        {key1: "WorkplacePortal.util.Reservation", key2: "There are no Contact Email Addresses in your Contact List", value: "Ihre Liste der Ansprechpartner enthält keine E-Mail-Adressen von Ansprechpartnern"},
        {key1: "WorkplacePortal.util.Reservation", key2: "This One", value: "Diese"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Verify", value: "Prüfen"},
        {key1: "WorkplacePortal.util.Reservation", key2: "Verifying", value: "Prüfung wird durchgeführt"},
        {key1: "WorkplacePortal.util.ServiceDeskRequest", key2: "Error", value: "Fehler"},
        {key1: "WorkplacePortal.util.ServiceDeskRequest", key2: "Submitting the Request", value: "Übermitteln der Anforderung"},
        {key1: "WorkplacePortal.util.SyncHelper", key2: "Error", value: "Fehler"},
        {key1: "WorkplacePortal.util.SyncHelper", key2: "Refreshing Views", value: "Ansichten aktualisieren"},
        {key1: "WorkplacePortal.util.SyncHelper", key2: "Syncing", value: "Synchronisieren"},
        {key1: "WorkplacePortal.util.SyncHelper", key2: "Syncing Service Desk Requests", value: "Servicedesk-Anforderungen werden synchronisiert"},
        {key1: "WorkplacePortal.util.SyncHelper", key2: "Updating Service Desk Requests", value: "Servicedesk-Anforderungen werden aktualisiert"},
        {key1: "WorkplacePortal.util.WorkflowRules", key2: "Error", value: "Fehler"},
        {key1: "WorkplacePortal.view.FacilityInformationList", key2: "Information", value: "Information"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Attendee", value: "Teilnehmer"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Date Start From", value: "Anfangsdatum ab"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Date Start From should not be greater than Date Start To.", value: "’Anfangsdatum ab’ darf nicht nach ’Anfangsdatum bis’ liegen."},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Date Start To", value: "Anfangsdatum bis"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Employees", value: "Personal"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "From", value: "Von"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "hh:mm", value: "hh:mm"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Name", value: "Name"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Requested For", value: "Angefordert für"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Room Arrangement Type", value: "Raumanordnungstyp"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Room Arrangement Types", value: "Raumanordnungstypen"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Status", value: "Status"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "Subject", value: "Betreff"},
        {key1: "WorkplacePortal.view.FilterReservations", key2: "To", value: "Bis"},
        {key1: "WorkplacePortal.view.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "WorkplacePortal.view.FloorPlan", key2: "Room List", value: "Raumliste"},
        {key1: "WorkplacePortal.view.FloorPlan", key2: "Search Rooms", value: "Räume suchen"},
        {key1: "WorkplacePortal.view.FloorPlan", key2: "Site", value: "Standort"},
        {key1: "WorkplacePortal.view.HotelingList", key2: "My Requests", value: "Meine Anforderungen"},
        {key1: "WorkplacePortal.view.HotelingList", key2: "{0} Tap {1} to add a new hoteling request.{2}", value: "{0} Tippen Sie auf {1}, um eine neue Hoteling-Anforderung hinzuzufügen.{2}"},
        {key1: "WorkplacePortal.view.HotelingListItem", key2: "Location:", value: "Standort:"},
        {key1: "WorkplacePortal.view.HotelingListItem", key2: "Status:", value: "Status:"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Book", value: "Buchen"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Book Room", value: "Raum buchen"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "End Date", value: "Enddatum"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Floor Code", value: "Geschoss"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Part of Day", value: "Tagesabschnitt"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Room Code", value: "Raum"},
        {key1: "WorkplacePortal.view.HotelingSearchConfirm", key2: "Start Date", value: "Anfangsdatum"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Category", value: "Kategorie"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Description", value: "Beschreibung"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Duration", value: "Dauer"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "End Date", value: "Enddatum"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Part of Day", value: "Tagesabschnitt"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Room Category", value: "Raumkategorie"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Room Type", value: "Raumtyp"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Room Types", value: "Raumtypen"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Search", value: "Suche"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Search Rooms", value: "Räume suchen"},
        {key1: "WorkplacePortal.view.HotelingSearchForm", key2: "Start Date", value: "Anfangsdatum"},
        {key1: "WorkplacePortal.view.LocateEmployee", key2: "First Name", value: "Vorname"},
        {key1: "WorkplacePortal.view.LocateEmployee", key2: "Last Name", value: "Nachname"},
        {key1: "WorkplacePortal.view.LocateEmployee", key2: "Locate", value: "Lokalisieren"},
        {key1: "WorkplacePortal.view.LocateEmployee", key2: "Locate Employee", value: "Personal lokalisieren"},
        {key1: "WorkplacePortal.view.LocateRoom", key2: "Locate", value: "Lokalisieren"},
        {key1: "WorkplacePortal.view.LocateRoom", key2: "Locate Room", value: "Raum lokalisieren"},
        {key1: "WorkplacePortal.view.Main", key2: "Apps", value: "Apps"},
        {key1: "WorkplacePortal.view.Main", key2: "Plan Types", value: "Plantypen"},
        {key1: "WorkplacePortal.view.ReservationAttendees", key2: "Add Contacts", value: "Ansprechpartner hinzufügen"},
        {key1: "WorkplacePortal.view.ReservationAttendees", key2: "Add Employees", value: "Mitarbeiter hinzufügen"},
        {key1: "WorkplacePortal.view.ReservationAttendees", key2: "Attendee", value: "Teilnehmer"},
        {key1: "WorkplacePortal.view.ReservationAttendees", key2: "Attendee E-mail", value: "Teilnehmer-E-Mail"},
        {key1: "WorkplacePortal.view.ReservationAttendees", key2: "Attendees", value: "Teilnehmer"},
        {key1: "WorkplacePortal.view.ReservationAttendees", key2: "Illegal Email Address", value: "Unzulässige E-Mail-Adresse"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Comments", value: "Bemerkungen"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Configuration Code", value: "Konfigurationskurzzeichen"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Cost", value: "Kosten"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Div. - Dept. Chargeback", value: "Bereich - Abt. für Verrechnung"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Floor Code", value: "Geschoss"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Requested For", value: "Angefordert für"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Reservation", value: "Reservierung"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Reservation Date & Time", value: "Reservierungsdatum u. -zeit"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Room Arrangement Type", value: "Raumanordnungstyp"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Room Code", value: "Raum"},
        {key1: "WorkplacePortal.view.ReservationDetailsForm", key2: "Subject", value: "Betreff"},
        {key1: "WorkplacePortal.view.ReservationList", key2: "My Reservations", value: "Meine Reservierungen"},
        {key1: "WorkplacePortal.view.ReservationList", key2: "{0} Tap {1} to add a new reservation.{2}", value: "{0} Tippen Sie auf {1}, um eine neue Reservierung hinzuzufügen.{2}"},
        {key1: "WorkplacePortal.view.ReservationListItem", key2: "Hours:", value: "Stunden:"},
        {key1: "WorkplacePortal.view.ReservationListItem", key2: "Location:", value: "Standort:"},
        {key1: "WorkplacePortal.view.ReservationListItem", key2: "Status:", value: "Status:"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Add Contacts", value: "Ansprechpartner hinzufügen"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Add Employees", value: "Mitarbeiter hinzufügen"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Attendee", value: "Teilnehmer"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Attendee E-mail", value: "Teilnehmer-E-Mail"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Configuration Code", value: "Konfigurationskurzzeichen"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Confirm", value: "Bestätigen"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Confirm Reservation", value: "Reservierungen bestätigen"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "End Time", value: "Endzeit"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Floor Code", value: "Geschoss"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Illegal Email Address", value: "Unzulässige E-Mail-Adresse"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Reservation Date", value: "Reservierungsdatum"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Room Arrangement Type", value: "Raumanordnungstyp"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Room Code", value: "Raum"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Start Time", value: "Startzeit"},
        {key1: "WorkplacePortal.view.ReservationSearchConfirm", key2: "Subject", value: "Betreff"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Confirm Reservation", value: "Reservierungen bestätigen"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Capacity", value: "Kapazität"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Check this box to show only rooms suitable for external guests", value: "Aktivieren Sie dieses Feld, damit nur Räume angezeigt werden, die für externe Gäste geeignet sind."},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Date and Time Information", value: "Datum- und Uhrzeitangaben"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Date Requested", value: "Gemeldet am"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "From", value: "Von"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "hh:mm", value: "hh:mm"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Location Information", value: "Standortdaten"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Name", value: "Name"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Reservation Search", value: "Reservierungssuche"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Room Arrangement Type", value: "Raumanordnungstyp"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Room Arrangement Types", value: "Raumanordnungstypen"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Room Information", value: "Raumdaten"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Room Resources", value: "Raumressourcen"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "Search", value: "Suche"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "To", value: "Bis"},
        {key1: "WorkplacePortal.view.ReservationSearchForm", key2: "With External Guests?", value: "Mit externen Gästen?"},
        {key1: "WorkplacePortal.view.ReservationSearchResult", key2: "Available Rooms", value: "Verfügbare Räume"},
        {key1: "WorkplacePortal.view.ReservationSearchResultItem", key2: "Select", value: "Auswählen"},
        {key1: "WorkplacePortal.view.RoomList", key2: "There are no Room Items for the selected floor.", value: "Für das ausgewählte Geschoss sind keine Raumobjekte verfügbar."},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Cancel", value: "Abbrechen"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Copy", value: "Kopieren"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Documents", value: "Dokumente"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Furniture", value: "Möbel"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Location Information", value: "Standortdaten"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Maintenance", value: "Wartung"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Move", value: "Umzug"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Phone", value: "Telefon"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Photo 1", value: "Foto 1"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Photo 2", value: "Foto 2"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Photo 3", value: "Foto 3"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Photo 4", value: "Foto 4"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Request Information", value: "Anforderungsinformationen"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Request Type", value: "Anforderungstyp"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Requestor", value: "Anforderer"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Requestor Information", value: "Anfordererinformationen"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Service Request ID", value: "Serviceanforderungs-ID"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestForm", key2: "Space", value: "Flächen"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestList", key2: "My Requests", value: "Meine Anforderungen"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestList", key2: "Status", value: "Status"},
        {key1: "WorkplacePortal.view.ServiceDeskRequestList", key2: "{0} Tap {1} to add a new request.{2}", value: "{0} Tippen Sie auf {1}, um eine neue Anforderung hinzuzufügen.{2}"},
        {key1: "WorkplacePortal.view.ServiceRequestList", key2: "Requests", value: "Anforderungen"},
        {key1: "WorkplacePortal.view.WorkplaceServicesList", key2: "Workplace Services Portal", value: "Workplace-Services-Portal"}
    ]
};
