var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.it = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Accettare la richiesta del browser di memorizzare i dati sul computer locale e aggiornare la pagina."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Errore nel caricamento del file di configurazione."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Il controller '{0}' non dispone di un metodo di avvio. Estenderlo da Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Formato del valore non valido:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Il valore non è un indirizzo e-mail valido:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Il valore non è un valore accettabile:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Questo valore non è incluso nell’elenco di valori accettabili:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Lunghezza del valore non valida:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Questo valore deve essere presente:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Allega"},
        {key1: "Common.control.Camera", key2: "Close", value: "Chiudi"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Cancella"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Fine"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Caricamento in corso..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Correggere quanto segue:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Errore scansione"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Fine"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Nessun dato da visualizzare per: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Mostra"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Nessun {0} da visualizzare"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Richiesta"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Ore"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuti"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Caricamento elemento {0} di {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Edifici"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Edifici"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Codice contatto"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Nome"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Cognome"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nome:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contatto"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Codice contatto"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Codice reparto"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Codice reparto:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Reparti"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Codice divisione"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Codice divisione:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Divisione"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Codice divisione"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Divisione:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisioni"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Dipendente"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Codice dipendente"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standard dipendente"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Apparecchiatura"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Codice apparecchiatura"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standard apparecchiature"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Apparecchiatura:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standard apparecchiature"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standard apparecchiature"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Piano"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Codice piano:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Piano"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Codice piano:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Piano:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Piani"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Tipo di problema"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Proprietà"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Codice proprietà"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Proprietà:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Edificio/piano:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Codice locale"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Codice locale:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Locali"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categoria:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Categorie di locale"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Categoria locale"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Piano"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Codice piano:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Piano:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Locale"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Codice locale"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Codice locale:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Locale:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Locali"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standard di locale"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standard"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categoria:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Categoria locale"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Tipo di locale"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Tipi di locale"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Tipo:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Sito"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Codice sito"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Sito:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Siti"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Non sono presenti ricerche precedenti salvate."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Cancella"},
        {key1: "Common.control.Signature", key2: "Done", value: "Fine"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Firma"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "È necessario fornire un parametro ref config mainView quando si amplia la classe Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annulla"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Salva"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Continuare?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Si è verificato un errore di annullamento della registrazione del dispositivo. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "La disconnessione non rimuove i dati dall’applicazione.<br>È necessario registrare nuovamente il dispositivo per accedere alle app."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registrazione"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registrazione non riuscita"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Servizio di registrazione dispositivi non disponibile. I servizi mobili potrebbero non essere abilitati in Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Modello con nome [{0}] inesistente."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Lettura codici a barre non disponibile"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Autorizzazione di accesso alle informazioni della posizione negata"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La posizione non è disponibile"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Timeout posizione"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Errore posizione sconosciuta"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Si è verificato un errore durante la visualizzazione del documento"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Visualizzazione documento"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Download del documento"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Funzione non disponibile in ambiente desktop."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Il file non esiste"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Impossibile visualizzare il file {0} su questo dispositivo."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Impossibile visualizzare il file {0} in modalità desktop."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Rimozione del documento"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Campo modificato: {0} nuovo valore: {1} vecchio valore: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Input"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Input per il campo {0} limitato a {1} caratteri"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annulla"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Cancella"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copia"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Fine"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Errore"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "No"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Incolla"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Ricarica"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nome del locale"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Nomi locali"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Salva immagine"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Rilievo"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Sì"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Carica altro..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Nessun altro record"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Carica altro..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Nessun altro record"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "L’applicazione è stata aggiornata all’ultima versione. Ricaricare l’applicazione."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Errore durante il caricamento dei servizi di rete. La connessione di rete potrebbe essere lenta o non disponibile"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Connessione di rete non disponibile"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Nessun dato ricevuto dal server"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Timeout"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Errore sconosciuto"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Errore durante la registrazione del dispositivo"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Errore nel recupero delle informazioni utente."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Errore nella definizione delle impostazioni internazionali della sessione."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Errore nell'avvio della sessione utente."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Errore di accesso singolo"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Errore durante il recupero di TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Dispositivo non registrato."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flusso di lavoro toJSON. Non è consentito effettuare il marshalling degli oggetti data mediante le regole del flusso di lavoro."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Regola flusso di lavoro eseguita"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Regola del flusso di lavoro non riuscita:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Preferenze app"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Edifici"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Tipi causa"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contatti"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Reparti"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisioni"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Dipendenti"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standard dipendenti"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Apparecchiatura"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standard apparecchiature"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Piani"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Area infortunata"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Categorie infortuni"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Tipologie incidente"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Gruppi tipo di piano"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Tipi di piani"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Tipi di problema"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Progetti"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Proprietà"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Errore database:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Nessuna modifica tabella di database applicata. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Nessun aggiornamento di valore predefinito per il campo: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Aggiorna valore predefinito: campo [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Errore proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Errore proxy Sqlite durante la creazione dell’operazione"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Errore proxy Sqlite durante l’eliminazione dell’operazione"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Errore proxy Sqlite durante la lettura dell’operazione"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Errore proxy Sqlite durante l’aggiornamento dell’operazione"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Errore durante l’apertura del database: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Errore database [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Errore database in proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView è di sola lettura e non supporta l'eliminazione dei record"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView è di sola lettura e non supporta l'aggiornamento dei record"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqlliteView è di sola lettura e non supporta la creazione dei record"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "Il database non contiene le definizioni della tabella richieste per la vista Sqlite {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Tipi di riparazione"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Categorie di locale"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Locali"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standard locali"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Tipi di locale"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Utilizzo locali"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Siti"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "file_non_disponibile"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Sincronizzazione"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Download in corso"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Errore"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Le preferenze applicazione non sono state caricate"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Esecuzione in modalità browser. Accesso al file system disattivato"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Esecuzione in Chrome o in WebView. Accesso al file system attivato"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Accesso al file interrotto"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "File esistente"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Errore codifica file"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Errore file"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Stato del file non valido"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Modifica del file non consentita"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Quota file superata"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Errore sicurezza file"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Errore corrispondenza tipo di file"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "File non trovato"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "File non leggibile"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Errore modifica file non valida"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Connessione di rete non disponibile"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Rete non raggiungibile"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Download dei dati background"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Errore"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "L'archivio Preferenze app non è caricato. Impossibile recuperare le preferenze"},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "m"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pd2"},
        {key1: "Common.util.Units", key2: "sq m", value: "m2"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Le informazioni sul profilo utente non sono disponibili. Eseguire la sincronizzazione per recuperare i dati del profilo utente."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Elimina alla sincronizzazione"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Visualizza"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documenti"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Nessun documento disponibile."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} di {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 di x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Il nome della classe Modello associata a questa visualizzazione deve essere indicato nella proprietà del modello"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "L'ID archivio della classe Archivio associata a questa visualizzazione deve essere indicato nella proprietà storeId"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Cancella"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtro"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Indietro"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Salva"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Campo"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identificatore"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Dimensioni (byte)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Messaggi sincronizzazione"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabella"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "I seguenti valori di campo di Web Central non sono stati scritti nel database del client, poiché le dimensioni dei dati superavano il limite del database"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Imposta filtro"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Eliminare l’oggetto?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Immettere il contenuto della casella di testo:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Planimetria non disponibile"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Copia"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Incolla"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Ricarica"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Salva immagine"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Eliminare la voce?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Modifica"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Nessuna planimetria disponibile per linee rosse"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Pubblica date"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Mappe del sito"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Planimetria"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Annotazione"},
        {key1: "Space.model.SpaceSurvey", key2: " can only consist of alpha-numeric characters.", value: "può essere costituito solo da caratteri alfanumerici."},
        {key1: "Space.SpaceDownload", key2: "Download Floor Plans", value: "Scarica planimetrie"},
        {key1: "Space.SpaceDownload", key2: "Downloaded plans for {0} floors.", value: "Piante scaricate per {0} piani."},
        {key1: "Space.SpaceDownload", key2: "Downloading Site Maps", value: "Download delle mappe del sito"},
        {key1: "Space.SpaceDownload", key2: "Floor Plan download was cancelled.", value: "Download della planimetria annullato."},
        {key1: "Space.SpaceDownload", key2: "Floor Plans", value: "Planimetrie"},
        {key1: "Space.SpaceDownload", key2: "Loading Plans for Floor {0} of {1}", value: "Caricamento piante per piano {0} di {1}"},
        {key1: "Space.SpaceDownload", key2: "No active plan types found.", value: "Impossibile trovare tipi di piani attivi."},
        {key1: "Space.SpaceDownload", key2: "No Floor Plans available to download", value: "Nessuna planimetria disponibile per il download"},
        {key1: "Space.SpaceDownload", key2: "No plan types found", value: "Nessun tipo di piano trovato."},
        {key1: "Space.SpaceDownload", key2: "Not all {0} floors of the selected buildings have floor plans available.", value: "Non tutti i piani {0} degli edifici selezionati hanno planimetrie disponibili."},
        {key1: "Space.SpaceDownload", key2: "Use the {0} icon to download your list of floors and buildings before downloading floor plans.", value: "Utilizzare l’icona {0} per scaricare l’elenco di piani ed edifici prima di scaricare le piante dei piani."},
        {key1: "Space.SpaceDownload", key2: "You are going to download plans for {0} floors and this action may take some time. Proceed?", value: "Si stanno per scaricare le planimetrie per i piani {0} e questa azione potrebbe richiedere alcuni minuti. Continuare?"},
        {key1: "Space.SpaceFloorPlan", key2: "Floor Plans", value: "Planimetrie"},
        {key1: "Space.SpaceFloorPlan", key2: "Rooms", value: "Locali"},
        {key1: "Space.SpaceFloorPlan", key2: "The Plan Type data is not loaded.", value: "I dati tipo di piano non sono caricati."},
        {key1: "Space.SpaceSurvey", key2: "There is no Room data available for the selected Room.<br>Tap the {0} icon and select \\'Add to Survey\\' to update the Room data.", value: "Non sono presenti dati locale per il locale selezionato.<br>Toccare l’icona {0} e selezionare \\'Aggiungi a rilievo\\' per aggiornare i dati del locale."},
        {key1: "Space.SpaceSurvey", key2: "There is not an active survey for this floor.<br>To initiate a survey, tap the {0} icon and select \\'Start Survey\\'.", value: "Non sono presenti rilievi attivi per questo piano.<br>Per avviare un rilievo, toccare l’icona {0} e selezionare \\'Avvia rilievo\\'."},
        {key1: "Space.store.Buildings", key2: "Buildings", value: "Edifici"},
        {key1: "Space.store.DownloadActions", key2: "Download Floor Plans", value: "Scarica planimetrie"},
        {key1: "Space.store.Floors", key2: "Floors", value: "Piani"},
        {key1: "Space.store.RoomSurveys", key2: "Rooms", value: "Locali"},
        {key1: "Space.store.Sites", key2: "Buildings Without a Site Assigned", value: "Edifici senza sito assegnato"},
        {key1: "Space.store.Sites", key2: "Sites", value: "Siti"},
        {key1: "Space.store.SpaceSurveys", key2: "Surveys", value: "Rilievi"},
        {key1: "Space.store.SurveyActions", key2: "Add to Survey", value: "Aggiunta a rilievo"},
        {key1: "Space.store.SurveyActions", key2: "Close Survey", value: "Chiusura rilievo"},
        {key1: "Space.store.SurveyActions", key2: "Complete Survey", value: "Rilievo completo"},
        {key1: "Space.store.SurveyActions", key2: "Start Survey", value: "Inizio rilievo"},
        {key1: "Space.store.UserGroups", key2: "User Groups", value: "Gruppi di utenti"},
        {key1: "Space.view.BuildingList", key2: "No buildings identified.", value: "Nessun edificio individuato."},
        {key1: "Space.view.FloorList", key2: "Floors", value: "Piani"},
        {key1: "Space.view.FloorList", key2: "No floors identified.", value: "Nessun piano identificato."},
        {key1: "Space.view.FloorList", key2: "Search Floors", value: "Cerca piani"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plan", value: "Planimetria"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plans", value: "Planimetrie"},
        {key1: "Space.view.FloorPlan", key2: "Room List", value: "Elenco dei locali"},
        {key1: "Space.view.Main", key2: "Apps", value: "App"},
        {key1: "Space.view.Main", key2: "Plan Types", value: "Tipi di piani"},
        {key1: "Space.view.report.Configuration", key2: "Address 1", value: "Indirizzo 1"},
        {key1: "Space.view.report.Configuration", key2: "Address 2", value: "Indirizzo 2"},
        {key1: "Space.view.report.Configuration", key2: "Building", value: "Edificio"},
        {key1: "Space.view.report.Configuration", key2: "Building Code", value: "Codice edificio"},
        {key1: "Space.view.report.Configuration", key2: "City", value: "Città"},
        {key1: "Space.view.report.Configuration", key2: "Country", value: "Paese"},
        {key1: "Space.view.report.Configuration", key2: "Department", value: "Reparto"},
        {key1: "Space.view.report.Configuration", key2: "Division", value: "Divisione"},
        {key1: "Space.view.report.Configuration", key2: "Email", value: "E-mail"},
        {key1: "Space.view.report.Configuration", key2: "Employee ID", value: "Codice dipendente"},
        {key1: "Space.view.report.Configuration", key2: "Employee Information", value: "Informazioni per i dipendenti"},
        {key1: "Space.view.report.Configuration", key2: "First Name", value: "Nome"},
        {key1: "Space.view.report.Configuration", key2: "Floor", value: "Piano"},
        {key1: "Space.view.report.Configuration", key2: "Floor Name", value: "Nome piano"},
        {key1: "Space.view.report.Configuration", key2: "Last Name", value: "Cognome"},
        {key1: "Space.view.report.Configuration", key2: "Phone", value: "Telefono"},
        {key1: "Space.view.report.Configuration", key2: "Room", value: "Locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Area", value: "Area del locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Category", value: "Categoria locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Information", value: "Informazioni sul locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Name", value: "Nome del locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Phone", value: "Telefono locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Standard", value: "Standard di locale"},
        {key1: "Space.view.report.Configuration", key2: "Room Type", value: "Tipo di locale"},
        {key1: "Space.view.report.Configuration", key2: "Site Code", value: "Codice sito"},
        {key1: "Space.view.report.Configuration", key2: "State", value: "Stato o Provincia"},
        {key1: "Space.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} Non sono presenti voci rilievo per il piano selezionato.<br> Toccare l’icona {1} e selezionare \\'Avvia rilievo\\' o \\'Aggiungi a rilievo\\' per generare voci rilievo per questo piano.{2}"},
        {key1: "Space.view.Site", key2: "Buildings", value: "Edifici"},
        {key1: "Space.view.Site", key2: "List View", value: "Visualizzazione elenco"},
        {key1: "Space.view.Site", key2: "Site Plan", value: "Piano del sito"},
        {key1: "Space.view.SiteList", key2: "No sites identified.", value: "Nessun sito individuato."},
        {key1: "Space.view.SiteList", key2: "Sites", value: "Siti"},
        {key1: "Space.view.StartSurvey", key2: "Start", value: "Inizio"},
        {key1: "Space.view.StartSurvey", key2: "Start Survey", value: "Inizio rilievo"},
        {key1: "Space.view.StartSurvey", key2: "Survey Code", value: "Codice rilievo"},
        {key1: "Space.view.StartSurvey", key2: "Survey Name", value: "Nome rilievo"},
        {key1: "Space.view.StartSurvey", key2: "Surveyor", value: "Geometra"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Codici edifici"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Attach photo", value: "Allega foto"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Attaching image", value: "Associazione immagine in corso"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Attaching photo", value: "Associazione foto in corso"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Error", value: "Errore"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Overwrite existing photo?", value: "Sovrascrivere la foto esistente?"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Are you sure you want to delete this employee from this room?", value: "Eliminare il dipendente da questo locale?"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Are you sure you want to delete this transaction?", value: "Eliminare questa transazione?"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Cancel", value: "Annulla"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Delete", value: "Elimina"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Delete employee location", value: "Elimina posizione dipendente"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Different employee location.", value: "Posizione dipendente diversa."},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Error", value: "Errore"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "For the employee you are about to work with, is this their primary or non-primary location?", value: "Per il dipendente con cui si sta per lavorare questa è la posizione primaria o non primaria?"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "New Employee", value: "Nuovo dipendente"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Non-Primary", value: "Non primario"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Pre-survey employee information is not available for this room.", value: "Indagine preventiva sulle informazioni del dipendente non disponibile per questo locale."},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Primary", value: "Primario"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "The Reconcile Workspace Transactions action must be run on Web Central.", value: "L'azione Riconcilia archivio ri-allocazioni degli spazi di lavoro deve essere eseguita in Web Central."},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "There is no employee assigned to this room.", value: "Nessun dipendente assegnato al locale."},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "There is no transaction for this room.", value: "Nessuna ri-allocazione per questa locale."},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "This action will add a new employee to the employee table. Do you want to continue?", value: "Questa azione comporterà l’aggiunta di un nuovo dipendente alla tabella dei dipendenti. Continuare?"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "This employee is currently assigned to building {0}, floor {1} and room {2}. Do you want to move this employee to the new location?", value: "Dipendente attualmente assegnato all’edificio {0}, piano {1} e locale {2}. Spostare il dipendente nella nuova posizione?"},
        {key1: "SpaceOccupancy.controller.Navigation", key2: "Use the form above to edit primary room information.", value: "Utilizzare il modello riportato sopra per modificare le informazioni sul locale primario."},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Building Code", value: "Codice edificio"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Building:", value: "Edificio:"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Floor Code", value: "Codice piano"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Floor:", value: "Piano:"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Room Code", value: "Codice locale"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Room Standard", value: "Standard di locale"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Room:", value: "Locale:"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Select Room", value: "Seleziona locale"},
        {key1: "SpaceOccupancy.controller.Documents", key2: "Standard:", value: "Standard:"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Add to Survey", value: "Aggiunta a rilievo"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Close Survey", value: "Chiusura rilievo"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Error", value: "Errore"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Error Closing the Survey", value: "Errore durante la chiusura del rilievo"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Error copying room and room transaction records", value: "Errore durante la copia dei record della locale e della variazione dello stato della locale"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Photos for the following employees could not be saved on the device: {0}", value: "Impossibile salvare nel dispositivo le foto dei seguenti dipendenti: {0}"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Start Survey", value: "Inizio rilievo"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Sync Survey", value: "Sincronizzazione rilievo"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "The Percentage of Space values for the workspace transaction records for current date range do not add up to 100% for some rooms and they need to be adjusted in Web Central.", value: "I valori di percentuale di spazio dei record di ri-allocazione dello spazio di lavoro per l’intervallo di date corrente non raggiungono il 100% per alcuni locali, che devono essere regolati in Web Central."},
        {key1: "SpaceOccupancy.controller.Survey", key2: "The system will update the inventory based on standard Web Central Workspace Transaction processes.<br>Proceed?", value: "Il sistema aggiornerà l'inventario in base ai processi standard di ri-allocazione degli spazi di lavoro di Web Central.<br>Procedere?"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "The system will update the inventory.<br>Proceed?", value: "Il sistema aggiornerà l’inventario.<br>Procedere?"},
        {key1: "SpaceOccupancy.controller.Survey", key2: "There exists workspace transaction records that contain different primary room attributes: {0}.", value: "Sono presenti record di ri-allocazione degli spazi di lavoro che contengono attributi di locali primari: {0}."},
        {key1: "SpaceOccupancy.controller.Survey", key2: "Update Floor Plans", value: "Aggiornamento planimetrie"},
        {key1: "SpaceOccupancy.model.RoomPct", key2: "The value of Percentage Split cannot be bigger than 100.", value: "Il valore di % occupazione reale non può essere superiore a 100."},
        {key1: "SpaceOccupancy.model.RoomPct", key2: "The value of Percentage Split cannot be negative.", value: "Il valore di % occupazione reale non può essere negativo."},
        {key1: "SpaceOccupancy.model.RoomPct", key2: "The value of Percentage Split needs to be numeric.", value: "Il valore di % occupazione reale deve essere numerico."},
        {key1: "SpaceOccupancy.model.RoomPct", key2: "{0} must be after {1}.", value: "{0} deve essere successivo a {1}."},
        {key1: "SpaceOccupancy.store.EmployeesSurvey", key2: "Employees", value: "Dipendenti"},
        {key1: "SpaceOccupancy.store.OccupancyRoomSurveys", key2: "Rooms", value: "Locali"},
        {key1: "SpaceOccupancy.store.RoomPcts", key2: "Room Percentanges", value: "Percentuali del locale"},
        {key1: "SpaceOccupancy.store.Rooms", key2: "Rooms", value: "Locali"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "%", value: "%"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "A record with the same Employee Name already exists.", value: "Esiste già un record con lo stesso Nome dipendente."},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Can't delete this record in this view. Please delete the record from the room or employee survey forms or from Web Central.", value: "Impossibile eliminare questo record in questa vista. Eliminare il record dai moduli di rilievo del locale o del dipendente o da Web Central."},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Category/ Type", value: "Categoria/Tipo"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Division/ Department", value: "Divisione/dipartimento"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Duplicate record", value: "Record duplicato"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Employee", value: "Dipendente"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Error", value: "Errore"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Even %", value: "% occupazione ideale"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Total", value: "Totale"},
        {key1: "SpaceOccupancy.util.NavigationHelper", key2: "Transaction #", value: "N. ri-allocazione"},
        {key1: "SpaceOccupancy.util.Ui", key2: "Active Survey:", value: "Rilievo attivo:"},
        {key1: "SpaceOccupancy.util.Ui", key2: "Download Floor Plans", value: "Scarica planimetrie"},
        {key1: "SpaceOccupancy.util.Ui", key2: "Room", value: "Locale"},
        {key1: "SpaceOccupancy.view.CategoryList", key2: "Survey Categories", value: "Categorie rilievo"},
        {key1: "SpaceOccupancy.view.CategoryListItem", key2: "(P)", value: "(P)"},
        {key1: "SpaceOccupancy.view.DepartmentList", key2: "Survey Departments", value: "Reparti rilievo"},
        {key1: "SpaceOccupancy.view.DepartmentListItem", key2: "(P)", value: "(P)"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Department", value: "Reparto"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Division", value: "Divisione"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Email", value: "E-mail"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Employee Edit Form", value: "Modulo modifica dipendente"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Name First", value: "Nome - Primo"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Name Last", value: "Nome - Ultimo"},
        {key1: "SpaceOccupancy.view.EmployeeEdit", key2: "Phone", value: "Telefono"},
        {key1: "SpaceOccupancy.view.EmployeeList", key2: "Survey Employees", value: "Censimento impiegati"},
        {key1: "SpaceOccupancy.view.EmployeeListItem", key2: "(P)", value: "(P)"},
        {key1: "SpaceOccupancy.view.EmployeePromptList", key2: "Employees", value: "Dipendenti"},
        {key1: "SpaceOccupancy.view.EmployeePromptList", key2: "No employee data to display", value: "Non sono presenti dati del dipendente da visualizzare"},
        {key1: "SpaceOccupancy.view.RoomForm", key2: "Capacity", value: "Capacità"},
        {key1: "SpaceOccupancy.view.RoomForm", key2: "Department", value: "Reparto"},
        {key1: "SpaceOccupancy.view.RoomForm", key2: "Division", value: "Divisione"},
        {key1: "SpaceOccupancy.view.RoomForm", key2: "Survey Comments", value: "Commenti rilievo"},
        {key1: "SpaceOccupancy.view.RoomList", key2: "Loading...", value: "Caricamento in corso..."},
        {key1: "SpaceOccupancy.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} Non sono presenti voci rilievo per il piano selezionato.<br> Toccare l’icona {1} e selezionare \\'Avvia rilievo\\' o \\'Aggiungi a rilievo\\' per generare voci rilievo per questo piano.{2}"},
        {key1: "SpaceOccupancy.view.RoomSurvey", key2: "Complete", value: "Completato"},
        {key1: "SpaceOccupancy.view.RoomSurvey", key2: "Documents", value: "Documenti"},
        {key1: "SpaceOccupancy.view.RoomSurvey", key2: "Survey Room", value: "Esegui rilievo locale"},
        {key1: "SpaceOccupancy.view.RoomSurvey", key2: "Workspace Transactions", value: "Archivio ri-allocazioni degli spazi di lavoro"},
        {key1: "SpaceOccupancy.view.TransactionEdit", key2: "Transactions", value: "Ri-allocazioni"},
        {key1: "SpaceOccupancy.view.TransactionForm", key2: "Department", value: "Reparto"},
        {key1: "SpaceOccupancy.view.TransactionForm", key2: "Division", value: "Divisione"},
        {key1: "SpaceOccupancy.view.TransactionForm", key2: "Employee", value: "Dipendente"},
        {key1: "SpaceOccupancy.view.TransactionForm", key2: "Primary Employee", value: "Dipendente primario"},
        {key1: "SpaceOccupancy.view.TransactionForm", key2: "Transaction Code", value: "Codice ri-allocazione"},
        {key1: "SpaceOccupancy.view.TransactionList", key2: "Workspace Transactions", value: "Archivio ri-allocazioni degli spazi di lavoro"},
        {key1: "SpaceOccupancy.view.TransactionListItem", key2: "(P)", value: "(P)"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Category", value: "Categoria"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Department", value: "Reparto"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Division", value: "Divisione"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Employee", value: "Dipendente"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "End Date", value: "Data di fine"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Percentage of Space", value: "Percentuale spazio"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Start Date", value: "Data di inizio"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Transaction Code", value: "Codice ri-allocazione"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Transaction Information", value: "Informazioni transazione"},
        {key1: "SpaceOccupancy.view.TransactionsReport", key2: "Type", value: "Tipo"},
    ]
};
