package com.archibus.app.solution.common.webservice.document.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.*;

/**
 * This class was generated by Apache CXF 2.2.3 Fri Nov 20 09:44:01 EST 2009 Generated source
 * version: 2.2.3
 * 
 */

@WebServiceClient(name = "Copy", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
public class CopyServiceProxy extends Service {

    public final static QName SERVICE = new QName("http://schemas.microsoft.com/sharepoint/soap/",
        "Copy");

    public final static QName CopySoap = new QName("http://schemas.microsoft.com/sharepoint/soap/",
        "CopySoap");

    public final static QName CopySoap12 = new QName(
        "http://schemas.microsoft.com/sharepoint/soap/", "CopySoap12");

    public CopyServiceProxy(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CopyServiceProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return returns CopySoap
     */
    @WebEndpoint(name = "CopySoap")
    public CopySoapPort getCopySoap() {
        return super.getPort(CopySoap, CopySoapPort.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *            Supported features not in the <code>features</code> parameter will have their
     *            default values.
     * @return returns CopySoap
     */
    @WebEndpoint(name = "CopySoap")
    public CopySoapPort getCopySoap(WebServiceFeature... features) {
        return super.getPort(CopySoap, CopySoapPort.class, features);
    }

    /**
     * 
     * @return returns CopySoap
     */
    @WebEndpoint(name = "CopySoap12")
    public CopySoapPort getCopySoap12() {
        return super.getPort(CopySoap12, CopySoapPort.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *            Supported features not in the <code>features</code> parameter will have their
     *            default values.
     * @return returns CopySoap
     */
    @WebEndpoint(name = "CopySoap12")
    public CopySoapPort getCopySoap12(WebServiceFeature... features) {
        return super.getPort(CopySoap12, CopySoapPort.class, features);
    }

}
