var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.fr = {
    localizedStrings: [
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "An error occured while executing the workflow rule.", value: "Une erreur s’est produite pendant l’exécution de la règle de workflow."},
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "Error", value: "Erreur"},
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "Not all records were saved because other assets with the same codes already exist in the inventory.", value: "Les enregistrements n’ont pas été tous sauvegardés car d’autres actifs dotés des mêmes codes existent déjà dans l’inventaire."},
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "Searching", value: "Recherche en cours"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Add Equipment", value: "Ajouter un équipement"},
        {key1: "AssetReceipt.controller.Navigation", key2: "An error occured while executing the workflow rule.", value: "Une erreur s’est produite pendant l’exécution de la règle de workflow."},
        {key1: "AssetReceipt.controller.Navigation", key2: "An error occured while quering the database.", value: "Une erreur s’est produite pendant l’interrogation de la base de données."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete", value: "Supprimer"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete ALL assets?", value: "Supprimer TOUS les actifs ?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete asset?", value: "Supprimer l’actif ?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete equipment standard?", value: "Supprimer le standard d’équipement ?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete selected asset(s)?", value: "Supprimer le ou les actifs sélectionnés ?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Done", value: "Terminé"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Enter an equipment code first.", value: "Saisissez d’abord un code équipement."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Equipment with code {0} already exists in inventory.", value: "L’équipement dont le code est {0} existe déjà dans l’inventaire."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Equipment with code {0} does not exist in inventory.", value: "L’équipement dont le code est {0} n’existe pas dans l’inventaire."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Error", value: "Erreur"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Next", value: "Suivant"},
        {key1: "AssetReceipt.controller.Navigation", key2: "No equipment found for selected prefix.", value: "Aucun équipement trouvé pour le préfixe sélectionné."},
        {key1: "AssetReceipt.controller.Navigation", key2: "No records have been created and no additional records will be created. Proceed with cancel action?", value: "Aucun enregistrement n’a été créé et aucun enregistrement supplémentaire ne le sera. Poursuivre l’action d’annulation ?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Only asset codes with {0} characters or less are supported. Codes with more than {0} characters will be truncated.", value: "Seuls les codes d’actifs comprenant un maximum de {0} caractères sont pris en charge. Les codes de plus de {0} caractères seront tronqués."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Please select Get Last Number field to verify there are no existing records for the selected Prefix. Trying to create records with existing values will generate errors.", value: "Veuillez sélectionner le champ Obtenir le dernier numéro pour vérifier qu’il n’existe aucun enregistrement pour le préfixe sélectionné. Des erreurs seront générées si vous essayez de créer des enregistrements déjà existant."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Please wait while we generate your new assets:<br/> {0} / {1}", value: "Veuillez patienter, nous générons les nouveaux actifs :<br/> {0} / {1}"},
        {key1: "AssetReceipt.controller.Navigation", key2: "The records numbered {0} - {1} have been created and no additional records will be created. Proceed with cancel action?", value: "Les enregistrements numérotés de {0} à {1} ont été créés. Aucun enregistrement supplémentaire ne sera créé. Poursuivre l’action d’annulation ?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "This equipment standard already exists: {0}", value: "Ce standard d’équipement existe déjà : {0}"},
        {key1: "AssetReceipt.controller.Navigation", key2: "This standard cannot be deleted because there are equipment items registered with this standard.", value: "Impossible de supprimer ce standard car des équipements y sont enregistrés."},
        {key1: "AssetReceipt.controller.Navigation", key2: "You have already added equipment with the following codes: {0}", value: "Vous avez déjà ajouté des équipements dont les codes sont {0}"},
        {key1: "AssetReceipt.controller.Navigation", key2: "You need to set the code for the first asset. Please fill the value for Start Number.", value: "Vous devez définir le code du premier actif. Veuillez renseigner Premier numéro."},
        {key1: "AssetReceipt.controller.Navigation", key2: "You need to set the number of assets you want to add. Please fill the value for Total Count.", value: "Vous devez définir le nombre d’actifs que vous voulez ajouter. Veuillez renseigner Décompte Total."},
        {key1: "AssetReceipt.store.AssetReceiptEmployees", key2: "Employees", value: "Employés"},
        {key1: "AssetReceipt.store.AssetReceiptEquipment", key2: "Equipment", value: "Equipement"},
        {key1: "AssetReceipt.store.AssetReceiptFloors", key2: "Floors", value: "Etages"},
        {key1: "AssetReceipt.store.AssetReceiptRooms", key2: "Rooms", value: "Pièces"},
        {key1: "AssetReceipt.store.EquipmentStandardsSync", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "AssetReceipt.util.Filter", key2: "Download times may be high if just the site is selected. Proceed?", value: "Les temps de téléchargement peuvent être élevés si vous sélectionnez uniquement le site. Continuer ?"},
        {key1: "AssetReceipt.util.Filter", key2: "Please select values for Site Code and Building Code.", value: "Sélectionnez les valeurs du code Site et du code Bâtiment."},
        {key1: "AssetReceipt.view.BackgroundDataFilter", key2: "Asset Inventory", value: "Inventaire d’actifs"},
        {key1: "AssetReceipt.view.CommonData", key2: "Barcode scanning", value: "Lecture de codes-barres"},
        {key1: "AssetReceipt.view.CommonData", key2: "Building", value: "Bâtiment"},
        {key1: "AssetReceipt.view.CommonData", key2: "Comments", value: "Commentaires"},
        {key1: "AssetReceipt.view.CommonData", key2: "Common Asset Data", value: "Données d’actifs communes"},
        {key1: "AssetReceipt.view.CommonData", key2: "Department", value: "Département"},
        {key1: "AssetReceipt.view.CommonData", key2: "Departments", value: "Départements"},
        {key1: "AssetReceipt.view.CommonData", key2: "Division", value: "Division"},
        {key1: "AssetReceipt.view.CommonData", key2: "Divisions", value: "Divisions"},
        {key1: "AssetReceipt.view.CommonData", key2: "Employee", value: "Employé"},
        {key1: "AssetReceipt.view.CommonData", key2: "Employees", value: "Employés"},
        {key1: "AssetReceipt.view.CommonData", key2: "Floor", value: "Etage"},
        {key1: "AssetReceipt.view.CommonData", key2: "Get Last Number", value: "Obtenir le dernier numéro"},
        {key1: "AssetReceipt.view.CommonData", key2: "Incremented Codes", value: "Codes incrémentés"},
        {key1: "AssetReceipt.view.CommonData", key2: "Inventory Method", value: "Méthode d’inventaire"},
        {key1: "AssetReceipt.view.CommonData", key2: "Prefix", value: "Préfixe"},
        {key1: "AssetReceipt.view.CommonData", key2: "Room", value: "Pièce"},
        {key1: "AssetReceipt.view.CommonData", key2: "Start Number", value: "Premier numéro"},
        {key1: "AssetReceipt.view.CommonData", key2: "Total Count", value: "Décompte Total"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Building:", value: "Bâtiment :"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Employee:", value: "Employé :"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Floor:", value: "Etage :"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Room:", value: "Pièce :"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "1 of x", value: "1 sur x"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Building", value: "Bâtiment"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Comments", value: "Commentaires"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Department", value: "Département"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Departments", value: "Départements"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Division", value: "Division"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Divisions", value: "Divisions"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Edit Equipment", value: "Editer l’Equipement"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Employee", value: "Employé"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Employees", value: "Employés"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Floor", value: "Etage"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Room", value: "Pièce"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "{0} of {1}", value: "{0} de {1}"},
        {key1: "AssetReceipt.view.EditEquipmentStandard", key2: "Add Standard", value: "Ajouter un standard"},
        {key1: "AssetReceipt.view.EquipmentStandardPromptListItem", key2: "Description:", value: "Description :"},
        {key1: "AssetReceipt.view.EquipmentStandardPromptListItem", key2: "Standard:", value: "Standard :"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Asset Inventory List", value: "Liste d’inventaire d’actifs"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Complete", value: "Terminer"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Delete ALL", value: "Tout supprimer"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Delete Selected", value: "Supprimer la sélection"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Location", value: "Localisation"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Owner", value: "Propriétaire"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Standard", value: "Standard"},
        {key1: "AssetReceipt.view.Main", key2: "Apps", value: "Applications"},
        {key1: "AssetReceipt.view.Options", key2: "Add an Asset", value: "Ajouter un actif"},
        {key1: "AssetReceipt.view.Options", key2: "Add Multiple Assets", value: "Ajouter plusieurs actifs"},
        {key1: "AssetReceipt.view.Options", key2: "Asset Inventory", value: "Inventaire d’actifs"},
        {key1: "AssetReceipt.view.Options", key2: "Review New Assets", value: "Examiner les nouveaux actifs"},
        {key1: "AssetReceipt.view.Options", key2: "Search for Existing Asset:", value: "Recherchez un actif existant :"},
        {key1: "AssetReceipt.view.Options", key2: "{0}To use this App, tap {1} to download background data{2}", value: "{0}Pour utiliser cette application, appuyez sur {1} pour télécharger les données fondamentales{2}"},
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Acceptez la demande du navigateur pour stocker les données sur votre ordinateur local et actualiser la page."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Erreur lors du chargement du fichier de configuration."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Le contrôleur « {0} » n'est associé à aucune méthode de lancement. Êtes-vous sûr qu'il s'étend à partir du paramètre Ext.app.Controller ?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Le format de cette valeur est incorrect :"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Cette valeur n’est pas un e-mail valide :"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Cette valeur n’est pas acceptable :"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Cette valeur ne figure pas dans la liste des valeurs acceptables :"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "La longueur de cette valeur est incorrecte :"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Cette valeur doit être présente :"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Joindre"},
        {key1: "Common.control.Camera", key2: "Close", value: "Fermer"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Photo"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Effacer"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Terminé"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Chargement…"},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Veuillez corriger ce qui suit :"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Erreur d’analyse"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Terminé"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Aucune donnée à afficher pour : {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Appliquer"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Pas de {0} à afficher"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Demander"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Heures"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minutes"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Chargement de l'élément {0} sur {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code Contact"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Prénom"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nom de Famille"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nom :"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contact"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code Contact"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Code Département"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Code Département :"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Départements"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Code Division"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Code Division :"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Division"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Code Division"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Division :"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisions"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "Adresse Electronique"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail :"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Employé"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Code Employé"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standard d’Employé"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Code Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standard Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Equipement :"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standard Equipement"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Etages"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Propriétés"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code Propriété"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Propriété :"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Bâtiment/Étage :"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code Pièce"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Pièce :"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Pièces"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Catégorie :"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Catégories de Pièces"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Etage :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Pièce :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Pièce :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Pièces"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standard de Pièce"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Catégorie :"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type de Pièce"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Types de Pièces"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type :"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Code site"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site :"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Aucune recherche précédente n’a été enregistrée."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Effacer"},
        {key1: "Common.control.Signature", key2: "Done", value: "Terminé"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Signature"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Une configuration de réf. mainView doit être fournie lors de l'extension de la classe Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuler"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Sauvegarder"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Voulez-vous continuer ?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "L’erreur s’est produite lors de la désinscription de l’appareil. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "La déconnexion ne supprime pas vos données d’application.<br>Il vous faudra réinscrire l’appareil pour accéder aux applications."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Enregistrement"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Echec de l'enregistrement"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Le service d'enregistrement des appareils n'est pas disponible. Il se peut que les services mobiles ne soient pas activés dans Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Le modèle nommé [{0}] n'existe pas."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "La lecture de codes-barres n'est pas disponible."},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Autorisation d’accès aux informations d’emplacement refusée"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La position n’est pas disponible."},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Délai d’expiration de position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Erreur de poste inconnu"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Une erreur s’est produite pendant l’affichage du document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Affichage du document"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Téléchargement des documents"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "La fonction n’est pas disponible dans l’environnement de bureau."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Le fichier n’existe pas."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Le fichier {0} ne peut pas être affiché sur cet appareil."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Le fichier {0} ne peut pas être affiché en mode Bureau."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Suppression du document"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Champ modifié : {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Entrée"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "L’entrée du champ {0} est limitée à {1} caractères"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuler"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Effacer"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copier"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Terminé"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Erreur"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "NON"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Coller"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Recharger"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nom de Pièce"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "nom de pièces"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Enregistrer l’image"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Evaluation"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "OUI"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Chargement supplémentaire..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Pas d'autres enregistrements"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Chargement supplémentaire..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Pas d'autres enregistrements"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Cette application a été mise à jour à la dernière version. Rechargement de l’application."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Erreur lors du chargement des services réseau. Il se peut que la connexion réseau soit lente ou indisponible."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Aucune connexion réseau disponible"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Aucune donnée reçue du serveur"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Délai"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Erreur inconnue"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Erreur lors de l'enregistrement de l'appareil"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Erreur lors de la récupération des informations d'utilisateur."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Erreur lors de la définition des paramètres régionaux de la session."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Erreur lors du démarrage de la session d'utilisateur."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Erreur d'authentification unique"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Erreur lors de la récupération de TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "L’appareil n’est pas inscrit."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flux d'opérations en JSON. Les objets de date ne peunvent pas être triés à l'aide de règles de workflow."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Règle de Workflow exécutée"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Echec de la règle de workflow :"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Préférences d’application"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types de causes"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contacts"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Départements"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisions"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Employés"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standards d’Employés"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Equipement"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Etages"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Surfaces touchées"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Catégories de blessure"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Types d’accident"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Groupes de types de plan"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Types de plan"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Types de problèmes"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projets"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Propriétés"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Erreur de base de données :"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Aucune modification de table de base de données appliquée. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Aucune mise à jour de la valeur par défaut du champ : [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Mettre à jour la valeur par défaut : champ [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Erreur du proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Erreur du proxy Sqlite pendant l’opération de création"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Erreur du proxy Sqlite pendant l’opération de destruction"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Erreur du proxy Sqlite pendant l’opération de lecture"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Erreur du proxy Sqlite pendant l’opération de mise à jour"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Erreur d’ouverture de la base de données : {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Erreur de base de données [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Erreur de base de données dans le proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView est en lecture seule et ne prend pas en charge la suppression d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView est en lecture seule et ne prend pas en charge la mise à jour d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView est en lecture seule et ne prend pas en charge la création d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "La base de données ne contient pas les définitions de tables requises pour SqliteView. {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Types de réparations"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Catégories de Pièces"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Pièces"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standards de Pièces"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Types de Pièces"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Utilisations des Pièces"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "fichier_non_disponible"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisation"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Téléchargement"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Erreur"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Les préférences de l'application n'ont pas été chargées"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Exécution en mode navigateur Accès au système de fichiers désactivé"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Exécution dans Chrome ou en vue Web. Accès au système de fichiers activé"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "L'accès au fichier a été interrompu"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Le fichier existe déjà"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Erreur de codage du fichier"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Erreur du fichier"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Le fichier est dans un état non valide"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "La modification du fichier n'est pas autorisée"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Quota de fichiers dépassé"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Erreur de sécurité du fichier"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Erreur de disparité de type de fichier"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Fichier introuvable"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Fichier illisible"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Erreur de modification de fichier non valide"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Aucune connexion réseau disponible"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Réseau inaccessible"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Téléchargement des données fondamentales"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Erreur"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Le magasin des préférences d'application n'est pas chargé. Impossible de récupérer les préférences"},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pi2"},
        {key1: "Common.util.Units", key2: "sq m", value: "m2"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Les informations du profil d'utilisateur ne sont pas disponibles. Veuillez synchroniser pour récupérer les données du profil d'utilisateur."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Supprimer à la synchronisation"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Afficher"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documents"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Aucun document disponible."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} de {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 sur x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Le nom de la classe Model associée à cette vue doit être fourni dans la propriété model"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "L'ID de magasin de la classe de la classe Store associée à cette vue doit être fourni dans la propriété storeId"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Effacer"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtrer les données"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Précédent"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Sauvegarder"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Champ"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifiant"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Taille (octets)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Messages de synchronisation"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Table"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Les valeurs de champ de Web Central énumérées ci-après n'ont pas été écrites dans la base de données cliente, car la taille des données dépasse la limite de la base de données."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Définir le Filtre"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Codes Bâtiment"},
    ]
};
