var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.es = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Acepte la solicitud del explorador para almacenar datos en su equipo local y actualizar la página."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Error al cargar el archivo de configuración."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "El controlador '{0}' carece de método de inicio.¿Seguro que se extiende de Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Este valor tiene un formato incorrecto:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Este valor no es un correo electrónico válido:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Este no es un valor aceptable:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Este valor no se incluye en la lista de valores aceptables:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Este valor tiene una longitud incorrecta:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Este valor debe estar presente:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Adjuntar"},
        {key1: "Common.control.Camera", key2: "Close", value: "Cerrar"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Borrar"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Listo"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Cargando..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Corrija lo siguiente:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Error al examinar"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Listo"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "No hay datos que mostrar para: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Aplicar"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "No hay {0} que mostrar"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Solicitar"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Horas"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minutos"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Cargando elemento {0} de {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Edificios"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Edificios"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Código de contacto"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Nombre"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Apellido"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nombre:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contacto"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Código de contacto"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Código de departamento"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Departamento:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Departamentos"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Código de división"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "División:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "División"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Código de división"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "División:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisiones"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "Correo electrónico"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "Correo electrónico:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Empleado"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Código de empleado"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Estándar de empleado"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Equipos"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Código de equipo"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Estándares de equipo"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Equipo:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Estándares de equipo"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Estándares de equipo"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Edificio:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Planta"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Código de planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Código de planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Planta:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Plantas"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Tipo de problema"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Propiedad"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Código de propiedad"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Propiedad:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Edificio/Planta:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Código de espacio"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Espacio:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Espacios"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categoría:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Categorías de espacio"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Categoría del espacio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Planta"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Código de planta"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Planta:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Espacio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Código de espacio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Espacio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Espacio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Espacios"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Estándar de espacio"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Estándares"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categoría:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Categoría del espacio"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Tipo de espacio"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Tipos de espacio"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Tipo:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Sede"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Código de sede"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Sede:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sedes"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "No hay guardadas búsquedas anteriores."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Borrar"},
        {key1: "Common.control.Signature", key2: "Done", value: "Listo"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Firma"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Debe facilitarse una configuración de referencia mainView al ampliar la clase Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Guardar"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "¿Desea continuar?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Se ha producido un error al dar de baja el dispositivo. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Al cerrar sesión, no se eliminan los datos de la aplicación.<br>Tendrá que volver a registrar el dispositivo para acceder a las aplicaciones."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registro"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Fallo de registro"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "No está disponible el servicio de registro del dispositivo. Puede que los servicios Mobile no estén habilitados en Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "El modelo con el nombre [{0}] no existe."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "No está disponible el escaneado de códigos de barra"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Permiso denegado para acceder a información sobre ubicación"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La posición no está disponible"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Tiempo de espera de posición agotado"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Error de posición desconocido"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Se produjo un error al mostrar el documento"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Visualización de documentos"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Descargando documento"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Función no disponible en el entorno del escritorio."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "El archivo no existe"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "El archivo {0} no puede mostrarse en este dispositivo."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "El archivo {0} no puede mostrarse en modo Escritorio."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Quitando documento"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Campo cambiado: {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Entrada"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "La entrada para el campo {0} está limitada a {1} caracteres"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Borrar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copiar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Listo"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Error"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "No"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Pegar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Volver a cargar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nombre de espacio"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Nombres de espacios"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Guardar imagen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Inspección física"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Sí"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Cargar más..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "No hay más registros"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Cargar más..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "No hay más registros"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Esta aplicación se acaba de actualizar correctamente a su última versión. Recargando la aplicación."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Error al cargar servicios de red. Puede que la conexión de red no esté disponible o sea lenta"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "La conexión de red no está disponible"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "No se han recibido datos del servidor"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Tiempo de espera agotado"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Error desconocido"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Error al registrar dispositivo"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Error al recuperar información de usuario."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Error al establecer valor local de sesión."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Error al iniciar sesión de usuario."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Error de inicio de sesión única"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Error al recuperar TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Dispositivo no registrado."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flujo de trabajo toJSON. No está permitido organizar objetos de fecha usando reglas de flujo de trabajo."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Ejecutada regla de flujo de trabajo"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Fallo de regla de flujo de trabajo:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Preferencias de aplicación"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Edificios"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Tipos de causa"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contactos"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Operarios"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Departamentos"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisiones"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Empleados"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Estándares de empleado"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Equipos"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Estándares de equipo"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Plantas"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Zonas lesionadas"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Categorías de lesiones"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Tipos de incidentes"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Grupos de tipo de plano"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Tipos de plano"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Tipos de problema"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Proyectos"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Propiedades"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Error de base de datos:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "No se ha aplicado ningún cambio en la tabla de la base de datos. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "No se ha actualizado ningún valor predeterminado para el campo: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Actualizar valor predeterminado: campo [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Error de proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Error de proxy Sqlite durante operación de creación"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Error de proxy Sqlite durante operación de destrucción"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Error de proxy Sqlite durante operación de lectura"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Error de proxy Sqlite durante operación de actualización"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Error al abrir base de datos: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Error de base de datos [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Error de base de datos en proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView es de sólo lectura y no admite la eliminación de registros"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView es de sólo lectura y no admite la actualización de registros"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView es de sólo lectura y no admite la creación registros"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "La base de datos no contiene las definiciones de tabla requeridas para la vista {0} de Sqlite"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Tipos de reparación"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Categorías de espacio"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Espacios"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Estándares de espacio"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Tipos de espacio"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Usos del espacio"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sedes"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "archivo_no_disponible"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Sincronizando"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Descargando"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Error"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "No se han cargado las preferencias de la aplicación"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Ejecutando en modo de navegador. Acceso a sistema de archivos deshabilitado"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Ejecutando en Chrome o en WebView. Acceso a sistema de archivos habilitado"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Se ha abortado el acceso al campo"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "El archivo ya existe"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Error de codificación del archivo"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Error de archivo"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "El archivo presenta un estado no válido"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "No se permite la modificación del archivo"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Cuota de archivos superada"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Error de seguridad del archivo"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Error de falta de coincidencia del tipo de archivo"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "No se ha encontrado el archivo"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "No se pudo leer el archivo"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Error al modificar archivo no válido"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "La conexión de red no está disponible"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Red inaccesible"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Descargando datos de base"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Error"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "No se ha cargado el almacén de preferencias de la aplicación. No se pueden recuperar las preferencias"},
        {key1: "Common.util.Units", key2: "ft", value: "pies"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pies cuad."},
        {key1: "Common.util.Units", key2: "sq m", value: "m cuad."},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "La información del perfil de usuario no está disponible. Sincronice para recuperar los datos del perfil de usuario."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Eliminar al sincronizar"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Visualizar"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documentos"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "No hay documentos disponibles"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} de {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 de x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "El nombre de la clase de modelo asociado a esta vista debe facilitarse en la propiedad del modelo"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "El ID de almacén de la clase de almacén asociado a esta vista debe facilitarse en la propiedad de ID de almacén"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Borrar"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtro"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Atrás"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Guardar"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Campo"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identificador"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Tamaño (bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Mensajes de sincronización"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabla"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Los siguientes valores de campo de Web Central no se escribieron en la base de datos cliente porque el tamaño de los datos sobrepasaba el límite de la base de datos"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Establecer filtro"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Description", value: "Descripción"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Description:", value: "Descripción:"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Injury Area", value: "Zona lesionada"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Injury Area:", value: "Zona lesionada:"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Injury Areas", value: "Zonas lesionadas"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Description", value: "Descripción"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Description:", value: "Descripción:"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Injury Categories", value: "Categorías de lesiones"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Injury Category", value: "Categoría de lesión"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Injury Category:", value: "Categoría de lesión:"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Description", value: "Descripción"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Description:", value: "Descripción:"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Incident Type", value: "Tipo de incidente"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Incident Types", value: "Tipos de incidentes"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Injury Type:", value: "Tipo de lesión:"},
        {key1: "IncidentReporting.view.General", key2: "Description", value: "Descripción"},
        {key1: "IncidentReporting.view.General", key2: "Incident Type", value: "Tipo de incidente"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Are you sure you want to delete this photo?", value: "¿Seguro que desea eliminar esta foto?"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Delete Photo", value: "Eliminar foto"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Incident unavailable", value: "Incidente no disponible"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Please first save the incident.", value: "Guarde primero el incidente."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Are you sure you want to delete this incident?", value: "¿Seguro que desea eliminar este incidente?"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Are you sure you want to delete this witness?", value: "¿Seguro que desea eliminar este testigo?"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Clear the field Non-Emp. Contact Code to replace it with a Non-Employee Witness Name that is not in the Contacts list.", value: "Borre el campo ’Cód. contacto per. ext.’ y sustitúyalo por un nombre de testigo que no esté en la lista de contactos."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Clear the field Non-Emp. Witness Name and Non-Emp. Witness Contact Inf. to replace it with an existing Non-Employee Contact.", value: "Borre el campo ’Nombre del testigo’ e ’Inf. de cont. testigo’ y sustitúyalo por un contacto de no empleado existente."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Delete Incident", value: "Eliminar incidente"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Delete Witness", value: "Eliminar testigo"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Employee {0} doesn't have a location defined.", value: "El empleado {0} no tiene una ubicación definida."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Fill in either Non-Emp. Contact Code or Non-Emp. Witness Name. Use Non-Emp. Witness Name if the witness is not in the Contacts list.", value: "Rellene ’Cód. contacto per. ext.’ o ’Nombre del testigo’. Use ’Nombre del testigo’ si el testigo no está en la lista de contactos."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Location not defined", value: "Ubicación no definida"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "One and only one of these fields is mandatory:<br />Affected Employee, Non-Emp. Contact Code or Affected Non-Emp. Name.", value: "Uno y solo uno de estos campos es obligatorio:<br />Empleado afectado, Cód. contacto per. ext. o Nombre del per. ext. afectado."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Please first fill the 'Reported By' field.", value: "Rellene primero el campo 'Comunicado por'."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Reporter unavailable", value: "Informador no disponible"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Same affected person", value: "Misma persona afectada"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "The incident was saved", value: "El incidente se ha guardado"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "The same affected person was already saved for a similar incident. Proceed?", value: "Ya se guardó la misma persona afectada para un incidente similar. ¿Continuar?"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "To report this incident for an affected non-employee, clear the field Affected Employee.", value: "Para informar de este incidente para un empleado no afectado, borre el campo Empleado afectado."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "To report this incident for different type of affected person, clear the field Non-Emp. Contact Code.", value: "Para informar de este incidente para un tipo distinto de persona afectada, borre el campo Cód. contacto per. ext."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "To report this incident for different type of affected person, clear the fields Affected Non-Emp. Name and Affected Non-Emp. Contact Inf.", value: "Para informar de este incidente para un tipo distinto de persona afectada, borre los campos Nombre del per. ext. afectado y Cód. contacto per. ext."},
        {key1: "IncidentReporting.controller.IncidentSync", key2: "Syncing Incidents", value: "Sincronizando incidentes"},
        {key1: "IncidentReporting.model.Incident", key2: "You can't create an Incident supposed to occur in the future. Please change the {0}.", value: "No se puede crear un incidente que se supone que sucederá en el futuro. Cambie {0}."},
        {key1: "IncidentReporting.model.Incident", key2: "You can't set a future date for {0}. Please change the {0}.", value: "No se puede fijar una fecha futura para {0}. Cambie {0}."},
        {key1: "IncidentReporting.model.Incident", key2: "You must complete one and only one of these fields: {0}, {1} or {2}.", value: "Debe rellenar uno y sólo uno de estos campos: {0}, {1} o {2}."},
        {key1: "IncidentReporting.model.IncidentWitness", key2: "You must complete one and only one of these fields: {1}, {2}, {3}.  Enter the {1} if {0} is Employee, else {2} or {3} if {0} is Non-Employee.", value: "Debe rellenar uno y sólo uno de estos campos: {1}, {2}, {3}. Elija {1} si {0} es empleado, y {2} o {3} si {0} no es empleado."},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Documents", value: "Documentos"},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Location Details", value: "Detalles de la ubicación"},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Medical Details", value: "Detalles médicos"},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Witness Details", value: "Detalles de testigo"},
        {key1: "IncidentReporting.store.DropDownActions", key2: "Employee Location", value: "Ubicación de empleado"},
        {key1: "IncidentReporting.store.DropDownActions", key2: "Reporter Location", value: "Ubicación de informador"},
        {key1: "IncidentReporting.store.IncidentWitnesses", key2: "Witnesses", value: "Testigos"},
        {key1: "IncidentReporting.view.General", key2: "Add Incident Details", value: "Agregar detalles de incidente"},
        {key1: "IncidentReporting.view.General", key2: "Incident Details", value: "Detalles de incidente"},
        {key1: "IncidentReporting.view.General", key2: "One and only one of these fields is mandatory:<br />Affected Employee, Non-Emp. Contact Code or Affected Non-Emp. Name", value: "Uno y solo uno de estos campos es obligatorio:<br />Empleado afectado, Cód. contacto per. ext. o Nombre del per. ext. afectado."},
        {key1: "IncidentReporting.view.IncidentList", key2: "Incidents", value: "Incidentes"},
        {key1: "IncidentReporting.view.IncidentList", key2: "{0} Press the {1} button to add a new incident.{2}", value: "{0} Pulse el botón {1} para agregar un nuevo incidente.{2}"},
        {key1: "IncidentReporting.view.Location", key2: "Location Details", value: "Detalles de la ubicación"},
        {key1: "IncidentReporting.view.Main", key2: "Apps", value: "Aplicaciones"},
        {key1: "IncidentReporting.view.Medical", key2: "Medical Information", value: "Información médica"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Attach", value: "Adjuntar"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Close", value: "Cerrar"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Delete", value: "Eliminar"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Photo", value: "Foto"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Photo Desc.", value: "Desc. foto"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Photo Name", value: "Nombre de foto"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Save", value: "Guardar"},
        {key1: "IncidentReporting.view.Witness", key2: "Delete", value: "Eliminar"},
        {key1: "IncidentReporting.view.Witness", key2: "Employee", value: "Empleado"},
        {key1: "IncidentReporting.view.Witness", key2: "Non-Employee", value: "No empleado"},
        {key1: "IncidentReporting.view.Witness", key2: "Witness", value: "Testigo"},
        {key1: "IncidentReporting.view.WitnessList", key2: "Witnesses", value: "Testigos"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "¿Está seguro de que desea eliminar este objeto?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Introduzca el contenido del cuadro de texto:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Plano de planta no disponible"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Copiar"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Pegar"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Volver a cargar"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Guardar imagen"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "¿Seguro que desea eliminar este elemento?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Editar"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "No hay ningún plano de planta disponible para la línea roja"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Publicar fechas"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Mapas de sede"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Plano de planta"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Línea roja"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Códigos de edificio"},
    ]
};
