var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.de = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Akzeptieren Sie die Browseranforderung, Daten auf Ihrem lokalen Computer zu speichern und die Seite zu aktualisieren."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fehler beim Laden der Konfigurationsdatei."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Der Controller '{0}' verfügt über keine Startmethode. Sind Sie sicher, dass der Controller eine Erweiterung von Ext.app.Controller ist?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Der Wert hat ein falsches Format:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Der Wert ist keine gültige E-Mail:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Der Wert ist kein zulässiger Wert:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Der Wert ist in der Liste zulässiger Werte nicht enthalten:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Der Wert hat eine falsche Länge:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Der folgende Wert muss vorhanden sein:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Anhängen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Schließen"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Fertig"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Ladevorgang wird ausgeführt..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Korrigieren Sie Folgendes:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scan-Fehler"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Fertig"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Keine Datenanzeige für: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Anwenden"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Kein(e) {0} zum Anzeigen"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Anforderung"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Stunden"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Objekt {0} von {1} wird geladen"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Vorname"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nachname"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Name:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Ansprechpartner"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Bezeichnung der Abteilung"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Abteilung:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Bereich"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-Mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-Mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Mitarbeiter"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Kurzzeichen Mitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standardmitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Geräte"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Gerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Geräte:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Geschosse"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Bezeichnung der Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Liegenschaft:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebäude/Geschoss:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Räume"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standardraum"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Raumtyp"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Typ:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Standort"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Standortcode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Standort:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Standorte"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Es wurden keine vorherigen Suchen gespeichert."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.Signature", key2: "Done", value: "Fertig"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Unterschrift"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Bei Erweiterung der Klasse Common.controller.NavigationController muss eine mainView-Ref.-Konfiguration bereitgestellt werden."},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Speichern"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Möchten Sie fortfahren?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Beim Aufheben der Geräteregistrierung ist ein Fehler aufgetreten. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Beim Abmelden werden Ihre Anwendungsdaten nicht entfernt.<br>Sie müssen das Gerät erneut registrieren, um auf die Apps zugreifen zu können."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registrierung"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registrierung fehlgeschlagen"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Der Gerätregistrierungsservice ist nicht verfügbar. Die Mobildienste sind in Web Central möglicherweise nicht aktiviert."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Modell mit dem Namen [{0}] ist nicht vorhanden."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Einlesen des Barcodes ist nicht möglich"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Berechtigung zum Zugriff auf Standortinformationen verweigert"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Position ist nicht verfügbar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Zeitüberschreitung der Position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fehler: Unbekannte Position"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Beim Anzeigen des Dokuments und der Finanzierungsquelle"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Dokumentanzeige"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Dokument wird heruntergeladen"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Funktion in Desktop-Umgebung nicht verfügbar."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Datei existiert nicht"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Datei {0} kann auf diesem Gerät nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Datei {0} kann im Desktop-Modus nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Dokument entfernen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Feld 'Feld geändert': {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Eingabe"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Eingabe für Feld {0} ist auf {1} Zeichen begrenzt"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Leeren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopieren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Fertig"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fehler"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nein"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Einfügen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Neu laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Raumname"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Raumnamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Bild speichern"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Umfrage"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Die Anwendung wurde auf die neueste Version aktualisiert. Die Anwendung wird neu geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fehler beim Laden von Netzwerkdiensten. Die Netzwerkverbindung ist möglicherweise langsam oder nicht verfügbar."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Keine Daten vom Server erhalten"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Zeitüberschreitung"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Unbekannter Fehler"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fehler beim Registrieren des Geräts."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fehler beim Abrufen von Benutzerinformationen."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fehler beim Festlegen des Sitzungsgebiets."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fehler beim Starten der Benutzersitzung."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fehler bei Einzelanmeldung"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fehler beim Abrufen von TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Gerät ist nicht registriert."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Workflow nach JSON. Datenobjekte dürfen nicht mithilfe von Workflow-Regeln gemarshallt werden."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Workflow-Regel ausgeführt"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Workflow-Regel fehlgeschlagen:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-Einstellungen"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Ursachentypen"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Ansprechpartner"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Personal"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standardpersonal"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Geräte"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Geschosse"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Verletzte Körperteile"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Verletzungskategorien"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Arbeitsunfall - Typen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantypgruppen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Problemtypen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projekte"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Liegenschaften"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Datenbankfehler:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Keine Änderung an Datenbanktabelle übernommen. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Keine Standardwertaktualisierung für Feld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standardwert aktualisieren: Feld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Sqlite-Proxy-Fehler"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Sqlite-Proxy-Fehler während Erstellungsvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Sqlite-Proxy-Fehler während Löschvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Sqlite-Proxy-Fehler während Lesevorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Sqlite-Proxy-Fehler während Aktualisierungsvorgang"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fehler beim Öffnen der Datenbank: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Datenbankfehler [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Datenbankfehler bei SqliteView-Proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Löschen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Aktualisieren von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Erstellen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "Die Datenbank enthält nicht die erforderlichen Tabellendefinitionen für die Sqlite-Ansicht {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Reparaturtypen"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Räume"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standardräume"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Raumnutzungsarten"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Standorte"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "datei_nicht_verfügbar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisieren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Herunterladen wird ausgeführt:"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fehler"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Date-Typ konvertiert werden."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Integer konvertiert werden."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Time konvertiert werden."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Timestamp konvertiert werden."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Die Anwendungseinstellungen wurden nicht geladen."},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Ausführung im Browser-Modus. Zugriff auf Dateisystem deaktiviert"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Ausführung in Chrome oder in WebView. Zugriff auf Dateisystem aktiviert"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Dateizugriff wurde abgebrochen"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Datei ist bereits vorhanden"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fehler bei Dateiverschlüsselung"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Dateifehler"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Datei befindet sich in einem ungültigen Zustand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Dateiänderung ist nicht zulässig"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Dateiquoten überschritten"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fehler bei Dateisicherheit"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fehler wegen Dateitypkonflikt"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Datei wurde nicht gefunden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Datei war nicht lesbar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fehler aufgrund ungültiger Dateiänderung"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netzwerk nicht erreichbar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Stammdaten werden heruntergeladen"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fehler"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Der App-Einstellungsspeicher ist nicht geladen. Einstellungen können nicht abgerufen werden."},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "m"},
        {key1: "Common.util.Units", key2: "sq ft", value: "Quadratmeter"},
        {key1: "Common.util.Units", key2: "sq m", value: "Quadratmeter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Die Benutzerprofilinformationen sind nicht verfügbar. Führen Sie eine Synchronisierung durch, um die Benutzerprofildaten abzurufen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Bei Synchronisierung löschen"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Anzeigen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Dokumente"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Keine Dokumente verfügbar."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} von {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 von x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Der Name der Modellklasse, die dieser Ansicht zugeordnet ist, muss in der Modelleigenschaft angegeben werden."},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "Die Speicher-ID der Speicherklasse, die dieser Ansicht zugeordnet ist, muss in der Eigenschaft -storeId- angegeben werden."},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Leeren"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Zurück"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Speichern"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Feld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Kennung"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Größe (Bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisierungsmeldungen"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabelle"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Die folgenden Web Central-Feldwerte wurden nicht in die Client-Datenbank übertragen, da die Datengröße die Kapazität der Datenbank überschreitet."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Assign the work request to you?", value: "Soll die Arbeitsanforderung Ihnen zugewiesen werden?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Cancel", value: "Abbrechen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Estimation", value: "Schätzung durchführen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Scheduling", value: "Planung durchführen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete", value: "Löschen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete the craftsperson?", value: "Handwerker löschen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate", value: "Schätzen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate requests to more accurately budget, to schedule labor, and to reserve parts. You can change your estimates until you issue the request.<br/><br/>Complete the estimation of the work request?", value: "Schätzen Sie Anforderungen, um eine genauere Haushaltsplanung, Arbeitsplanung und Teilereservierung zu erhalten. Sie können Ihre Schätzungen bis zur Anforderungsausstellung ändern.<br/><br/>Die Schätzung der Arbeitsanforderung durchführen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Forward", value: "Weiterleiten"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Map functionility can not run on Phone.", value: "Kartenfunktion kann nicht auf Telefon ausgeführt werden."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Pending workflow step", value: "Ausstehender Workflow-Schritt"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please add your comments before rejecting the work request", value: "Fügen Sie Kommentare ein, bevor Sie die Arbeitsanforderung ablehnen."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please complete the pending workflow step", value: "Schließen Sie den ausstehenden Workflow-Schritt ab."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Reject", value: "Ablehnen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Resume the work request to Issued?", value: "Die auszustellende Arbeitsanforderung wiederaufnehmen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Return", value: "Zurück"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Schedule requests to better plan and balance work for teams and craftspersons. You can change the schedule assignments until you issue the request.<br/><br/>Complete the scheduling of the work request?", value: "Planen Sie Anforderungen, um die Arbeit für Teams und Handwerker besser planen und abstimmen zu können. Sie können die Planungszuweisungen bis zur Anforderungsausstellung ändern.<br/><br/>Die Planung der Arbeitsanforderung durchführen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Self Assign", value: "Selbst zuweisen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Supervisor or Work Team Id must be completed before forwarding the request", value: "Vorarbeiter oder Arbeitsteam-ID muss vor dem Weiterleiten der Anforderung angegeben werden"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The request will be automatically be sent back one step", value: "Die Anforderung wird automatisch einen Schritt zurückgesetzt."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The work request is already assigned to you", value: "Die Arbeitsanforderung wurde Ihnen bereits zugewiesen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "There is another existing record with the same primary keys.", value: "Es ist ein weiterer Datensatz mit den gleichen Hauptschlüsseln vorhanden."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action archives the request and prevents any further updates to it.<br/><br/>Close the work request?", value: "Diese Aktion archiviert die Anforderung und verhindert weitere Aktualisierungen.<br/><br/>Die Arbeitsanforderung schließen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Diese Aktion bricht eine Anforderung vor Beginn der Arbeiten ab. Durch Stornieren einer Anforderung wird der Workflow der Anforderung beendet.<br/><br/>Die Arbeitsanforderung stornieren?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action issues the request to field personnel. Once you issue the request, it cannot be cancelled; it can be completed, put on hold, or stopped.<br/><br/>Issue the work request?", value: "Mit dieser Aktion wird die Anforderung an das Außendienstpersonal ausgestellt. Wenn Sie die Anforderung ausstellen, kann sie nicht mehr abgebrochen werden; sie kann durchgeführt, zurückgestellt oder angehalten werden.<br/><br/>Die Arbeitsanforderung ausstellen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action marks the request as Completed. A Supervisor can update labor, parts, comments, and other work details until the request is Closed.<br/><br/>Complete the work request?", value: "Diese Aktion kennzeichnet die Anforderung als 'Abgeschlossen'. Ein Vorarbeiter kann Arbeitskräfte, Teile, Kommentare und sonstige Arbeitsdetails aktualisieren, bis die Anforderung geschlossen ist.<br/><br/>Die Arbeitsanforderung abschließen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action puts a request on hold while waiting for parts, the appropriate trade, or security access. You can stop or complete a request that is on hold.<br/><br/>Put on hold the work request?", value: "Diese Aktion stellt eine Anforderung zurück, während auf Teile, das entsprechende Gewerk oder Sicherheitszugriff gewartet wird. Sie können eine zurückgestellte Anforderung anhalten oder abschließen.<br/><br/>Die Arbeitsanforderung zurückstellen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action stops a request on which some work has already been performed and which may be billed. Stopping a request ends the request workflow.<br/><br/>Stop the work request?", value: "Diese Aktion hält eine Anforderung an, für die bereits Arbeiten durchgeführt wurden und die in Rechnung gestellt werden kann. Durch Anhalten einer Anforderung wird der Workflow der Anforderung beendet.<br/><br/>Die Arbeitsanforderung anhalten?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Two resource records of the same type can not be added for the same day.  Please edit the existing record to reflect the correct totals.", value: "Zwei Ressourcendatensätze desselben Typs können nicht zum selben Tag hinzugefügt werden.  Bearbeiten Sie den bestehenden Datensatz, um die korrekten Gesamtsummen wiederzugeben."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work Request", value: "Arbeitsanforderung"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work request assigned", value: "Arbeitsanforderung zugewiesen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You cannot select both Supervisor and Work Team Id before forwarding the request", value: "Sie können vor dem Weiterleiten der Anforderung nicht sowohl eine Supervisor- als auch eine Arbeitsteam-ID auswählen."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You have changed the work request. Please sync before taking any further actions on it", value: "Die Arbeitsanforderung wurde geändert. Synchronisieren Sie, bevor Sie weitere Aktionen daran vornehmen."},
        {key1: "Maintenance.controller.manager.WorkRequestActionsMultiple", key2: "Please input the comments first", value: "Geben Sie zuerst die Kommentare ein"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work requests assigned", value: "Arbeitsanforderungen zugewiesen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Other Cost", value: "Sonstige Kosten hinzufügen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Part", value: "Teil hinzufügen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Trade", value: "Gewerk hinzufügen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Other Cost", value: "Sonstige Kosten bearbeiten"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Part", value: "Teil bearbeiten"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Trade", value: "Gewerk bearbeiten"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "Alle Felder für Arbeitsanforderungsdokumente sind in Gebrauch.<br>Das Foto kann nicht an die Arbeitsanforderung angehängt werden"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "Documents", value: "Dokumente"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "This action will remove the document. Do you want to proceed?", value: "Diese Maßnahme entfernt das Dokument. Möchten Sie fortfahren?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Cancel", value: "Abbrechen"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Complete", value: "Erledigt"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Craftsperson Labor", value: "Handwerkerarbeit"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "One or more craftsperson entries are missing labor hours<br>Do you want to Complete the Work Request?", value: "In mindestens einem Handwerkereintrag fehlen Arbeitsstunden.<br>Möchten Sie die Arbeitsanforderung abschließen?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Please input the comments first", value: "Geben Sie zuerst die Kommentare ein"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Status", value: "Status"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "The Work Request status is Completed.<br>The status cannot be modified.", value: "Der Status der Arbeitsanforderung lautet Erledigt.<br>Der Status kann nicht geändert werden."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Diese Aktion bricht eine Anforderung vor Beginn der Arbeiten ab. Durch Stornieren einer Anforderung wird der Workflow der Anforderung beendet.<br/><br/>Die Arbeitsanforderung stornieren?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action marks your assignment as Completed. Supervisors can update labor, parts, comments, and other work details until the request is Closed.<br>Complete your assignment?", value: "Diese Maßnahme kennzeichnet Ihre Zuweisung als ’Abgeschlossen’. Supervisors können Arbeit, Teile, Kommentare und sonstige Details der Arbeit aktualisieren, bis die Anforderung geschlossen ist.<br>Zuweisung abschließen?"},
        {key1: "Maintenance.controller.FloorPlan", key2: "Locate Room", value: "Raum lokalisieren"},
        {key1: "Maintenance.controller.FloorPlan", key2: "The work request is not assigned to a room and therefore cannot be located.", value: "Die Arbeitsanforderung ist keinem Raum zugewiesen und kann daher nicht gefunden werden."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Craftsperson is required.", value: "Handwerker ist erforderlich."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "User Account", value: "Benutzerkonto"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Validation", value: "Bestätigung"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Your account does not have Craftsperson access. Submit Work Requests using the My Request tab.", value: "Ihr Konto besitzt keinen Zugriff für Handwerker. Übermitteln Sie Arbeitsanforderungen über die Registerkarte 'Meine Anforderungen'."},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Info", value: "Info"},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Updating Work Requests", value: "Arbeitsanf. aktualisieren"},
        {key1: "Maintenance.model.manager.WorkRequestTool", key2: " {0} and {1} must be before {2} and {3}", value: "{0} und {1} müssen vor {2} und {3} liegen"},
        {key1: "Maintenance.model.PartStorageLocation", key2: "must be greater than 0.", value: "muss größer als 0 sein."},
        {key1: "Maintenance.model.WorkRequest", key2: " {0} is required", value: "{0} ist erforderlich"},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be greater than or equal to 0.", value: "muss größer oder gleich 0 sein."},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be less than or equal to 100,000,000.", value: "muss kleiner oder gleich 100.000.000 sein."},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0} and {1} must be before {2} and {3}", value: "{0} und {1} müssen vor {2} und {3} liegen"},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0}, {1}, or {2} are required", value: "{0}, {1} oder {2} sind erforderlich"},
        {key1: "Maintenance.store.Accounts", key2: "Accounts", value: "Kostenträger"},
        {key1: "Maintenance.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Maintenance.store.manager.Craftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.store.manager.CraftspersonWorkTeams", key2: "Craftsperson Work Teams", value: "Handwerker - Arbeitsteams"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Approved", value: "Genehmigt"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Completed", value: "Erledigt am"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Issued", value: "Ausgestellt"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Requests", value: "Meine Anforderungen"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Work", value: "Meine Arbeit"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Requested", value: "Angefordert"},
        {key1: "Maintenance.store.manager.PartStorageLocations", key2: "Part Storage Locations", value: "Lagerungsstandorte für Teil"},
        {key1: "Maintenance.store.manager.StorageLocations", key2: "Storage Locations", value: "Lagerungsstandorte"},
        {key1: "Maintenance.store.manager.Tools", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.store.manager.Trades", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve", value: "Genehmigen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Estimate", value: "Schätzung genehmigen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Schedule", value: "Plan genehmigen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Cancel", value: "Abbrechen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Close", value: "Schließen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Complete", value: "Erledigt"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Estimate", value: "Schätzen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Forward", value: "Weiterleiten"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Access", value: "Auf Zugang warten"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Labor", value: "Auf Arbeitskraft warten"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Parts", value: "Auf Teile warten"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Issue", value: "Ausstellen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Link New", value: "Neues verknüpfen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Resume To Issued", value: "Wie ausgestellt wiederaufnehmen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Return", value: "Zurück"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Schedule", value: "Plan"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Self Assign", value: "Selbst zuweisen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Stop", value: "Stopp"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Update", value: "Aktualisiert"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Verify", value: "Prüfen"},
        {key1: "Maintenance.store.manager.WorkRequestReferences", key2: "References", value: "Referenzen"},
        {key1: "Maintenance.store.manager.WorkRequestTools", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.store.manager.WorkRequestTrades", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.store.OtherResources", key2: "Resources", value: "Ressourcen"},
        {key1: "Maintenance.store.PmProcedures", key2: "PM Procedures", value: "Instandhaltungsvorgänge"},
        {key1: "Maintenance.store.ProblemDescriptions", key2: "Problem Descriptions", value: "Problembeschreibungen"},
        {key1: "Maintenance.store.ProblemResolutions", key2: "Problem Resolutions", value: "Problemlösungen"},
        {key1: "Maintenance.store.WorkRequestCosts", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.store.WorkRequestCraftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.store.WorkRequestParts", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.store.WorkRequests", key2: "Due Today", value: "Heute fällig"},
        {key1: "Maintenance.store.WorkRequests", key2: "On Hold", value: "Zurückgestellt"},
        {key1: "Maintenance.store.WorkRequests", key2: "Other", value: "Sonstige"},
        {key1: "Maintenance.store.WorkRequests", key2: "Overdue", value: "Überfällig"},
        {key1: "Maintenance.store.WorkRequests", key2: "Pending", value: "Bevorstehend"},
        {key1: "Maintenance.store.WorkRequests", key2: "Work Request", value: "Arbeitsanforderung"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Approved", value: "Genehmigt"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Completed", value: "Erledigt am"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Issued", value: "Ausgestellt"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Requests", value: "Meine Anforderungen"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Work", value: "Meine Arbeit"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Requested", value: "Angefordert"},
        {key1: "Maintenance.view.FloorPlan", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Maintenance.view.FloorPlan", key2: "Site", value: "Standort"},
        {key1: "Maintenance.view.Main", key2: "Add Purchased Parts", value: "Gekaufte Teile hinzufügen"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Code", value: "Teilekurzzeichen"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Storage Locations", value: "Lagerungsstandorte für Teil"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Quantity Available", value: "Menge verfügbar"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Code", value: "Lagerungsstandort Kurzzeichen"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Name", value: "Lagerungsstandort Name"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Work Request Code", value: "Arbeitsanforderungnr."},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account", value: "Kostenträger"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account Code", value: "Kostenträger"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Add Purchased Parts to Inventory", value: "Gekaufte Teile zu Bestandsliste hinzufügen"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part", value: "Teil"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part Code", value: "Teilekurzzeichen"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Price", value: "Preis"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Quantity (each)", value: "Menge (jeweils)"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location", value: "Lagerungsstandort"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location Code", value: "Lagerungsstandort Kurzzeichen"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve", value: "Genehmigen"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Request", value: "Genehmigungsanforderung"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Cancel", value: "Abbrechen"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Documents", value: "Dokumente"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "References", value: "Referenzen"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Reject", value: "Ablehnen"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Approve", value: "Genehmigen"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Reject", value: "Ablehnen"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Requests", value: "Anforderungen genehmigen"},
        {key1: "Maintenance.view.manager.EstimateApproveForm", key2: "Approve Request Estimation", value: "Anforderungsschätzung genehmigen"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Documents", value: "Dokumente"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "References", value: "Referenzen"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Complete Estimation", value: "Schätzung durchführen"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Estimate", value: "Schätzen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Actual Cost", value: "Tatsächliche Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Add Other Cost", value: "Sonstige Kosten hinzufügen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Labor", value: "Arbeitskosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Parts", value: "Teilekosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Estimated Cost", value: "Geschätzte Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Costs", value: "Sonstige Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Description", value: "Beschreibung der sonstigen Ressourcen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Type", value: "Weiterer Ressourcentyp"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Quantity Used", value: "Menge: Benutzt"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Actual Costs", value: "Zusammenfassung der tatsächlichen Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Estimated Costs", value: "Zusammenfassung der geschätzten Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Total Cost", value: "Gesamtkosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Units", value: "Einheiten"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Complete Estimation", value: "Schätzung durchführen"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Estimate", value: "Schätzen"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Requests to Estimate", value: "Anforderungen zum Schätzen"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Part", value: "Teil hinzufügen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Purchased Parts", value: "Gekaufte Teile hinzufügen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part", value: "Teil"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part Code", value: "Teilekurzzeichen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Available", value: "Menge verfügbar"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Estimated", value: "Geschätzte Menge"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Used", value: "Menge: Benutzt"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Code", value: "Lagerungsstandort Kurzzeichen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Name", value: "Lagerungsstandort Name"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Email", value: "E-Mail"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Employee Code", value: "Kurzzeichen Mitarbeiter"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Forward", value: "Weiterleiten"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Supervisor", value: "Vorarbeiter"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Work Team Code", value: "Kurzzeichen Arbeitsteam"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Forward", value: "Weiterleiten"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Requests to Forward", value: "Anforderungen zum Weiterleiten"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Supervisor", value: "Vorarbeiter"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Work Team Code", value: "Kurzzeichen Arbeitsteam"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Completer", value: "Abgeschlossen von"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Estimator", value: "Schätzer"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Issuer", value: "Aussteller"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject", value: "Ablehnen"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject Request", value: "Anforderung ablehnen"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Requestor", value: "Anforderer"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Scheduler", value: "Planer"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Approver's Comments", value: "Kommentare der genehmigenden Person"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Building", value: "Gebäude"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Craftsperson Notes", value: "Handwerkeranmerkungen"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Date Requested", value: "Gemeldet am"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Equipment Code", value: "Gerät"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Floor", value: "Geschoss"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Priority", value: "Priorität"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Location", value: "Problemstelle"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Related Requests", value: "Zugehörige Anforderungen"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Requestor", value: "Anforderer"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Room", value: "Raum"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return", value: "Zurück"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return Work Request", value: "Arbeitsanforderung zurückgeben"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Requests to Forward", value: "Anforderungen zum Weiterleiten"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return", value: "Zurück"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return Work Request", value: "Arbeitsanforderung zurückgeben"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Approved", value: "Genehmigt"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "by", value: "von"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Completed", value: "Erledigt am"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Access", value: "Auf Zugang warten"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Labor", value: "Auf Arbeitskraft warten"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Parts", value: "Auf Teile warten"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Issued", value: "Ausgestellt"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Rejected", value: "Abgelehnt"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Requested", value: "Angefordert"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return", value: "Zurück"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return Work Request", value: "Arbeitsanforderung zurückgeben"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.manager.ScheduleApproveForm", key2: "Approve Request Schedule", value: "Anforderungsplan genehmigen"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Add Trade", value: "Gewerk hinzufügen"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Estimated Hours", value: "Geschätzte Stunden"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Hours", value: "Stunden"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade", value: "Gewerk"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Code", value: "Kurzzeichen Gewerk"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Description", value: "Gewerkebeschreibung"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Complete Scheduling", value: "Planung durchführen"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Documents", value: "Dokumente"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Forward", value: "Weiterleiten"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "References", value: "Referenzen"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Schedule", value: "Plan"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Actual Hours", value: "Tats. Stunden"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Assign Craftsperson", value: "Handwerker zuweisen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Copy", value: "Kopieren"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson", value: "Handwerker"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson Code", value: "Kurzzeichen Handwerker"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Finished", value: "Fertig am"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Scheduled", value: "Geplant für"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Started", value: "Anfangsdatum"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Doubletime Hours", value: "200% Überstundenrate (Stunden)"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Overtime Hours", value: "150% Überstundentrate (Stunden)"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Primary Trade", value: "Hauptgewerk"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Scheduled Hours", value: "Planstunden"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Start", value: "Start"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Stop", value: "Stopp"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Finished", value: "Fertig um"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Scheduled", value: "Geplante Zeit"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Started", value: "Startzeit"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Work Type", value: "Arbeitstyp"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Complete Scheduling", value: "Planung durchführen"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Forward", value: "Weiterleiten"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Requests to Schedule", value: "Anforderungen zum Planen"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Schedule", value: "Plan"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Trades", value: "Leistung nach Gewerk"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Straight Time Hours Used", value: "Normalzeitrate - verwendete Stunden"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Assign Tool", value: "Zu Werkzeug zuweisen"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Finished", value: "Fertig am"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Scheduled", value: "Geplant für"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Started", value: "Anfangsdatum"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Hours", value: "Stunden"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Scheduled Hours", value: "Planstunden"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Start", value: "Start"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Stop", value: "Stopp"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Finished", value: "Fertig um"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Scheduled", value: "Geplante Zeit"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Started", value: "Startzeit"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool", value: "Werkzeug"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Code", value: "Kurzzeichen Werkzeug"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Type", value: "Werkzeugtyp"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Complete", value: "Erledigt"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Mark only my assignment as Completed.", value: "Nur meine Zuweisung als abgeschlossen markieren."},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Return Work Request", value: "Arbeitsanforderung zurückgeben"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Set all craftsperson assignments as Completed", value: "Alle Handwerkerzuweisungen als abgeschlossen festlegen"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Documents", value: "Dokumente"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "References", value: "Referenzen"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Update", value: "Aktualisiert"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Work Request Details", value: "Arbeitsanforderung - Details"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Update", value: "Anforderungen zum Aktualisieren"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Update", value: "Aktualisiert"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Confirm", value: "Bestätigen"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Return Incomplete", value: "Unvollständig zurückgeben"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Verify", value: "Prüfen"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Verify", value: "Anforderungen zum Prüfen"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Confirm", value: "Bestätigen"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Return Incomplete", value: "Unvollständig zurückgeben"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Verify", value: "Prüfen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Nearing Escalation", value: "10 kurz vor der Eskalation"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Newest Requests", value: "10 Neueste Anforderungen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Oldest Requests", value: "10 Älteste Anforderungen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "All", value: "Alle"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Any", value: "Beliebig"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Both", value: "Beide"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftsperson", value: "Handwerker"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested From", value: "Datum - Angefordert von"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested To", value: "Datum - Angefordert bis"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform From", value: "Durchführungsdatum ab"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform To", value: "Durchführungsdatum bis"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Equipment", value: "Geräte"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated", value: "Eskaliert"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated ?", value: "Eskaliert?"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Approved Requests", value: "Meine genehmigten Anforderungen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Requests", value: "Meine Anforderungen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "On Demand", value: "Störungsarbeitsaufträge"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Part", value: "Teil"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "PM", value: "PM"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Priority", value: "Priorität"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requestor", value: "Anforderer"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requests Requiring my Approval", value: "Anforderungen, die meine Genehmigung erfordern"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Show", value: "Anzeigen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Unassigned Requests", value: "Nicht zugeordnete Anforderungen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Request", value: "Arbeitsanforderung"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Requests", value: "Arbeitsanforderungen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Type", value: "Arbeitstyp"},
        {key1: "Maintenance.view.manager.WorkRequestManagerList", key2: "REQUESTED", value: "Angefordert"},
        {key1: "Maintenance.view.manager.WorkRequestManagerListItem", key2: "Assigned To:", value: "Zugewiesen an:"},
        {key1: "Maintenance.view.manager.WorkRequestSelection", key2: "Requests to Schedule", value: "Anforderungen zum Planen"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Hours", value: "Stunden"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Job Setup or Prep.", value: "Vorbereitung"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Material Pickup", value: "Material abholen"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Travel Time", value: "Reisezeit"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "UnSpecified", value: "Nicht spezifiziert"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Client", value: "Warten auf Kunde"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Security", value: "Warten auf Sicherheitsdienst"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Work", value: "Arbeit"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "No Status Change", value: "Keine Statusänderung"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Access", value: "Wartet auf Zugang"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Labor", value: "Wartet auf Arbeitskräfte"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold For Parts", value: "Wartet auf Teile"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "Resume To Issued", value: "Wie ausgestellt wiederaufnehmen"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Actual Hours", value: "Tats. Stunden"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Cancel", value: "Abbrechen"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Doubletime Hours", value: "200% Überstundenrate (Stunden)"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Overtime Hours", value: "150% Überstundentrate (Stunden)"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Save", value: "Speichern"},
        {key1: "Maintenance.view.phone.Main", key2: "Apps", value: "Apps"},
        {key1: "Maintenance.view.phone.QuickComplete", key2: "Complete Request", value: "Anforderung erledigen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cancel", value: "Abbrechen"},
        {key1: "Maintenance.view.SiteMap", key2: "Buildings", value: "Gebäude"},
        {key1: "Maintenance.view.tablet.Main", key2: "Apps", value: "Apps"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Actual Cost", value: "Tatsächliche Kosten"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Add Cost", value: "Kosten hinzufügen"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Date Used", value: "Benutzt am"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Edit Cost", value: "Kosten bearbeiten"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Quantity Used", value: "Menge: Benutzt"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Resource Type", value: "Ressourcentyp"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Units", value: "Einheiten"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Cost:", value: "Kosten:"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Other Costs", value: "Sonstige Kosten"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Actual Hours", value: "Tats. Stunden"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Add Craftsperson", value: "Handwerker hinzufügen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Craftsperson", value: "Handwerker"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Finished", value: "Fertig am"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Started", value: "Anfangsdatum"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Doubletime Hours", value: "200% Überstundenrate (Stunden)"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Edit Craftsperson", value: "Handwerker bearbeiten"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Overtime Hours", value: "150% Überstundentrate (Stunden)"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Start", value: "Start"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Stop", value: "Stopp"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Finished", value: "Fertig um"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Started", value: "Startzeit"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Work Type", value: "Arbeitstyp"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Hours", value: "Stunden"},
        {key1: "Maintenance.view.manager.WorkRequestEdit", key2: "References", value: "Referenzen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Assigned Date", value: "Zuwiesenes Datum"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cause Type", value: "Ursachentyp"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Code", value: "Kurzzeichen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftsperson Notes", value: "Handwerkeranmerkungen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Related Work Request", value: "Zugehörige Arbeitsanforderung erstellen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Work Request", value: "Arbeitsanforderung erstellen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Description", value: "Beschreibung"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Documents", value: "Dokumente"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 1", value: "Foto 1"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 2", value: "Foto 2"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 3", value: "Foto 3"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 4", value: "Foto 4"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "PM Procedure", value: "IH-Vorgang"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Description", value: "Problembeschreibung"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Location", value: "Problemstelle"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Repair Type", value: "Reparaturtyp"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested", value: "Angefordert"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested By", value: "Angefordert von"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Scheduled Date", value: "Geplantes Datum"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Tools", value: "Werkzeuge"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Update", value: "Aktualisiert"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Work Request Details", value: "Arbeitsanforderung - Details"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Escalation", value: "Eskalation"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Loading...", value: "Ladevorgang wird ausgeführt..."},
        {key1: "Maintenance.view.WorkRequestList", key2: "Location", value: "Standort"},
        {key1: "Maintenance.view.WorkRequestList", key2: "My Work", value: "Meine Arbeit"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search", value: "Suche"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search Work Requests", value: "Arbeitsanforderungen suchen"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Add Part", value: "Teil hinzufügen"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Assigned", value: "Zuweisungsdatum:"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Comments", value: "Bemerkungen"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Edit Part", value: "Teil bearbeiten"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Part", value: "Teil"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Quantity", value: "Menge"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Parts", value: "Teile"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Quantity", value: "Menge"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "OpenURL", value: "URL öffnen"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "URL does not exsits", value: "URL ist nicht vorhanden"},
        {key1: "Maintenance.view.WorkRequestReferencesLists", key2: "References", value: "Referenzen"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Möchten Sie dieses Objekt wirklich löschen?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Geben Sie den Textfeldinhalt ein:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Grundriss nicht verfügbar"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Kopieren"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Einfügen"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Neu laden"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Bild speichern"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Möchten Sie dieses Objekt wirklich löschen?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Bearbeiten"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Für Redline ist kein Geschossplan verfügbar."},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Datum veröffentlichen"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Standortkarten"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Redline"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Bezeichnung des Gebäudes"},
    ]
};
