var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.fr = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Acceptez la demande du navigateur pour stocker les données sur votre ordinateur local et actualiser la page."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Erreur lors du chargement du fichier de configuration."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Le contrôleur « {0} » n'est associé à aucune méthode de lancement. Êtes-vous sûr qu'il s'étend à partir du paramètre Ext.app.Controller ?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Le format de cette valeur est incorrect :"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Cette valeur n’est pas un e-mail valide :"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Cette valeur n’est pas acceptable :"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Cette valeur ne figure pas dans la liste des valeurs acceptables :"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "La longueur de cette valeur est incorrecte :"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Cette valeur doit être présente :"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Joindre"},
        {key1: "Common.control.Camera", key2: "Close", value: "Fermer"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Photo"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Effacer"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Terminé"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Chargement…"},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Veuillez corriger ce qui suit :"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Erreur d’analyse"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Terminé"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Aucune donnée à afficher pour : {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Appliquer"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Pas de {0} à afficher"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Demander"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Heures"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minutes"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Chargement de l'élément {0} sur {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code Contact"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Prénom"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nom de Famille"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nom :"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contact"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code Contact"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Code Département"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Code Département :"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Départements"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Code Division"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Code Division :"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Division"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Code Division"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Division :"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisions"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "Adresse Electronique"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail :"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Employé"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Code Employé"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standard d’Employé"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Code Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standard Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Equipement :"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standard Equipement"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Etages"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Propriétés"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code Propriété"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Propriété :"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Bâtiment/Étage :"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code Pièce"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Pièce :"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Pièces"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Catégorie :"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Catégories de Pièces"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Etage :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Pièce :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Pièce :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Pièces"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standard de Pièce"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Catégorie :"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type de Pièce"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Types de Pièces"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type :"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Code site"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site :"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Aucune recherche précédente n’a été enregistrée."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Effacer"},
        {key1: "Common.control.Signature", key2: "Done", value: "Terminé"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Signature"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Une configuration de réf. mainView doit être fournie lors de l'extension de la classe Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuler"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Sauvegarder"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Voulez-vous continuer ?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "L’erreur s’est produite lors de la désinscription de l’appareil. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "La déconnexion ne supprime pas vos données d’application.<br>Il vous faudra réinscrire l’appareil pour accéder aux applications."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Enregistrement"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Echec de l'enregistrement"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Le service d'enregistrement des appareils n'est pas disponible. Il se peut que les services mobiles ne soient pas activés dans Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Le modèle nommé [{0}] n'existe pas."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "La lecture de codes-barres n'est pas disponible."},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Autorisation d’accès aux informations d’emplacement refusée"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La position n’est pas disponible."},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Délai d’expiration de position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Erreur de poste inconnu"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Une erreur s’est produite pendant l’affichage du document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Affichage du document"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Téléchargement des documents"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "La fonction n’est pas disponible dans l’environnement de bureau."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Le fichier n’existe pas."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Le fichier {0} ne peut pas être affiché sur cet appareil."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Le fichier {0} ne peut pas être affiché en mode Bureau."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Suppression du document"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Champ modifié : {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Entrée"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "L’entrée du champ {0} est limitée à {1} caractères"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuler"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Effacer"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copier"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Terminé"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Erreur"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "NON"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Coller"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Recharger"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nom de Pièce"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "nom de pièces"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Enregistrer l’image"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Evaluation"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "OUI"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Chargement supplémentaire..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Pas d'autres enregistrements"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Chargement supplémentaire..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Pas d'autres enregistrements"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Cette application a été mise à jour à la dernière version. Rechargement de l’application."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Erreur lors du chargement des services réseau. Il se peut que la connexion réseau soit lente ou indisponible."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Aucune connexion réseau disponible"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Aucune donnée reçue du serveur"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Délai"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Erreur inconnue"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Erreur lors de l'enregistrement de l'appareil"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Erreur lors de la récupération des informations d'utilisateur."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Erreur lors de la définition des paramètres régionaux de la session."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Erreur lors du démarrage de la session d'utilisateur."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Erreur d'authentification unique"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Erreur lors de la récupération de TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "L’appareil n’est pas inscrit."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flux d'opérations en JSON. Les objets de date ne peunvent pas être triés à l'aide de règles de workflow."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Règle de Workflow exécutée"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Echec de la règle de workflow :"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Préférences d’application"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types de causes"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contacts"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Départements"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisions"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Employés"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standards d’Employés"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Equipement"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Etages"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Surfaces touchées"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Catégories de blessure"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Types d’accident"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Groupes de types de plan"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Types de plan"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Types de problèmes"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projets"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Propriétés"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Erreur de base de données :"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Aucune modification de table de base de données appliquée. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Aucune mise à jour de la valeur par défaut du champ : [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Mettre à jour la valeur par défaut : champ [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Erreur du proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Erreur du proxy Sqlite pendant l’opération de création"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Erreur du proxy Sqlite pendant l’opération de destruction"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Erreur du proxy Sqlite pendant l’opération de lecture"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Erreur du proxy Sqlite pendant l’opération de mise à jour"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Erreur d’ouverture de la base de données : {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Erreur de base de données [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Erreur de base de données dans le proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView est en lecture seule et ne prend pas en charge la suppression d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView est en lecture seule et ne prend pas en charge la mise à jour d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView est en lecture seule et ne prend pas en charge la création d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "La base de données ne contient pas les définitions de tables requises pour SqliteView. {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Types de réparations"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Catégories de Pièces"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Pièces"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standards de Pièces"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Types de Pièces"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Utilisations des Pièces"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "fichier_non_disponible"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisation"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Téléchargement"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Erreur"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Les préférences de l'application n'ont pas été chargées"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Exécution en mode navigateur Accès au système de fichiers désactivé"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Exécution dans Chrome ou en vue Web. Accès au système de fichiers activé"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "L'accès au fichier a été interrompu"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Le fichier existe déjà"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Erreur de codage du fichier"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Erreur du fichier"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Le fichier est dans un état non valide"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "La modification du fichier n'est pas autorisée"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Quota de fichiers dépassé"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Erreur de sécurité du fichier"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Erreur de disparité de type de fichier"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Fichier introuvable"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Fichier illisible"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Erreur de modification de fichier non valide"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Aucune connexion réseau disponible"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Réseau inaccessible"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Téléchargement des données fondamentales"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Erreur"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Le magasin des préférences d'application n'est pas chargé. Impossible de récupérer les préférences"},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pi2"},
        {key1: "Common.util.Units", key2: "sq m", value: "m2"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Les informations du profil d'utilisateur ne sont pas disponibles. Veuillez synchroniser pour récupérer les données du profil d'utilisateur."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Supprimer à la synchronisation"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Afficher"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documents"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Aucun document disponible."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} de {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 sur x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Le nom de la classe Model associée à cette vue doit être fourni dans la propriété model"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "L'ID de magasin de la classe de la classe Store associée à cette vue doit être fourni dans la propriété storeId"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Effacer"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtrer les données"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Précédent"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Sauvegarder"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Champ"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifiant"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Taille (octets)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Messages de synchronisation"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Table"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Les valeurs de champ de Web Central énumérées ci-après n'ont pas été écrites dans la base de données cliente, car la taille des données dépasse la limite de la base de données."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Définir le Filtre"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Assign the work request to you?", value: "Vous affecter la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Cancel", value: "Annuler"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Estimation", value: "Terminer l’estimation"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Scheduling", value: "Terminer la programmation"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete", value: "Supprimer"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete the craftsperson?", value: "Supprimer le technicien ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate", value: "Estimer"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate requests to more accurately budget, to schedule labor, and to reserve parts. You can change your estimates until you issue the request.<br/><br/>Complete the estimation of the work request?", value: "Evaluez les demandes pour budgéter plus précisément, pour programmer la main-d’oeuvre, et pour réserver les pièces. Vous pouvez modifier vos estimations jusqu’à l’émission de la demande.<br/><br/>Terminer l’estimation de la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Forward", value: "Transférer"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Map functionility can not run on Phone.", value: "La fonction carte ne fonctionne pas sur le téléphone."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Pending workflow step", value: "Etape de workflow en attente"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please add your comments before rejecting the work request", value: "Ajoutez vos commentaires avant de rejeter la demande d’intervention."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please complete the pending workflow step", value: "Terminez l’étape du workflow en attente."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Reject", value: "Rejeter"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Resume the work request to Issued?", value: "Reprendre la demande d’intervention à émettre ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Return", value: "Retour"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Schedule requests to better plan and balance work for teams and craftspersons. You can change the schedule assignments until you issue the request.<br/><br/>Complete the scheduling of the work request?", value: "Programmez les demandes pour mieux programmer et répartir le travail et le niveau de travail des équipes et des techniciens. Vous pouvez modifier les affectations programmées jusqu’à l’émission de la demande.<br/><br/>Terminer la programmation de la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Self Assign", value: "Affecter automatiquement"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Supervisor or Work Team Id must be completed before forwarding the request", value: "ID du superviseur ou de l’équipe d’intervention doit être renseigné avant de transférer la demande."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The request will be automatically be sent back one step", value: "La demande reviendra automatiquement à l’étape précédente"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The work request is already assigned to you", value: "La demande d’intervention vous a déjà été affectée."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "There is another existing record with the same primary keys.", value: "Un enregistrement possédant les mêmes clés principales existe déjà."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action archives the request and prevents any further updates to it.<br/><br/>Close the work request?", value: "Cette action archive la demande et empêche ses mises à jour ultérieures.<br/><br/>Fermer cette demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Cette action annule une demande avant le début d’une quelconque intervention. L’annulation d’une demande termine le workflow de demande.<br/><br/>Annuler la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action issues the request to field personnel. Once you issue the request, it cannot be cancelled; it can be completed, put on hold, or stopped.<br/><br/>Issue the work request?", value: "Cette action émet la demande pour le personnel du site. À ce stade, elle ne peut plus être annulée, elle peut seulement être terminée, mise en attente ou arrêtée.<br/><br/>Émettre la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action marks the request as Completed. A Supervisor can update labor, parts, comments, and other work details until the request is Closed.<br/><br/>Complete the work request?", value: "Cette action marque la demande comme étant Terminée. Un superviseur peut mettre à jour la main-d'œuvre, les pièces détachées, les commentaires et d'autres détails de travail tant que la demande n'est pas fermée.<br/><br/>Terminer la demande d'intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action puts a request on hold while waiting for parts, the appropriate trade, or security access. You can stop or complete a request that is on hold.<br/><br/>Put on hold the work request?", value: "Cette action met une demande en attente pendant l’attente de pièces détachées, du corps de métier approprié ou d’un accès de sécurité. Vous pouvez arrêter ou terminer une demande qui est en attente.<br/><br/>Mettre en attente la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action stops a request on which some work has already been performed and which may be billed. Stopping a request ends the request workflow.<br/><br/>Stop the work request?", value: "Cette action arrête une demande pour laquelle une intervention a déjà été réalisée et pourrait être facturée. L’arrêt d’une demande termine le workflow de demande.<br/><br/>Arrêter la demande d’intervention ?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Two resource records of the same type can not be added for the same day.  Please edit the existing record to reflect the correct totals.", value: "Il n’est pas possible d’ajouter deux enregistrements de ressources du même type pour le même jour.  Veuillez modifier l’enregistrement existant pour qu’il contienne les totaux corrects."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work Request", value: "Demande d’Intervention"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work request assigned", value: "Demande d’intervention affectée"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You cannot select both Supervisor and Work Team Id before forwarding the request", value: "Vous ne pouvez pas sélectionner un ID de superviseur et un ID d’équipe d’intervention avant de transférer la demande."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You have changed the work request. Please sync before taking any further actions on it", value: "Vous avez modifié la demande d’intervention. Veuillez synchroniser avant d’exécuter d’autres actions la concernant."},
        {key1: "Maintenance.controller.manager.WorkRequestActionsMultiple", key2: "Please input the comments first", value: "Saisissez d’abord les commentaires."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work requests assigned", value: "Demandes d’intervention affectées"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Other Cost", value: "Ajouter un autre coût"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Part", value: "Ajouter une Pièce Détachée"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Trade", value: "Ajouter un Corps de Métier"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Other Cost", value: "Editer un autre coût"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Part", value: "Editer la pièce"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Trade", value: "Editer le métier"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "Tous les champs de document de la demande d'intervention sont utilisés.<br>La photo ne peut pas être jointe à la demande d'intervention"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "Documents", value: "Documents"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "This action will remove the document. Do you want to proceed?", value: "Cette action supprime le document. Voulez-vous continuer ?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Cancel", value: "Annuler"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Complete", value: "Terminer"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Craftsperson Labor", value: "Main d'oeuvre de techniciens"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "One or more craftsperson entries are missing labor hours<br>Do you want to Complete the Work Request?", value: "Il manque des heures de travail pour un ou plusieurs techniciens.<br>Voulez-vous compléter la demande d'intervention ?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Please input the comments first", value: "Saisissez d’abord les commentaires."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Status", value: "Statut"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "The Work Request status is Completed.<br>The status cannot be modified.", value: "L'état de la demande d'intervention est Terminée.<br>L'état ne peut pas être modifié."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Cette action annule une demande avant le début d’une quelconque intervention. L’annulation d’une demande termine le workflow de demande.<br/><br/>Annuler la demande d’intervention ?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action marks your assignment as Completed. Supervisors can update labor, parts, comments, and other work details until the request is Closed.<br>Complete your assignment?", value: "Cette action marque votre affectation comme étant Terminée. Les superviseurs peuvent mettre à jour la main-d’oeuvre, les pièces détachées, les commentaires et d’autres détails de travail tant que la demande n’est pas fermée.<br>Terminer votre affectation ?"},
        {key1: "Maintenance.controller.FloorPlan", key2: "Locate Room", value: "Localiser une pièce"},
        {key1: "Maintenance.controller.FloorPlan", key2: "The work request is not assigned to a room and therefore cannot be located.", value: "La demande d’intervention n’est pas affectée à une pièce, et ne peut donc pas être localisée."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Craftsperson is required.", value: "Un technicien est obligatoire."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "User Account", value: "Compte utilisateur"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Validation", value: "Validation"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Your account does not have Craftsperson access. Submit Work Requests using the My Request tab.", value: "Votre compte n'a pas d'accès Technicien. Envoyez des demandes d'intervention au moyen de l'onglet Ma demande."},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Info", value: "Info"},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Updating Work Requests", value: "Mise à jour des demandes d'intervention"},
        {key1: "Maintenance.model.manager.WorkRequestTool", key2: " {0} and {1} must be before {2} and {3}", value: "{0} et {1} doivent être antérieures à {2} et {3}"},
        {key1: "Maintenance.model.PartStorageLocation", key2: "must be greater than 0.", value: "doit être supérieur à 0."},
        {key1: "Maintenance.model.WorkRequest", key2: " {0} is required", value: "{0} est requis"},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be greater than or equal to 0.", value: "doit être supérieur ou égal à 0."},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be less than or equal to 100,000,000.", value: "doit être inférieur ou égal à 100 000 000."},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0} and {1} must be before {2} and {3}", value: "{0} et {1} doivent être antérieures à {2} et {3}"},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0}, {1}, or {2} are required", value: "{0}, {1} ou {2} sont requis"},
        {key1: "Maintenance.store.Accounts", key2: "Accounts", value: "Postes comptables"},
        {key1: "Maintenance.store.Buildings", key2: "Buildings", value: "Bâtiments"},
        {key1: "Maintenance.store.manager.Craftspersons", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.store.manager.CraftspersonWorkTeams", key2: "Craftsperson Work Teams", value: "Equipes d’intervention de techniciens"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Approved", value: "Approuvé"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Completed", value: "Terminé"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Issued", value: "Emis"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Requests", value: "Mes demandes"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Work", value: "Mon travail"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Requested", value: "Demandé pour"},
        {key1: "Maintenance.store.manager.PartStorageLocations", key2: "Part Storage Locations", value: "Lieux de stockage de pièce"},
        {key1: "Maintenance.store.manager.StorageLocations", key2: "Storage Locations", value: "Lieux de Stockage"},
        {key1: "Maintenance.store.manager.Tools", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.store.manager.Trades", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve", value: "Approuver"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Estimate", value: "Approuver l’estimation"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Schedule", value: "Approuver le programme"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Cancel", value: "Annuler"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Close", value: "Fermer"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Complete", value: "Terminer"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Estimate", value: "Estimer"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Forward", value: "Transférer"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Access", value: "En attente d’accès"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Labor", value: "En attente de main d’oeuvre"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Parts", value: "En attente de pièces détachées"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Issue", value: "Emettre"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Link New", value: "Associer nouvel élément"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Resume To Issued", value: "Reprendre sur Émis"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Return", value: "Retour"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Schedule", value: "Programmer"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Self Assign", value: "Affecter automatiquement"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Stop", value: "Arrêter"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Update", value: "Mettre à jour"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Verify", value: "Vérifier"},
        {key1: "Maintenance.store.manager.WorkRequestReferences", key2: "References", value: "Références"},
        {key1: "Maintenance.store.manager.WorkRequestTools", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.store.manager.WorkRequestTrades", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.store.OtherResources", key2: "Resources", value: "Ressources"},
        {key1: "Maintenance.store.PmProcedures", key2: "PM Procedures", value: "Procédures de MP"},
        {key1: "Maintenance.store.ProblemDescriptions", key2: "Problem Descriptions", value: "Descriptions des problèmes"},
        {key1: "Maintenance.store.ProblemResolutions", key2: "Problem Resolutions", value: "Résolutions des problèmes"},
        {key1: "Maintenance.store.WorkRequestCosts", key2: "Costs", value: "Coûts"},
        {key1: "Maintenance.store.WorkRequestCraftspersons", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.store.WorkRequestParts", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.store.WorkRequests", key2: "Due Today", value: "Dû aujourd'hui"},
        {key1: "Maintenance.store.WorkRequests", key2: "On Hold", value: "En Attente"},
        {key1: "Maintenance.store.WorkRequests", key2: "Other", value: "Autre"},
        {key1: "Maintenance.store.WorkRequests", key2: "Overdue", value: "En Retard"},
        {key1: "Maintenance.store.WorkRequests", key2: "Pending", value: "En attente"},
        {key1: "Maintenance.store.WorkRequests", key2: "Work Request", value: "Demande d’Intervention"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Approved", value: "Approuvé"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Completed", value: "Terminé"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Issued", value: "Emis"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Requests", value: "Mes demandes"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Work", value: "Mon travail"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Requested", value: "Demandé pour"},
        {key1: "Maintenance.view.FloorPlan", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "Maintenance.view.FloorPlan", key2: "Site", value: "Site"},
        {key1: "Maintenance.view.Main", key2: "Add Purchased Parts", value: "Ajouter des pièces achetées"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Code", value: "Code pièce"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Storage Locations", value: "Lieux de stockage de pièce"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Quantity Available", value: "Quantité Disponible"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Code", value: "Code de lieu de stockage"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Name", value: "Nom de lieu de stockage"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Work Request Code", value: "Code Demande d’Intervention"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account", value: "Poste comptable"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account Code", value: "Poste Comptable"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Add Purchased Parts to Inventory", value: "Ajouter des pièces achetées à l’inventaire"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part", value: "Pièce détachée"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part Code", value: "Code pièce"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Price", value: "Prix"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Quantity (each)", value: "Quantité (unitaire)"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location", value: "Lieu de stockage"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location Code", value: "Code de lieu de stockage"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve", value: "Approuver"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Request", value: "Approuver une demande"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Cancel", value: "Annuler"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Documents", value: "Documents"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "References", value: "Références"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Reject", value: "Rejeter"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Approve", value: "Approuver"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Reject", value: "Rejeter"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Requests", value: "Approuver les demandes"},
        {key1: "Maintenance.view.manager.EstimateApproveForm", key2: "Approve Request Estimation", value: "Approuver l’estimation de la demande"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Costs", value: "Coûts"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Documents", value: "Documents"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "References", value: "Références"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Complete Estimation", value: "Terminer l’estimation"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Estimate", value: "Estimer"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Actual Cost", value: "Coût réel"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Add Other Cost", value: "Ajouter un autre coût"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Labor", value: "Coût de la Main d’Oeuvre"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Parts", value: "Coût des Pièces Détachées"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Estimated Cost", value: "Coût Estimé"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Costs", value: "Autres Coûts"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Description", value: "Description de l'autre ressource"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Type", value: "Autre type de ressource"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Quantity Used", value: "Quantité utilisée"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Actual Costs", value: "Résumé des coûts réels"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Estimated Costs", value: "Résumé des coûts estimés"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Total Cost", value: "Coût Total"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Units", value: "Unités"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Complete Estimation", value: "Terminer l’estimation"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Costs", value: "Coûts"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Estimate", value: "Estimer"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Requests to Estimate", value: "Demandes à estimer"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Part", value: "Ajouter une Pièce Détachée"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Purchased Parts", value: "Ajouter des pièces achetées"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part", value: "Pièce détachée"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part Code", value: "Code pièce"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Available", value: "Quantité Disponible"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Estimated", value: "Quantité Estimée"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Used", value: "Quantité utilisée"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Code", value: "Code de lieu de stockage"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Name", value: "Nom de lieu de stockage"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Email", value: "Adresse Electronique"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Employee Code", value: "Code Employé"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Forward", value: "Transférer"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Supervisor", value: "Superviseur"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Work Team Code", value: "Code de l’équipe d’intervention"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Forward", value: "Transférer"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Requests to Forward", value: "Demandes à transférer"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Supervisor", value: "Superviseur"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Work Team Code", value: "Code de l’équipe d’intervention"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Completer", value: "Termineur"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Estimator", value: "Estimateur"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Issuer", value: "Emetteur"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject", value: "Rejeter"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject Request", value: "Rejeter la demande"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Requestor", value: "Demandeur"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Scheduler", value: "Planificateur"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Approver's Comments", value: "Commentaires de'l’approbateur"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Building", value: "Bâtiment"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Craftsperson Notes", value: "Notes du Technicien"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Date Requested", value: "Demandé le"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Equipment Code", value: "Code Equipement"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Floor", value: "Etage"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Priority", value: "Priorité"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Location", value: "Localisation du Problème :"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Related Requests", value: "Demandes associées"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Requestor", value: "Demandeur"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Room", value: "Pièce"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Status", value: "Statut"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return", value: "Retour"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return Work Request", value: "Retourner la demande d’intervention"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Requests to Forward", value: "Demandes à transférer"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return", value: "Retour"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return Work Request", value: "Retourner la demande d’intervention"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Approved", value: "Approuvé"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "by", value: "par"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Completed", value: "Terminé"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Access", value: "En attente d’accès"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Labor", value: "En attente de main d’oeuvre"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Parts", value: "En attente de pièces détachées"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Issued", value: "Emis"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Rejected", value: "Rejeté"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Requested", value: "Demandé pour"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return", value: "Retour"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return Work Request", value: "Retourner la demande d’intervention"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.manager.ScheduleApproveForm", key2: "Approve Request Schedule", value: "Approuver le planning de la demande"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Add Trade", value: "Ajouter un Corps de Métier"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Estimated Hours", value: "Nbre Heures Estimées"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Hours", value: "Heures"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade", value: "Métier"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Code", value: "Code métier"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Description", value: "Description du corps de métier"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Complete Scheduling", value: "Terminer la programmation"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Documents", value: "Documents"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Forward", value: "Transférer"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "References", value: "Références"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Schedule", value: "Programmer"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Actual Hours", value: "Hrs Réelles"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Assign Craftsperson", value: "Affecter un Technicien"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Copy", value: "Copier"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson", value: "Technicien"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson Code", value: "Code Technicien"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Finished", value: "Fini le"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Scheduled", value: "Programmé pour le"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Started", value: "Démarré le"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Doubletime Hours", value: "Heures Doubles"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Overtime Hours", value: "Heures Supplémentaires"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Primary Trade", value: "Métier Principal"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Scheduled Hours", value: "Heures programmées"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Start", value: "Démarrer"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Status", value: "Statut"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Stop", value: "Arrêter"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Finished", value: "Fini à"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Scheduled", value: "Temps programmé"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Started", value: "Démarré à"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Work Type", value: "Type de Travaux"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Complete Scheduling", value: "Terminer la programmation"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Forward", value: "Transférer"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Requests to Schedule", value: "Demandes à programmer"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Schedule", value: "Programmer"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Trades", value: "Métiers"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Straight Time Hours Used", value: "Heures norm. utilisées"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Assign Tool", value: "Affecter un outil"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Finished", value: "Fini le"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Scheduled", value: "Programmé pour le"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Started", value: "Démarré le"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Hours", value: "Heures"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Scheduled Hours", value: "Heures programmées"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Start", value: "Démarrer"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Stop", value: "Arrêter"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Finished", value: "Fini à"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Scheduled", value: "Temps programmé"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Started", value: "Démarré à"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool", value: "Outil"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Code", value: "Code Outil"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Type", value: "Type d’outil"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Complete", value: "Terminer"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Mark only my assignment as Completed.", value: "Marquer uniquement mon affectation comme terminée."},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Return Work Request", value: "Retourner la demande d’intervention"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Set all craftsperson assignments as Completed", value: "Définir toutes les affectations de technicien comme terminée"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Costs", value: "Coûts"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Documents", value: "Documents"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "References", value: "Références"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Update", value: "Mettre à jour"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Work Request Details", value: "Détails de la Demande d’Intervention"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Costs", value: "Coûts"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Update", value: "Demandes à mettre à jour"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Update", value: "Mettre à jour"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Confirm", value: "Confirmer"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Return Incomplete", value: "Retour incomplet"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Verify", value: "Vérifier"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Verify", value: "Demandes à vérifier"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Confirm", value: "Confirmer"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Return Incomplete", value: "Retour incomplet"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Verify", value: "Vérifier"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Nearing Escalation", value: "10 prochains recours hiérarchiques"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Newest Requests", value: "10 demandes les plus récentes"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Oldest Requests", value: "10 demandes les plus anciennes"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "All", value: "Toutes"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Any", value: "Tout"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Both", value: "Les deux"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftsperson", value: "Technicien"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested From", value: "Demandé depuis le"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested To", value: "Demandé jusqu’au"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform From", value: "Exécuter à partir du"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform To", value: "Exécuter jusqu’au"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Equipment", value: "Equipement"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated", value: "Données remontées"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated ?", value: "Remonté ?"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Approved Requests", value: "Mes demandes approuvées"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Requests", value: "Mes demandes"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "On Demand", value: "Sur Demande"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Part", value: "Pièce détachée"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "PM", value: "PM"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Priority", value: "Priorité"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requestor", value: "Demandeur"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requests Requiring my Approval", value: "Demandes nécessitant mon approbation"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Set Filter", value: "Définir le Filtre"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Show", value: "Afficher"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Unassigned Requests", value: "Demandes non affectées"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Request", value: "Demande d’Intervention"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Requests", value: "Demandes d’Intervention"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Type", value: "Type de Travaux"},
        {key1: "Maintenance.view.manager.WorkRequestManagerList", key2: "REQUESTED", value: "Demandé pour"},
        {key1: "Maintenance.view.manager.WorkRequestManagerListItem", key2: "Assigned To:", value: "Assigné à :"},
        {key1: "Maintenance.view.manager.WorkRequestSelection", key2: "Requests to Schedule", value: "Demandes à programmer"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Hours", value: "Heures"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Job Setup or Prep.", value: "Mise en place ou prép. travail"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Material Pickup", value: "Enlèvement Matériel"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Travel Time", value: "Temps de Déplacement"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "UnSpecified", value: "Non spécifiée"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Client", value: "Attente Client"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Security", value: "Attente Sécurité"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Work", value: "Travaux"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "No Status Change", value: "Aucun changement de statut"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Access", value: "En Attente d’Accès"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Labor", value: "En Attente de Main d’Oeuvre"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold For Parts", value: "En Attente de Pièces"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "Resume To Issued", value: "Reprendre sur Émis"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Actual Hours", value: "Hrs Réelles"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Cancel", value: "Annuler"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Doubletime Hours", value: "Heures Doubles"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Overtime Hours", value: "Heures Supplémentaires"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Save", value: "Sauvegarder"},
        {key1: "Maintenance.view.phone.Main", key2: "Apps", value: "Applications"},
        {key1: "Maintenance.view.phone.QuickComplete", key2: "Complete Request", value: "Terminer la demande"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cancel", value: "Annuler"},
        {key1: "Maintenance.view.SiteMap", key2: "Buildings", value: "Bâtiments"},
        {key1: "Maintenance.view.tablet.Main", key2: "Apps", value: "Applications"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Actual Cost", value: "Coût réel"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Add Cost", value: "Ajouter un coût"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Date Used", value: "Utilisé le"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Edit Cost", value: "Editer le coût"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Quantity Used", value: "Quantité utilisée"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Resource Type", value: "Type de ressource"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Units", value: "Unités"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Cost:", value: "Coût :"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Other Costs", value: "Autres Coûts"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Actual Hours", value: "Hrs Réelles"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Add Craftsperson", value: "Ajouter un technicien"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Craftsperson", value: "Technicien"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Finished", value: "Fini le"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Started", value: "Démarré le"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Doubletime Hours", value: "Heures Doubles"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Edit Craftsperson", value: "Editer le technicien"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Overtime Hours", value: "Heures Supplémentaires"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Start", value: "Démarrer"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Status", value: "Statut"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Stop", value: "Arrêter"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Finished", value: "Fini à"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Started", value: "Démarré à"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Work Type", value: "Type de Travaux"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Hours", value: "Heures"},
        {key1: "Maintenance.view.manager.WorkRequestEdit", key2: "References", value: "Références"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Assigned Date", value: "Date d'affectation"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cause Type", value: "Type de cause"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Code", value: "Code"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Costs", value: "Coûts"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftsperson Notes", value: "Notes du Technicien"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Related Work Request", value: "Créer une demande d’intervention associée"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Work Request", value: "Créer une demande d’intervention"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Description", value: "Description"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Documents", value: "Documents"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 1", value: "Photo 1"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 2", value: "Photo 2"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 3", value: "Photo 3"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 4", value: "Photo 4"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "PM Procedure", value: "Procédure MP"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Description", value: "Description du Problème"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Location", value: "Localisation du Problème :"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Repair Type", value: "Type de réparation"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested", value: "Demandé pour"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested By", value: "Demandé par"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Scheduled Date", value: "programmé le"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Status", value: "Statut"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Tools", value: "Outils"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Update", value: "Mettre à jour"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Work Request Details", value: "Détails de la Demande d’Intervention"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Escalation", value: "Recours hiérarchique"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Loading...", value: "Chargement…"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Location", value: "Localisation"},
        {key1: "Maintenance.view.WorkRequestList", key2: "My Work", value: "Mon travail"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search", value: "Rechercher"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search Work Requests", value: "Recherche de Demandes d’Intervention"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Status", value: "Statut"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Add Part", value: "Ajouter une Pièce Détachée"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Assigned", value: "Affecté"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Comments", value: "Commentaires"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Edit Part", value: "Editer la pièce"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Part", value: "Pièce détachée"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Quantity", value: "Quantité"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Parts", value: "Pièces détachées"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Quantity", value: "Quantité"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "OpenURL", value: "Ouvrir l’URL"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "URL does not exsits", value: "L’URL n’existe pas"},
        {key1: "Maintenance.view.WorkRequestReferencesLists", key2: "References", value: "Références"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Voulez-vous vraiment supprimer cet objet ?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Veuillez saisir le contenu de la zone de texte :"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Le plan d'étage n'est pas disponible"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Copier"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Coller"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Recharger"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Enregistrer l’image"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Voulez-vous vraiment supprimer cet élément ?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Editer"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Aucun plan d’étage ne peut être annoté"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Dates de publication"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Plans de sites"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Plans d'étage"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Annotation"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Codes Bâtiment"},
    ]
};
