var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.ch = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>接受浏览器请求将数据存储在本地，并刷新页面."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "装入配置文件出错."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "控制 '{0}' 没有 launch 方法。你确定它是 Ext.app.Controller 的扩充吗？"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "该数值格式错误:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "该值不是有效的邮件地址:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "该值不可接受:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "该值不在可接受的列表中:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "该值为错误的长度:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "此值必须呈现:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "添加"},
        {key1: "Common.control.Camera", key2: "Close", value: "关闭"},
        {key1: "Common.control.Camera", key2: "Photo", value: "照片"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "取消"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "清除"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "完成"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "正在加载..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "请纠正下面的错误:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "扫描出错"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "完成"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "无数据显示: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "应用"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "取消"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "取消"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "没有{0}可显示"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "请求"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "小时"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "分钟"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "取消"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "调入第 {0} 个，共 {1}个"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "大厦"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "大厦"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "联系人"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "名字"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "姓(L)"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "名称:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "联系人"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "联系人"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "部门"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "部门:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "部门"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "业务部"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "业务部:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "业务部"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "业务部"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "业务部:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "业务部"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "电子邮件"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "邮件:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "员工"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "员工"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "员工级别"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "设备"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "设备编码"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "设备规格"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "设备:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "设备规格"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "设备规格"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "大厦:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "楼层"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "楼层:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "大厦:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "楼层"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "楼层:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "楼层:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "楼层"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "取消"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "问题类型"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "不动产"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "不动产"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "不动产:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "大厦/楼层:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "房间"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "房间:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "房间"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "类别:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "房间类别"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "房间类别"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "大厦"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "大厦"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "大厦:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "大厦:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "楼层"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "楼层"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "楼层:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "楼层:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "房间"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "房间"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "房间:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "房间:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "房间"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "房间标准"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "标准:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "标准"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "类别:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "说明"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "说明:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "房间类别"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "房间类型"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "房间类型"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "类型:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "编码:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "街区"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "街区"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "街区:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "街区"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "没有前期的查找."},
        {key1: "Common.control.Signature", key2: "Clear", value: "清除"},
        {key1: "Common.control.Signature", key2: "Done", value: "完成"},
        {key1: "Common.control.Signature", key2: "Signature", value: "签字"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "当扩充 Common.controller.NavigationController 类时，需要提供一个 mainView ref config"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "取消"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "保存"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "你要继续？"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "推出连接设备出错. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "登出并不删除应用数据.<br>你需要重新注册设备从而再次使用该应用."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "注册"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "注册失败"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "设备注册服务不能使用，移动服务可能没有在网络中心激活"},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "模型 [{0}] 不存在."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "无法扫描条码"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "拒绝察看地点信息"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "没有位置"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "位置超时"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "未知位置错误"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "显示文档时出错"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "显示文档"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "下载文件"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "功能在桌面环境不可用."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "字段不存在"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "文件 {0} 无法显示在本设备."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "文件 {0} 在桌面模式无法显示."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "移除文档"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "字段变更，字段: {0} 新值: {1} 旧值: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "输入"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "字段 {0} 输入不能超过 {1} 字符"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "取消"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "清除"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "复制"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "完成"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "错误"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "否"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "粘贴"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "重新加载"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "房间名称"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "房间名字"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "保存图片"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "评价"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "是"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "装入更多…"},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "没有更多记录了"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "装入更多…"},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "没有更多记录了"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "该应用被升级到最新版. 正在重新装载应用."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "访问网络出错。可能网络连接慢或不可用。"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "没有连接到网络"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "没有从服务器收到数据"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "超时"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "未知错误"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "注册设备出错。"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "提取用户信息出错."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "设置进程语言出错."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "启动用户进程出错."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "登录错"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "获取表格定义出错。"},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "设备没有注册."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Workflow toJSON. Date objects 不允许用 Workflow Rules 来配置。"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "执行工作流规则"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Workflow rule 失败:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "应用预选项"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "大厦"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "原因类型"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "联系人"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "技工"},
        {key1: "Common.store.Departments", key2: "Departments", value: "部门"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "业务部"},
        {key1: "Common.store.Employees", key2: "Employees", value: "员工"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "员工级别"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "设备"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "设备规格"},
        {key1: "Common.store.Floors", key2: "Floors", value: "楼层"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "受伤区域"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "受伤类型"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "事故类型"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "平面图组"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "平面图类型"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "问题类型"},
        {key1: "Common.store.Projects", key2: "Projects", value: "项目"},
        {key1: "Common.store.Properties", key2: "Properties", value: "属性"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "数据库错误:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "没有数据库表变更. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "字段: [{0}] 缺省值没有更新"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "更新缺省值: 字段 [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Sqlite Proxy 出错"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "创建操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "销毁操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "读操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "更新操作发生 Sqlite Proxy 错误"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "打开数据库出错: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "数据库错误 [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "数据库错误 SqliteView proxy 问题."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView 是只读的，不支持删除记录操作"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView 是只读的，不支持更新记录操作"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqlliteView是只读的，不支持创建新记录操作"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "数据库不包含所需要的Sqllite视图 {0} 的表定义"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "维修类型"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "房间类别"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "房间"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "房间标准"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "房间类型"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "房间用途"},
        {key1: "Common.store.Sites", key2: "Sites", value: "街区"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "文件找不到"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "同步"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "下载"},
        {key1: "Common.sync.Manager", key2: "Error", value: "错误"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "输入的值无法转换为 Common.type.Date 类型"},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "输入的值无法转换为 Common.type.Integer 类型"},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "输入的值无法转换为 Common.type.Time 类型"},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "输入的值无法转换为 Common.type.Timestamp 类型"},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "应用的偏好参数没有装入"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "运行在浏览器方式. 停止文件系统读取"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "运行于 Chrome 或 WebView. 停止文件系统读取"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "中止文件访问"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "此文件已存在"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "文件编码错误"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "文件错误"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "文件处于无效状态"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "不允许修改文件"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "文件超过配额"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "文件安全错误"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "文件类型不匹配错误"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "文件未找到"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "文件不可读"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "无效的文件修改错误"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "没有连接到网络"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "没有网络"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "下载背景数据"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "错误"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "App Preferences store 没有载入. 无法读取 preferences"},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "M"},
        {key1: "Common.util.Units", key2: "sq ft", value: "平方英尺"},
        {key1: "Common.util.Units", key2: "sq m", value: "平方米"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "用户基本情况信息得不到. 请点击同步获取用户基本状况信息."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "同步的时候删除"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "显示"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "文档"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "没有文档"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "第 {0} ，共 {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1/ x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "该视图相关的 Model class 名称应该在 model property 中提供"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "该视图相关的 Store class 的 store id 必须在storeId property 中提供"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "清除"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "筛选"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "返回"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "保存"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "字段"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "标识"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "长度(Bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "同步信息"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "表格"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "下列 Web Central 字段值没有写入客户数据库，因为数据大小超过数据库定义"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "设置查询条件"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Assign the work request to you?", value: "分配工作请求到你?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Cancel", value: "取消"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Estimation", value: "完成评估"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Scheduling", value: "完成排程"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete", value: "删除"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete the craftsperson?", value: "删除维修工?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate", value: "预估"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate requests to more accurately budget, to schedule labor, and to reserve parts. You can change your estimates until you issue the request.<br/><br/>Complete the estimation of the work request?", value: "工作请求的预估工作可以更准确地预算成本，排程工时，预订部件. 在发出工单前你都可以预估工作请求.<br/><br/>结束预估工作请求吗?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Forward", value: "转发"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Map functionility can not run on Phone.", value: "地图功能不能在手机上运行。"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Pending workflow step", value: "等待工作流步骤"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please add your comments before rejecting the work request", value: "拒绝工作请求前请添加说明"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please complete the pending workflow step", value: "请完成等待的工作流步骤"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Reject", value: "拒绝"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Resume the work request to Issued?", value: "恢复工作请求到已发布状态?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Return", value: "返回"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Schedule requests to better plan and balance work for teams and craftspersons. You can change the schedule assignments until you issue the request.<br/><br/>Complete the scheduling of the work request?", value: "排程工作请求可平衡工作组和维修工的工作量. 在发出工单前都可以调整排程.<br/><br/>结束工作请求的排程工作吗?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Self Assign", value: "分给自己"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Supervisor or Work Team Id must be completed before forwarding the request", value: "转发工作前，必须填入主管或工作组"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The request will be automatically be sent back one step", value: "请求会被自动返回上一步。"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The work request is already assigned to you", value: "工作已经分配给你"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "There is another existing record with the same primary keys.", value: "已经存在一条主键值完全相同的数据。"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action archives the request and prevents any further updates to it.<br/><br/>Close the work request?", value: "该功能将存档工作请求，从此不能更新了。<br/><br/>关闭工作请求?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "该功能在工作尚未开始前取消工作请求. 取消工作请求将结束请求的工作流.<br/><br/>取消工作请求吗?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action issues the request to field personnel. Once you issue the request, it cannot be cancelled; it can be completed, put on hold, or stopped.<br/><br/>Issue the work request?", value: "该功能将工单转发给外业人员. 发出后，可以完成，等待，或停止.<br/><br/>发出工作请求?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action marks the request as Completed. A Supervisor can update labor, parts, comments, and other work details until the request is Closed.<br/><br/>Complete the work request?", value: "该功能将标记工作请求为完成状态. 主管可以更新维修工，部件，说明，以及其他工作信息，直到工作请求关闭.<br/><br/>完成工作请求吗?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action puts a request on hold while waiting for parts, the appropriate trade, or security access. You can stop or complete a request that is on hold.<br/><br/>Put on hold the work request?", value: "该功能将工作请求暂停，等待部件，维修工或进入. 你可以将此类暂停的工作请求停止或完成.<br/><br/>暂停工作请求吗?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action stops a request on which some work has already been performed and which may be billed. Stopping a request ends the request workflow.<br/><br/>Stop the work request?", value: "该功能将停止工作请求，即使工作已经开始而且将可能收费. 停止工作请求将结束该工作流.<br/><br/>停止工作请求?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Two resource records of the same type can not be added for the same day.  Please edit the existing record to reflect the correct totals.", value: "同类型的两个资源记录不能在同一天加入。请编辑已有的记录来反映正确的合计值。"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work Request", value: "工作请求"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work request assigned", value: "已分配工作请求"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You cannot select both Supervisor and Work Team Id before forwarding the request", value: "转发工作请求前，你不能同时选择主管和工作组"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You have changed the work request. Please sync before taking any further actions on it", value: "你修改了工作请求. 请先完成同步，然后再做进一步操作"},
        {key1: "Maintenance.controller.manager.WorkRequestActionsMultiple", key2: "Please input the comments first", value: "请先输入备注"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work requests assigned", value: "已分配的工作请求"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Other Cost", value: "添加其它成本"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Part", value: "添加备件"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Trade", value: "添加工种"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Other Cost", value: "编辑其他费用"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Part", value: "编辑备件"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Trade", value: "编辑工种"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "所有的工作请求文档字段都在使用.<br>图片加不到工作请求"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "Documents", value: "文档"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "This action will remove the document. Do you want to proceed?", value: "这个操作将删除文档。你想继续吗？"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Cancel", value: "取消"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Complete", value: "完成"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Craftsperson Labor", value: "技工工作量"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "One or more craftsperson entries are missing labor hours<br>Do you want to Complete the Work Request?", value: "一个或多个工人的工时被丢失<br>完成请求？"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Please input the comments first", value: "请先输入备注"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Status", value: "状态"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "The Work Request status is Completed.<br>The status cannot be modified.", value: "工作请求状态为完成.<br>这个状态不能再修改了."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "该功能在工作尚未开始前取消工作请求. 取消工作请求将结束请求的工作流.<br/><br/>取消工作请求吗?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action marks your assignment as Completed. Supervisors can update labor, parts, comments, and other work details until the request is Closed.<br>Complete your assignment?", value: "这个操作把你的的任务设置为已完成。在请求被关闭之前，主管可以更新技工，备件，备注和其他工作详情。<br>完成你的任务？"},
        {key1: "Maintenance.controller.FloorPlan", key2: "Locate Room", value: "查找房间"},
        {key1: "Maintenance.controller.FloorPlan", key2: "The work request is not assigned to a room and therefore cannot be located.", value: "工作请求没有指定到房间，因此无法定位."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Craftsperson is required.", value: "需要维修工."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "User Account", value: "用户账号"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Validation", value: "验证"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Your account does not have Craftsperson access. Submit Work Requests using the My Request tab.", value: "你的账户没有维修工权限. 提交工作请求请使用 - 我的工作请求- 标签页."},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Info", value: "信息"},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Updating Work Requests", value: "正在更新工作请求"},
        {key1: "Maintenance.model.manager.WorkRequestTool", key2: " {0} and {1} must be before {2} and {3}", value: "{0}和{1}必须在{2}和{3}前面"},
        {key1: "Maintenance.model.PartStorageLocation", key2: "must be greater than 0.", value: "必须大于0."},
        {key1: "Maintenance.model.WorkRequest", key2: " {0} is required", value: "{0}是必须的"},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be greater than or equal to 0.", value: "必须 >= 0."},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be less than or equal to 100,000,000.", value: "必须 <= 100,000,000."},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0} and {1} must be before {2} and {3}", value: "{0}和{1}必须在{2}和{3}前面"},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0}, {1}, or {2} are required", value: "{0}，{1}，{2} 是必要的"},
        {key1: "Maintenance.store.Accounts", key2: "Accounts", value: "资金账户"},
        {key1: "Maintenance.store.Buildings", key2: "Buildings", value: "大厦"},
        {key1: "Maintenance.store.manager.Craftspersons", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.store.manager.CraftspersonWorkTeams", key2: "Craftsperson Work Teams", value: "工匠的工作团队"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Approved", value: "已批准"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Completed", value: "已完成"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Issued", value: "已发出"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Requests", value: "我的请求"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Work", value: "我的工作"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Requested", value: "已请求"},
        {key1: "Maintenance.store.manager.PartStorageLocations", key2: "Part Storage Locations", value: "备件存储位置"},
        {key1: "Maintenance.store.manager.StorageLocations", key2: "Storage Locations", value: "存储位置"},
        {key1: "Maintenance.store.manager.Tools", key2: "Tools", value: "工具"},
        {key1: "Maintenance.store.manager.Trades", key2: "Trades", value: "工种"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve", value: "批准"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Estimate", value: "批准评估"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Schedule", value: "批准排程"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Cancel", value: "取消"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Close", value: "关闭"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Complete", value: "完成"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Estimate", value: "预估"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Forward", value: "转发"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Access", value: "暂停等待进入"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Labor", value: "暂停等待维修工"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Parts", value: "暂停等待备件"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Issue", value: "发出"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Link New", value: "链接新请求"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Resume To Issued", value: "恢复到已发布"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Return", value: "返回"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Schedule", value: "排程"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Self Assign", value: "分给自己"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Stop", value: "停止"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Update", value: "更新"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Verify", value: "验证"},
        {key1: "Maintenance.store.manager.WorkRequestReferences", key2: "References", value: "参考"},
        {key1: "Maintenance.store.manager.WorkRequestTools", key2: "Tools", value: "工具"},
        {key1: "Maintenance.store.manager.WorkRequestTrades", key2: "Trades", value: "工种"},
        {key1: "Maintenance.store.OtherResources", key2: "Resources", value: "资源"},
        {key1: "Maintenance.store.PmProcedures", key2: "PM Procedures", value: "定期维护程序"},
        {key1: "Maintenance.store.ProblemDescriptions", key2: "Problem Descriptions", value: "问题描述"},
        {key1: "Maintenance.store.ProblemResolutions", key2: "Problem Resolutions", value: "问题解决方案"},
        {key1: "Maintenance.store.WorkRequestCosts", key2: "Costs", value: "成本"},
        {key1: "Maintenance.store.WorkRequestCraftspersons", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.store.WorkRequestParts", key2: "Parts", value: "备件"},
        {key1: "Maintenance.store.WorkRequests", key2: "Due Today", value: "今天到期"},
        {key1: "Maintenance.store.WorkRequests", key2: "On Hold", value: "待定"},
        {key1: "Maintenance.store.WorkRequests", key2: "Other", value: "其它"},
        {key1: "Maintenance.store.WorkRequests", key2: "Overdue", value: "已过期"},
        {key1: "Maintenance.store.WorkRequests", key2: "Pending", value: "等待中"},
        {key1: "Maintenance.store.WorkRequests", key2: "Work Request", value: "工作请求"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Approved", value: "已批准"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Completed", value: "已完成"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Issued", value: "已发出"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Requests", value: "我的请求"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Work", value: "我的工作"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Requested", value: "已请求"},
        {key1: "Maintenance.view.FloorPlan", key2: "Floor Plans", value: "楼层平面图"},
        {key1: "Maintenance.view.FloorPlan", key2: "Site", value: "街区"},
        {key1: "Maintenance.view.Main", key2: "Add Purchased Parts", value: "添加采购的备件"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code", value: "大厦"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code:", value: "大厦:"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Code", value: "备件"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Storage Locations", value: "备件存储位置"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Quantity Available", value: "可使用的数量"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Code", value: "备件存储位置"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Name", value: "备件存储位置名称"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Work Request Code", value: "工作请求编码"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account", value: "资金账户"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account Code", value: "账户编码"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Add Purchased Parts to Inventory", value: "添加已购买备件到清册"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part", value: "备件"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part Code", value: "备件"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Price", value: "价格"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Quantity (each)", value: "数量 (每个)"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location", value: "存储位置"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location Code", value: "备件存储位置"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve", value: "批准"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Request", value: "批准请求"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Cancel", value: "取消"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Documents", value: "文档"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "References", value: "参考"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Reject", value: "拒绝"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Approve", value: "批准"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Reject", value: "拒绝"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Requests", value: "批准请求"},
        {key1: "Maintenance.view.manager.EstimateApproveForm", key2: "Approve Request Estimation", value: "批准请求的预估"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Costs", value: "成本"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Documents", value: "文档"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "References", value: "参考"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Trades", value: "工种"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Complete Estimation", value: "完成评估"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Estimate", value: "预估"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Actual Cost", value: "实际成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Add Other Cost", value: "添加其它成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Labor", value: "人工成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Parts", value: "备件成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Estimated Cost", value: "预估成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Costs", value: "其它成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Description", value: "其他资源描述"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Type", value: "其他资源类型"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Quantity Used", value: "使用数量"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Actual Costs", value: "实际花费总计"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Estimated Costs", value: "预估费用总计"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Total Cost", value: "合计成本"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Units", value: "单位"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Complete Estimation", value: "完成评估"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Costs", value: "成本"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Estimate", value: "预估"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Requests to Estimate", value: "需要评估的请求"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Trades", value: "工种"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Part", value: "添加备件"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Purchased Parts", value: "添加采购的备件"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Building Code", value: "大厦"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part", value: "备件"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part Code", value: "备件"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Available", value: "可使用的数量"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Estimated", value: "预估数量"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Used", value: "使用数量"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Code", value: "备件存储位置"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Name", value: "备件存储位置名称"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Email", value: "电子邮件"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Employee Code", value: "员工"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Forward", value: "转发"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Supervisor", value: "主管"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Work Team Code", value: "工作组编码"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Forward", value: "转发"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Requests to Forward", value: "需要转发的请求"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Supervisor", value: "主管"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Work Team Code", value: "工作组编码"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Completer", value: "完成人"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Estimator", value: "估计人"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Issuer", value: "发出人"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject", value: "拒绝"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject Request", value: "拒绝请求"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Requestor", value: "申请人"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Scheduler", value: "调度人"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Approver's Comments", value: "批准人的备注"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Building", value: "大厦"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Craftsperson Notes", value: "技工备注"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Date Requested", value: "申请日期"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Equipment Code", value: "设备编码"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Floor", value: "楼层"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Priority", value: "优先级"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Location", value: "发生问题的地点"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Type", value: "问题类型"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Related Requests", value: "相关的请求"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Requestor", value: "申请人"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Room", value: "房间"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Status", value: "状态"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return", value: "返回"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return Work Request", value: "返回工作请求"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Requests to Forward", value: "需要转发的请求"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return", value: "返回"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return Work Request", value: "返回工作请求"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Approved", value: "已批准"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "by", value: "由"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Completed", value: "已完成"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Access", value: "暂停等待进入"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Labor", value: "暂停等待维修工"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Parts", value: "暂停等待备件"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Issued", value: "已发出"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Rejected", value: "已拒"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Requested", value: "已请求"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return", value: "返回"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return Work Request", value: "返回工作请求"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.manager.ScheduleApproveForm", key2: "Approve Request Schedule", value: "批准请求的计划"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Add Trade", value: "添加工种"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Estimated Hours", value: "预估小时"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Hours", value: "小时"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade", value: "工种"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Code", value: "工种编码"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Description", value: "工种说明"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trades", value: "工种"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Complete Scheduling", value: "完成排程"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Documents", value: "文档"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Forward", value: "转发"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "References", value: "参考"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Schedule", value: "排程"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Trades", value: "工种"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Actual Hours", value: "实际时数"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Assign Craftsperson", value: "指派技工"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Copy", value: "复制"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson", value: "技工"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson Code", value: "技工"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Finished", value: "结束日期"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Scheduled", value: "计划日期"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Started", value: "开始日期"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Doubletime Hours", value: "双倍工时"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Overtime Hours", value: "加班工时"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Primary Trade", value: "基本工种"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Scheduled Hours", value: "计划工时"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Start", value: "开始"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Status", value: "状态"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Stop", value: "停止"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Finished", value: "完成时间"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Scheduled", value: "排程时间"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Started", value: "开始时间"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Work Type", value: "工作类型"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Complete Scheduling", value: "完成排程"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Forward", value: "转发"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Requests to Schedule", value: "需要排程的请求"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Schedule", value: "排程"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Trades", value: "工种"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Straight Time Hours Used", value: "使用的时间"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Assign Tool", value: "指派工具"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Building Code", value: "大厦"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Finished", value: "结束日期"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Scheduled", value: "计划日期"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Started", value: "开始日期"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Hours", value: "小时"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Scheduled Hours", value: "计划工时"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Start", value: "开始"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Stop", value: "停止"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Finished", value: "完成时间"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Scheduled", value: "排程时间"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Started", value: "开始时间"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool", value: "工具"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Code", value: "工具"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Type", value: "工具类型"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Complete", value: "完成"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Mark only my assignment as Completed.", value: "仅把我的的任务设置为已完成"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Return Work Request", value: "返回工作请求"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Set all craftsperson assignments as Completed", value: "将所有的技工的任务都设置为已完成"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Costs", value: "成本"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Documents", value: "文档"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "References", value: "参考"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Update", value: "更新"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Work Request Details", value: "工作请求详情"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Costs", value: "成本"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Update", value: "需要更新的请求"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Update", value: "更新"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Confirm", value: "确认"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Return Incomplete", value: "返回至未完成"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Verify", value: "验证"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Verify", value: "验证的请求"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Confirm", value: "确认"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Return Incomplete", value: "返回至未完成"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Verify", value: "验证"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Nearing Escalation", value: "10个最新升级"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Newest Requests", value: "10个最新请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Oldest Requests", value: "10个最久请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "All", value: "全部"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Any", value: "任何"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Both", value: "全部"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftsperson", value: "技工"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested From", value: "申请起始从"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested To", value: "申请日期到"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform From", value: "执行起始从"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform To", value: "执行日期到"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Equipment", value: "设备"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated", value: "已升级"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated ?", value: "已升级 ?"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Approved Requests", value: "我批准过的请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Requests", value: "我的请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "On Demand", value: "应需维护"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Part", value: "备件"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "PM", value: "PM"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Priority", value: "优先级"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Problem Type", value: "问题类型"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requestor", value: "申请人"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requests Requiring my Approval", value: "等待我批准的请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Set Filter", value: "设置查询条件"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Show", value: "显示"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Unassigned Requests", value: "尚未派发的请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Request", value: "工作请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Requests", value: "工作请求"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Type", value: "工作类型"},
        {key1: "Maintenance.view.manager.WorkRequestManagerList", key2: "REQUESTED", value: "已请求"},
        {key1: "Maintenance.view.manager.WorkRequestManagerListItem", key2: "Assigned To:", value: "分配至:"},
        {key1: "Maintenance.view.manager.WorkRequestSelection", key2: "Requests to Schedule", value: "需要排程的请求"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Hours", value: "小时"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Job Setup or Prep.", value: "工作准备"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Material Pickup", value: "挑选材料"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Travel Time", value: "旅行时间"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "UnSpecified", value: "未指明"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Client", value: "等待客户"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Security", value: "等待安检"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Work", value: "工作"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "No Status Change", value: "无状态变化"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Access", value: "等待进入"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Labor", value: "等待技工"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold For Parts", value: "等待备件"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "Resume To Issued", value: "恢复到已发布"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Actual Hours", value: "实际时数"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Cancel", value: "取消"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Doubletime Hours", value: "双倍工时"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Overtime Hours", value: "加班工时"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Save", value: "保存"},
        {key1: "Maintenance.view.phone.Main", key2: "Apps", value: "移动应用"},
        {key1: "Maintenance.view.phone.QuickComplete", key2: "Complete Request", value: "完成请求"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cancel", value: "取消"},
        {key1: "Maintenance.view.SiteMap", key2: "Buildings", value: "大厦"},
        {key1: "Maintenance.view.tablet.Main", key2: "Apps", value: "移动应用"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Actual Cost", value: "实际成本"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Add Cost", value: "添加成本"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Date Used", value: "使用日期"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Edit Cost", value: "编辑成本"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Quantity Used", value: "使用数量"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Resource Type", value: "资源类型"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Units", value: "单位"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Cost:", value: "费用:"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Other Costs", value: "其它成本"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Actual Hours", value: "实际时数"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Add Craftsperson", value: "添加技术工人"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Craftsperson", value: "技工"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Finished", value: "结束日期"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Started", value: "开始日期"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Doubletime Hours", value: "双倍工时"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Edit Craftsperson", value: "编辑技工"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Overtime Hours", value: "加班工时"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Start", value: "开始"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Status", value: "状态"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Stop", value: "停止"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Finished", value: "完成时间"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Started", value: "开始时间"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Work Type", value: "工作类型"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Hours", value: "小时"},
        {key1: "Maintenance.view.manager.WorkRequestEdit", key2: "References", value: "参考"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Assigned Date", value: "已分配的日期"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cause Type", value: "原因类型"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Code", value: "编码"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Costs", value: "成本"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftsperson Notes", value: "技工备注"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftspersons", value: "技工"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Related Work Request", value: "创建相关工作请求"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Work Request", value: "创建工作请求"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Description", value: "说明"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Documents", value: "文档"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 1", value: "图片1"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 2", value: "图片2"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 3", value: "图片3"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 4", value: "图片4"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "PM Procedure", value: "定期维护程序"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Description", value: "问题描述"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Location", value: "发生问题的地点"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Type", value: "问题类型"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Repair Type", value: "维修类型"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested", value: "已请求"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested By", value: "请求人"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Scheduled Date", value: "计划日期"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Status", value: "状态"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Tools", value: "工具"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Update", value: "更新"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Work Request Details", value: "工作请求详情"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Escalation", value: "升级"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Loading...", value: "正在加载..."},
        {key1: "Maintenance.view.WorkRequestList", key2: "Location", value: "地点"},
        {key1: "Maintenance.view.WorkRequestList", key2: "My Work", value: "我的工作"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Problem Type", value: "问题类型"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search", value: "查找"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search Work Requests", value: "搜索工作请求"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Status", value: "状态"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Add Part", value: "添加备件"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Assigned", value: "已分派"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Comments", value: "备注"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Edit Part", value: "编辑备件"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Part", value: "备件"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Quantity", value: "数量"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Parts", value: "备件"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Quantity", value: "数量"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "OpenURL", value: "打开URL"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "URL does not exsits", value: "URL不存在"},
        {key1: "Maintenance.view.WorkRequestReferencesLists", key2: "References", value: "参考"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "确定要删除该目标?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "请输入文字:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "没有楼层图"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "复制"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "粘贴"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "重新加载"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "保存图片"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "你确定要删除此项?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "编辑"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "没有楼层图来画红线"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "发布日期"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "街区地图"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "楼层图"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "红线"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "大厦"},
    ]
};
