package com.archibus.datasource.cascade.sqlbuilder;

import org.apache.log4j.Logger;

/**
 * Holds cascade SQL commands generated by handler. Extended by CascadeUpdateCommandsImpl and
 * Cascade DeleteCommandsImpl.
 * 
 * @author Catalin Purice
 * 
 */
public class CascadeCommands {
    
    /**
     * Logger to write messages to archibus.log.
     */
    protected final Logger log = Logger.getLogger(this.getClass());
    
    /**
     * All SQL commands for table.
     */
    protected final SqlCommandsStore sqlStatements = new SqlCommandsStore();
    
    /**
     * Foreign key restriction.
     */
    private final SqlRestriction foreignKeysSqlRestriction;
    
    /**
     * Constructor.
     * 
     * @param sqlRestriction SQL restriction
     */
    public CascadeCommands(final SqlRestriction sqlRestriction) {
        this.foreignKeysSqlRestriction = sqlRestriction;
    }
    
    /**
     * Getter for the foreignKeysSqlRestriction property.
     * 
     * @see foreignKeysSqlRestriction
     * @return the sqlRestriction property.
     */
    public SqlRestriction getForeignKeysSqlRestriction() {
        return this.foreignKeysSqlRestriction;
        
    }
    
    /**
     * Getter for the sqlStatements property.
     * 
     * @see sqlStatements
     * @return the sqlStatements property.
     */
    public SqlCommandsStore getSqlStatements() {
        return this.sqlStatements;
    }
}
