var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.de = {
    localizedStrings: [
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "An error occured while executing the workflow rule.", value: "Beim Ausführen der Workflow-Regel ist ein Fehler aufgetreten."},
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "Error", value: "Fehler"},
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "Not all records were saved because other assets with the same codes already exist in the inventory.", value: "Es wurden nicht alle Datensätze gespeichert, weil die Bestandsliste bereits andere Objekte mit demselben Kurzzeichen enthält."},
        {key1: "AssetReceipt.controller.AssetReceiptSync", key2: "Searching", value: "Sucht"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Add Equipment", value: "Geräte hinzufügen"},
        {key1: "AssetReceipt.controller.Navigation", key2: "An error occured while executing the workflow rule.", value: "Beim Ausführen der Workflow-Regel ist ein Fehler aufgetreten."},
        {key1: "AssetReceipt.controller.Navigation", key2: "An error occured while quering the database.", value: "Beim Abfragen der Datenbank ist ein Fehler aufgetreten."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete", value: "Löschen"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete ALL assets?", value: "ALLE Objekte löschen?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete asset?", value: "Objekt löschen?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete equipment standard?", value: "Gerätestandard löschen?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Delete selected asset(s)?", value: "Ausgewählte(s) Objekt(e) löschen?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Done", value: "Fertig"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Enter an equipment code first.", value: "Geben Sie zuerst ein Gerätekurzzeichen ein."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Equipment with code {0} already exists in inventory.", value: "Geräte mit Kurzzeichen {0} sind bereits in Gerätebestandsliste enthalten."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Equipment with code {0} does not exist in inventory.", value: "Geräte mit Kurzzeichen {0} sind nicht in Gerätebestandsliste enthalten."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Error", value: "Fehler"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Next", value: "Vor"},
        {key1: "AssetReceipt.controller.Navigation", key2: "No equipment found for selected prefix.", value: "Keine Geräte für ausgewähltes Präfix gefunden."},
        {key1: "AssetReceipt.controller.Navigation", key2: "No records have been created and no additional records will be created. Proceed with cancel action?", value: "Es wurden keine Datensätze erstellt und es werden keine zusätzlichen Datensätze erstellt. Abbruchmaßnahme fortsetzen?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "Only asset codes with {0} characters or less are supported. Codes with more than {0} characters will be truncated.", value: "Es werden nur Objektkurzzeichen mit maximal {0} Zeichen unterstützt. Kurzzeichen mit mehr als {0} Zeichen werden abgeschnitten."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Please select Get Last Number field to verify there are no existing records for the selected Prefix. Trying to create records with existing values will generate errors.", value: "Wählen Sie das Feld ’Letzte Nummer abrufen’ aus, um zu überprüfen, ob es für das ausgewählte Präfix einen bestehenden Datensatz gibt. Beim Erstellen von Datensätzen mit bestehenden Werten wird eine Fehlermeldung ausgegeben."},
        {key1: "AssetReceipt.controller.Navigation", key2: "Please wait while we generate your new assets:<br/> {0} / {1}", value: "Warten Sie, während wir Ihre neuen Objekte generieren:<br/> {0} / {1}"},
        {key1: "AssetReceipt.controller.Navigation", key2: "The records numbered {0} - {1} have been created and no additional records will be created. Proceed with cancel action?", value: "Die Datensätze {0} - {1} wurden erstellt; es werden keine zusätzlichen Datensätze erstellt. Abbruchmaßnahme fortsetzen?"},
        {key1: "AssetReceipt.controller.Navigation", key2: "This equipment standard already exists: {0}", value: "Dieser Gerätestandard ist bereits vorhanden: {0}"},
        {key1: "AssetReceipt.controller.Navigation", key2: "This standard cannot be deleted because there are equipment items registered with this standard.", value: "Dieser Standard kann nicht gelöscht werden, weil Geräteobjekte mit diesem Standard registriert sind."},
        {key1: "AssetReceipt.controller.Navigation", key2: "You have already added equipment with the following codes: {0}", value: "Sie haben bereits Geräte mit den folgenden Kurzzeichen hinzugefügt: {0}"},
        {key1: "AssetReceipt.controller.Navigation", key2: "You need to set the code for the first asset. Please fill the value for Start Number.", value: "Sie müssen das Kurzzeichen für das erste Objekt einstellen. Geben Sie einen Wert für ’Anfangsnummer’ ein."},
        {key1: "AssetReceipt.controller.Navigation", key2: "You need to set the number of assets you want to add. Please fill the value for Total Count.", value: "Sie müssen die Anzahl der Objekte einstellen, die Sie hinzufügen möchten. Geben Sie einen Wert für ’Gesamtanzahl’ ein."},
        {key1: "AssetReceipt.store.AssetReceiptEmployees", key2: "Employees", value: "Personal"},
        {key1: "AssetReceipt.store.AssetReceiptEquipment", key2: "Equipment", value: "Geräte"},
        {key1: "AssetReceipt.store.AssetReceiptFloors", key2: "Floors", value: "Geschosse"},
        {key1: "AssetReceipt.store.AssetReceiptRooms", key2: "Rooms", value: "Räume"},
        {key1: "AssetReceipt.store.EquipmentStandardsSync", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "AssetReceipt.util.Filter", key2: "Download times may be high if just the site is selected. Proceed?", value: "Das Herunterladen kann lange dauern, wenn nur der Standort ausgewählt wird. Fortfahren?"},
        {key1: "AssetReceipt.util.Filter", key2: "Please select values for Site Code and Building Code.", value: "Wählen Sie Werte für ’Standortkurzzeichen’ und ’Gebäudekurzzeichen’ aus."},
        {key1: "AssetReceipt.view.BackgroundDataFilter", key2: "Asset Inventory", value: "Objektbestandsliste"},
        {key1: "AssetReceipt.view.CommonData", key2: "Barcode scanning", value: "Einlesen des Barcodes"},
        {key1: "AssetReceipt.view.CommonData", key2: "Building", value: "Gebäude"},
        {key1: "AssetReceipt.view.CommonData", key2: "Comments", value: "Bemerkungen"},
        {key1: "AssetReceipt.view.CommonData", key2: "Common Asset Data", value: "Gemeinsame Objektdaten"},
        {key1: "AssetReceipt.view.CommonData", key2: "Department", value: "Abteilung"},
        {key1: "AssetReceipt.view.CommonData", key2: "Departments", value: "Abteilungen"},
        {key1: "AssetReceipt.view.CommonData", key2: "Division", value: "Bereich"},
        {key1: "AssetReceipt.view.CommonData", key2: "Divisions", value: "Bereiche"},
        {key1: "AssetReceipt.view.CommonData", key2: "Employee", value: "Mitarbeiter"},
        {key1: "AssetReceipt.view.CommonData", key2: "Employees", value: "Personal"},
        {key1: "AssetReceipt.view.CommonData", key2: "Floor", value: "Geschoss"},
        {key1: "AssetReceipt.view.CommonData", key2: "Get Last Number", value: "Letzte Zahl abrufen"},
        {key1: "AssetReceipt.view.CommonData", key2: "Incremented Codes", value: "Erhöhte Kurzzeichen"},
        {key1: "AssetReceipt.view.CommonData", key2: "Inventory Method", value: "Bestandslisten-methode"},
        {key1: "AssetReceipt.view.CommonData", key2: "Prefix", value: "Präfix"},
        {key1: "AssetReceipt.view.CommonData", key2: "Room", value: "Raum"},
        {key1: "AssetReceipt.view.CommonData", key2: "Start Number", value: "Anfangsnummer"},
        {key1: "AssetReceipt.view.CommonData", key2: "Total Count", value: "Gesamtanzahl"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Building:", value: "Gebäude:"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Employee:", value: "Mitarbeiter:"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Floor:", value: "Geschoss:"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Room:", value: "Räume"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "1 of x", value: "1 von x"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Building", value: "Gebäude"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Comments", value: "Bemerkungen"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Department", value: "Abteilung"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Departments", value: "Abteilungen"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Division", value: "Bereich"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Divisions", value: "Bereiche"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Edit Equipment", value: "Geräte bearbeiten"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Employee", value: "Mitarbeiter"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Employees", value: "Personal"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Floor", value: "Geschoss"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "Room", value: "Raum"},
        {key1: "AssetReceipt.view.EditEquipment", key2: "{0} of {1}", value: "{0} von {1}"},
        {key1: "AssetReceipt.view.EditEquipmentStandard", key2: "Add Standard", value: "Standard hinzufügen"},
        {key1: "AssetReceipt.view.EquipmentStandardPromptListItem", key2: "Description:", value: "Beschreibung:"},
        {key1: "AssetReceipt.view.EquipmentStandardPromptListItem", key2: "Standard:", value: "Standard:"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Asset Inventory List", value: "Objektbestandsliste"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Complete", value: "Erledigt"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Delete ALL", value: "Alle löschen"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Delete Selected", value: "Auswahl Löschen"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Location", value: "Standort"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Owner", value: "Besitzer"},
        {key1: "AssetReceipt.view.InventoryList", key2: "Standard", value: "Standard"},
        {key1: "AssetReceipt.view.Main", key2: "Apps", value: "Apps"},
        {key1: "AssetReceipt.view.Options", key2: "Add an Asset", value: "Objekt hinzufügen"},
        {key1: "AssetReceipt.view.Options", key2: "Add Multiple Assets", value: "Mehrere Objekte hinzufügen"},
        {key1: "AssetReceipt.view.Options", key2: "Asset Inventory", value: "Objektbestandsliste"},
        {key1: "AssetReceipt.view.Options", key2: "Review New Assets", value: "Neue Objekte überprüfen"},
        {key1: "AssetReceipt.view.Options", key2: "Search for Existing Asset:", value: "Vorhandene Objekte suchen:"},
        {key1: "AssetReceipt.view.Options", key2: "{0}To use this App, tap {1} to download background data{2}", value: "{0}Um diese App zu verwenden, tippen Sie auf {1}, um Stammdaten herunterzuladen.{2}"},
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Akzeptieren Sie die Browseranforderung, Daten auf Ihrem lokalen Computer zu speichern und die Seite zu aktualisieren."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fehler beim Laden der Konfigurationsdatei."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Der Controller '{0}' verfügt über keine Startmethode. Sind Sie sicher, dass der Controller eine Erweiterung von Ext.app.Controller ist?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Der Wert hat ein falsches Format:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Der Wert ist keine gültige E-Mail:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Der Wert ist kein zulässiger Wert:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Der Wert ist in der Liste zulässiger Werte nicht enthalten:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Der Wert hat eine falsche Länge:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Der folgende Wert muss vorhanden sein:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Anhängen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Schließen"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Fertig"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Ladevorgang wird ausgeführt..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Korrigieren Sie Folgendes:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scan-Fehler"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Fertig"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Keine Datenanzeige für: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Anwenden"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Kein(e) {0} zum Anzeigen"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Anforderung"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Stunden"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Objekt {0} von {1} wird geladen"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Vorname"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nachname"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Name:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Ansprechpartner"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Bezeichnung der Abteilung"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Abteilung:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Bereich"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-Mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-Mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Mitarbeiter"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Kurzzeichen Mitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standardmitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Geräte"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Gerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Geräte:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Geschosse"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Bezeichnung der Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Liegenschaft:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebäude/Geschoss:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Räume"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standardraum"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Raumtyp"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Typ:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Standort"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Standortcode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Standort:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Standorte"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Es wurden keine vorherigen Suchen gespeichert."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.Signature", key2: "Done", value: "Fertig"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Unterschrift"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Bei Erweiterung der Klasse Common.controller.NavigationController muss eine mainView-Ref.-Konfiguration bereitgestellt werden."},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Speichern"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Möchten Sie fortfahren?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Beim Aufheben der Geräteregistrierung ist ein Fehler aufgetreten. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Beim Abmelden werden Ihre Anwendungsdaten nicht entfernt.<br>Sie müssen das Gerät erneut registrieren, um auf die Apps zugreifen zu können."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registrierung"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registrierung fehlgeschlagen"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Der Gerätregistrierungsservice ist nicht verfügbar. Die Mobildienste sind in Web Central möglicherweise nicht aktiviert."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Modell mit dem Namen [{0}] ist nicht vorhanden."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Einlesen des Barcodes ist nicht möglich"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Berechtigung zum Zugriff auf Standortinformationen verweigert"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Position ist nicht verfügbar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Zeitüberschreitung der Position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fehler: Unbekannte Position"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Beim Anzeigen des Dokuments und der Finanzierungsquelle"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Dokumentanzeige"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Dokument wird heruntergeladen"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Funktion in Desktop-Umgebung nicht verfügbar."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Datei existiert nicht"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Datei {0} kann auf diesem Gerät nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Datei {0} kann im Desktop-Modus nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Dokument entfernen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Feld 'Feld geändert': {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Eingabe"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Eingabe für Feld {0} ist auf {1} Zeichen begrenzt"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Leeren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopieren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Fertig"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fehler"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nein"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Einfügen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Neu laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Raumname"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Raumnamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Bild speichern"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Umfrage"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Die Anwendung wurde auf die neueste Version aktualisiert. Die Anwendung wird neu geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fehler beim Laden von Netzwerkdiensten. Die Netzwerkverbindung ist möglicherweise langsam oder nicht verfügbar."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Keine Daten vom Server erhalten"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Zeitüberschreitung"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Unbekannter Fehler"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fehler beim Registrieren des Geräts."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fehler beim Abrufen von Benutzerinformationen."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fehler beim Festlegen des Sitzungsgebiets."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fehler beim Starten der Benutzersitzung."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fehler bei Einzelanmeldung"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fehler beim Abrufen von TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Gerät ist nicht registriert."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Workflow nach JSON. Datenobjekte dürfen nicht mithilfe von Workflow-Regeln gemarshallt werden."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Workflow-Regel ausgeführt"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Workflow-Regel fehlgeschlagen:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-Einstellungen"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Ursachentypen"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Ansprechpartner"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Personal"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standardpersonal"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Geräte"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Geschosse"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Verletzte Körperteile"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Verletzungskategorien"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Arbeitsunfall - Typen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantypgruppen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Problemtypen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projekte"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Liegenschaften"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Datenbankfehler:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Keine Änderung an Datenbanktabelle übernommen. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Keine Standardwertaktualisierung für Feld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standardwert aktualisieren: Feld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Sqlite-Proxy-Fehler"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Sqlite-Proxy-Fehler während Erstellungsvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Sqlite-Proxy-Fehler während Löschvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Sqlite-Proxy-Fehler während Lesevorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Sqlite-Proxy-Fehler während Aktualisierungsvorgang"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fehler beim Öffnen der Datenbank: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Datenbankfehler [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Datenbankfehler bei SqliteView-Proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Löschen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Aktualisieren von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Erstellen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "Die Datenbank enthält nicht die erforderlichen Tabellendefinitionen für die Sqlite-Ansicht {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Reparaturtypen"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Räume"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standardräume"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Raumnutzungsarten"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Standorte"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "datei_nicht_verfügbar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisieren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Herunterladen wird ausgeführt:"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fehler"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Date-Typ konvertiert werden."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Integer konvertiert werden."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Time konvertiert werden."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Timestamp konvertiert werden."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Die Anwendungseinstellungen wurden nicht geladen."},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Ausführung im Browser-Modus. Zugriff auf Dateisystem deaktiviert"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Ausführung in Chrome oder in WebView. Zugriff auf Dateisystem aktiviert"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Dateizugriff wurde abgebrochen"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Datei ist bereits vorhanden"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fehler bei Dateiverschlüsselung"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Dateifehler"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Datei befindet sich in einem ungültigen Zustand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Dateiänderung ist nicht zulässig"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Dateiquoten überschritten"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fehler bei Dateisicherheit"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fehler wegen Dateitypkonflikt"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Datei wurde nicht gefunden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Datei war nicht lesbar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fehler aufgrund ungültiger Dateiänderung"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netzwerk nicht erreichbar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Stammdaten werden heruntergeladen"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fehler"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Der App-Einstellungsspeicher ist nicht geladen. Einstellungen können nicht abgerufen werden."},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "m"},
        {key1: "Common.util.Units", key2: "sq ft", value: "Quadratmeter"},
        {key1: "Common.util.Units", key2: "sq m", value: "Quadratmeter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Die Benutzerprofilinformationen sind nicht verfügbar. Führen Sie eine Synchronisierung durch, um die Benutzerprofildaten abzurufen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Bei Synchronisierung löschen"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Anzeigen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Dokumente"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Keine Dokumente verfügbar."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} von {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 von x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Der Name der Modellklasse, die dieser Ansicht zugeordnet ist, muss in der Modelleigenschaft angegeben werden."},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "Die Speicher-ID der Speicherklasse, die dieser Ansicht zugeordnet ist, muss in der Eigenschaft -storeId- angegeben werden."},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Leeren"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Zurück"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Speichern"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Feld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Kennung"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Größe (Bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisierungsmeldungen"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabelle"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Die folgenden Web Central-Feldwerte wurden nicht in die Client-Datenbank übertragen, da die Datengröße die Kapazität der Datenbank überschreitet."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Bezeichnung des Gebäudes"},
    ]
};
