var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.nl = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Accepteer het browserverzoek om gegevens op de lokale computer op te slaan en vernieuw de pagina."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fout tijdens laden van configuratiebestand."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "De controller '{0}' heeft geen startmethode. Weet u zeker dat dit een uitbreiding is van Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Deze waarde heeft de verkeerde notatie:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Dit is geen geldig e-mailadres:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Dit is geen geldige waarde:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Deze waarde is niet opgenomen in de lijst met acceptabele waarden:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Deze waarde heeft de verkeerde lengte:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Deze waarde moet aanwezig zijn:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Koppelen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Sluiten"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Gereed"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Bezig met laden..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Corrigeer het volgende:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scanfout"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Gereed"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Geen gegevens om weer te geven voor: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Toepassen"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Geen {0} om weer te geven."},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Aanvraag"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Uren"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Item {0} van {1} laden"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Voornaam"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Achternaam"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Naam:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contactpersoon"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Afdelingscode"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Afdeling:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Divisiecode:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Divisie"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Divisie:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisies"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Medewerker"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Personeelscode"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Personeelsstandaard"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Uitrusting:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type probleem"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code van vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Vastgoedobject:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebouw/verdieping:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Ruimtestandaard"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standaards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type ruimte"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Vestigingscode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Er zijn geen eerdere zoekopdrachten opgeslagen."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.Signature", key2: "Done", value: "Gereed"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Handtekening"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Er moet een mainView-referentieconfiguratie worden verstrekt bij het uitbreiden van de Common.controller.NavigationController-klasse"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Opslaan"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Doorgaan?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Fout bij het ongedaan maken van de apparaatregistratie. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Door uit te loggen worden uw toepassingsgegevens niet verwijderd.<br>U moet het apparaat opnieuw registreren om toegang tot de apps te krijgen."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registratie"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registratie is mislukt"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "De service voor apparaatregistratie is niet beschikbaar. De Mobiel-services zijn mogelijk niet ingeschakeld in Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Model met de naam [{0}] bestaat niet."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Scannen van barcodes is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Toestemming voor toegang tot locatiegegevens geweigerd"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Positie is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Time-out voor positie"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fout onbekende positie"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Er is een fout opgetreden tijdens het weergeven van het document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Documentweergave"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Document downloaden"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Functie niet beschikbaar in de desktopomgeving."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Bestand bestaat niet"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Bestand {0} kan niet op dit apparaat worden weergegeven."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Bestand {0} kan niet worden weergegeven in de Desktop-modus."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Document verwijderen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Veld met de naam Veld gewijzigd: {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Invoer"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Invoer voor veld {0} is beperkt tot {1} tekens"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Wissen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopiëren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Gereed"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fout"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nee"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Plakken"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Ruimtenaam"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Ruimtenamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Survey"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Deze toepassing is bijgewerkt naar de laatste versie. De toepassing wordt opnieuw geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fout bij laden van netwerkservices. De netwerkverbinding kan traag of niet beschikbaar zijn"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Geen gegevens ontvangen van server"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Time-out"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Onbekende fout"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fout bij registreren van apparaat"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fout tijdens ophalen van gebruikersinformatie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fout tijdens instellen van landinstellingen voor sessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fout tijdens opstarten van gebruikerssessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fout bij eenmalige aanmelding"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fout bij ophalen van TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Apparaat is niet geregistreerd"},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Werkstroom toJSON. Datumobjecten mogen niet worden gerangschikt aan de hand van Werkstroomregels."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Werkstroomregel uitgevoerd"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Werkstroomregel mislukt:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-voorkeuren"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types oorzaken"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contactpersonen"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisies"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Medewerkers"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Personeelsstandaarden"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Letsels"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Letselcategorieën"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Incidenttypen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantype Groepen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Type problemen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projecten"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Eigenschappen"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Databasefout:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Geen wijziging aan databasetabel toegepast. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Standaardwaarde niet bijgewerkt voor veld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standaardwaarde bijwerken: veld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Fout Sqlite-proxy"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Fout Sqlite-proxy tijdens aanmaken"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Fout Sqlite-proxy tijdens vernietigen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Fout Sqlite-proxy tijdens lezen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Fout Sqlite-proxy tijdens bijwerken"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fout bij openen van database: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Databasefout [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Databasefout in SqliteView-proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView is alleen-lezen; het verwijderen van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView is alleen-lezen; het bijwerken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView is alleen-lezen; het maken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "De database bevat niet de vereiste tabeldefinities voor Sqllite-weergave {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Type reparaties"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Ruimtestandaarden"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Ruimtefuncties"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "bestand_niet_beschikbaar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchroniseren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Downloaden"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fout"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "De applicatievoorkeuren zijn niet geladen"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Uitvoeren in browsermodus. Toegang tot bestandssysteem uitgeschakeld"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Uitvoeren in Chrome of in webweergave. Toegang tot bestandssysteem ingeschakeld"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Toegang tot bestanden werd afgebroken"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Bestand bestaat al"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fout bij bestandscodering"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Bestandsfout"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Bestand is in ongeldige toestand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Bestandswijziging is niet toegestaan"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Bestandsquotum is overschreden"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fout bij bestandsbeveiliging"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fout bij vergelijken bestandstype"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Bestand is niet gevonden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Bestand is niet leesbaar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fout: ongeldige bestandswijziging"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netwerk onbereikbaar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Basisgegevens downloaden"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fout"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Het toepassingsvoorkeurenarchief is niet geladen. Kan voorkeuren niet ophalen."},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "sq ft"},
        {key1: "Common.util.Units", key2: "sq m", value: "vierkante meter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "De gegevens van het gebruikersprofiel zijn niet beschikbaar. Synchroniseer om de gegevens van het gebruikersprofiel op te halen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Verwijderen tijdens synchroniseren"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Tonen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documenten"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Geen documenten beschikbaar"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} of {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 van x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "De naam van de Model-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de modeleigenschap"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "De opslag-id van de Opslag-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de storeId-eigenschap"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Wissen"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Terug"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Opslaan"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Veld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifier"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Grootte (in bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisatieberichten"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabel"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "De volgende Web Central-veldwaarden zijn niet naar de clientdatabase geschreven omdat de hoeveelheid gegevens de databaselimiet overschrijdt"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter instellen"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Description", value: "Omschrijving"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Description:", value: "Omschrijving:"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Injury Area", value: "Letsel"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Injury Area:", value: "Letsel:"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryArea", key2: "Injury Areas", value: "Letsels"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Description", value: "Omschrijving"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Description:", value: "Omschrijving:"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Injury Categories", value: "Letselcategorieën"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Injury Category", value: "Letselcategorie"},
        {key1: "IncidentReporting.control.prompt.IncidentInjuryCategory", key2: "Injury Category:", value: "Letselcategorie:"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Description", value: "Omschrijving"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Description:", value: "Omschrijving:"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Incident Type", value: "Incidenttype"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Incident Types", value: "Incidenttypen"},
        {key1: "IncidentReporting.control.prompt.IncidentType", key2: "Injury Type:", value: "Letseltype:"},
        {key1: "IncidentReporting.view.General", key2: "Description", value: "Omschrijving"},
        {key1: "IncidentReporting.view.General", key2: "Incident Type", value: "Incidenttype"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Are you sure you want to delete this photo?", value: "Weet u zeker dat u deze foto wilt verwijderen?"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Delete Photo", value: "Foto verwijderen"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Incident unavailable", value: "Incident niet beschikbaar"},
        {key1: "IncidentReporting.controller.IncidentDocuments", key2: "Please first save the incident.", value: "Sla eerst het incident op."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Are you sure you want to delete this incident?", value: "Weet u zeker dat u dit incident wilt verwijderen?"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Are you sure you want to delete this witness?", value: "Weet u zeker dat u deze getuige wilt verwijderen?"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Clear the field Non-Emp. Contact Code to replace it with a Non-Employee Witness Name that is not in the Contacts list.", value: "Het veld Niet-medewerker wissen Code van contactpersoon te vervangen door een Getuigenaam niet-medewerker die niet in de lijst Contacten staat."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Clear the field Non-Emp. Witness Name and Non-Emp. Witness Contact Inf. to replace it with an existing Non-Employee Contact.", value: "Het veld Niet-medewerker wissen Getuigenaam en niet-medewerker Gegevens getuige te vervangen door een bestaand Contact niet-medewerker."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Delete Incident", value: "Incident verwijderen"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Delete Witness", value: "Getuige verwijderen"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Employee {0} doesn't have a location defined.", value: "Voor medewerker {0} is geen locatie gedefinieerd."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Fill in either Non-Emp. Contact Code or Non-Emp. Witness Name. Use Non-Emp. Witness Name if the witness is not in the Contacts list.", value: "Vul in: Niet-medewerker Code van contactpersoon of Naam externe getuige. Gebruik Naam externe getuige als de getuige niet is opgenomen in de lijst Contacten."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Location not defined", value: "Locatie niet gedefinieerd"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "One and only one of these fields is mandatory:<br />Affected Employee, Non-Emp. Contact Code or Affected Non-Emp. Name.", value: "Slechts één van deze velden is verplicht:<br />Betrokken medewerker, Contactcode niet-medewerker of Naam betrokken niet-medewerker."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Please first fill the 'Reported By' field.", value: "Vul eerst het veld 'Gerapporteerd op basis van' in."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Reporter unavailable", value: "Melder niet beschikbaat"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "Same affected person", value: "Dezelfde betrokken persoon"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "The incident was saved", value: "Het incident is opgeslagen"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "The same affected person was already saved for a similar incident. Proceed?", value: "Dezelfde betrokken persoon is al opgeslagen voor een soortgelijk incident. Wilt u doorgaan?"},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "To report this incident for an affected non-employee, clear the field Affected Employee.", value: "Wis de inhoud van het veld Betrokken medewerker om dit incident te melden voor een betrokken niet-medewerker."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "To report this incident for different type of affected person, clear the field Non-Emp. Contact Code.", value: "Als u dit incident voor een ander type betrokken persoon wilt melden, wist u de inhoud van het veld Contactcode niet-medewerker."},
        {key1: "IncidentReporting.controller.IncidentNavigation", key2: "To report this incident for different type of affected person, clear the fields Affected Non-Emp. Name and Affected Non-Emp. Contact Inf.", value: "Als u dit incident voor een ander type betrokken persoon wilt melden, wist u de inhoud van de velden Naam betrokken niet-medewerker en Contactgegevens niet-medewerker."},
        {key1: "IncidentReporting.controller.IncidentSync", key2: "Syncing Incidents", value: "Incidenten synchroniseren"},
        {key1: "IncidentReporting.model.Incident", key2: "You can't create an Incident supposed to occur in the future. Please change the {0}.", value: "U kunt geen incident aanmaken dat in de toekomst moet plaatsvinden. Wijzig {0}."},
        {key1: "IncidentReporting.model.Incident", key2: "You can't set a future date for {0}. Please change the {0}.", value: "U kunt geen datum in de toekomst instellen voor {0}. Wijzig {0}."},
        {key1: "IncidentReporting.model.Incident", key2: "You must complete one and only one of these fields: {0}, {1} or {2}.", value: "U mag slechts één van deze velden invullen: {0}, {1} of {2}."},
        {key1: "IncidentReporting.model.IncidentWitness", key2: "You must complete one and only one of these fields: {1}, {2}, {3}.  Enter the {1} if {0} is Employee, else {2} or {3} if {0} is Non-Employee.", value: "U mag slechts één van deze velden invullen: {1}, {2}, {3}.  Voer {1} in als {0} een medewerker is, voer anders {2} of {3} in als {0} een niet-medewerker is."},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Documents", value: "Documenten"},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Location Details", value: "Locatiedetails"},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Medical Details", value: "Medische details"},
        {key1: "IncidentReporting.store.DetailButtons", key2: "Witness Details", value: "Getuigedetails"},
        {key1: "IncidentReporting.store.DropDownActions", key2: "Employee Location", value: "Locatie medewerker"},
        {key1: "IncidentReporting.store.DropDownActions", key2: "Reporter Location", value: "Locatie rapporteur"},
        {key1: "IncidentReporting.store.IncidentWitnesses", key2: "Witnesses", value: "Getuigen"},
        {key1: "IncidentReporting.view.General", key2: "Add Incident Details", value: "Details incident toevoegen"},
        {key1: "IncidentReporting.view.General", key2: "Incident Details", value: "Details incident"},
        {key1: "IncidentReporting.view.General", key2: "One and only one of these fields is mandatory:<br />Affected Employee, Non-Emp. Contact Code or Affected Non-Emp. Name", value: "Slechts één van deze velden is verplicht:<br />Betrokken medewerker, Contactcode niet-medewerker of Naam betrokken niet-medewerker"},
        {key1: "IncidentReporting.view.IncidentList", key2: "Incidents", value: "Incidenten"},
        {key1: "IncidentReporting.view.IncidentList", key2: "{0} Press the {1} button to add a new incident.{2}", value: "{0} Klik op de knop {1} om een nieuw incident toe te voegen.{2}"},
        {key1: "IncidentReporting.view.Location", key2: "Location Details", value: "Locatiedetails"},
        {key1: "IncidentReporting.view.Main", key2: "Apps", value: "Apps"},
        {key1: "IncidentReporting.view.Medical", key2: "Medical Information", value: "Medische gegevens"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Attach", value: "Koppelen"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Close", value: "Sluiten"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Delete", value: "Verwijderen"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Photo", value: "Foto"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Photo Desc.", value: "Omschr. van foto"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Photo Name", value: "Naam van foto"},
        {key1: "IncidentReporting.view.PhotoPanel", key2: "Save", value: "Opslaan"},
        {key1: "IncidentReporting.view.Witness", key2: "Delete", value: "Verwijderen"},
        {key1: "IncidentReporting.view.Witness", key2: "Employee", value: "Medewerker"},
        {key1: "IncidentReporting.view.Witness", key2: "Non-Employee", value: "Niet-medewerker"},
        {key1: "IncidentReporting.view.Witness", key2: "Witness", value: "Getuige"},
        {key1: "IncidentReporting.view.WitnessList", key2: "Witnesses", value: "Getuigen"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Weet u zeker dat u dit object wilt verwijderen?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Voer de inhoud voor het tekstvak in:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Plattegrond is niet beschikbaar"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Kopiëren"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Plakken"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Weet u zeker dat u dit item wilt verwijderen?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Bewerken"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Er is geen verdiepingplattegrond beschikbaar voor Rode lijn"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Datums publiceren"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Locatieplattegronden"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Verdiepingplattegrond"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Rode lijn"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Gebouwcodes"},
    ]
};
