/**
 * Handles events generated by the Solutions document feature in CameraForm demo
 */
Ext.define('Solutions.controller.Documents', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            cameraPanel: 'camera',
            cameraForm: 'cameraform',
            viewSelectorPanel: 'viewSelectorPanel'
        },

        control: {
            cameraPanel: {
                attach: 'onAttachPhoto'
            }
        }
    },

    /**
     * Sets the image in the document field.
     * @param cameraPanel
     */
    onAttachPhoto: function (cameraPanel) {
        var me = this,
            imageData = cameraPanel.getImageData(),
            cameraForm = me.getCameraForm(),
            viewSelectorPanel = me.getViewSelectorPanel(),
            documentFields, viewSelectorButton, record,
            attachNewPhotoFunction;

        if (cameraForm && !cameraForm.getHidden()) {

            //For Image in Form example

            documentFields = cameraForm.query('documentfield');
            documentFields[0].setImageData(imageData);
            cameraPanel.onClosePanel();

        } else if (viewSelectorPanel && !viewSelectorPanel.getHidden()) {

            //For View Selector example

            attachNewPhotoFunction = function () {
                record = Ext.create('Solutions.model.Document');
                record.set('name', 'Photo');
                record.set('doc', 'Photo.jpg');
                record.set('doc_contents', imageData);
                record.set('doc_isnew', true);

                // Set the record on the button to update the value displayed on the badge.
                // It uses the getDocumentCount function in the model to calculate the value displayed.
                viewSelectorButton = viewSelectorPanel.query('#documentViewSelector');
                viewSelectorButton[0].setRecord(record);

                // Set the record on the viewSelector to use on the view displaying the photos.
                viewSelectorPanel.setRecord(record);

                cameraPanel.onClosePanel();
            };

            if ((viewSelectorPanel.getRecord() && viewSelectorPanel.getRecord().getDocumentCount() === 0)
                || viewSelectorPanel.getRecord() === null) {
                attachNewPhotoFunction.call();
            } else {
                Ext.Msg.confirm('Attach photo', 'Overwrite existing photo?', function (buttonId) {
                    if (buttonId === 'yes') {
                        attachNewPhotoFunction.call();
                    }
                });
            }
        }
    }
});