/**
 * Contains application level events. Allows controllers to handle events generated by other controllers.
 * @since 21.3
 * @author Jeff Martin
 */
Ext.define('Common.controller.EventBus', {
    mixins: ['Ext.mixin.Observable'],
    singleton: true,

    /**
     * Fired by the Common.controller.NavigationController when the Android Back Button is
     * pressed and the navigation controller is displaying the main view.
     *
     * Handled in the Common.controller.AppHomeController class
     */
    fireNavigateToAppLauncherEvent: function() {
        this.fireEvent('navigateToAppLauncher');
    },


    fireFieldSizeLimitExceeded: function(serverTableName, fieldName, primaryKeyValues, fieldSize) {
        this.fireEvent('fieldsizelimitexceeded', serverTableName, fieldName, primaryKeyValues, fieldSize);
    },

    fireStoreSyncStart: function(store) {
        this.fireEvent('storesyncstart', store);
    },

    fireStoreSyncEnd: function(store) {
        this.fireEvent('storesyncend', store);
    },

    fireDeviceNotRegistered: function() {
        this.fireEvent('devicenotregistered');
    },
    
    fireChangeWebCentralUrl: function() {
        this.fireEvent('changeurl');
    },

    fireRegistratoinViewClosed: function() {
        this.fireEvent('registrationviewclose');
    }
});