var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.es = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Acepte la solicitud del explorador para almacenar datos en su equipo local y actualizar la página."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Error al cargar el archivo de configuración."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "El controlador '{0}' carece de método de inicio.¿Seguro que se extiende de Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Este valor tiene un formato incorrecto:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Este valor no es un correo electrónico válido:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Este no es un valor aceptable:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Este valor no se incluye en la lista de valores aceptables:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Este valor tiene una longitud incorrecta:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Este valor debe estar presente:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Adjuntar"},
        {key1: "Common.control.Camera", key2: "Close", value: "Cerrar"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Borrar"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Listo"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Cargando..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Corrija lo siguiente:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Error al examinar"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Listo"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "No hay datos que mostrar para: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Aplicar"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "No hay {0} que mostrar"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Solicitar"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Horas"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minutos"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Cargando elemento {0} de {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Edificios"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Edificios"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Código de contacto"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Nombre"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Apellido"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nombre:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contacto"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Código de contacto"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Código de departamento"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Departamento:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Departamentos"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Código de división"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "División:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "División"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Código de división"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "División:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisiones"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "Correo electrónico"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "Correo electrónico:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Empleado"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Código de empleado"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Estándar de empleado"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Equipos"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Código de equipo"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Estándares de equipo"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Equipo:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Estándares de equipo"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Estándares de equipo"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Edificio:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Planta"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Código de planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Código de planta"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Planta:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Plantas"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Tipo de problema"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Propiedad"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Código de propiedad"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Propiedad:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Edificio/Planta:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Código de espacio"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Espacio:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Espacios"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categoría:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Categorías de espacio"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Categoría del espacio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Código de edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Planta"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Código de planta"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Código de planta"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Planta:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Espacio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Código de espacio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Espacio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Espacio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Espacios"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Estándar de espacio"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Estándar:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Estándares"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categoría:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Descripción"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Descripción:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Categoría del espacio"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Tipo de espacio"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Tipos de espacio"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Tipo:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Código:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Sede"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Código de sede"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Sede:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sedes"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "No hay guardadas búsquedas anteriores."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Borrar"},
        {key1: "Common.control.Signature", key2: "Done", value: "Listo"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Firma"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Debe facilitarse una configuración de referencia mainView al ampliar la clase Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Guardar"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "¿Desea continuar?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Se ha producido un error al dar de baja el dispositivo. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Al cerrar sesión, no se eliminan los datos de la aplicación.<br>Tendrá que volver a registrar el dispositivo para acceder a las aplicaciones."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registro"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Fallo de registro"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "No está disponible el servicio de registro del dispositivo. Puede que los servicios Mobile no estén habilitados en Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "El modelo con el nombre [{0}] no existe."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "No está disponible el escaneado de códigos de barra"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Permiso denegado para acceder a información sobre ubicación"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La posición no está disponible"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Tiempo de espera de posición agotado"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Error de posición desconocido"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Se produjo un error al mostrar el documento"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Visualización de documentos"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Descargando documento"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Función no disponible en el entorno del escritorio."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "El archivo no existe"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "El archivo {0} no puede mostrarse en este dispositivo."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "El archivo {0} no puede mostrarse en modo Escritorio."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Quitando documento"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Campo cambiado: {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Entrada"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "La entrada para el campo {0} está limitada a {1} caracteres"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Cancelar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Borrar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copiar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Listo"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Error"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "No"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Pegar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Volver a cargar"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nombre de espacio"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Nombres de espacios"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Guardar imagen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Inspección física"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Sí"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Cargar más..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "No hay más registros"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Cargar más..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "No hay más registros"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Esta aplicación se acaba de actualizar correctamente a su última versión. Recargando la aplicación."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Error al cargar servicios de red. Puede que la conexión de red no esté disponible o sea lenta"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "La conexión de red no está disponible"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "No se han recibido datos del servidor"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Tiempo de espera agotado"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Error desconocido"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Error al registrar dispositivo"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Error al recuperar información de usuario."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Error al establecer valor local de sesión."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Error al iniciar sesión de usuario."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Error de inicio de sesión única"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Error al recuperar TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Dispositivo no registrado."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flujo de trabajo toJSON. No está permitido organizar objetos de fecha usando reglas de flujo de trabajo."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Ejecutada regla de flujo de trabajo"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Fallo de regla de flujo de trabajo:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Preferencias de aplicación"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Edificios"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Tipos de causa"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contactos"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Operarios"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Departamentos"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisiones"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Empleados"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Estándares de empleado"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Equipos"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Estándares de equipo"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Plantas"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Zonas lesionadas"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Categorías de lesiones"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Tipos de incidentes"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Grupos de tipo de plano"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Tipos de plano"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Tipos de problema"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Proyectos"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Propiedades"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Error de base de datos:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "No se ha aplicado ningún cambio en la tabla de la base de datos. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "No se ha actualizado ningún valor predeterminado para el campo: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Actualizar valor predeterminado: campo [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Error de proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Error de proxy Sqlite durante operación de creación"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Error de proxy Sqlite durante operación de destrucción"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Error de proxy Sqlite durante operación de lectura"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Error de proxy Sqlite durante operación de actualización"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Error al abrir base de datos: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Error de base de datos [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Error de base de datos en proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView es de sólo lectura y no admite la eliminación de registros"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView es de sólo lectura y no admite la actualización de registros"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView es de sólo lectura y no admite la creación registros"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "La base de datos no contiene las definiciones de tabla requeridas para la vista {0} de Sqlite"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Tipos de reparación"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Categorías de espacio"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Espacios"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Estándares de espacio"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Tipos de espacio"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Usos del espacio"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sedes"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "archivo_no_disponible"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Sincronizando"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Descargando"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Error"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "El valor de entrada no puede convertirse a un tipo Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "No se han cargado las preferencias de la aplicación"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Ejecutando en modo de navegador. Acceso a sistema de archivos deshabilitado"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Ejecutando en Chrome o en WebView. Acceso a sistema de archivos habilitado"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Se ha abortado el acceso al campo"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "El archivo ya existe"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Error de codificación del archivo"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Error de archivo"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "El archivo presenta un estado no válido"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "No se permite la modificación del archivo"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Cuota de archivos superada"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Error de seguridad del archivo"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Error de falta de coincidencia del tipo de archivo"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "No se ha encontrado el archivo"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "No se pudo leer el archivo"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Error al modificar archivo no válido"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "La conexión de red no está disponible"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Red inaccesible"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Descargando datos de base"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Error"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "No se ha cargado el almacén de preferencias de la aplicación. No se pueden recuperar las preferencias"},
        {key1: "Common.util.Units", key2: "ft", value: "pies"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pies cuad."},
        {key1: "Common.util.Units", key2: "sq m", value: "m cuad."},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "La información del perfil de usuario no está disponible. Sincronice para recuperar los datos del perfil de usuario."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Eliminar al sincronizar"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Visualizar"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documentos"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "No hay documentos disponibles"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} de {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 de x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "El nombre de la clase de modelo asociado a esta vista debe facilitarse en la propiedad del modelo"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "El ID de almacén de la clase de almacén asociado a esta vista debe facilitarse en la propiedad de ID de almacén"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Borrar"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtro"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Atrás"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Guardar"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Campo"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identificador"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Tamaño (bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Mensajes de sincronización"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabla"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Los siguientes valores de campo de Web Central no se escribieron en la base de datos cliente porque el tamaño de los datos sobrepasaba el límite de la base de datos"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Establecer filtro"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Assign the work request to you?", value: "¿Asignarle la solicitud de trabajo a usted?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Cancel", value: "Cancelar"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Estimation", value: "Terminar estimación"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Scheduling", value: "Terminar programación"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete", value: "Eliminar"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete the craftsperson?", value: "¿Eliminar el operario?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate", value: "Estimar"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate requests to more accurately budget, to schedule labor, and to reserve parts. You can change your estimates until you issue the request.<br/><br/>Complete the estimation of the work request?", value: "Estime solicitudes para presupuestar, programar tareas y reservar piezas con mayor precisión. Puede cambiar sus estimaciones hasta que emita la solicitud.<br/><br/>¿Completar la estimación de la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Forward", value: "Remitir"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Map functionility can not run on Phone.", value: "La funcionalidad del mapa no puede ejecutarse en el teléfono."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Pending workflow step", value: "Paso pendiente de flujo de trabajo"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please add your comments before rejecting the work request", value: "Añada sus comentarios antes de rechazar la solicitud de trabajo."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please complete the pending workflow step", value: "Complete el paso pendiente del flujo de trabajo"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Reject", value: "Rechazar"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Resume the work request to Issued?", value: "¿Reanudar la solicitud de trabajo como emitida?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Return", value: "Volver"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Schedule requests to better plan and balance work for teams and craftspersons. You can change the schedule assignments until you issue the request.<br/><br/>Complete the scheduling of the work request?", value: "Programe solicitudes para planificar mejor el trabajo y repartirlo equitativamente entre equipos y operarios. Puede cambiar las asignaciones de su programa hasta que emita la solicitud.<br/><br/>¿Completar la programación de la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Self Assign", value: "Autoasignar"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Supervisor or Work Team Id must be completed before forwarding the request", value: "Debe rellenarse el ID del equipo de trabajo o supervisor antes de remitirse la solicitud"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The request will be automatically be sent back one step", value: "La solicitud retrocederá automáticamente un paso"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The work request is already assigned to you", value: "Ya tiene asignada la solicitud de trabajo"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "There is another existing record with the same primary keys.", value: "Hay otro registro existente con las mismas claves principales."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action archives the request and prevents any further updates to it.<br/><br/>Close the work request?", value: "Esta acción archivará la solicitud y ya no se podrá actualizar más.<br/><br/>¿Cerrar la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Esta acción cancela una solicitud antes de que haya dado comienzo el trabajo. Al cancelar una solicitud, finaliza el flujo de trabajo de esta.<br/><br/>¿Cancelar la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action issues the request to field personnel. Once you issue the request, it cannot be cancelled; it can be completed, put on hold, or stopped.<br/><br/>Issue the work request?", value: "Esta acción emite la solicitud al personal de campo. Una vez que emita la solicitud, no podrá cancelarla; sólo puede completarse, ponerse en espera o detenerse.<br/><br/>¿Emitir la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action marks the request as Completed. A Supervisor can update labor, parts, comments, and other work details until the request is Closed.<br/><br/>Complete the work request?", value: "Esta acción marca la solicitud como Completada. Un supervisor puede actualizar tareas, piezas, comentarios y otros detalles del trabajo hasta que se cierre la solicitud.<br/><br/>¿Completar la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action puts a request on hold while waiting for parts, the appropriate trade, or security access. You can stop or complete a request that is on hold.<br/><br/>Put on hold the work request?", value: "Esta acción pone una solicitud en espera mientras aguarda piezas, el oficio adecuado o acceso de seguridad. Se puede detener o completar una solicitud que está a la espera.<br/><br/>¿Poner en espera la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action stops a request on which some work has already been performed and which may be billed. Stopping a request ends the request workflow.<br/><br/>Stop the work request?", value: "Esta acción detiene una solicitud por la que se haya realizado ya algún trabajo y que puede facturarse. Al detener una solicitud, finaliza el flujo de trabajo de esta.<br/><br/>¿Detener la solicitud de trabajo?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Two resource records of the same type can not be added for the same day.  Please edit the existing record to reflect the correct totals.", value: "No se pueden agregar dos registros de recursos del mismo tipo para el mismo día.  Edite el registro existente para reflejar los totales correctos."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work Request", value: "Solicitud de trabajo"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work request assigned", value: "Solicitud de trabajo asignada"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You cannot select both Supervisor and Work Team Id before forwarding the request", value: "No se puede seleccionar un ID de equipo de trabajo y supervisor antes de remitir la solicitud"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You have changed the work request. Please sync before taking any further actions on it", value: "Ha cambiado la solicitud de trabajo. Sincronice antes de realizar más acciones con ella"},
        {key1: "Maintenance.controller.manager.WorkRequestActionsMultiple", key2: "Please input the comments first", value: "Escriba primero los comentarios"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work requests assigned", value: "Solicitudes de trabajo asignadas"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Other Cost", value: "Agregar otro coste"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Part", value: "Agregar pieza"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Trade", value: "Agregar oficio"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Other Cost", value: "Editar otro coste"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Part", value: "Editar pieza"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Trade", value: "Editar oficio"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "Todos los campos de los documentos de solicitud de trabajo están en uso.<br>No puede adjuntarse la foto a la solicitud de trabajo"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "Documents", value: "Documentos"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "This action will remove the document. Do you want to proceed?", value: "Esta acción quitará el documento. ¿Desea continuar?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Cancel", value: "Cancelar"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Complete", value: "Completar"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Craftsperson Labor", value: "Tarea de operario"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "One or more craftsperson entries are missing labor hours<br>Do you want to Complete the Work Request?", value: "A uno o varios operarios les faltan horas de trabajo<br>¿Desea completar la solicitud de trabajo?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Please input the comments first", value: "Escriba primero los comentarios"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Status", value: "Estado"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "The Work Request status is Completed.<br>The status cannot be modified.", value: "El estado de la Solicitud de trabajo es Completado.<br>El estado no puede modificarse."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Esta acción cancela una solicitud antes de que haya dado comienzo el trabajo. Al cancelar una solicitud, finaliza el flujo de trabajo de esta.<br/><br/>¿Cancelar la solicitud de trabajo?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action marks your assignment as Completed. Supervisors can update labor, parts, comments, and other work details until the request is Closed.<br>Complete your assignment?", value: "Esta acción marca su asignación como Completada. Los supervisores pueden actualizar tareas, piezas, comentarios y otros detalles del trabajo hasta que se cierre la solicitud.<br>¿Completar su asignación?"},
        {key1: "Maintenance.controller.FloorPlan", key2: "Locate Room", value: "Localizar espacio"},
        {key1: "Maintenance.controller.FloorPlan", key2: "The work request is not assigned to a room and therefore cannot be located.", value: "La solicitud de trabajo no está asignada a un espacio y, por tanto, no puede localizarse."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Craftsperson is required.", value: "Se necesita un operario."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Floor Plans", value: "Planos de planta"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "User Account", value: "Cuenta de usuario"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Validation", value: "Validación"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Your account does not have Craftsperson access. Submit Work Requests using the My Request tab.", value: "Su cuenta no tiene acceso de operario. Use la ficha Mi solicitud para enviar solicitudes de trabajo."},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Info", value: "Info"},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Updating Work Requests", value: "Actualizando solicitudes de trabajo"},
        {key1: "Maintenance.model.manager.WorkRequestTool", key2: " {0} and {1} must be before {2} and {3}", value: "{0} y {1} deben ir antes que {2} y {3}"},
        {key1: "Maintenance.model.PartStorageLocation", key2: "must be greater than 0.", value: "debe ser mayor que 0."},
        {key1: "Maintenance.model.WorkRequest", key2: " {0} is required", value: "Se requiere {0}"},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be greater than or equal to 0.", value: "debe ser superior o igual a 0."},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be less than or equal to 100,000,000.", value: "debe ser inferior o igual a 100.000.000."},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0} and {1} must be before {2} and {3}", value: "{0} y {1} deben ir antes que {2} y {3}"},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0}, {1}, or {2} are required", value: "{0}, {1} o {2} son obligatorios"},
        {key1: "Maintenance.store.Accounts", key2: "Accounts", value: "Cuentas"},
        {key1: "Maintenance.store.Buildings", key2: "Buildings", value: "Edificios"},
        {key1: "Maintenance.store.manager.Craftspersons", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.store.manager.CraftspersonWorkTeams", key2: "Craftsperson Work Teams", value: "Equipos de trabajo de operario"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Approved", value: "Aprobado"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Completed", value: "Terminado"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Issued", value: "Emitido"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Requests", value: "Mis solicitudes"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Work", value: "Mi trabajo"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Requested", value: "Solicitado"},
        {key1: "Maintenance.store.manager.PartStorageLocations", key2: "Part Storage Locations", value: "Lugares de almacenamiento de piezas"},
        {key1: "Maintenance.store.manager.StorageLocations", key2: "Storage Locations", value: "Lugares de almacenamiento"},
        {key1: "Maintenance.store.manager.Tools", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.store.manager.Trades", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve", value: "Aprobar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Estimate", value: "Aprobar estimación"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Schedule", value: "Aprobar programa"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Cancel", value: "Cancelar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Close", value: "Cerrar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Complete", value: "Completar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Estimate", value: "Estimar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Forward", value: "Remitir"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Access", value: "Esperar acceso"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Labor", value: "Esperar recursos humanos"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Parts", value: "Esperar piezas"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Issue", value: "Emitir"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Link New", value: "Vincular nuevo"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Resume To Issued", value: "Reanudar como emitida"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Return", value: "Volver"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Schedule", value: "Programar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Self Assign", value: "Autoasignar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Stop", value: "Detener"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Update", value: "Actualizar"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Verify", value: "Verificar"},
        {key1: "Maintenance.store.manager.WorkRequestReferences", key2: "References", value: "Referencias"},
        {key1: "Maintenance.store.manager.WorkRequestTools", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.store.manager.WorkRequestTrades", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.store.OtherResources", key2: "Resources", value: "Recursos"},
        {key1: "Maintenance.store.PmProcedures", key2: "PM Procedures", value: "Procedimientos MP"},
        {key1: "Maintenance.store.ProblemDescriptions", key2: "Problem Descriptions", value: "Descripciones de problemas"},
        {key1: "Maintenance.store.ProblemResolutions", key2: "Problem Resolutions", value: "Soluciones de problemas"},
        {key1: "Maintenance.store.WorkRequestCosts", key2: "Costs", value: "Costes"},
        {key1: "Maintenance.store.WorkRequestCraftspersons", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.store.WorkRequestParts", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.store.WorkRequests", key2: "Due Today", value: "Vence hoy"},
        {key1: "Maintenance.store.WorkRequests", key2: "On Hold", value: "En espera"},
        {key1: "Maintenance.store.WorkRequests", key2: "Other", value: "Otro"},
        {key1: "Maintenance.store.WorkRequests", key2: "Overdue", value: "Retrasado"},
        {key1: "Maintenance.store.WorkRequests", key2: "Pending", value: "Pendiente"},
        {key1: "Maintenance.store.WorkRequests", key2: "Work Request", value: "Solicitud de trabajo"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Approved", value: "Aprobado"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Completed", value: "Terminado"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Issued", value: "Emitido"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Requests", value: "Mis solicitudes"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Work", value: "Mi trabajo"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Requested", value: "Solicitado"},
        {key1: "Maintenance.view.FloorPlan", key2: "Floor Plans", value: "Planos de planta"},
        {key1: "Maintenance.view.FloorPlan", key2: "Site", value: "Sede"},
        {key1: "Maintenance.view.Main", key2: "Add Purchased Parts", value: "Agregar piezas compradas"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code", value: "Código de edificio"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code:", value: "Edificio:"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Code", value: "Código de pieza"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Storage Locations", value: "Lugares de almacenamiento de piezas"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Quantity Available", value: "Cantidad disponible"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Code", value: "Código de lugar de almacenamiento"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Name", value: "Nombre de lugar de almacenamiento"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Work Request Code", value: "Número de solicitud de trabajo"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account", value: "Cuenta"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account Code", value: "Código de cuenta"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Add Purchased Parts to Inventory", value: "Agregar piezas compradas a inventario"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part", value: "Pieza"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part Code", value: "Código de pieza"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Price", value: "Precio"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Quantity (each)", value: "Cantidad (cada uno)"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location", value: "Lugar de almacenamiento"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location Code", value: "Código de lugar de almacenamiento"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve", value: "Aprobar"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Request", value: "Aprobar solicitud"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Cancel", value: "Cancelar"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Documents", value: "Documentos"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "References", value: "Referencias"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Reject", value: "Rechazar"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Approve", value: "Aprobar"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Reject", value: "Rechazar"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Requests", value: "Aprobar solicitudes"},
        {key1: "Maintenance.view.manager.EstimateApproveForm", key2: "Approve Request Estimation", value: "Aprobar estimación de solicitud"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Costs", value: "Costes"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Documents", value: "Documentos"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "References", value: "Referencias"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Complete Estimation", value: "Terminar estimación"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Estimate", value: "Estimar"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Actual Cost", value: "Coste real"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Add Other Cost", value: "Agregar otro coste"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Labor", value: "Coste de recursos humanos"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Parts", value: "Coste de piezas"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Estimated Cost", value: "Coste estimado"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Costs", value: "Otros costes"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Description", value: "Descripción de otros recursos"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Type", value: "Tipo de otros recursos"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Quantity Used", value: "Cantidad utilizada"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Actual Costs", value: "Resumen de costes reales"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Estimated Costs", value: "Resumen de costes estimados"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Total Cost", value: "Coste total"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Units", value: "Unidades"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Complete Estimation", value: "Terminar estimación"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Costs", value: "Costes"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Estimate", value: "Estimar"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Requests to Estimate", value: "Solicitudes para estimación"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Part", value: "Agregar pieza"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Purchased Parts", value: "Agregar piezas compradas"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Building Code", value: "Código de edificio"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part", value: "Pieza"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part Code", value: "Código de pieza"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Available", value: "Cantidad disponible"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Estimated", value: "Cantidad estimada"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Used", value: "Cantidad utilizada"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Code", value: "Código de lugar de almacenamiento"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Name", value: "Nombre de lugar de almacenamiento"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Email", value: "Correo electrónico"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Employee Code", value: "Código de empleado"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Forward", value: "Remitir"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Supervisor", value: "Supervisor"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Work Team Code", value: "Código de equipo de trabajo"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Forward", value: "Remitir"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Requests to Forward", value: "Solicitudes para remitir"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Supervisor", value: "Supervisor"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Work Team Code", value: "Código de equipo de trabajo"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Completer", value: "Completado por"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Estimator", value: "Tasador"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Issuer", value: "Emisor"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject", value: "Rechazar"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject Request", value: "Rechazar solicitud"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Requestor", value: "Solicitante"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Scheduler", value: "Programador"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Approver's Comments", value: "Comentarios de aprobador"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Building", value: "Edificio"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Craftsperson Notes", value: "Notas del obrero"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Date Requested", value: "Fecha de solicitud"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Equipment Code", value: "Código de equipo"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Floor", value: "Planta"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Priority", value: "Prioridad"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Location", value: "Ubicación del problema"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Type", value: "Tipo de problema"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Related Requests", value: "Solicitudes relacionadas"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Requestor", value: "Solicitante"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Room", value: "Espacio"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Status", value: "Estado"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return", value: "Volver"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return Work Request", value: "Devolver solicitud de trabajo"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Requests to Forward", value: "Solicitudes para remitir"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return", value: "Volver"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return Work Request", value: "Devolver solicitud de trabajo"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Approved", value: "Aprobado"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "by", value: "por"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Completed", value: "Terminado"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Access", value: "Esperar acceso"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Labor", value: "Esperar recursos humanos"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Parts", value: "Esperar piezas"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Issued", value: "Emitido"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Rejected", value: "Rechazado"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Requested", value: "Solicitado"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return", value: "Volver"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return Work Request", value: "Devolver solicitud de trabajo"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.manager.ScheduleApproveForm", key2: "Approve Request Schedule", value: "Aprobar programa de solicitud"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Add Trade", value: "Agregar oficio"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Estimated Hours", value: "Horas estimadas"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Hours", value: "Horas"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade", value: "Oficio"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Code", value: "Código de oficio"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Description", value: "Descripción de oficio"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Complete Scheduling", value: "Terminar programación"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Documents", value: "Documentos"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Forward", value: "Remitir"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "References", value: "Referencias"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Schedule", value: "Programar"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Actual Hours", value: "Horas reales"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Assign Craftsperson", value: "Asignar operario"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Copy", value: "Copiar"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson", value: "Operario"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson Code", value: "Código de operario"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Finished", value: "Fecha de terminación"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Scheduled", value: "Fecha programada"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Started", value: "Fecha de inicio"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Doubletime Hours", value: "Horas de tarifa horaria de 200%"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Overtime Hours", value: "Horas de tarifa horaria de 150%"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Primary Trade", value: "Oficio principal"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Scheduled Hours", value: "Horas programadas"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Start", value: "Fecha de inicio"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Status", value: "Estado"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Stop", value: "Detener"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Finished", value: "Hora de terminación"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Scheduled", value: "Hora programada"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Started", value: "Hora de inicio"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Work Type", value: "Tipo de trabajo"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Complete Scheduling", value: "Terminar programación"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Forward", value: "Remitir"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Requests to Schedule", value: "Solicitudes para programar"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Schedule", value: "Programar"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Trades", value: "Oficios"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Straight Time Hours Used", value: "Horas tarifa 100% utilizadas"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Assign Tool", value: "Asignar herramienta"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Building Code", value: "Código de edificio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Finished", value: "Fecha de terminación"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Scheduled", value: "Fecha programada"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Started", value: "Fecha de inicio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Hours", value: "Horas"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Scheduled Hours", value: "Horas programadas"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Start", value: "Fecha de inicio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Stop", value: "Detener"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Finished", value: "Hora de terminación"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Scheduled", value: "Hora programada"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Started", value: "Hora de inicio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool", value: "Herramienta"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Code", value: "Código de herramienta"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Type", value: "Tipo de herramienta"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Complete", value: "Completar"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Mark only my assignment as Completed.", value: "Marcar solo mi asignación como Completada."},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Return Work Request", value: "Devolver solicitud de trabajo"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Set all craftsperson assignments as Completed", value: "Establecer como completadas todas las asignaciones de operarios"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Costs", value: "Costes"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Documents", value: "Documentos"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "References", value: "Referencias"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Update", value: "Actualizar"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Work Request Details", value: "Detalles de solicitud de trabajo"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Costs", value: "Costes"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Update", value: "Solicitudes para actualizar"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Update", value: "Actualizar"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Confirm", value: "Confirmar"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Return Incomplete", value: "Devolución incompleta"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Verify", value: "Verificar"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Verify", value: "Solicitudes por verificar"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Confirm", value: "Confirmar"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Return Incomplete", value: "Devolución incompleta"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Verify", value: "Verificar"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Nearing Escalation", value: "10 cerca de escalado"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Newest Requests", value: "10 solicitudes más recientes"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Oldest Requests", value: "10 solicitudes más antiguas"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "All", value: "Todo"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Any", value: "Cualquiera"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Both", value: "Ambos"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftsperson", value: "Operario"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested From", value: "Fecha de solicitud desde"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested To", value: "Fecha de solicitud hasta"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform From", value: "Fecha para ejecución desde"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform To", value: "Fecha para ejecución hasta"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Equipment", value: "Equipos"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated", value: "Escalado"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated ?", value: "¿Escalado?"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Approved Requests", value: "Mis solicitudes aprobadas"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Requests", value: "Mis solicitudes"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "On Demand", value: "En demanda"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Part", value: "Pieza"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "PM", value: "MP"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Priority", value: "Prioridad"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Problem Type", value: "Tipo de problema"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requestor", value: "Solicitante"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requests Requiring my Approval", value: "Solicitudes que requieren mi aprobación"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Set Filter", value: "Establecer filtro"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Show", value: "Mostrar"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Unassigned Requests", value: "Solicitudes sin asignar"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Request", value: "Solicitud de trabajo"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Requests", value: "Solicitudes de trabajo"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Type", value: "Tipo de trabajo"},
        {key1: "Maintenance.view.manager.WorkRequestManagerList", key2: "REQUESTED", value: "Solicitado"},
        {key1: "Maintenance.view.manager.WorkRequestManagerListItem", key2: "Assigned To:", value: "Asignado a:"},
        {key1: "Maintenance.view.manager.WorkRequestSelection", key2: "Requests to Schedule", value: "Solicitudes para programar"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Hours", value: "Horas"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Job Setup or Prep.", value: "Configuración de trabajo o prep."},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Material Pickup", value: "Recogida de material"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Travel Time", value: "Tiempo de deplazamiento"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "UnSpecified", value: "Sin especificar"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Client", value: "Esperar cliente"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Security", value: "Esperar seguridad"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Work", value: "Trabajo"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "No Status Change", value: "No hubo cambio de estado"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Access", value: "En espera de acceso"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Labor", value: "En espera de recursos humanos"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold For Parts", value: "En espera de piezas"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "Resume To Issued", value: "Reanudar como emitida"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Actual Hours", value: "Horas reales"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Cancel", value: "Cancelar"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Doubletime Hours", value: "Horas de tarifa horaria de 200%"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Overtime Hours", value: "Horas de tarifa horaria de 150%"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Save", value: "Guardar"},
        {key1: "Maintenance.view.phone.Main", key2: "Apps", value: "Aplicaciones"},
        {key1: "Maintenance.view.phone.QuickComplete", key2: "Complete Request", value: "Terminar solicitud"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cancel", value: "Cancelar"},
        {key1: "Maintenance.view.SiteMap", key2: "Buildings", value: "Edificios"},
        {key1: "Maintenance.view.tablet.Main", key2: "Apps", value: "Aplicaciones"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Actual Cost", value: "Coste real"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Add Cost", value: "Agregar coste"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Date Used", value: "Fecha de uso"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Edit Cost", value: "Editar coste"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Quantity Used", value: "Cantidad utilizada"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Resource Type", value: "Tipo de recurso"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Units", value: "Unidades"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Cost:", value: "Coste:"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Other Costs", value: "Otros costes"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Actual Hours", value: "Horas reales"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Add Craftsperson", value: "Agregar operario"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Craftsperson", value: "Operario"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Finished", value: "Fecha de terminación"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Started", value: "Fecha de inicio"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Doubletime Hours", value: "Horas de tarifa horaria de 200%"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Edit Craftsperson", value: "Editar operario"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Overtime Hours", value: "Horas de tarifa horaria de 150%"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Start", value: "Fecha de inicio"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Status", value: "Estado"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Stop", value: "Detener"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Finished", value: "Hora de terminación"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Started", value: "Hora de inicio"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Work Type", value: "Tipo de trabajo"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Hours", value: "Horas"},
        {key1: "Maintenance.view.manager.WorkRequestEdit", key2: "References", value: "Referencias"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Assigned Date", value: "Fecha de asignación"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cause Type", value: "Tipo de causa"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Code", value: "Código"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Costs", value: "Costes"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftsperson Notes", value: "Notas del obrero"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftspersons", value: "Operarios"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Related Work Request", value: "Crear solicitud de trabajo relacionada"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Work Request", value: "Crear solicitud de trabajo"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Description", value: "Descripción"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Documents", value: "Documentos"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 1", value: "Foto 1"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 2", value: "Foto 2"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 3", value: "Foto 3"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 4", value: "Foto 4"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "PM Procedure", value: "Procedimiento MP"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Description", value: "Descripción del problema"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Location", value: "Ubicación del problema"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Type", value: "Tipo de problema"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Repair Type", value: "Tipo de reparación"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested", value: "Solicitado"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested By", value: "Solicitado por"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Scheduled Date", value: "fecha programada"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Status", value: "Estado"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Tools", value: "Herramientas"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Update", value: "Actualizar"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Work Request Details", value: "Detalles de solicitud de trabajo"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Escalation", value: "Escalado"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Loading...", value: "Cargando..."},
        {key1: "Maintenance.view.WorkRequestList", key2: "Location", value: "Ubicación"},
        {key1: "Maintenance.view.WorkRequestList", key2: "My Work", value: "Mi trabajo"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Problem Type", value: "Tipo de problema"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search", value: "Buscar"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search Work Requests", value: "Buscar solicitudes de trabajo"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Status", value: "Estado"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Add Part", value: "Agregar pieza"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Assigned", value: "Asignado"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Comments", value: "Comentarios"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Edit Part", value: "Editar pieza"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Part", value: "Pieza"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Quantity", value: "Cantidad"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Parts", value: "Piezas"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Quantity", value: "Cantidad"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "OpenURL", value: "Abrir URL"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "URL does not exsits", value: "No existe la URL"},
        {key1: "Maintenance.view.WorkRequestReferencesLists", key2: "References", value: "Referencias"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "¿Está seguro de que desea eliminar este objeto?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Introduzca el contenido del cuadro de texto:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Plano de planta no disponible"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Copiar"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Pegar"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Volver a cargar"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Guardar imagen"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "¿Seguro que desea eliminar este elemento?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Editar"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "No hay ningún plano de planta disponible para la línea roja"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Publicar fechas"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Mapas de sede"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Plano de planta"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Línea roja"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Códigos de edificio"},
    ]
};
