var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.it = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Accettare la richiesta del browser di memorizzare i dati sul computer locale e aggiornare la pagina."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Errore nel caricamento del file di configurazione."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Il controller '{0}' non dispone di un metodo di avvio. Estenderlo da Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Formato del valore non valido:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Il valore non è un indirizzo e-mail valido:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Il valore non è un valore accettabile:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Questo valore non è incluso nell’elenco di valori accettabili:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Lunghezza del valore non valida:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Questo valore deve essere presente:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Allega"},
        {key1: "Common.control.Camera", key2: "Close", value: "Chiudi"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Cancella"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Fine"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Caricamento in corso..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Correggere quanto segue:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Errore scansione"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Fine"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Nessun dato da visualizzare per: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Mostra"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Nessun {0} da visualizzare"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Richiesta"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Ore"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuti"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Caricamento elemento {0} di {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Edifici"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Edifici"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Codice contatto"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Nome"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Cognome"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nome:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contatto"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Codice contatto"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Codice reparto"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Codice reparto:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Reparti"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Codice divisione"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Codice divisione:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Divisione"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Codice divisione"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Divisione:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisioni"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Dipendente"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Codice dipendente"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standard dipendente"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Apparecchiatura"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Codice apparecchiatura"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standard apparecchiature"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Apparecchiatura:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standard apparecchiature"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standard apparecchiature"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Piano"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Codice piano:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Piano"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Codice piano:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Piano:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Piani"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annulla"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Tipo di problema"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Proprietà"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Codice proprietà"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Proprietà:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Edificio/piano:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Codice locale"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Codice locale:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Locali"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categoria:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Categorie di locale"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Categoria locale"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Codice edificio"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Edificio:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Piano"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Codice piano"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Codice piano:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Piano:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Locale"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Codice locale"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Codice locale:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Locale:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Locali"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standard di locale"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standard"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categoria:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Descrizione"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Descrizione:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Categoria locale"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Tipo di locale"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Tipi di locale"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Tipo:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Codice:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Sito"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Codice sito"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Sito:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Siti"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Non sono presenti ricerche precedenti salvate."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Cancella"},
        {key1: "Common.control.Signature", key2: "Done", value: "Fine"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Firma"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "È necessario fornire un parametro ref config mainView quando si amplia la classe Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annulla"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Salva"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Continuare?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Si è verificato un errore di annullamento della registrazione del dispositivo. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "La disconnessione non rimuove i dati dall’applicazione.<br>È necessario registrare nuovamente il dispositivo per accedere alle app."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registrazione"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registrazione non riuscita"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Servizio di registrazione dispositivi non disponibile. I servizi mobili potrebbero non essere abilitati in Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Modello con nome [{0}] inesistente."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Lettura codici a barre non disponibile"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Autorizzazione di accesso alle informazioni della posizione negata"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La posizione non è disponibile"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Timeout posizione"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Errore posizione sconosciuta"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Si è verificato un errore durante la visualizzazione del documento"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Visualizzazione documento"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Download del documento"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Funzione non disponibile in ambiente desktop."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Il file non esiste"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Impossibile visualizzare il file {0} su questo dispositivo."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Impossibile visualizzare il file {0} in modalità desktop."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Rimozione del documento"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Campo modificato: {0} nuovo valore: {1} vecchio valore: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Input"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Input per il campo {0} limitato a {1} caratteri"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annulla"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Cancella"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copia"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Fine"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Errore"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "No"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Incolla"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Ricarica"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nome del locale"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Nomi locali"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Salva immagine"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Rilievo"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Sì"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Carica altro..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Nessun altro record"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Carica altro..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Nessun altro record"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "L’applicazione è stata aggiornata all’ultima versione. Ricaricare l’applicazione."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Errore durante il caricamento dei servizi di rete. La connessione di rete potrebbe essere lenta o non disponibile"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Connessione di rete non disponibile"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Nessun dato ricevuto dal server"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Timeout"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Errore sconosciuto"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Errore durante la registrazione del dispositivo"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Errore nel recupero delle informazioni utente."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Errore nella definizione delle impostazioni internazionali della sessione."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Errore nell'avvio della sessione utente."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Errore di accesso singolo"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Errore durante il recupero di TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Dispositivo non registrato."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flusso di lavoro toJSON. Non è consentito effettuare il marshalling degli oggetti data mediante le regole del flusso di lavoro."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Regola flusso di lavoro eseguita"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Regola del flusso di lavoro non riuscita:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Preferenze app"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Edifici"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Tipi causa"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contatti"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Reparti"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisioni"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Dipendenti"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standard dipendenti"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Apparecchiatura"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standard apparecchiature"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Piani"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Area infortunata"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Categorie infortuni"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Tipologie incidente"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Gruppi tipo di piano"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Tipi di piani"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Tipi di problema"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Progetti"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Proprietà"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Errore database:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Nessuna modifica tabella di database applicata. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Nessun aggiornamento di valore predefinito per il campo: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Aggiorna valore predefinito: campo [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Errore proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Errore proxy Sqlite durante la creazione dell’operazione"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Errore proxy Sqlite durante l’eliminazione dell’operazione"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Errore proxy Sqlite durante la lettura dell’operazione"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Errore proxy Sqlite durante l’aggiornamento dell’operazione"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Errore durante l’apertura del database: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Errore database [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Errore database in proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView è di sola lettura e non supporta l'eliminazione dei record"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView è di sola lettura e non supporta l'aggiornamento dei record"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqlliteView è di sola lettura e non supporta la creazione dei record"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "Il database non contiene le definizioni della tabella richieste per la vista Sqlite {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Tipi di riparazione"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Categorie di locale"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Locali"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standard locali"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Tipi di locale"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Utilizzo locali"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Siti"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "file_non_disponibile"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Sincronizzazione"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Download in corso"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Errore"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "Il valore di input non può essere convertito in uno di tipo Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Le preferenze applicazione non sono state caricate"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Esecuzione in modalità browser. Accesso al file system disattivato"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Esecuzione in Chrome o in WebView. Accesso al file system attivato"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Accesso al file interrotto"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "File esistente"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Errore codifica file"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Errore file"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Stato del file non valido"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Modifica del file non consentita"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Quota file superata"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Errore sicurezza file"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Errore corrispondenza tipo di file"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "File non trovato"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "File non leggibile"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Errore modifica file non valida"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Connessione di rete non disponibile"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Rete non raggiungibile"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Download dei dati background"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Errore"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "L'archivio Preferenze app non è caricato. Impossibile recuperare le preferenze"},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "m"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pd2"},
        {key1: "Common.util.Units", key2: "sq m", value: "m2"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Le informazioni sul profilo utente non sono disponibili. Eseguire la sincronizzazione per recuperare i dati del profilo utente."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Elimina alla sincronizzazione"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Visualizza"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documenti"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Nessun documento disponibile."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} di {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 di x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Il nome della classe Modello associata a questa visualizzazione deve essere indicato nella proprietà del modello"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "L'ID archivio della classe Archivio associata a questa visualizzazione deve essere indicato nella proprietà storeId"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Cancella"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtro"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Indietro"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Salva"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Campo"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identificatore"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Dimensioni (byte)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Messaggi sincronizzazione"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabella"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "I seguenti valori di campo di Web Central non sono stati scritti nel database del client, poiché le dimensioni dei dati superavano il limite del database"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Imposta filtro"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Assign the work request to you?", value: "Autoassegnarsi la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Cancel", value: "Annulla"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Estimation", value: "Completa stima"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Scheduling", value: "Completa programmazione"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete", value: "Elimina"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete the craftsperson?", value: "Eliminare l’addetto?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate", value: "Stima"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate requests to more accurately budget, to schedule labor, and to reserve parts. You can change your estimates until you issue the request.<br/><br/>Complete the estimation of the work request?", value: "Effettuare una stima delle richieste per ottenere un budget più preciso, per programmare il lavoro e per prenotare parti. È possibile modificare le stime finché la richiesta non viene emessa.<br/><br/>Completare la stima della richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Forward", value: "Inoltra"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Map functionility can not run on Phone.", value: "La funzionalità della mappa non può essere eseguita sul telefono."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Pending workflow step", value: "Fase flusso di lavoro in sospeso"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please add your comments before rejecting the work request", value: "Aggiungere i commenti prima di rifiutare la richiesta di lavoro"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please complete the pending workflow step", value: "Completare la fase del flusso di lavoro in sospeso"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Reject", value: "Rifiuta"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Resume the work request to Issued?", value: "Ripristinare la richiesta di lavoro sullo stato emesso?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Return", value: "Ritorna"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Schedule requests to better plan and balance work for teams and craftspersons. You can change the schedule assignments until you issue the request.<br/><br/>Complete the scheduling of the work request?", value: "Programmare le richieste per pianificare e bilanciare meglio il lavoro per team e addetti. È possibile modificare le assegnazioni della pianificazione finché la richiesta non viene emessa.<br/><br/>Completare la pianificazione della richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Self Assign", value: "Autoassegnazione"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Supervisor or Work Team Id must be completed before forwarding the request", value: "È necessario specificare l’ID del supervisore o del team di lavoro prima di inoltrare la richiesta"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The request will be automatically be sent back one step", value: "La richiesta verrà automaticamente arretrata di un passaggio"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The work request is already assigned to you", value: "La richiesta di lavoro è già assegnata all’utente"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "There is another existing record with the same primary keys.", value: "È presente un altro record esistente con le stesse chiavi primarie."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action archives the request and prevents any further updates to it.<br/><br/>Close the work request?", value: "Questa azione archivia la richiesta e impedisce ulteriori eventuali aggiornamenti alla stessa<br/><br/>Chiudere la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "L’azione annulla una richiesta prima dell’inizio di qualsiasi lavoro. Annullando una richiesta, il flusso di lavoro della richiesta viene terminato.<br/><br/>Annullare la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action issues the request to field personnel. Once you issue the request, it cannot be cancelled; it can be completed, put on hold, or stopped.<br/><br/>Issue the work request?", value: "Questa azione invia la richiesta al personale sul campo. Una volta inviata, la richiesta non può essere annullata; può essere completata, messa in attesa o interrotta.<br/><br/>Emettere la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action marks the request as Completed. A Supervisor can update labor, parts, comments, and other work details until the request is Closed.<br/><br/>Complete the work request?", value: "L'azione contrassegna la richiesta come Completata. Un supervisore può aggiornare le informazioni su manodopera, parti, commenti e altri dettagli del lavoro finché la richiesta non viene chiusa.<br/><br/>Completare la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action puts a request on hold while waiting for parts, the appropriate trade, or security access. You can stop or complete a request that is on hold.<br/><br/>Put on hold the work request?", value: "L’azione mette in attesa una richiesta in attesa di parti, della richiesta di lavoro appropriata o dell’accesso di sicurezza. È possibile interrompere o completare una richiesta che è in attesa.<br/><br/>Mettere in attesa la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action stops a request on which some work has already been performed and which may be billed. Stopping a request ends the request workflow.<br/><br/>Stop the work request?", value: "Questa azione interrompe una richiesta per la quale è già stato eseguito del lavoro e che può essere fatturata. Interrompendo una richiesta, il flusso di lavoro della richiesta viene terminato.<br/><br/>Interrompere la richiesta di lavoro?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Two resource records of the same type can not be added for the same day.  Please edit the existing record to reflect the correct totals.", value: "Non è possibile aggiungere due record risorse dello stesso tipo per lo stesso giorno. Modificare il record esistente per rispecchiare i totali corretti."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work Request", value: "Richiesta di lavoro"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work request assigned", value: "Richiesta di lavoro assegnata"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You cannot select both Supervisor and Work Team Id before forwarding the request", value: "Impossibile selezionare l’ID supervisore e team di lavoro prima dell’invio della richiesta"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You have changed the work request. Please sync before taking any further actions on it", value: "La richiesta di lavoro è stata modificata. Effettuare la sincronizzazione prima di eseguire altre azioni sulla richiesta"},
        {key1: "Maintenance.controller.manager.WorkRequestActionsMultiple", key2: "Please input the comments first", value: "Immettere prima i commenti"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work requests assigned", value: "Richieste di lavoro assegnate"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Other Cost", value: "Aggiungi altro costo"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Part", value: "Aggiungi parte"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Trade", value: "Aggiungi fornitura"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Other Cost", value: "Modifica altro costo"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Part", value: "Modifica parte"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Trade", value: "Modifica settore"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "Tutti i campi del documento richiesta di lavoro sono in uso.<br>Impossibile allegare la foto alla richiesta di lavoro"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "Documents", value: "Documenti"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "This action will remove the document. Do you want to proceed?", value: "Questa azione elimina il documento. Procedere?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Cancel", value: "Annulla"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Complete", value: "Completato"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Craftsperson Labor", value: "Lavoro addetti"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "One or more craftsperson entries are missing labor hours<br>Do you want to Complete the Work Request?", value: "Per una o più voci addetto mancano le ore di lavoro<br>Completare la richiesta di lavoro?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Please input the comments first", value: "Immettere prima i commenti"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Status", value: "Stato"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "The Work Request status is Completed.<br>The status cannot be modified.", value: "Lo stato della richiesta di lavoro è Completo.<br>Impossibile modificare lo stato."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "L’azione annulla una richiesta prima dell’inizio di qualsiasi lavoro. Annullando una richiesta, il flusso di lavoro della richiesta viene terminato.<br/><br/>Annullare la richiesta di lavoro?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action marks your assignment as Completed. Supervisors can update labor, parts, comments, and other work details until the request is Closed.<br>Complete your assignment?", value: "L’azione contrassegna la richiesta come Completata. I supervisori possono aggiornare manodopera, parti, commenti e altri dettagli del lavoro finché la richiesta non viene chiusa.<br>Completare l’assegnazione?"},
        {key1: "Maintenance.controller.FloorPlan", key2: "Locate Room", value: "Individua locale"},
        {key1: "Maintenance.controller.FloorPlan", key2: "The work request is not assigned to a room and therefore cannot be located.", value: "La richiesta di lavoro non è assegnata a un locale e pertanto non è possibile trovarla."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Craftsperson is required.", value: "Addetto obbligatorio."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Floor Plans", value: "Planimetrie"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "User Account", value: "Account utente"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Validation", value: "Convalida"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Your account does not have Craftsperson access. Submit Work Requests using the My Request tab.", value: "L'account non dispone di accesso di tipo addetto. Inviare le richieste di lavoro mediante la scheda Richieste personali."},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Info", value: "Info"},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Updating Work Requests", value: "Aggiornamento richieste di lavoro"},
        {key1: "Maintenance.model.manager.WorkRequestTool", key2: " {0} and {1} must be before {2} and {3}", value: "{0} e {1} devono essere prima di {2} e {3}"},
        {key1: "Maintenance.model.PartStorageLocation", key2: "must be greater than 0.", value: "deve essere superiore a 0."},
        {key1: "Maintenance.model.WorkRequest", key2: " {0} is required", value: "{0} è richiesto"},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be greater than or equal to 0.", value: "deve essere superiore o uguale a 0."},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be less than or equal to 100,000,000.", value: "deve essere inferiore o uguale a 100.000.000."},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0} and {1} must be before {2} and {3}", value: "{0} e {1} devono essere prima di {2} e {3}"},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0}, {1}, or {2} are required", value: "{0}, {1} o {2} sono richiesti"},
        {key1: "Maintenance.store.Accounts", key2: "Accounts", value: "Commesse"},
        {key1: "Maintenance.store.Buildings", key2: "Buildings", value: "Edifici"},
        {key1: "Maintenance.store.manager.Craftspersons", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.store.manager.CraftspersonWorkTeams", key2: "Craftsperson Work Teams", value: "Team di lavoro addetti"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Approved", value: "Approvato"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Completed", value: "Completato"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Issued", value: "Emesso"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Requests", value: "Richieste personali"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Work", value: "Lavoro personale"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Requested", value: "Richiesto"},
        {key1: "Maintenance.store.manager.PartStorageLocations", key2: "Part Storage Locations", value: "Posizioni stoccaggio parti"},
        {key1: "Maintenance.store.manager.StorageLocations", key2: "Storage Locations", value: "Posizioni di stoccaggio"},
        {key1: "Maintenance.store.manager.Tools", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.store.manager.Trades", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve", value: "Approva"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Estimate", value: "Approva stima"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Schedule", value: "Approva pianificazione"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Cancel", value: "Annulla"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Close", value: "Chiudi"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Complete", value: "Completato"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Estimate", value: "Stima"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Forward", value: "Inoltra"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Access", value: "In sospeso per accesso"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Labor", value: "In sospeso per manodopera"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Parts", value: "In sospeso per parti"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Issue", value: "Emetti"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Link New", value: "Collega nuovo"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Resume To Issued", value: "Ripristina su emesso"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Return", value: "Ritorna"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Schedule", value: "Programma"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Self Assign", value: "Autoassegnazione"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Stop", value: "Interrompi"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Update", value: "Aggiorna"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Verify", value: "Verifica"},
        {key1: "Maintenance.store.manager.WorkRequestReferences", key2: "References", value: "Riferimenti"},
        {key1: "Maintenance.store.manager.WorkRequestTools", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.store.manager.WorkRequestTrades", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.store.OtherResources", key2: "Resources", value: "Risorse"},
        {key1: "Maintenance.store.PmProcedures", key2: "PM Procedures", value: "Procedure MP"},
        {key1: "Maintenance.store.ProblemDescriptions", key2: "Problem Descriptions", value: "Descrizioni dei problemi"},
        {key1: "Maintenance.store.ProblemResolutions", key2: "Problem Resolutions", value: "Risoluzioni dei problemi"},
        {key1: "Maintenance.store.WorkRequestCosts", key2: "Costs", value: "Costi"},
        {key1: "Maintenance.store.WorkRequestCraftspersons", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.store.WorkRequestParts", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.store.WorkRequests", key2: "Due Today", value: "Scadenza odierna"},
        {key1: "Maintenance.store.WorkRequests", key2: "On Hold", value: "In attesa"},
        {key1: "Maintenance.store.WorkRequests", key2: "Other", value: "Altro"},
        {key1: "Maintenance.store.WorkRequests", key2: "Overdue", value: "Scaduto"},
        {key1: "Maintenance.store.WorkRequests", key2: "Pending", value: "In sospeso"},
        {key1: "Maintenance.store.WorkRequests", key2: "Work Request", value: "Richiesta di lavoro"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Approved", value: "Approvato"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Completed", value: "Completato"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Issued", value: "Emesso"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Requests", value: "Richieste personali"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Work", value: "Lavoro personale"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Requested", value: "Richiesto"},
        {key1: "Maintenance.view.FloorPlan", key2: "Floor Plans", value: "Planimetrie"},
        {key1: "Maintenance.view.FloorPlan", key2: "Site", value: "Sito"},
        {key1: "Maintenance.view.Main", key2: "Add Purchased Parts", value: "Aggiungi parti acquistate"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code", value: "Codice edificio"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code:", value: "Codice edificio:"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Code", value: "Codice parte"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Storage Locations", value: "Posizioni stoccaggio parti"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Quantity Available", value: "Quantità disponibile"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Code", value: "Codice posizione di stoccaggio"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Name", value: "Nome posizione stoccaggio"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Work Request Code", value: "Codice richiesta di lavoro"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account", value: "Commessa"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account Code", value: "Codice commessa"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Add Purchased Parts to Inventory", value: "Aggiungi parti acquistate a inventario"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part", value: "Parte"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part Code", value: "Codice parte"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Price", value: "Prezzo"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Quantity (each)", value: "Quantità (ciascuna)"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location", value: "Posizione di stoccaggio"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location Code", value: "Codice posizione di stoccaggio"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve", value: "Approva"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Request", value: "Approva richiesta"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Cancel", value: "Annulla"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Documents", value: "Documenti"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "References", value: "Riferimenti"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Reject", value: "Rifiuta"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Approve", value: "Approva"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Reject", value: "Rifiuta"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Requests", value: "Approva richieste"},
        {key1: "Maintenance.view.manager.EstimateApproveForm", key2: "Approve Request Estimation", value: "Approva stima richiesta"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Costs", value: "Costi"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Documents", value: "Documenti"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "References", value: "Riferimenti"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Complete Estimation", value: "Completa stima"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Estimate", value: "Stima"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Actual Cost", value: "Costo effettivo"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Add Other Cost", value: "Aggiungi altro costo"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Labor", value: "Costo manodopera"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Parts", value: "Costo parti"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Estimated Cost", value: "Costo stimato"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Costs", value: "Altri costi"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Description", value: "Altra descrizione di risorsa"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Type", value: "Altro tipo di risorsa"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Quantity Used", value: "Quantità utilizzata"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Actual Costs", value: "Riepilogo costi effettivi"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Estimated Costs", value: "Riepilogo di costi stimati"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Total Cost", value: "Costo totale"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Units", value: "Unità"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Complete Estimation", value: "Completa stima"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Costs", value: "Costi"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Estimate", value: "Stima"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Requests to Estimate", value: "Richieste da stimare"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Part", value: "Aggiungi parte"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Purchased Parts", value: "Aggiungi parti acquistate"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Building Code", value: "Codice edificio"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part", value: "Parte"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part Code", value: "Codice parte"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Available", value: "Quantità disponibile"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Estimated", value: "Quantità stimata"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Used", value: "Quantità utilizzata"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Code", value: "Codice posizione di stoccaggio"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Name", value: "Nome posizione stoccaggio"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Email", value: "E-mail"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Employee Code", value: "Codice dipendente"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Forward", value: "Inoltra"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Supervisor", value: "Supervisore"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Work Team Code", value: "Codice team di lavoro"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Forward", value: "Inoltra"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Requests to Forward", value: "Richieste da inoltrare"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Supervisor", value: "Supervisore"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Work Team Code", value: "Codice team di lavoro"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Completer", value: "Responsabile saldo"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Estimator", value: "Stimatore"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Issuer", value: "Emittente"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject", value: "Rifiuta"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject Request", value: "Rifiuta richiesta"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Requestor", value: "Richiedente"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Scheduler", value: "Utilità di pianificazione"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Approver's Comments", value: "Commenti'responsabile approvazione"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Building", value: "Edificio"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Craftsperson Notes", value: "Note addetti"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Date Requested", value: "Data richiesta"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Equipment Code", value: "Codice apparecchiatura"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Floor", value: "Piano"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Priority", value: "Priorità"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Location", value: "Posizione"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Type", value: "Tipo di problema"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Related Requests", value: "Richieste correlate"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Requestor", value: "Richiedente"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Room", value: "Locale"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Status", value: "Stato"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return", value: "Ritorna"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return Work Request", value: "Restituisci richiesta di lavoro"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Requests to Forward", value: "Richieste da inoltrare"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return", value: "Ritorna"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return Work Request", value: "Restituisci richiesta di lavoro"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Approved", value: "Approvato"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "by", value: "per"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Completed", value: "Completato"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Access", value: "In sospeso per accesso"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Labor", value: "In sospeso per manodopera"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Parts", value: "In sospeso per parti"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Issued", value: "Emesso"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Rejected", value: "Rifiutato"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Requested", value: "Richiesto"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return", value: "Ritorna"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return Work Request", value: "Restituisci richiesta di lavoro"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.manager.ScheduleApproveForm", key2: "Approve Request Schedule", value: "Approva pianificazione richiesta"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Add Trade", value: "Aggiungi fornitura"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Estimated Hours", value: "Ore stimate"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Hours", value: "Ore"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade", value: "Fornitura"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Code", value: "Codice settore"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Description", value: "Descrizione settore"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Complete Scheduling", value: "Completa programmazione"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Documents", value: "Documenti"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Forward", value: "Inoltra"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "References", value: "Riferimenti"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Schedule", value: "Programma"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Actual Hours", value: "Ore effettive"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Assign Craftsperson", value: "Assegna addetto"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Copy", value: "Copia"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson", value: "Addetto"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson Code", value: "Codice addetto"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Finished", value: "Data di completamento"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Scheduled", value: "Data di programmazione"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Started", value: "Data inizio"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Doubletime Hours", value: "Ore straordinari festivi"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Overtime Hours", value: "Ore straordinario"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Primary Trade", value: "Settore primario"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Scheduled Hours", value: "Ore programmate"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Start", value: "Inizio"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Status", value: "Stato"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Stop", value: "Interrompi"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Finished", value: "Orario termine"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Scheduled", value: "Ora programmata"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Started", value: "Ora inizio"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Work Type", value: "Tipo di lavoro"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Complete Scheduling", value: "Completa programmazione"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Forward", value: "Inoltra"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Requests to Schedule", value: "Richieste da pianificare"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Schedule", value: "Programma"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Trades", value: "Settori"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Straight Time Hours Used", value: "Ore effettive"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Assign Tool", value: "Assegna strumento"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Building Code", value: "Codice edificio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Finished", value: "Data di completamento"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Scheduled", value: "Data di programmazione"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Started", value: "Data inizio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Hours", value: "Ore"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Scheduled Hours", value: "Ore programmate"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Start", value: "Inizio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Stop", value: "Interrompi"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Finished", value: "Orario termine"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Scheduled", value: "Ora programmata"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Started", value: "Ora inizio"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool", value: "Strumento"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Code", value: "Codice attrezzo"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Type", value: "Tipo strumento"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Complete", value: "Completato"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Mark only my assignment as Completed.", value: "Contrassegna solo la mia assegnazione come Operazione completata."},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Return Work Request", value: "Restituisci richiesta di lavoro"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Set all craftsperson assignments as Completed", value: "Imposta tutte le assegnazioni addetto come completate"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Costs", value: "Costi"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Documents", value: "Documenti"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "References", value: "Riferimenti"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Update", value: "Aggiorna"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Work Request Details", value: "Dettagli richiesta di lavoro"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Costs", value: "Costi"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Update", value: "Richieste da aggiornare"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Update", value: "Aggiorna"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Confirm", value: "Conferma"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Return Incomplete", value: "Restituisci incompleti"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Verify", value: "Verifica"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Verify", value: "Richieste da verificare"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Confirm", value: "Conferma"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Return Incomplete", value: "Restituisci incompleti"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Verify", value: "Verifica"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Nearing Escalation", value: "10 prossimi a inoltro"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Newest Requests", value: "10 richieste più nuove"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Oldest Requests", value: "10 richieste più vecchie"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "All", value: "Tutto"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Any", value: "Qualsiasi"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Both", value: "Entrambi"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftsperson", value: "Addetto"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested From", value: "Data inizio richiesta"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested To", value: "Data fine richiesta"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform From", value: "Data inizio esecuzione"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform To", value: "Data fine esecuzione"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Equipment", value: "Apparecchiatura"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated", value: "Inoltrato"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated ?", value: "Inoltrato?"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Approved Requests", value: "Richieste approvate"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Requests", value: "Richieste personali"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "On Demand", value: "Su richiesta"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Part", value: "Parte"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "PM", value: "PM"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Priority", value: "Priorità"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Problem Type", value: "Tipo di problema"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requestor", value: "Richiedente"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requests Requiring my Approval", value: "Richieste che necessitano di approvazione utente"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Set Filter", value: "Imposta filtro"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Show", value: "Mostra"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Unassigned Requests", value: "Richieste non assegnate"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Request", value: "Richiesta di lavoro"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Requests", value: "Richieste di lavoro"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Type", value: "Tipo di lavoro"},
        {key1: "Maintenance.view.manager.WorkRequestManagerList", key2: "REQUESTED", value: "Richiesto"},
        {key1: "Maintenance.view.manager.WorkRequestManagerListItem", key2: "Assigned To:", value: "Assegnato a:"},
        {key1: "Maintenance.view.manager.WorkRequestSelection", key2: "Requests to Schedule", value: "Richieste da pianificare"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Hours", value: "Ore"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Job Setup or Prep.", value: "Impostazione o prepar. lavoro"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Material Pickup", value: "Raccolta di materiali"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Travel Time", value: "Durata viaggio"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "UnSpecified", value: "Non specificato"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Client", value: "In attesa del client"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Security", value: "In attesa di protezione"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Work", value: "Lavoro"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "No Status Change", value: "Nessuna modifica di stato"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Access", value: "In attesa di accedere"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Labor", value: "In attesa di lavoro"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold For Parts", value: "In attesa di pezzi"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "Resume To Issued", value: "Ripristina su emesso"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Actual Hours", value: "Ore effettive"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Cancel", value: "Annulla"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Doubletime Hours", value: "Ore straordinari festivi"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Overtime Hours", value: "Ore straordinario"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Save", value: "Salva"},
        {key1: "Maintenance.view.phone.Main", key2: "Apps", value: "App"},
        {key1: "Maintenance.view.phone.QuickComplete", key2: "Complete Request", value: "Completa richiesta"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cancel", value: "Annulla"},
        {key1: "Maintenance.view.SiteMap", key2: "Buildings", value: "Edifici"},
        {key1: "Maintenance.view.tablet.Main", key2: "Apps", value: "App"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Actual Cost", value: "Costo effettivo"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Add Cost", value: "Aggiungi costo"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Date Used", value: "Data utilizzata"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Edit Cost", value: "Modifica costo"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Quantity Used", value: "Quantità utilizzata"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Resource Type", value: "Tipo di risorsa"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Units", value: "Unità"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Cost:", value: "Costo:"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Other Costs", value: "Altri costi"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Actual Hours", value: "Ore effettive"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Add Craftsperson", value: "Aggiungi addetto"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Craftsperson", value: "Addetto"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Finished", value: "Data di completamento"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Started", value: "Data inizio"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Doubletime Hours", value: "Ore straordinari festivi"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Edit Craftsperson", value: "Modifica addetto"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Overtime Hours", value: "Ore straordinario"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Start", value: "Inizio"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Status", value: "Stato"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Stop", value: "Interrompi"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Finished", value: "Orario termine"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Started", value: "Ora inizio"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Work Type", value: "Tipo di lavoro"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Hours", value: "Ore"},
        {key1: "Maintenance.view.manager.WorkRequestEdit", key2: "References", value: "Riferimenti"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Assigned Date", value: "Assegna data"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cause Type", value: "Tipo causa"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Code", value: "Codice"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Costs", value: "Costi"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftsperson Notes", value: "Note addetti"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftspersons", value: "Addetti manutenzione"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Related Work Request", value: "Crea richiesta di lavoro correlata"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Work Request", value: "Crea richiesta di lavoro"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Description", value: "Descrizione"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Documents", value: "Documenti"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 1", value: "Foto 1"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 2", value: "Foto 2"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 3", value: "Foto 3"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 4", value: "Foto 4"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "PM Procedure", value: "Procedura MP"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Description", value: "Descrizione problema"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Location", value: "Posizione"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Type", value: "Tipo di problema"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Repair Type", value: "Tipo di riparazione"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested", value: "Richiesto"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested By", value: "Richiesto da"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Scheduled Date", value: "data programmata"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Status", value: "Stato"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Tools", value: "Strumenti"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Update", value: "Aggiorna"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Work Request Details", value: "Dettagli richiesta di lavoro"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Escalation", value: "Escalation"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Loading...", value: "Caricamento in corso..."},
        {key1: "Maintenance.view.WorkRequestList", key2: "Location", value: "Posizione"},
        {key1: "Maintenance.view.WorkRequestList", key2: "My Work", value: "Lavoro personale"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Problem Type", value: "Tipo di problema"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search", value: "Ricerca"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search Work Requests", value: "Cerca richieste di lavoro"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Status", value: "Stato"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Add Part", value: "Aggiungi parte"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Assigned", value: "Assegnato"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Comments", value: "Commenti"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Edit Part", value: "Modifica parte"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Part", value: "Parte"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Quantity", value: "Quantità"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Parts", value: "Parti"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Quantity", value: "Quantità"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "OpenURL", value: "Apri URL"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "URL does not exsits", value: "L’URL non esiste"},
        {key1: "Maintenance.view.WorkRequestReferencesLists", key2: "References", value: "Riferimenti"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Eliminare l’oggetto?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Immettere il contenuto della casella di testo:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Planimetria non disponibile"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Copia"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Incolla"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Ricarica"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Salva immagine"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Eliminare la voce?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Modifica"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Nessuna planimetria disponibile per linee rosse"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Pubblica date"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Mappe del sito"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Planimetria"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Annotazione"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Codici edifici"},
    ]
};
