/**
 * Handles events generated by the Service Request document feature
 */
Ext.define('WorkplacePortal.controller.Documents', {
    extend: 'Ext.app.Controller',

    requires: 'Common.document.DocumentManager',

    config: {
        refs: {
            mainView: 'mainview',
            serviceRequestView: 'serviceDeskRequestFormPanel',
            documentViewItem: 'documentItem',
            cameraPanel: 'camera',
            documentListView: 'serviceDeskDocumentList'
        },
        control: {
            cameraPanel: {
                attach: 'onAttachPhoto'
            },
            documentViewItem: {
                displaydocument: 'onDisplayDocument',
                deleteDocument: 'onDeleteDocument'
            }
        },

        documentFieldsUsedMessage: LocaleManager.getLocalizedString('All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request',
            'WorkplacePortal.controller.Documents'),

        documentFieldsUsedTitle: LocaleManager.getLocalizedString('Documents', 'WorkplacePortal.controller.Documents'),
        documentDeleteMessage: LocaleManager.getLocalizedString('This action will remove the document. Do you want to proceed?', 'WorkplacePortal.controller.Documents')
    },

    onDisplayDocument: function (mobileWrId, fileName, documentFieldId, fieldName) {
        var me = this,
            workRequestStore = Ext.getStore('serviceDeskRequestsStore'),
            workRequestRecord = workRequestStore.findRecord('id', mobileWrId),
            documentField = fieldName + '_contents',
            documentData;

        if (workRequestRecord) {
            documentData = workRequestRecord.get(documentField);
            DocumentManager.displayDocumentOrImage(documentData, fileName, me.getCameraPanel());
        }
    },

    onDeleteDocument: function (recordId, documentFieldId, fieldName, documentData, documentListItem) {
        var me = this,
            store = Ext.getStore('serviceDeskRequestsStore'),
            record = store.findRecord('id', recordId);

        if (record) {
            Ext.Msg.confirm(me.getDocumentFieldsUsedTitle(), me.getDocumentDeleteMessage(), function (buttonId) {
                if (buttonId === 'yes') {
                    documentListItem.setDocumentData(documentListItem.MARK_DELETED_TEXT);
                    me.doDeleteDocument(store, record, fieldName);
                }
            });
        }
    },

    doDeleteDocument: function (store, record, fieldName) {
        var me = this;
        // if record was not synchronized yet it can be removed immediately
        if (record.get(fieldName + '_isnew')) {
            me.clearDocumentContents(record, fieldName);
            me.getDocumentListView().processDocumentFields(record);
        } else {
            return DocumentManager.deleteDocumentFile(store, record, fieldName)
                .then(function () {
                    return DocumentManager.markDocumentDeleted(store, record, fieldName);
                })
                .then(function (record) {
                    me.getDocumentListView().processDocumentFields(record);
                })
                .then(null, function (error) {
                    Log.log(error, 'error');
                    Ext.Msg.alert('', error);
                });
        }
    },

    clearDocumentContents: function (record, documentField) {
        record.set(documentField, null);
        record.set(documentField + '_contents', null);
        record.set(documentField + '_isnew', false);
        record.set(documentField + '_file', '');
    },

    /**
     * Saves the photo data in the Work Request record.
     * @param cameraPanel
     */
    onAttachPhoto: function (cameraPanel) {
        var me = this,
            imageData = cameraPanel.getImageData(),
            serviceRequestView = me.getServiceRequestView(),
            serviceRequestRecord,
            serviceDeskRequestsStore = Ext.getStore('serviceDeskRequestsStore'),
            documentListView = me.getDocumentListView();

        if (serviceRequestView) {
            serviceRequestRecord = serviceRequestView.getRecord();
        }

        serviceDeskRequestsStore.setAutoSync(false);
        me.addPhotoToWorkRequestRecord(serviceRequestRecord, imageData);

        if (documentListView) {
            documentListView.setRecord(serviceRequestRecord);
        }

        serviceDeskRequestsStore.setAutoSync(true);

        // If this is an update view we need to save the work request record
        if (serviceRequestView && serviceRequestView.getIsCreateView()) {
            serviceRequestView.applyPhotoData();
        } else {
            serviceDeskRequestsStore.sync();
        }

        cameraPanel.onClosePanel();
    },

    addPhotoToWorkRequestRecord: function (serviceDeskRequestRecord, imageData) {
        var me = this,
            documentField = serviceDeskRequestRecord.getAvailableDocumentField();

        if (documentField === null) {
            Ext.Msg.alert(me.getDocumentFieldsUsedTitle(), me.getDocumentFieldsUsedMessage());
        } else {
            serviceDeskRequestRecord.setDocumentFieldData(documentField, imageData);
        }
    }
});