var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.nl = {
    localizedStrings: [
        {key1: "AppLauncher.controller.Preferences", key2: "<p>Changing the Web Central URL requires the Mobile Client app to be stopped and restarted.</p><p>The app data will be removed from the device during the registration process.</p><p>Synchronize your data before proceeding to prevent any data loss.</p><br>", value: "<p>Om de URL van Web Central te kunnen wijzigen, moet de app Mobile Client worden gestopt en opnieuw worden gestart.</p><p>De app-gegevens worden tijdens het registratieproces uit het apparaat verwijderd.</p><p>Synchroniseer uw gegevens voordat u verdergaat om verlies van gegevens te voorkomen.</p><br>"},
        {key1: "AppLauncher.controller.Preferences", key2: "Change URL", value: "URL wijzigen"},
        {key1: "AppLauncher.controller.Preferences", key2: "Do you wish to continue?", value: "Wil U doorgaan?"},
        {key1: "AppLauncher.controller.Preferences", key2: "Logging", value: "Logboekregistratie"},
        {key1: "AppLauncher.controller.Preferences", key2: "Reset Sync Flag", value: "Sync-markering resetten"},
        {key1: "AppLauncher.controller.Preferences", key2: "Sync", value: "Sync"},
        {key1: "AppLauncher.controller.Preferences", key2: "The background data sync flag will be reset.<br>The background data will be downloaded during the next application sync.<br>", value: "De sync.-markering basisgegevens wordt gereset.<br>De basisgegevens zullen tijdens de volgende applicatiesynchronisatie worden gedownload.<br>"},
        {key1: "AppLauncher.controller.Preferences", key2: "This action will remove all of your data from the device. Do you want to proceed?", value: "Met deze actie worden al uw gegevens van het apparaat verwijderd. Wilt u doorgaan?"},
        {key1: "AppLauncher.controller.Preferences", key2: "Uploading Log Messages", value: "Logboekberichten uploaden"},
        {key1: "AppLauncher.controller.Preferences", key2: "URL Required", value: "URL vereist"},
        {key1: "AppLauncher.controller.Preferences", key2: "User", value: "Gebruiker"},
        {key1: "AppLauncher.controller.Preferences", key2: "Version", value: "Versie"},
        {key1: "AppLauncher.controller.Preferences", key2: "Web Central URL", value: "Web Central-URL"},
        {key1: "AppLauncher.controller.Registration", key2: "App", value: "App"},
        {key1: "AppLauncher.controller.Registration", key2: "Log Out", value: "Afmelden"},
        {key1: "AppLauncher.controller.Registration", key2: "The requested application is not available. The network connection is not available or the app has not been cached.", value: "De aangevraagde toepassing is niet beschikbaar. De netwerkverbinding is niet beschikbaar of de toepassing staat niet in de cache."},
        {key1: "AppLauncher.controller.About", key2: "App Launcher", value: "Startprogramma voor apps"},
        {key1: "AppLauncher.controller.About", key2: "Application", value: "Toepassing"},
        {key1: "AppLauncher.controller.About", key2: "Build Date", value: "Build-datum"},
        {key1: "AppLauncher.controller.About", key2: "Build Version", value: "Build-versie"},
        {key1: "AppLauncher.controller.About", key2: "Registered Applications", value: "Geregistreerde toepassingen"},
        {key1: "AppLauncher.view.AppList", key2: "{0}No Applications are Available. Tap the {1} icon in the title bar above to register this device.{2}", value: "{0}Er zijn geen toepassingen beschikbaar. Tik op het pictogram {1} in de titelbalk hierboven om dit apparaat te registreren.{2}"},
        {key1: "AppLauncher.view.Log", key2: "Done", value: "Gereed"},
        {key1: "AppLauncher.view.Log", key2: "Log", value: "Logboek"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Archived Files", value: "Gearchiveerde bestanden"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Console Writer", value: "Schrijven naar console"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Database Writer", value: "Schrijven naar database"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "DEPRECATE", value: "AFSCHRIJVEN"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Display Log", value: "Logboek weergeven"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Displays messages in the device console", value: "Berichten in de apparaatconsole weergeven"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Enabled", value: "Ingeschakeld"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "ERROR", value: "Fout"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "File Writer", value: "Schrijven naar bestand"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "INFO", value: "Info"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Level", value: "Niveau"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Logging", value: "Logboekregistratie"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Logging messages will affect performance of your apps. Only enable logging when required.", value: "Logboekberichten zijn van invloed op de prestaties van uw apps. Schakel logboekregistratie alleen in wanneer dat vereist is."},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Logging Settings", value: "Instellingen voor aanmelden"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Max. File Size", value: "Max. bestandsgrootte"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Max. Records", value: "Max. records"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Sync Log", value: "Logboek synchroniseren"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "VERBOSE", value: "Uitgebreid"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "WARN", value: "WAARSCHUWEN"},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Writes messages to the archibusmobile.log file. The file will be truncated when it reaches the Max. File setting.", value: "Schrijft berichten naar het bestand archibusmobile.log. Het bestand wordt ingekort wanneer de instelling voor maximale bestandsgrootte wordt bereikt."},
        {key1: "AppLauncher.view.LoggingSettings", key2: "Writes messages to the device database.", value: "Schrijft berichten naar de apparaatdatabase."},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Back", value: "Terug"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Done", value: "Gereed"},
        {key1: "AppLauncher.view.PreferenceList", key2: "Preferences", value: "Voorkeuren"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Change Registered User", value: "Geregistreerde gebruiker wijzigen"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Change Web Central Server URL", value: "URL van Web Central-server wijzigen"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Display Log", value: "Logboek weergeven"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Preferences", value: "Voorkeuren"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Registered User", value: "Geregistreerde gebruiker"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Reset Background Data Sync Flag", value: "Sync.-markering basisgegevens resetten"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Web Central URL", value: "Web Central-URL"},
        {key1: "AppLauncher.view.RestartDevice", key2: "Click the Home button and open the Mobile Client app again.", value: "Klik op de knop Home en open nogmaals de app Mobile Client."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Click the Home button to return to the Home screen.", value: "Klik op de knop Home om terug te keren naar het startscherm."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Find the Mobile Client app. Swipe left or right if the app is not displayed", value: "Zoek de app Mobile Client. Veeg naar links of naar rechts als de app niet wordt weergegeven"},
        {key1: "AppLauncher.view.RestartDevice", key2: "From the Application menu screen, select Settings.", value: "Selecteer Instellingen in het menu Toepassing."},
        {key1: "AppLauncher.view.RestartDevice", key2: "From the Home screen, click the Home button twice.", value: "Klik in het startscherm tweemaal op de knop Home."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Open the Mobile Client app again.", value: "Open nogmaals de app Mobile Client."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Restart Mobile Client", value: "Mobile Client opnieuw starten"},
        {key1: "AppLauncher.view.RestartDevice", key2: "Restart the Mobile Client app.", value: "Start de app Mobile Client opnieuw op."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Select Application manager.", value: "Selecteer toepassingsbeheerder."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Select the Mobile Client app.", value: "Selecteer de app Mobile Client."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Stop the Mobile Client app.", value: "Stop de app Mobile Client."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Swipe up on the app to close it.", value: "Veeg omhoog in de app om deze te sluiten."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Tap and hold on the Mobile Client app.", value: "Houd uw vinger op de app Mobile Client."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Tap the Force stop button.", value: "Tik op de knop Geforceerd stoppen."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Tap the Home button.", value: "Tik op de knop Home."},
        {key1: "AppLauncher.view.RestartDevice", key2: "Tap the Home icon/button to return to the Home screen.", value: "Tik op Home om terug te keren naar het startscherm."},
        {key1: "AppLauncher.view.RestartDevice", key2: "When it starts to jiggle, tap the red (-) icon to close it.", value: "Wanneer het rode (-) pictogram heen en weer begint te bewegen, tikt u erop om de weergave te sluiten."},
        {key1: "AppLauncher.view.SyncSettings", key2: "Clear Data", value: "Gegevens wissen"},
        {key1: "AppLauncher.view.SyncSettings", key2: "Reset Background Data Sync Flag", value: "Sync.-markering basisgegevens resetten"},
        {key1: "AppLauncher.view.SyncSettings", key2: "Sync Settings", value: "Synchronisatie-instellingen"},
        {key1: "AppLauncher.view.tablet.Preferences", key2: "Setting", value: "Instelling"},
        {key1: "AppLauncher.view.UserSettings", key2: "Building", value: "Gebouw"},
        {key1: "AppLauncher.view.UserSettings", key2: "Department", value: "Afdeling"},
        {key1: "AppLauncher.view.UserSettings", key2: "Device is not Registered", value: "Uitrusting is niet geregistreerd"},
        {key1: "AppLauncher.view.UserSettings", key2: "Division", value: "Divisie"},
        {key1: "AppLauncher.view.UserSettings", key2: "Email", value: "E-mail"},
        {key1: "AppLauncher.view.UserSettings", key2: "Employee ID", value: "Personeels-ID"},
        {key1: "AppLauncher.view.UserSettings", key2: "Floor", value: "Verdieping"},
        {key1: "AppLauncher.view.UserSettings", key2: "Log Out", value: "Afmelden"},
        {key1: "AppLauncher.view.UserSettings", key2: "Phone", value: "Telefoon"},
        {key1: "AppLauncher.view.UserSettings", key2: "Register Device", value: "Apparaat registreren"},
        {key1: "AppLauncher.view.UserSettings", key2: "Registered User", value: "Geregistreerde gebruiker"},
        {key1: "AppLauncher.view.UserSettings", key2: "Room", value: "Ruimte"},
        {key1: "AppLauncher.view.UserSettings", key2: "User", value: "Gebruiker"},
        {key1: "AppLauncher.view.About", key2: "Mobile Client 2.0 Version", value: "Mobile Client versie 2.0"},
        {key1: "AppLauncher.view.About", key2: "Web Central Version", value: "Web Central-versie"},
        {key1: "AppLauncher.view.WebCentral", key2: "Change Web Central Server URL", value: "URL van Web Central-server wijzigen"},
        {key1: "AppLauncher.view.WebCentral", key2: "Web Central Server", value: "Web Central-server"},
        {key1: "AppLauncher.view.WebCentral", key2: "Web Central URL", value: "Web Central-URL"},
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Accepteer het browserverzoek om gegevens op de lokale computer op te slaan en vernieuw de pagina."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fout tijdens laden van configuratiebestand."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "De controller '{0}' heeft geen startmethode. Weet u zeker dat dit een uitbreiding is van Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Deze waarde heeft de verkeerde notatie:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Dit is geen geldig e-mailadres:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Dit is geen geldige waarde:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Deze waarde is niet opgenomen in de lijst met acceptabele waarden:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Deze waarde heeft de verkeerde lengte:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Deze waarde moet aanwezig zijn:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Koppelen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Sluiten"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Gereed"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Bezig met laden..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Corrigeer het volgende:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scanfout"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Gereed"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Geen gegevens om weer te geven voor: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Toepassen"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Geen {0} om weer te geven."},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Aanvraag"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Uren"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Item {0} van {1} laden"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Voornaam"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Achternaam"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Naam:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contactpersoon"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Afdelingscode"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Afdeling:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Divisiecode:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Divisie"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Divisie:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisies"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Medewerker"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Personeelscode"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Personeelsstandaard"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Uitrusting:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type probleem"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code van vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Vastgoedobject:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebouw/verdieping:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Ruimtestandaard"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standaards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type ruimte"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Vestigingscode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Er zijn geen eerdere zoekopdrachten opgeslagen."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.Signature", key2: "Done", value: "Gereed"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Handtekening"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Er moet een mainView-referentieconfiguratie worden verstrekt bij het uitbreiden van de Common.controller.NavigationController-klasse"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Opslaan"},
        {key1: "AppLauncher.controller.Registration", key2: "Register Device", value: "Apparaat registreren"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Doorgaan?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Fout bij het ongedaan maken van de apparaatregistratie. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Door uit te loggen worden uw toepassingsgegevens niet verwijderd.<br>U moet het apparaat opnieuw registreren om toegang tot de apps te krijgen."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registratie"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registratie is mislukt"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "De service voor apparaatregistratie is niet beschikbaar. De Mobiel-services zijn mogelijk niet ingeschakeld in Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Model met de naam [{0}] bestaat niet."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Scannen van barcodes is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Toestemming voor toegang tot locatiegegevens geweigerd"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Positie is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Time-out voor positie"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fout onbekende positie"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Er is een fout opgetreden tijdens het weergeven van het document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Documentweergave"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Document downloaden"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Functie niet beschikbaar in de desktopomgeving."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Bestand bestaat niet"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Bestand {0} kan niet op dit apparaat worden weergegeven."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Bestand {0} kan niet worden weergegeven in de Desktop-modus."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Document verwijderen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Veld met de naam Veld gewijzigd: {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Invoer"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Invoer voor veld {0} is beperkt tot {1} tekens"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Wissen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopiëren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Gereed"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fout"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nee"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Plakken"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Ruimtenaam"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Ruimtenamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Survey"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Deze toepassing is bijgewerkt naar de laatste versie. De toepassing wordt opnieuw geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fout bij laden van netwerkservices. De netwerkverbinding kan traag of niet beschikbaar zijn"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Geen gegevens ontvangen van server"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Time-out"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Onbekende fout"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fout bij registreren van apparaat"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fout tijdens ophalen van gebruikersinformatie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fout tijdens instellen van landinstellingen voor sessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fout tijdens opstarten van gebruikerssessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fout bij eenmalige aanmelding"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fout bij ophalen van TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Apparaat is niet geregistreerd"},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Werkstroom toJSON. Datumobjecten mogen niet worden gerangschikt aan de hand van Werkstroomregels."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Werkstroomregel uitgevoerd"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Werkstroomregel mislukt:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-voorkeuren"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types oorzaken"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contactpersonen"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisies"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Medewerkers"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Personeelsstandaarden"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Letsels"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Letselcategorieën"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Incidenttypen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantype Groepen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Type problemen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projecten"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Eigenschappen"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Databasefout:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Geen wijziging aan databasetabel toegepast. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Standaardwaarde niet bijgewerkt voor veld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standaardwaarde bijwerken: veld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Fout Sqlite-proxy"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Fout Sqlite-proxy tijdens aanmaken"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Fout Sqlite-proxy tijdens vernietigen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Fout Sqlite-proxy tijdens lezen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Fout Sqlite-proxy tijdens bijwerken"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fout bij openen van database: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Databasefout [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Databasefout in SqliteView-proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView is alleen-lezen; het verwijderen van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView is alleen-lezen; het bijwerken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView is alleen-lezen; het maken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "De database bevat niet de vereiste tabeldefinities voor Sqllite-weergave {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Type reparaties"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Ruimtestandaarden"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Ruimtefuncties"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "bestand_niet_beschikbaar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchroniseren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Downloaden"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fout"},
        {key1: "AppLauncher.controller.Registration", key2: "Device", value: "Uitrusting"},
        {key1: "AppLauncher.controller.Registration", key2: "TestKey", value: "TestKey"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "De applicatievoorkeuren zijn niet geladen"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Uitvoeren in browsermodus. Toegang tot bestandssysteem uitgeschakeld"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Uitvoeren in Chrome of in webweergave. Toegang tot bestandssysteem ingeschakeld"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Toegang tot bestanden werd afgebroken"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Bestand bestaat al"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fout bij bestandscodering"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Bestandsfout"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Bestand is in ongeldige toestand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Bestandswijziging is niet toegestaan"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Bestandsquotum is overschreden"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fout bij bestandsbeveiliging"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fout bij vergelijken bestandstype"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Bestand is niet gevonden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Bestand is niet leesbaar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fout: ongeldige bestandswijziging"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netwerk onbereikbaar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Basisgegevens downloaden"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fout"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Het toepassingsvoorkeurenarchief is niet geladen. Kan voorkeuren niet ophalen."},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "sq ft"},
        {key1: "Common.util.Units", key2: "sq m", value: "vierkante meter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "De gegevens van het gebruikersprofiel zijn niet beschikbaar. Synchroniseer om de gegevens van het gebruikersprofiel op te halen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Verwijderen tijdens synchroniseren"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Tonen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documenten"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Geen documenten beschikbaar"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} of {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 van x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "De naam van de Model-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de modeleigenschap"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "De opslag-id van de Opslag-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de storeId-eigenschap"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Wissen"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Terug"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Opslaan"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Veld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifier"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Grootte (in bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisatieberichten"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabel"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "De volgende Web Central-veldwaarden zijn niet naar de clientdatabase geschreven omdat de hoeveelheid gegevens de databaselimiet overschrijdt"},
        {key1: "AppLauncher.view.Registration", key2: "ARCHIBUS password (case-sensitive)", value: "ARCHIBUS-wachtwoord (hoofdlettergevoelig):"},
        {key1: "AppLauncher.view.Registration", key2: "ARCHIBUS user name (upper case)", value: "ARCHIBUS-gebruikersnaam (hoofdletters)"},
        {key1: "AppLauncher.view.Registration", key2: "Password", value: "Wachtwoord"},
        {key1: "AppLauncher.view.Registration", key2: "Password (case-sensitive)", value: "Wachtwoord (hoofdlettergevoelig)"},
        {key1: "AppLauncher.view.Registration", key2: "Register Device", value: "Apparaat registreren"},
        {key1: "AppLauncher.view.Registration", key2: "Sign in as Guest", value: "Inloggen als gast"},
        {key1: "AppLauncher.view.Registration", key2: "User name (upper case)", value: "Gebruikersnaam (hoofdletters)"},
        {key1: "AppLauncher.view.Registration", key2: "Username", value: "Gebruikersnaam"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter instellen"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Gebouwcodes"},
    ]
};
