/* Disable JSHint warning of Missing 'new' prefix for the StartTest function. */
/* jshint newcap: false */
/* global StartTest */
StartTest(function (t) {

    t.requireOk('Common.security.PermutationGenerator', 'Common.security.Password',
            'Common.security.Security', function () {

                var pwd,
                    decrypt;

                // Compare hashed strings to strings generated by the original doSecure function
                pwd = Common.security.Security.encryptString('jsmith');
                t.is(pwd, 'sh@y^*-m 13579t02468ji0ZXw=+', 'Text is hashed');

                pwd = Common.security.Security.encryptString('Mahal-Ko-1964');
                t.is(pwd, 'a-K @y 4+hK90Z357Kh1402^*8Mlo609Xw=6', 'Text is hashed');

                decrypt = Common.security.Security.decryptString('a-K @y 4+hK90Z357Kh1402^*8Mlo609Xw=6');

                // decryption adds blank spaces to the end of the string. We can ignore those.
                decrypt = Ext.String.trim(decrypt);

                t.is(decrypt, 'Mahal-Ko-1964', 'Decrypted strings match');

                t.done();

            });
});