var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.de = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Akzeptieren Sie die Browseranforderung, Daten auf Ihrem lokalen Computer zu speichern und die Seite zu aktualisieren."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fehler beim Laden der Konfigurationsdatei."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Der Controller '{0}' verfügt über keine Startmethode. Sind Sie sicher, dass der Controller eine Erweiterung von Ext.app.Controller ist?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Der Wert hat ein falsches Format:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Der Wert ist keine gültige E-Mail:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Der Wert ist kein zulässiger Wert:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Der Wert ist in der Liste zulässiger Werte nicht enthalten:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Der Wert hat eine falsche Länge:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Der folgende Wert muss vorhanden sein:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Anhängen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Schließen"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Fertig"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Ladevorgang wird ausgeführt..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Korrigieren Sie Folgendes:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scan-Fehler"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Fertig"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Keine Datenanzeige für: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Anwenden"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Kein(e) {0} zum Anzeigen"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Anforderung"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Stunden"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Objekt {0} von {1} wird geladen"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Vorname"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nachname"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Name:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Ansprechpartner"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Bezeichnung des Ansprechpartners"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Bezeichnung der Abteilung"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Abteilung:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Bereich"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Bezeichnung des Bereichs"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Bereich:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-Mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-Mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Mitarbeiter"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Kurzzeichen Mitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standardmitarbeiter"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Geräte"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Gerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Geräte:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standardgerät"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Geschosse"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Problemtyp"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Bezeichnung der Liegenschaft"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Liegenschaft:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebäude/Geschoss:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Kurzzeichen Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebäude:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Geschoss"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Geschoss:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Raum"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Raum:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Räume"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Räume"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standardraum"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Kategorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Beschreibung"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Beschreibung:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Raumtyp"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Typ:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Kurzzeich.:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Standort"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Standortcode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Standort:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Standorte"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Es wurden keine vorherigen Suchen gespeichert."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Leeren"},
        {key1: "Common.control.Signature", key2: "Done", value: "Fertig"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Unterschrift"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Bei Erweiterung der Klasse Common.controller.NavigationController muss eine mainView-Ref.-Konfiguration bereitgestellt werden."},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Speichern"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Möchten Sie fortfahren?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Beim Aufheben der Geräteregistrierung ist ein Fehler aufgetreten. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Beim Abmelden werden Ihre Anwendungsdaten nicht entfernt.<br>Sie müssen das Gerät erneut registrieren, um auf die Apps zugreifen zu können."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registrierung"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registrierung fehlgeschlagen"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Der Gerätregistrierungsservice ist nicht verfügbar. Die Mobildienste sind in Web Central möglicherweise nicht aktiviert."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Modell mit dem Namen [{0}] ist nicht vorhanden."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Einlesen des Barcodes ist nicht möglich"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Berechtigung zum Zugriff auf Standortinformationen verweigert"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Position ist nicht verfügbar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Zeitüberschreitung der Position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fehler: Unbekannte Position"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Beim Anzeigen des Dokuments und der Finanzierungsquelle"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Dokumentanzeige"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Dokument wird heruntergeladen"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Funktion in Desktop-Umgebung nicht verfügbar."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Datei existiert nicht"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Datei {0} kann auf diesem Gerät nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Datei {0} kann im Desktop-Modus nicht angezeigt werden."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Dokument entfernen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Feld 'Feld geändert': {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Eingabe"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Eingabe für Feld {0} ist auf {1} Zeichen begrenzt"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Abbrechen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Leeren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopieren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Fertig"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fehler"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nein"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Einfügen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Neu laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Raumname"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Raumnamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Bild speichern"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Umfrage"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Mehr laden…"},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Keine weiteren Datensätze"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Die Anwendung wurde auf die neueste Version aktualisiert. Die Anwendung wird neu geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fehler beim Laden von Netzwerkdiensten. Die Netzwerkverbindung ist möglicherweise langsam oder nicht verfügbar."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Keine Daten vom Server erhalten"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Zeitüberschreitung"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Unbekannter Fehler"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fehler beim Registrieren des Geräts."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fehler beim Abrufen von Benutzerinformationen."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fehler beim Festlegen des Sitzungsgebiets."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fehler beim Starten der Benutzersitzung."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fehler bei Einzelanmeldung"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fehler beim Abrufen von TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Gerät ist nicht registriert."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Workflow nach JSON. Datenobjekte dürfen nicht mithilfe von Workflow-Regeln gemarshallt werden."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Workflow-Regel ausgeführt"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Workflow-Regel fehlgeschlagen:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-Einstellungen"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Ursachentypen"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Ansprechpartner"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Handwerker"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Abteilungen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Bereiche"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Personal"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standardpersonal"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Geräte"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standardgeräte"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Geschosse"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Verletzte Körperteile"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Verletzungskategorien"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Arbeitsunfall - Typen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantypgruppen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Problemtypen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projekte"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Liegenschaften"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Datenbankfehler:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Keine Änderung an Datenbanktabelle übernommen. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Keine Standardwertaktualisierung für Feld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standardwert aktualisieren: Feld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Sqlite-Proxy-Fehler"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Sqlite-Proxy-Fehler während Erstellungsvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Sqlite-Proxy-Fehler während Löschvorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Sqlite-Proxy-Fehler während Lesevorgang"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Sqlite-Proxy-Fehler während Aktualisierungsvorgang"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fehler beim Öffnen der Datenbank: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Datenbankfehler [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Datenbankfehler bei SqliteView-Proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Löschen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Aktualisieren von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView ist schreibgeschützt und unterstützt nicht das Erstellen von Datensätzen."},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "Die Datenbank enthält nicht die erforderlichen Tabellendefinitionen für die Sqlite-Ansicht {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Reparaturtypen"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Raumkategorien"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Räume"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standardräume"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Raumtypen"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Raumnutzungsarten"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Standorte"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "datei_nicht_verfügbar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisieren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Herunterladen wird ausgeführt:"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fehler"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Date-Typ konvertiert werden."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Integer konvertiert werden."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Time konvertiert werden."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "Der Eingabewert kann nicht in den Typ Common.type.Timestamp konvertiert werden."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Die Anwendungseinstellungen wurden nicht geladen."},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Ausführung im Browser-Modus. Zugriff auf Dateisystem deaktiviert"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Ausführung in Chrome oder in WebView. Zugriff auf Dateisystem aktiviert"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Dateizugriff wurde abgebrochen"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Datei ist bereits vorhanden"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fehler bei Dateiverschlüsselung"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Dateifehler"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Datei befindet sich in einem ungültigen Zustand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Dateiänderung ist nicht zulässig"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Dateiquoten überschritten"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fehler bei Dateisicherheit"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fehler wegen Dateitypkonflikt"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Datei wurde nicht gefunden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Datei war nicht lesbar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fehler aufgrund ungültiger Dateiänderung"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netzwerkverbindung ist nicht verfügbar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netzwerk nicht erreichbar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Stammdaten werden heruntergeladen"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fehler"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Der App-Einstellungsspeicher ist nicht geladen. Einstellungen können nicht abgerufen werden."},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "m"},
        {key1: "Common.util.Units", key2: "sq ft", value: "Quadratmeter"},
        {key1: "Common.util.Units", key2: "sq m", value: "Quadratmeter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Die Benutzerprofilinformationen sind nicht verfügbar. Führen Sie eine Synchronisierung durch, um die Benutzerprofildaten abzurufen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Bei Synchronisierung löschen"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Anzeigen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Dokumente"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Keine Dokumente verfügbar."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} von {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 von x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Der Name der Modellklasse, die dieser Ansicht zugeordnet ist, muss in der Modelleigenschaft angegeben werden."},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "Die Speicher-ID der Speicherklasse, die dieser Ansicht zugeordnet ist, muss in der Eigenschaft -storeId- angegeben werden."},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Leeren"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Zurück"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Speichern"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Feld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Kennung"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Größe (Bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisierungsmeldungen"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabelle"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Die folgenden Web Central-Feldwerte wurden nicht in die Client-Datenbank übertragen, da die Datengröße die Kapazität der Datenbank überschreitet."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Date Updated", value: "Aktualisiert am"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Edited By", value: "Zuletzt bearbeitet von"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Inventoried", value: "Datum der letzten Bestandsaufnahme"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle", value: "Gang"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code:", value: "Gangkurzzeichen:"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisles", value: "Gänge"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Name", value: "Name"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle/Cabinet/Shelf:", value: "Gang/Schrank/Regal:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code", value: "Lagercontainerkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code:", value: "Lagercontainerkurzzeichen:"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bins", value: "Lagercontainer"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Cabinet Code", value: "Schrankkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Shelf Code", value: "Regalkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code:", value: "Gangkurzzeichen:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinet Code", value: "Schrankkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "cabinet Code:", value: "Schrankkurzzeichen:"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinets", value: "Schränke"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building/Floor:", value: "Gebäude/Geschoss:"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Floor Code", value: "Geschoss"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code", value: "Raum"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code:", value: "Raum:"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Rooms", value: "Räume"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle/Cabinet:", value: "Gang/Schrank:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Cabinet Code", value: "Schrankkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code", value: "Regalkurzzeichen"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code:", value: "Regalkurzzeichen:"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelves", value: "Regale"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Loading...", value: "Ladevorgang wird ausgeführt..."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No document available for selected location.", value: "Kein Dokument für ausgewählten Standort verfügbar."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floor plans available.", value: "Keine Grundrisse verfügbar."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floors available.", value: "Keine Geschosse verfügbar."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Not all floor plans were downloaded.", value: "Es wurden nicht alle Grundrisse heruntergeladen."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Sync Material Locations", value: "Materialstandorte synchronisieren"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "There are no buildings in the selected site.", value: "Im ausgewählten Standort befinden sich keine Gebäude."},
        {key1: "MaterialInventory.controller.Materials", key2: "Cancel", value: "Abbrechen"},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is not registered.", value: "Behälter ist nicht registriert."},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is registered multiple times.", value: "Container ist mehrmals registriert."},
        {key1: "MaterialInventory.controller.Materials", key2: "Document unavailable", value: "Dokument nicht verfügbar"},
        {key1: "MaterialInventory.controller.Materials", key2: "Downloading Document", value: "Dokument wird heruntergeladen"},
        {key1: "MaterialInventory.controller.Materials", key2: "Error", value: "Fehler"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory", value: "Bestandsliste"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory Start Date cannot be in the future", value: "Das Startdatum der Bestandsliste darf nicht in der Zukunft liegen."},
        {key1: "MaterialInventory.controller.Materials", key2: "The container you have scanned is in a different location: {0}. Do you want to update its location as your current location: {1} or do you want to cancel the scan and navigate to a different location?", value: "Der gescannte Behälter befindet sich an einem anderen Standort: {0}. Möchten Sie seinen Standort als Ihren aktuellen Standort aktualisieren: {1} oder möchten Sie den Scan-Vorgang abbrechen und zu einem anderen Standort navigieren?"},
        {key1: "MaterialInventory.controller.Materials", key2: "This action will save your changes on the server. If you reset the Inventory Start Date then the app will no longer highlight inventoried items. Are you sure you want to clear the Inventory Start Date?", value: "Diese Maßnahme speichert Ihre Änderungen auf dem Server. Wenn Sie das Startdatum der Bestandsliste zurücksetzen, hebt die Anwendung inventarisierte Objekte nicht mehr hervor. Wollen Sie das Startdatum der Bestandsliste löschen?"},
        {key1: "MaterialInventory.controller.Materials", key2: "Update location", value: "Standort aktualisieren"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Aisle with code \\'{0}\\' not found.", value: "Gang mit Kurzzeichen \\'{0}\\' nicht gefunden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Bin with code \\'{0}\\' not found.", value: "Lagercontainer mit Kurzzeichen \\'{0}\\' nicht gefunden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Cabinet with code \\'{0}\\' not found.", value: "Schrank mit Kurzzeichen \\'{0}\\' nicht gefunden."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Close", value: "Schließen"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Floor Plan", value: "Grundriss laden"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Site Map", value: "Standortkarte wird geladen"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Room with code \\'{0}\\' not found.", value: "Raum mit Kurzzeichen \\'{0}\\' nicht gefunden"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Selected building is not registered in the current site.", value: "Das ausgewählte Gebäude ist nicht am derzeitigen Standort registriert."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Shelf with code \\'{0}\\' not found.", value: "Regal mit Kurzzeichen \\'{0}\\' nicht gefunden"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Updating Lists", value: "Listen aktualisieren"},
        {key1: "MaterialInventory.model.MaterialLocation", key2: "{0} cannot be greater than {1}.", value: "{0} darf nicht größer sein als {1}."},
        {key1: "MaterialInventory.store.Actions", key2: "Download Documents", value: "Dokumente herunterladen"},
        {key1: "MaterialInventory.store.MaterialData", key2: "Material Data", value: "Material: Daten"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Locations", value: "Standorte"},
        {key1: "MaterialInventory.store.MaterialMsds", key2: "Documents", value: "Dokumente"},
        {key1: "MaterialInventory.store.prompt.ContainerCategories", key2: "Container Categories", value: "Behälterkategorien"},
        {key1: "MaterialInventory.store.prompt.ContainerTypes", key2: "Container Types", value: "Sicherheitsbehältertypen"},
        {key1: "MaterialInventory.store.prompt.MaterialChemicals", key2: "Chemicals", value: "Chemikalien"},
        {key1: "MaterialInventory.store.prompt.MaterialConstituents", key2: "Constituents", value: "Inhaltsstoffe"},
        {key1: "MaterialInventory.store.MaterialEmployees", key2: "Employees", value: "Personal"},
        {key1: "MaterialInventory.store.prompt.MaterialUnits", key2: "Material Units", value: "Material-Einheiten"},
        {key1: "MaterialInventory.store.prompt.PressureUnits", key2: "Pressure Units", value: "Druckeinheiten"},
        {key1: "MaterialInventory.store.MaterialAisles", key2: "Aisles", value: "Gänge"},
        {key1: "MaterialInventory.store.MaterialBins", key2: "Bins", value: "Lagercontainer"},
        {key1: "MaterialInventory.store.MaterialBuildings", key2: "Buildings", value: "Gebäude"},
        {key1: "MaterialInventory.store.MaterialCabinets", key2: "Cabinets", value: "Schränke"},
        {key1: "MaterialInventory.store.space.MaterialFloors", key2: "Floors", value: "Geschosse"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Rooms", value: "Räume"},
        {key1: "MaterialInventory.store.MaterialShelves", key2: "Shelves", value: "Regale"},
        {key1: "MaterialInventory.store.MaterialSites", key2: "Sites", value: "Standorte"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Cancel", value: "Abbrechen"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Inventory Start Date", value: "Startdatum der Bestandsliste"},
        {key1: "MaterialInventory.view.Filter", key2: "All", value: "Alle"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Category", value: "Behälterkategorie"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Type", value: "Sicherheitsbehältertyp"},
        {key1: "MaterialInventory.view.Filter", key2: "Custodian", value: "Verwalter"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From", value: "Letzte Bestandsaufnahme von"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From should not be greater than Date Last Inventory To.", value: "’Letzte Bestandsaufnahme von’ darf nicht nach ’Letzte Bestandsaufnahme bis’ liegen."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory To", value: "Letzte Bestandsaufnahme bis"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From", value: "Aktualisiert von"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From should not be greater than Date Updated To.", value: "’Aktualisiert von’ darf nicht nach ’Aktualisiert bis’ liegen."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated To", value: "Aktualisiert bis"},
        {key1: "MaterialInventory.view.Filter", key2: "Description", value: "Beschreibung"},
        {key1: "MaterialInventory.view.Filter", key2: "Display only items not inventoried", value: "Nur nicht inventarisierte Objekte anzeigen"},
        {key1: "MaterialInventory.view.Filter", key2: "GHS Product Identifier", value: "GHS Produkt-ID"},
        {key1: "MaterialInventory.view.Filter", key2: "Last Edited By", value: "Zuletzt bearbeitet von"},
        {key1: "MaterialInventory.view.Filter", key2: "Manufacturer", value: "Hersteller"},
        {key1: "MaterialInventory.view.Filter", key2: "No", value: "Nein"},
        {key1: "MaterialInventory.view.Filter", key2: "Product Name", value: "Produktname"},
        {key1: "MaterialInventory.view.Filter", key2: "Set Filter", value: "Filter einstellen"},
        {key1: "MaterialInventory.view.Filter", key2: "Yes", value: "Ja"},
        {key1: "MaterialInventory.view.Main", key2: "Apps", value: "Apps"},
        {key1: "MaterialInventory.view.Main", key2: "Plan Types", value: "Plantypen"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Comments", value: "Bemerkungen"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Category", value: "Behälterkategorie"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Type", value: "Sicherheitsbehältertyp"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Custodian", value: "Verwalter"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Date Last Updated:", value: "Zuletzt aktualisiert am:"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Description", value: "Beschreibung"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Edit Material", value: "Material bearbeiten"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "GHS Product Identifier", value: "GHS Produkt-ID"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Manufacturer", value: "Hersteller"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Pressure", value: "Druck"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Product Name", value: "Produktname"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Products", value: "Produkte"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Quantity", value: "Menge"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Review Material", value: "Material überprüfen"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Type", value: "Typ"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Unit", value: "Einheit"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Add Material", value: "Material hinzufügen"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Hazmat", value: "Gef.stoff"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Inventory", value: "Bestandsliste"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Location", value: "Standort"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Materials", value: "Materialien"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Product Name", value: "Produktname"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Review", value: "Überprüfen"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Status", value: "Status"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building:", value: "Gebäude:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor Code", value: "Geschoss"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor:", value: "Geschoss:"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room Code", value: "Raum"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room:", value: "Räume"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Select Aisle Location", value: "Gangstandort auswählen"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Bin:", value: "Lagercontainer:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building:", value: "Gebäude:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet Code", value: "Schrankkurzzeichen"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet:", value: "Schrank:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor Code", value: "Geschoss"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor:", value: "Geschoss:"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room Code", value: "Raum"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room:", value: "Räume"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Select Bin Location", value: "Lagercontainerstandort auswählen"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf Code", value: "Regalkurzzeichen"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf:", value: "Regal:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building:", value: "Gebäude:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet Code", value: "Schrankkurzzeichen"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet:", value: "Schrank:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor Code", value: "Geschoss"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor:", value: "Geschoss:"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room Code", value: "Raum"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room:", value: "Räume"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Select Cabinet Location", value: "Schrankstandort auswählen"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building:", value: "Gebäude:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor Code", value: "Geschoss"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor:", value: "Geschoss:"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room Code", value: "Raum"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room:", value: "Räume"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Select Room Location", value: "Raumstandort auswählen"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle Code", value: "Gangkurzzeichen"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle:", value: "Gang:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building:", value: "Gebäude:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet Code", value: "Schrankkurzzeichen"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet:", value: "Schrank:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor Code", value: "Geschoss"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor:", value: "Geschoss:"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room Code", value: "Raum"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room:", value: "Räume"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Select Shelf Location", value: "Regalstandort auswählen"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf Code", value: "Regalkurzzeichen"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf:", value: "Regal:"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Aisles", value: "Gänge"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Materials in Room", value: "Materialien in Raum"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "No aisles identified.", value: "Keine Gänge ermittelt."},
        {key1: "MaterialInventory.view.space.BinList", key2: "Bins", value: "Lagercontainer"},
        {key1: "MaterialInventory.view.space.BinList", key2: "Materials on Shelf", value: "Materialien in Regal"},
        {key1: "MaterialInventory.view.space.BinList", key2: "No bins identified.", value: "Keine Behälter ermittelt."},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "Materials at Site", value: "Materialien am Standort"},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "No buildings identified.", value: "Keine Gebäude ermittelt."},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Cabinets", value: "Schränke"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Materials in Aisle", value: "Materialien in Gang"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "No cabinets identified.", value: "Keine Schränke ermittelt."},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Floors", value: "Geschosse"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Materials in Building", value: "Materialien in Gebäude"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "No floors identified.", value: "Keine Geschosse ermittelt."},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Room List", value: "Raumliste"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "Materials on Floor", value: "Materialien auf Geschoss"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "No rooms identified.", value: "Keine Räume ermittelt."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Materials in Cabinet", value: "Materialien in Schrank"},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "No shelves identified.", value: "Keine Regale ermittelt."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Shelves", value: "Regale"},
        {key1: "MaterialInventory.view.space.Site", key2: "Buildings", value: "Gebäude"},
        {key1: "MaterialInventory.view.space.Site", key2: "List View", value: "Listenansicht"},
        {key1: "MaterialInventory.view.space.Site", key2: "Site Plan", value: "Standortplan"},
        {key1: "MaterialInventory.view.space.SiteList", key2: "No sites identified.", value: "Keine Standorte ermittelt."},
        {key1: "MaterialInventory.view.space.SiteList", key2: "Sites", value: "Standorte"},
        {key1: "MaterialInventory.view.space.SiteMap", key2: "Site Plan is not available", value: "Standortplan ist nicht verfügbar"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Möchten Sie dieses Objekt wirklich löschen?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Geben Sie den Textfeldinhalt ein:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Grundriss nicht verfügbar"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Kopieren"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Einfügen"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Neu laden"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Bild speichern"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Möchten Sie dieses Objekt wirklich löschen?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Bearbeiten"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Für Redline ist kein Geschossplan verfügbar."},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Datum veröffentlichen"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Standortkarten"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Redline"},
        {key1: "Space.model.SpaceSurvey", key2: " can only consist of alpha-numeric characters.", value: "kann nur aus alphanumerischen Zeichen bestehen."},
        {key1: "Space.SpaceDownload", key2: "Download Floor Plans", value: "Grundrisse herunterladen"},
        {key1: "Space.SpaceDownload", key2: "Downloaded plans for {0} floors.", value: "Heruntergeladene Grundrisse für {0} Geschosse."},
        {key1: "Space.SpaceDownload", key2: "Downloading Site Maps", value: "Standortkarten werden heruntergeladen"},
        {key1: "Space.SpaceDownload", key2: "Floor Plan download was cancelled.", value: "Herunterladen des Grundrisses wurde abgebrochen."},
        {key1: "Space.SpaceDownload", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Space.SpaceDownload", key2: "Loading Plans for Floor {0} of {1}", value: "Pläne für Geschoss {0} von {1} laden"},
        {key1: "Space.SpaceDownload", key2: "No active plan types found.", value: "Keine aktiven Plantypen gefunden."},
        {key1: "Space.SpaceDownload", key2: "No Floor Plans available to download", value: "Kein Grundrissplan zum Download verfügbar"},
        {key1: "Space.SpaceDownload", key2: "No plan types found", value: "Keine Plantypen gefunden"},
        {key1: "Space.SpaceDownload", key2: "Not all {0} floors of the selected buildings have floor plans available.", value: "Für nicht alle {0} Geschosse der ausgewählten Gebäude sind Grundrisse verfügbar."},
        {key1: "Space.SpaceDownload", key2: "Use the {0} icon to download your list of floors and buildings before downloading floor plans.", value: "Verwenden Sie das Symbol {0}, um Ihre Geschoss- und Gebäudeliste herunterzuladen, bevor Sie Grundrisse herunterladen."},
        {key1: "Space.SpaceDownload", key2: "You are going to download plans for {0} floors and this action may take some time. Proceed?", value: "Sie beginnen mit dem Download von {0} Grundrissen. Diese Aktion kann einige Zeit in Anspruch nehmen. Fortfahren?"},
        {key1: "Space.SpaceFloorPlan", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Space.SpaceFloorPlan", key2: "Rooms", value: "Räume"},
        {key1: "Space.SpaceFloorPlan", key2: "The Plan Type data is not loaded.", value: "Die Plantypdaten wurden nicht geladen."},
        {key1: "Space.SpaceSurvey", key2: "There is no Room data available for the selected Room.<br>Tap the {0} icon and select \\'Add to Survey\\' to update the Room data.", value: "Für den ausgewählten Raum sind keine Raumdaten verfügbar.<br>Tippen Sie auf das {0}-Symbol und wählen Sie \\'Zu Erfassung hinzufügen\\' aus, um die Raumdaten zu aktualisieren."},
        {key1: "Space.SpaceSurvey", key2: "There is not an active survey for this floor.<br>To initiate a survey, tap the {0} icon and select \\'Start Survey\\'.", value: "Für dieses Geschoss gibt es keine aktive Erfassung.<br>Um eine Erfassung einzuleiten, tippen Sie auf das {0}-Symbol und wählen Sie \\'Erfassen\\' aus."},
        {key1: "Space.store.Buildings", key2: "Buildings", value: "Gebäude"},
        {key1: "Space.store.DownloadActions", key2: "Download Floor Plans", value: "Grundrisse herunterladen"},
        {key1: "Space.store.Floors", key2: "Floors", value: "Geschosse"},
        {key1: "Space.store.RoomSurveys", key2: "Rooms", value: "Räume"},
        {key1: "Space.store.Sites", key2: "Buildings Without a Site Assigned", value: "Gebäude ohne zugewiesenen Standort"},
        {key1: "Space.store.Sites", key2: "Sites", value: "Standorte"},
        {key1: "Space.store.SpaceSurveys", key2: "Surveys", value: "Inventaraufnahmen"},
        {key1: "Space.store.SurveyActions", key2: "Add to Survey", value: "Zu Erfassung hinzufügen"},
        {key1: "Space.store.SurveyActions", key2: "Close Survey", value: "Erfassung schließen"},
        {key1: "Space.store.SurveyActions", key2: "Complete Survey", value: "Erfassung abschließen"},
        {key1: "Space.store.SurveyActions", key2: "Start Survey", value: "Erfassung starten"},
        {key1: "Space.store.UserGroups", key2: "User Groups", value: "Benutzergruppen"},
        {key1: "Space.view.BuildingList", key2: "No buildings identified.", value: "Keine Gebäude ermittelt."},
        {key1: "Space.view.FloorList", key2: "Floors", value: "Geschosse"},
        {key1: "Space.view.FloorList", key2: "No floors identified.", value: "Keine Geschosse ermittelt."},
        {key1: "Space.view.FloorList", key2: "Search Floors", value: "Geschosse suchen"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plan", value: "Grundriss"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plans", value: "Grundrisse"},
        {key1: "Space.view.FloorPlan", key2: "Room List", value: "Raumliste"},
        {key1: "Space.view.Main", key2: "Apps", value: "Apps"},
        {key1: "Space.view.Main", key2: "Plan Types", value: "Plantypen"},
        {key1: "Space.view.report.Configuration", key2: "Address 1", value: "Adresse 1"},
        {key1: "Space.view.report.Configuration", key2: "Address 2", value: "Adresse 2"},
        {key1: "Space.view.report.Configuration", key2: "Building", value: "Gebäude"},
        {key1: "Space.view.report.Configuration", key2: "Building Code", value: "Kurzzeichen Gebäude"},
        {key1: "Space.view.report.Configuration", key2: "City", value: "Stadt"},
        {key1: "Space.view.report.Configuration", key2: "Country", value: "Land"},
        {key1: "Space.view.report.Configuration", key2: "Department", value: "Abteilung"},
        {key1: "Space.view.report.Configuration", key2: "Division", value: "Bereich"},
        {key1: "Space.view.report.Configuration", key2: "Email", value: "E-Mail"},
        {key1: "Space.view.report.Configuration", key2: "Employee ID", value: "Mitarbeiter-ID"},
        {key1: "Space.view.report.Configuration", key2: "Employee Information", value: "Personaldaten"},
        {key1: "Space.view.report.Configuration", key2: "First Name", value: "Vorname"},
        {key1: "Space.view.report.Configuration", key2: "Floor", value: "Geschoss"},
        {key1: "Space.view.report.Configuration", key2: "Floor Name", value: "Geschossname"},
        {key1: "Space.view.report.Configuration", key2: "Last Name", value: "Nachname"},
        {key1: "Space.view.report.Configuration", key2: "Phone", value: "Telefon"},
        {key1: "Space.view.report.Configuration", key2: "Room", value: "Raum"},
        {key1: "Space.view.report.Configuration", key2: "Room Area", value: "Raumfläche"},
        {key1: "Space.view.report.Configuration", key2: "Room Category", value: "Raumkategorie"},
        {key1: "Space.view.report.Configuration", key2: "Room Information", value: "Raumdaten"},
        {key1: "Space.view.report.Configuration", key2: "Room Name", value: "Raumname"},
        {key1: "Space.view.report.Configuration", key2: "Room Phone", value: "Raumtelefon"},
        {key1: "Space.view.report.Configuration", key2: "Room Standard", value: "Standardraum"},
        {key1: "Space.view.report.Configuration", key2: "Room Type", value: "Raumtyp"},
        {key1: "Space.view.report.Configuration", key2: "Site Code", value: "Standortcode"},
        {key1: "Space.view.report.Configuration", key2: "State", value: "Bundesland/Kanton"},
        {key1: "Space.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} Für das ausgewählte Geschoss sind keine Erfassungselemente verfügbar.<br> Tippen Sie auf das {1}-Symbol und wählen Sie \\'Erfassung starten\\' oder \\'Zu Erfassung hinzufügen\\', um Erfassungselemente für dieses Geschoss zu generieren.{2}"},
        {key1: "Space.view.Site", key2: "Buildings", value: "Gebäude"},
        {key1: "Space.view.Site", key2: "List View", value: "Listenansicht"},
        {key1: "Space.view.Site", key2: "Site Plan", value: "Standortplan"},
        {key1: "Space.view.SiteList", key2: "No sites identified.", value: "Keine Standorte ermittelt."},
        {key1: "Space.view.SiteList", key2: "Sites", value: "Standorte"},
        {key1: "Space.view.StartSurvey", key2: "Start", value: "Start"},
        {key1: "Space.view.StartSurvey", key2: "Start Survey", value: "Erfassung starten"},
        {key1: "Space.view.StartSurvey", key2: "Survey Code", value: "Kurzzeichen Erfassung"},
        {key1: "Space.view.StartSurvey", key2: "Survey Name", value: "Erfassungsname"},
        {key1: "Space.view.StartSurvey", key2: "Surveyor", value: "Prüfer"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Bezeichnung des Gebäudes"},
    ]
};
