var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.fr = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Acceptez la demande du navigateur pour stocker les données sur votre ordinateur local et actualiser la page."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Erreur lors du chargement du fichier de configuration."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "Le contrôleur « {0} » n'est associé à aucune méthode de lancement. Êtes-vous sûr qu'il s'étend à partir du paramètre Ext.app.Controller ?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Le format de cette valeur est incorrect :"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Cette valeur n’est pas un e-mail valide :"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Cette valeur n’est pas acceptable :"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Cette valeur ne figure pas dans la liste des valeurs acceptables :"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "La longueur de cette valeur est incorrecte :"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Cette valeur doit être présente :"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Joindre"},
        {key1: "Common.control.Camera", key2: "Close", value: "Fermer"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Photo"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Effacer"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Terminé"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Chargement…"},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Veuillez corriger ce qui suit :"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Erreur d’analyse"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Terminé"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Aucune donnée à afficher pour : {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Appliquer"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Pas de {0} à afficher"},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Demander"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Heures"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minutes"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Chargement de l'élément {0} sur {1}"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code Contact"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Prénom"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Nom de Famille"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Nom :"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contact"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code Contact"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Code Département"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Code Département :"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Départements"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Code Division"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Code Division :"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Division"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Code Division"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Division :"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisions"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "Adresse Electronique"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail :"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Employé"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Code Employé"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Standard d’Employé"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Code Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Standard Equipement"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Equipement :"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Standard Equipement"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Etage :"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Etages"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuler"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type de Problème"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Propriétés"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code Propriété"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Propriété :"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Bâtiment/Étage :"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code Pièce"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Pièce :"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Pièces"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Catégorie :"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Catégories de Pièces"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Bâtiment"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Code Bâtiment :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Bâtiment :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Etage"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code Etage"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Etage :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Etage :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code Pièce"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Pièce :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Pièce :"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Pièces"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Standard de Pièce"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standard :"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Catégorie :"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Description"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Description :"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type de Pièce"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Types de Pièces"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type :"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code :"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Code site"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site :"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Aucune recherche précédente n’a été enregistrée."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Effacer"},
        {key1: "Common.control.Signature", key2: "Done", value: "Terminé"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Signature"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Une configuration de réf. mainView doit être fournie lors de l'extension de la classe Common.controller.NavigationController"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuler"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Sauvegarder"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Voulez-vous continuer ?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "L’erreur s’est produite lors de la désinscription de l’appareil. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "La déconnexion ne supprime pas vos données d’application.<br>Il vous faudra réinscrire l’appareil pour accéder aux applications."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Enregistrement"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Echec de l'enregistrement"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "Le service d'enregistrement des appareils n'est pas disponible. Il se peut que les services mobiles ne soient pas activés dans Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Le modèle nommé [{0}] n'existe pas."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "La lecture de codes-barres n'est pas disponible."},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Autorisation d’accès aux informations d’emplacement refusée"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "La position n’est pas disponible."},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Délai d’expiration de position"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Erreur de poste inconnu"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Une erreur s’est produite pendant l’affichage du document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Affichage du document"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Téléchargement des documents"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "La fonction n’est pas disponible dans l’environnement de bureau."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Le fichier n’existe pas."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Le fichier {0} ne peut pas être affiché sur cet appareil."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Le fichier {0} ne peut pas être affiché en mode Bureau."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Suppression du document"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Champ modifié : {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Entrée"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "L’entrée du champ {0} est limitée à {1} caractères"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuler"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Effacer"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Copier"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Terminé"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Erreur"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "NON"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Coller"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Recharger"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Nom de Pièce"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "nom de pièces"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Enregistrer l’image"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Evaluation"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "OUI"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Chargement supplémentaire..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Pas d'autres enregistrements"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Chargement supplémentaire..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Pas d'autres enregistrements"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Cette application a été mise à jour à la dernière version. Rechargement de l’application."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Erreur lors du chargement des services réseau. Il se peut que la connexion réseau soit lente ou indisponible."},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Aucune connexion réseau disponible"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Aucune donnée reçue du serveur"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Délai"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Erreur inconnue"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Erreur lors de l'enregistrement de l'appareil"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Erreur lors de la récupération des informations d'utilisateur."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Erreur lors de la définition des paramètres régionaux de la session."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Erreur lors du démarrage de la session d'utilisateur."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Erreur d'authentification unique"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Erreur lors de la récupération de TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "L’appareil n’est pas inscrit."},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Flux d'opérations en JSON. Les objets de date ne peunvent pas être triés à l'aide de règles de workflow."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Règle de Workflow exécutée"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Echec de la règle de workflow :"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "Préférences d’application"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Bâtiments"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types de causes"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contacts"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Techniciens"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Départements"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisions"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Employés"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Standards d’Employés"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Equipement"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Standards d’équipement"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Etages"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Surfaces touchées"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Catégories de blessure"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Types d’accident"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Groupes de types de plan"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Types de plan"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Types de problèmes"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projets"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Propriétés"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Erreur de base de données :"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Aucune modification de table de base de données appliquée. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Aucune mise à jour de la valeur par défaut du champ : [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Mettre à jour la valeur par défaut : champ [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Erreur du proxy Sqlite"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Erreur du proxy Sqlite pendant l’opération de création"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Erreur du proxy Sqlite pendant l’opération de destruction"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Erreur du proxy Sqlite pendant l’opération de lecture"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Erreur du proxy Sqlite pendant l’opération de mise à jour"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Erreur d’ouverture de la base de données : {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Erreur de base de données [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Erreur de base de données dans le proxy SqliteView."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView est en lecture seule et ne prend pas en charge la suppression d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView est en lecture seule et ne prend pas en charge la mise à jour d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView est en lecture seule et ne prend pas en charge la création d'enregistrements"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "La base de données ne contient pas les définitions de tables requises pour SqliteView. {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Types de réparations"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Catégories de Pièces"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Pièces"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Standards de Pièces"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Types de Pièces"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Utilisations des Pièces"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "fichier_non_disponible"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchronisation"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Téléchargement"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Erreur"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "La valeur d'entrée ne peut pas être convertie en type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "Les préférences de l'application n'ont pas été chargées"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Exécution en mode navigateur Accès au système de fichiers désactivé"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Exécution dans Chrome ou en vue Web. Accès au système de fichiers activé"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "L'accès au fichier a été interrompu"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Le fichier existe déjà"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Erreur de codage du fichier"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Erreur du fichier"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Le fichier est dans un état non valide"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "La modification du fichier n'est pas autorisée"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Quota de fichiers dépassé"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Erreur de sécurité du fichier"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Erreur de disparité de type de fichier"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Fichier introuvable"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Fichier illisible"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Erreur de modification de fichier non valide"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Aucune connexion réseau disponible"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Réseau inaccessible"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Téléchargement des données fondamentales"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Erreur"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Le magasin des préférences d'application n'est pas chargé. Impossible de récupérer les préférences"},
        {key1: "Common.util.Units", key2: "ft", value: "m"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "pi2"},
        {key1: "Common.util.Units", key2: "sq m", value: "m2"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "Les informations du profil d'utilisateur ne sont pas disponibles. Veuillez synchroniser pour récupérer les données du profil d'utilisateur."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Supprimer à la synchronisation"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Afficher"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documents"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Aucun document disponible."},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} de {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 sur x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "Le nom de la classe Model associée à cette vue doit être fourni dans la propriété model"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "L'ID de magasin de la classe de la classe Store associée à cette vue doit être fourni dans la propriété storeId"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Effacer"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filtrer les données"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Précédent"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Sauvegarder"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Champ"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifiant"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Taille (octets)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Messages de synchronisation"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Table"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "Les valeurs de champ de Web Central énumérées ci-après n'ont pas été écrites dans la base de données cliente, car la taille des données dépasse la limite de la base de données."},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Définir le Filtre"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Date Updated", value: "Date de mise à jour"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Edited By", value: "Dernière édition par"},
        {key1: "MaterialInventory.control.FormHeader", key2: "Last Inventoried", value: "Dernier inventaire"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle", value: "Allée"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisle Code:", value: "Code Allée :"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Aisles", value: "Allées"},
        {key1: "MaterialInventory.control.prompt.Aisle", key2: "Name", value: "Nom"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Aisle/Cabinet/Shelf:", value: "Allée/Armoire/Etagère :"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code", value: "Code Bac"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bin Code:", value: "Code Bac :"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Bins", value: "Bacs"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Cabinet Code", value: "Code Armoire"},
        {key1: "MaterialInventory.control.prompt.Bin", key2: "Shelf Code", value: "Code Etagère"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Aisle Code:", value: "Code Allée :"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinet Code", value: "Code Armoire"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "cabinet Code:", value: "code Armoire :"},
        {key1: "MaterialInventory.control.prompt.Cabinet", key2: "Cabinets", value: "Armoires :"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Building/Floor:", value: "Bâtiment/Étage :"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Floor Code", value: "Code Etage"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code", value: "Code Pièce"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Room Code:", value: "Pièce :"},
        {key1: "MaterialInventory.control.prompt.Room", key2: "Rooms", value: "Pièces"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Aisle/Cabinet:", value: "Allée/Armoire :"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Cabinet Code", value: "Code Armoire"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code", value: "Code Etagère"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelf Code:", value: "Code Etagère :"},
        {key1: "MaterialInventory.control.prompt.Shelf", key2: "Shelves", value: "Etagères"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Loading...", value: "Chargement…"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No document available for selected location.", value: "Aucun document disponible pour l’emplacement sélectionné."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floor plans available.", value: "Aucun plan d’étage disponible."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "No floors available.", value: "Aucun étage disponible."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Not all floor plans were downloaded.", value: "Les plans d’étage n’ont pas tous été téléchargés."},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "Sync Material Locations", value: "Synchroniser les emplacements des matières"},
        {key1: "MaterialInventory.controller.MaterialInventorySync", key2: "There are no buildings in the selected site.", value: "Il n’y a aucun bâtiment dans le site sélectionné."},
        {key1: "MaterialInventory.controller.Materials", key2: "Cancel", value: "Annuler"},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is not registered.", value: "Le conteneur n’est pas enregistré."},
        {key1: "MaterialInventory.controller.Materials", key2: "Container is registered multiple times.", value: "Le conteneur est enregistré plusieurs fois."},
        {key1: "MaterialInventory.controller.Materials", key2: "Document unavailable", value: "Document non disponible"},
        {key1: "MaterialInventory.controller.Materials", key2: "Downloading Document", value: "Téléchargement des documents"},
        {key1: "MaterialInventory.controller.Materials", key2: "Error", value: "Erreur"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory", value: "Inventaire"},
        {key1: "MaterialInventory.controller.Materials", key2: "Inventory Start Date cannot be in the future", value: "La date de début de l’inventaire ne peut pas être dans le futur."},
        {key1: "MaterialInventory.controller.Materials", key2: "The container you have scanned is in a different location: {0}. Do you want to update its location as your current location: {1} or do you want to cancel the scan and navigate to a different location?", value: "Le conteneur que vous avez scanné se trouve à un autre emplacement : {0}. Voulez-vous mettre à jour son emplacement comme votre localisation actuelle : {1} ou annuler la lecture et accéder à un autre emplacement ?"},
        {key1: "MaterialInventory.controller.Materials", key2: "This action will save your changes on the server. If you reset the Inventory Start Date then the app will no longer highlight inventoried items. Are you sure you want to clear the Inventory Start Date?", value: "Cette action sauvegarde vos modifications sur le serveur. Si vous réinitialisez la date de début de l’inventaire, l’application cessera de mettre en surbrillance les éléments inventoriés. Voulez-vous vraiment effacer la date de début de l’inventaire ?"},
        {key1: "MaterialInventory.controller.Materials", key2: "Update location", value: "Mettre à jour l’emplacement"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Aisle with code \\'{0}\\' not found.", value: "L’allée dont le code est \\'{0}\\' est introuvable."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Bin with code \\'{0}\\' not found.", value: "Le bac dont le code est \\'{0}\\' est introuvable."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Cabinet with code \\'{0}\\' not found.", value: "L’armoire dont le code est \\'{0}\\' est introuvable."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Close", value: "Fermer"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Floor Plan", value: "Chargement du plan d’étage"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Loading Site Map", value: "Chargement du plan du site"},
        {key1: "MaterialInventory.controller.Navigation", key2: "Room with code \\'{0}\\' not found.", value: "La pièce dont le code est \\'{0}\\' est introuvable."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Selected building is not registered in the current site.", value: "Le bâtiment sélectionné n’est pas enregistré dans site actuel."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Shelf with code \\'{0}\\' not found.", value: "L’étagère dont le code est \\'{0}\\' est introuvable."},
        {key1: "MaterialInventory.controller.Navigation", key2: "Updating Lists", value: "Mise à jour des listes"},
        {key1: "MaterialInventory.model.MaterialLocation", key2: "{0} cannot be greater than {1}.", value: "{0} ne peut pas être supérieur à {1}."},
        {key1: "MaterialInventory.store.Actions", key2: "Download Documents", value: "Télécharger les documents"},
        {key1: "MaterialInventory.store.MaterialData", key2: "Material Data", value: "Données sur les matières"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Locations", value: "Localisations"},
        {key1: "MaterialInventory.store.MaterialMsds", key2: "Documents", value: "Documents"},
        {key1: "MaterialInventory.store.prompt.ContainerCategories", key2: "Container Categories", value: "Catégories de contenant"},
        {key1: "MaterialInventory.store.prompt.ContainerTypes", key2: "Container Types", value: "Types de contenant"},
        {key1: "MaterialInventory.store.prompt.MaterialChemicals", key2: "Chemicals", value: "Produits Chimiques"},
        {key1: "MaterialInventory.store.prompt.MaterialConstituents", key2: "Constituents", value: "Composés"},
        {key1: "MaterialInventory.store.MaterialEmployees", key2: "Employees", value: "Employés"},
        {key1: "MaterialInventory.store.prompt.MaterialUnits", key2: "Material Units", value: "Unités de Mesure"},
        {key1: "MaterialInventory.store.prompt.PressureUnits", key2: "Pressure Units", value: "Unités de pression"},
        {key1: "MaterialInventory.store.MaterialAisles", key2: "Aisles", value: "Allées"},
        {key1: "MaterialInventory.store.MaterialBins", key2: "Bins", value: "Bacs"},
        {key1: "MaterialInventory.store.MaterialBuildings", key2: "Buildings", value: "Bâtiments"},
        {key1: "MaterialInventory.store.MaterialCabinets", key2: "Cabinets", value: "Armoires :"},
        {key1: "MaterialInventory.store.space.MaterialFloors", key2: "Floors", value: "Etages"},
        {key1: "MaterialInventory.store.MaterialLocations", key2: "Rooms", value: "Pièces"},
        {key1: "MaterialInventory.store.MaterialShelves", key2: "Shelves", value: "Etagères"},
        {key1: "MaterialInventory.store.MaterialSites", key2: "Sites", value: "Sites"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Cancel", value: "Annuler"},
        {key1: "MaterialInventory.view.CalendarView", key2: "Inventory Start Date", value: "Date de début de l’inventaire"},
        {key1: "MaterialInventory.view.Filter", key2: "All", value: "Toutes"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Category", value: "Catégorie de contenant"},
        {key1: "MaterialInventory.view.Filter", key2: "Container Type", value: "Type de contenant"},
        {key1: "MaterialInventory.view.Filter", key2: "Custodian", value: "Gardien"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From", value: "Date de dernier inventaire Du"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory From should not be greater than Date Last Inventory To.", value: "Date de dernier inventaire Du ne doit pas être postérieure à Date de dernier inventaire Au."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Last Inventory To", value: "Date de dernier inventaire Au"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From", value: "Date de mise à jour Du"},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated From should not be greater than Date Updated To.", value: "Date de mise à jour Du ne doit pas être postérieure à Date de mise à jour Au."},
        {key1: "MaterialInventory.view.Filter", key2: "Date Updated To", value: "Date de mise à jour"},
        {key1: "MaterialInventory.view.Filter", key2: "Description", value: "Description"},
        {key1: "MaterialInventory.view.Filter", key2: "Display only items not inventoried", value: "Afficher uniquement les éléments non inventoriés"},
        {key1: "MaterialInventory.view.Filter", key2: "GHS Product Identifier", value: "Identifiant produit SGH"},
        {key1: "MaterialInventory.view.Filter", key2: "Last Edited By", value: "Dernière édition par"},
        {key1: "MaterialInventory.view.Filter", key2: "Manufacturer", value: "Fabricant"},
        {key1: "MaterialInventory.view.Filter", key2: "No", value: "NON"},
        {key1: "MaterialInventory.view.Filter", key2: "Product Name", value: "Nom du produit"},
        {key1: "MaterialInventory.view.Filter", key2: "Set Filter", value: "Définir le Filtre"},
        {key1: "MaterialInventory.view.Filter", key2: "Yes", value: "OUI"},
        {key1: "MaterialInventory.view.Main", key2: "Apps", value: "Applications"},
        {key1: "MaterialInventory.view.Main", key2: "Plan Types", value: "Types de plan"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Comments", value: "Commentaires"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Category", value: "Catégorie de contenant"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Container Type", value: "Type de contenant"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Custodian", value: "Gardien"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Date Last Updated:", value: "Date de dernière mise à jour :"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Description", value: "Description"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Edit Material", value: "Editer la matière"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "GHS Product Identifier", value: "Identifiant produit SGH"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Manufacturer", value: "Fabricant"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Pressure", value: "Pression"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Product Name", value: "Nom du produit"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Products", value: "Produits"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Quantity", value: "Quantité"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Review Material", value: "Examiner la matière"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Type", value: "Type"},
        {key1: "MaterialInventory.view.MaterialForm", key2: "Unit", value: "Unité"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Add Material", value: "Ajouter un matériau"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Hazmat", value: "Matières dangeureuses"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Inventory", value: "Inventaire"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Location", value: "Localisation"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Materials", value: "Matières"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Product Name", value: "Nom du produit"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Review", value: "Examiner"},
        {key1: "MaterialInventory.view.MaterialList", key2: "Status", value: "Statut"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Aisle:", value: "Allée :"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Building:", value: "Bâtiment :"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor Code", value: "Code Etage"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Floor:", value: "Etage :"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room Code", value: "Code Pièce"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Room:", value: "Pièce :"},
        {key1: "MaterialInventory.view.AislePromptList", key2: "Select Aisle Location", value: "Sélectionner un emplacement d’allée"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Aisle:", value: "Allée :"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Bin:", value: "Bac :"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Building:", value: "Bâtiment :"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet Code", value: "Code Armoire"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Cabinet:", value: "Armoire :"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor Code", value: "Code Etage"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Floor:", value: "Etage :"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room Code", value: "Code Pièce"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Room:", value: "Pièce :"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Select Bin Location", value: "Sélectionner l’emplacement de bac"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf Code", value: "Code Etagère"},
        {key1: "MaterialInventory.view.BinPromptList", key2: "Shelf:", value: "Etagère :"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Aisle:", value: "Allée :"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Building:", value: "Bâtiment :"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet Code", value: "Code Armoire"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Cabinet:", value: "Armoire :"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor Code", value: "Code Etage"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Floor:", value: "Etage :"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room Code", value: "Code Pièce"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Room:", value: "Pièce :"},
        {key1: "MaterialInventory.view.CabinetPromptList", key2: "Select Cabinet Location", value: "Sélectionner l’emplacement d’armoire"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Building:", value: "Bâtiment :"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor Code", value: "Code Etage"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Floor:", value: "Etage :"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room Code", value: "Code Pièce"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Room:", value: "Pièce :"},
        {key1: "MaterialInventory.view.RoomPromptList", key2: "Select Room Location", value: "Sélectionner un emplacement de pièce"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle Code", value: "Code Allée"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Aisle:", value: "Allée :"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Building:", value: "Bâtiment :"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet Code", value: "Code Armoire"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Cabinet:", value: "Armoire :"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor Code", value: "Code Etage"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Floor:", value: "Etage :"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room Code", value: "Code Pièce"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Room:", value: "Pièce :"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Select Shelf Location", value: "Sélectionner un emplacement d’étagère"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf Code", value: "Code Etagère"},
        {key1: "MaterialInventory.view.ShelfPromptList", key2: "Shelf:", value: "Etagère :"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Aisles", value: "Allées"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "Materials in Room", value: "Matières dans pièce"},
        {key1: "MaterialInventory.view.space.AisleList", key2: "No aisles identified.", value: "Aucune allée identifiée."},
        {key1: "MaterialInventory.view.space.BinList", key2: "Bins", value: "Bacs"},
        {key1: "MaterialInventory.view.space.BinList", key2: "Materials on Shelf", value: "Matières sur étagère"},
        {key1: "MaterialInventory.view.space.BinList", key2: "No bins identified.", value: "Aucun bac identifié."},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "Materials at Site", value: "Matières sur site"},
        {key1: "MaterialInventory.view.space.BuildingList", key2: "No buildings identified.", value: "Aucun bâtiment identifié."},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Cabinets", value: "Armoires :"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "Materials in Aisle", value: "Matières dans allée"},
        {key1: "MaterialInventory.view.space.CabinetList", key2: "No cabinets identified.", value: "Aucune armoire identifiée."},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Floors", value: "Etages"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "Materials in Building", value: "Matières dans bâtiment"},
        {key1: "MaterialInventory.view.space.FloorList", key2: "No floors identified.", value: "Aucun étage identifié."},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plan", value: "Plans d'étage"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "MaterialInventory.view.space.FloorPlan", key2: "Room List", value: "Liste des Pièces"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "Materials on Floor", value: "Matières à étage"},
        {key1: "MaterialInventory.view.space.RoomList", key2: "No rooms identified.", value: "Aucune pièce identifiée."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Materials in Cabinet", value: "Matières dans armoire"},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "No shelves identified.", value: "Aucune étagère identifiée."},
        {key1: "MaterialInventory.view.space.ShelfList", key2: "Shelves", value: "Etagères"},
        {key1: "MaterialInventory.view.space.Site", key2: "Buildings", value: "Bâtiments"},
        {key1: "MaterialInventory.view.space.Site", key2: "List View", value: "Vue Liste"},
        {key1: "MaterialInventory.view.space.Site", key2: "Site Plan", value: "Plan de site"},
        {key1: "MaterialInventory.view.space.SiteList", key2: "No sites identified.", value: "Aucun site identifié."},
        {key1: "MaterialInventory.view.space.SiteList", key2: "Sites", value: "Sites"},
        {key1: "MaterialInventory.view.space.SiteMap", key2: "Site Plan is not available", value: "Le plan de site n’est pas disponible"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Voulez-vous vraiment supprimer cet objet ?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Veuillez saisir le contenu de la zone de texte :"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Le plan d'étage n'est pas disponible"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Copier"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Coller"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Recharger"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Enregistrer l’image"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Voulez-vous vraiment supprimer cet élément ?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Editer"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Aucun plan d’étage ne peut être annoté"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Dates de publication"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Plans de sites"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Plans d'étage"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Annotation"},
        {key1: "Space.model.SpaceSurvey", key2: " can only consist of alpha-numeric characters.", value: "ne peut comprendre que des caractères alphanumériques."},
        {key1: "Space.SpaceDownload", key2: "Download Floor Plans", value: "Télécharger des plans d'étage"},
        {key1: "Space.SpaceDownload", key2: "Downloaded plans for {0} floors.", value: "Plans téléchargés pour {0} étages."},
        {key1: "Space.SpaceDownload", key2: "Downloading Site Maps", value: "Téléchargement des plans du site"},
        {key1: "Space.SpaceDownload", key2: "Floor Plan download was cancelled.", value: "Le téléchargement des plans d’étage a été annulé."},
        {key1: "Space.SpaceDownload", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "Space.SpaceDownload", key2: "Loading Plans for Floor {0} of {1}", value: "Chargement des plans pour l’étage {0} sur {1}"},
        {key1: "Space.SpaceDownload", key2: "No active plan types found.", value: "Aucun type de plan actif trouvé."},
        {key1: "Space.SpaceDownload", key2: "No Floor Plans available to download", value: "Aucun plan d’étage n’est disponible à télécharger."},
        {key1: "Space.SpaceDownload", key2: "No plan types found", value: "Aucun type de plan trouvé."},
        {key1: "Space.SpaceDownload", key2: "Not all {0} floors of the selected buildings have floor plans available.", value: "Les {0} étages des bâtiments sélectionnés n’ont pas tous de plans d’étage de disponible."},
        {key1: "Space.SpaceDownload", key2: "Use the {0} icon to download your list of floors and buildings before downloading floor plans.", value: "Utilisez l’icône {0} pour télécharger votre liste d’étages et de bâtiments avant de télécharger des plans d’étage."},
        {key1: "Space.SpaceDownload", key2: "You are going to download plans for {0} floors and this action may take some time. Proceed?", value: "Vous êtes sur le point de télécharger les plans de {0} étages et cette action peut prendre un certain temps. Continuer ?"},
        {key1: "Space.SpaceFloorPlan", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "Space.SpaceFloorPlan", key2: "Rooms", value: "Pièces"},
        {key1: "Space.SpaceFloorPlan", key2: "The Plan Type data is not loaded.", value: "Les données du type de plan ne sont pas chargées."},
        {key1: "Space.SpaceSurvey", key2: "There is no Room data available for the selected Room.<br>Tap the {0} icon and select \\'Add to Survey\\' to update the Room data.", value: "Il n’y a aucune donnée de pièce disponible pour la pièce sélectionnée.<br>Appuyez sur l’icône {0} et sélectionnez \\'Ajouter au relevé\\' pour mettre à jour les données de pièce."},
        {key1: "Space.SpaceSurvey", key2: "There is not an active survey for this floor.<br>To initiate a survey, tap the {0} icon and select \\'Start Survey\\'.", value: "Il n’y a aucun relevé actif pour cet étage.<br>Pour démarrer un relevé, appuyez sur l’icône {0} et \\'Démarrer le relevé\\'."},
        {key1: "Space.store.Buildings", key2: "Buildings", value: "Bâtiments"},
        {key1: "Space.store.DownloadActions", key2: "Download Floor Plans", value: "Télécharger des plans d'étage"},
        {key1: "Space.store.Floors", key2: "Floors", value: "Etages"},
        {key1: "Space.store.RoomSurveys", key2: "Rooms", value: "Pièces"},
        {key1: "Space.store.Sites", key2: "Buildings Without a Site Assigned", value: "Bâtiments sans site affecté"},
        {key1: "Space.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Space.store.SpaceSurveys", key2: "Surveys", value: "Relevés"},
        {key1: "Space.store.SurveyActions", key2: "Add to Survey", value: "Ajouter au relevé"},
        {key1: "Space.store.SurveyActions", key2: "Close Survey", value: "Fermer le relevé"},
        {key1: "Space.store.SurveyActions", key2: "Complete Survey", value: "Terminer le relevé"},
        {key1: "Space.store.SurveyActions", key2: "Start Survey", value: "Démarrer le relevé"},
        {key1: "Space.store.UserGroups", key2: "User Groups", value: "Groupes d’utilisateurs"},
        {key1: "Space.view.BuildingList", key2: "No buildings identified.", value: "Aucun bâtiment identifié."},
        {key1: "Space.view.FloorList", key2: "Floors", value: "Etages"},
        {key1: "Space.view.FloorList", key2: "No floors identified.", value: "Aucun étage identifié."},
        {key1: "Space.view.FloorList", key2: "Search Floors", value: "Rechercher des étages"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plan", value: "Plans d'étage"},
        {key1: "Space.view.FloorPlan", key2: "Floor Plans", value: "Plans d'étage"},
        {key1: "Space.view.FloorPlan", key2: "Room List", value: "Liste des Pièces"},
        {key1: "Space.view.Main", key2: "Apps", value: "Applications"},
        {key1: "Space.view.Main", key2: "Plan Types", value: "Types de plan"},
        {key1: "Space.view.report.Configuration", key2: "Address 1", value: "Adresse 1"},
        {key1: "Space.view.report.Configuration", key2: "Address 2", value: "Adresse 2"},
        {key1: "Space.view.report.Configuration", key2: "Building", value: "Bâtiment"},
        {key1: "Space.view.report.Configuration", key2: "Building Code", value: "Code Bâtiment"},
        {key1: "Space.view.report.Configuration", key2: "City", value: "Ville"},
        {key1: "Space.view.report.Configuration", key2: "Country", value: "Pays"},
        {key1: "Space.view.report.Configuration", key2: "Department", value: "Département"},
        {key1: "Space.view.report.Configuration", key2: "Division", value: "Division"},
        {key1: "Space.view.report.Configuration", key2: "Email", value: "Adresse Electronique"},
        {key1: "Space.view.report.Configuration", key2: "Employee ID", value: "ID Employé"},
        {key1: "Space.view.report.Configuration", key2: "Employee Information", value: "Informations sur les Employés"},
        {key1: "Space.view.report.Configuration", key2: "First Name", value: "Prénom"},
        {key1: "Space.view.report.Configuration", key2: "Floor", value: "Etage"},
        {key1: "Space.view.report.Configuration", key2: "Floor Name", value: "Nom de l’Etage"},
        {key1: "Space.view.report.Configuration", key2: "Last Name", value: "Nom de Famille"},
        {key1: "Space.view.report.Configuration", key2: "Phone", value: "Téléphone"},
        {key1: "Space.view.report.Configuration", key2: "Room", value: "Pièce"},
        {key1: "Space.view.report.Configuration", key2: "Room Area", value: "Surface de la Pièce"},
        {key1: "Space.view.report.Configuration", key2: "Room Category", value: "Catégorie de Pièce"},
        {key1: "Space.view.report.Configuration", key2: "Room Information", value: "Informations sur les Pièces"},
        {key1: "Space.view.report.Configuration", key2: "Room Name", value: "Nom de Pièce"},
        {key1: "Space.view.report.Configuration", key2: "Room Phone", value: "Téléphone de la pièce"},
        {key1: "Space.view.report.Configuration", key2: "Room Standard", value: "Standard de Pièce"},
        {key1: "Space.view.report.Configuration", key2: "Room Type", value: "Type de Pièce"},
        {key1: "Space.view.report.Configuration", key2: "Site Code", value: "Code site"},
        {key1: "Space.view.report.Configuration", key2: "State", value: "Dépt/État"},
        {key1: "Space.view.RoomList", key2: "{0} There are no Survey Items for the selected floor.<br> Tap the {1} icon and select \\'Start Survey\\' or \\'Add to Survey\\' to generate Survey Items for this floor.{2}", value: "{0} Il n’y a aucun élément de relevé pour l’étage sélectionné.<br> Appuyez sur l’icône {1} et sélectionnez \\'Démarrer le relevé\\' ou \\'Ajouter au relevé\\' pour générer des éléments de relevé pour cet étage.{2}"},
        {key1: "Space.view.Site", key2: "Buildings", value: "Bâtiments"},
        {key1: "Space.view.Site", key2: "List View", value: "Vue Liste"},
        {key1: "Space.view.Site", key2: "Site Plan", value: "Plan de site"},
        {key1: "Space.view.SiteList", key2: "No sites identified.", value: "Aucun site identifié."},
        {key1: "Space.view.SiteList", key2: "Sites", value: "Sites"},
        {key1: "Space.view.StartSurvey", key2: "Start", value: "Démarrer"},
        {key1: "Space.view.StartSurvey", key2: "Start Survey", value: "Démarrer le relevé"},
        {key1: "Space.view.StartSurvey", key2: "Survey Code", value: "Code de relevé"},
        {key1: "Space.view.StartSurvey", key2: "Survey Name", value: "Nom du relevé"},
        {key1: "Space.view.StartSurvey", key2: "Surveyor", value: "Agent d’inventaire"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Codes Bâtiment"},
    ]
};
