
package com.archibus.app.solution.common.webservice.employee.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Jan 13 11:18:18 EST 2010
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "InvalidArgumentException", targetNamespace = "http://server.employee.webservice.mycompany.com/")
public class InvalidArgumentException_Exception extends Exception {
    public static final long serialVersionUID = 20100113111818L;
    
    private com.archibus.app.solution.common.webservice.employee.client.InvalidArgumentException invalidArgumentException;

    public InvalidArgumentException_Exception() {
        super();
    }
    
    public InvalidArgumentException_Exception(String message) {
        super(message);
    }
    
    public InvalidArgumentException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentException_Exception(String message, com.archibus.app.solution.common.webservice.employee.client.InvalidArgumentException invalidArgumentException) {
        super(message);
        this.invalidArgumentException = invalidArgumentException;
    }

    public InvalidArgumentException_Exception(String message, com.archibus.app.solution.common.webservice.employee.client.InvalidArgumentException invalidArgumentException, Throwable cause) {
        super(message, cause);
        this.invalidArgumentException = invalidArgumentException;
    }

    public com.archibus.app.solution.common.webservice.employee.client.InvalidArgumentException getFaultInfo() {
        return this.invalidArgumentException;
    }
}
