var Mobile = Mobile || {};

Mobile.language = Mobile.language || {};
Mobile.language.nl = {
    localizedStrings: [
        {key1: "Common.Application", key2: "<br>Accept the browser request to store data on your local computer and refresh the page.", value: "<br>Accepteer het browserverzoek om gegevens op de lokale computer op te slaan en vernieuw de pagina."},
        {key1: "Common.Application", key2: "Error loading the Configuration file.", value: "Fout tijdens laden van configuratiebestand."},
        {key1: "Common.Application", key2: "The controller '{0}' doesn't have a launch method. Are you sure it extends from Ext.app.Controller?", value: "De controller '{0}' heeft geen startmethode. Weet u zeker dat dit een uitbreiding is van Ext.app.Controller?"},
        {key1: "Common.Application", key2: "This value has the wrong format:", value: "Deze waarde heeft de verkeerde notatie:"},
        {key1: "Common.Application", key2: "This value is not a valid email:", value: "Dit is geen geldig e-mailadres:"},
        {key1: "Common.Application", key2: "This value is not an acceptable value:", value: "Dit is geen geldige waarde:"},
        {key1: "Common.Application", key2: "This value is not included in the list of acceptable values:", value: "Deze waarde is niet opgenomen in de lijst met acceptabele waarden:"},
        {key1: "Common.Application", key2: "This value is the wrong length:", value: "Deze waarde heeft de verkeerde lengte:"},
        {key1: "Common.Application", key2: "This value must be present:", value: "Deze waarde moet aanwezig zijn:"},
        {key1: "Common.control.Camera", key2: "Attach", value: "Koppelen"},
        {key1: "Common.control.Camera", key2: "Close", value: "Sluiten"},
        {key1: "Common.control.Camera", key2: "Photo", value: "Foto"},
        {key1: "Common.control.config.TimePicker", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.config.TimePicker", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.config.TimePicker", key2: "Done", value: "Gereed"},
        {key1: "Common.control.DataView", key2: "Loading...", value: "Bezig met laden..."},
        {key1: "Common.control.ErrorPanel", key2: "Please correct the following:", value: "Corrigeer het volgende:"},
        {key1: "Common.control.field.Barcode", key2: "Scan Error", value: "Scanfout"},
        {key1: "Common.control.field.Prompt", key2: "Done", value: "Gereed"},
        {key1: "Common.control.field.Prompt", key2: "No data to display for: {0}", value: "Geen gegevens om weer te geven voor: {0}"},
        {key1: "Common.control.field.TextArea", key2: "Apply", value: "Toepassen"},
        {key1: "Common.control.field.TextArea", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.field.TextPrompt", key2: "No {0} to Display", value: "Geen {0} om weer te geven."},
        {key1: "Common.control.FormHeader", key2: "Request", value: "Aanvraag"},
        {key1: "Common.control.picker.Time", key2: "Hours", value: "Uren"},
        {key1: "Common.control.picker.Time", key2: "Minutes", value: "Minuten"},
        {key1: "Common.control.ProgressBar", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.ProgressBar", key2: "Loading Item {0} of {1}", value: "Item {0} van {1} laden"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingPrompt", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.Building", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Building", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.control.prompt.BuildingFriendlyValues", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Contact", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Contact", key2: "First Name", value: "Voornaam"},
        {key1: "Common.control.prompt.Contact", key2: "Last Name", value: "Achternaam"},
        {key1: "Common.control.prompt.Contact", key2: "Name:", value: "Naam:"},
        {key1: "Common.control.prompt.Site", key2: "Contact", value: "Contactpersoon"},
        {key1: "Common.control.prompt.Site", key2: "Contact Code", value: "Code van contactpersoon"},
        {key1: "Common.control.prompt.Department", key2: "Department Code", value: "Afdelingscode"},
        {key1: "Common.control.prompt.Department", key2: "Department Code:", value: "Afdeling:"},
        {key1: "Common.control.prompt.Department", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.control.prompt.Department", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Department", key2: "Division Code:", value: "Divisiecode:"},
        {key1: "Common.control.prompt.Division", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Division", key2: "Division", value: "Divisie"},
        {key1: "Common.control.prompt.Division", key2: "Division Code", value: "Divisiecode"},
        {key1: "Common.control.prompt.Division", key2: "Division:", value: "Divisie:"},
        {key1: "Common.control.prompt.Division", key2: "Divisions", value: "Divisies"},
        {key1: "Common.control.prompt.Employee", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Employee", key2: "Email", value: "E-mail"},
        {key1: "Common.control.prompt.Employee", key2: "Email:", value: "E-mail:"},
        {key1: "Common.control.prompt.Employee", key2: "Employee", value: "Medewerker"},
        {key1: "Common.control.prompt.Employee", key2: "Employee Code", value: "Personeelscode"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Employee Standard", value: "Personeelsstandaard"},
        {key1: "Common.control.prompt.EmployeeStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Code", value: "Uitrusting"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.Equipment", key2: "Equipment:", value: "Uitrusting:"},
        {key1: "Common.control.prompt.Equipment", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standard", value: "Uitrustingsstandaard"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.control.prompt.EquipmentStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Floor", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.Floor", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Floor", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.FloorFriendlyValues", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.control.prompt.ProblemType", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.control.prompt.ProblemType", key2: "Problem Type", value: "Type probleem"},
        {key1: "Common.control.prompt.Property", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Property", key2: "Property", value: "Vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property Code", value: "Code van vastgoedobject"},
        {key1: "Common.control.prompt.Property", key2: "Property:", value: "Vastgoedobject:"},
        {key1: "Common.control.prompt.Room", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.Room", key2: "Building/Floor:", value: "Gebouw/verdieping:"},
        {key1: "Common.control.prompt.Room", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.Room", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.Room", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.Room", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.control.prompt.RoomCategory", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building", value: "Gebouw"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Building:", value: "Gebouw:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor", value: "Verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code", value: "Code verdieping"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor Code:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Floor:", value: "Verdieping:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room", value: "Ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code", value: "Code ruimte"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room Code:", value: "Code ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Room:", value: "Ruimte:"},
        {key1: "Common.control.prompt.RoomFriendlyValues", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Room Standard", value: "Ruimtestandaard"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standard:", value: "Standaard:"},
        {key1: "Common.control.prompt.RoomStandard", key2: "Standards", value: "Standaards"},
        {key1: "Common.control.prompt.RoomType", key2: "Category:", value: "Categorie:"},
        {key1: "Common.control.prompt.RoomType", key2: "Description", value: "Omschrijving"},
        {key1: "Common.control.prompt.RoomType", key2: "Description:", value: "Omschrijving:"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Category", value: "Ruimtecategorie"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Type", value: "Type ruimte"},
        {key1: "Common.control.prompt.RoomType", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.control.prompt.RoomType", key2: "Type:", value: "Type:"},
        {key1: "Common.control.prompt.Site", key2: "Code:", value: "Code:"},
        {key1: "Common.control.prompt.Site", key2: "Site", value: "Site"},
        {key1: "Common.control.prompt.Site", key2: "Site Code", value: "Vestigingscode"},
        {key1: "Common.control.prompt.Site", key2: "Site:", value: "Site:"},
        {key1: "Common.control.prompt.Site", key2: "Sites", value: "Sites"},
        {key1: "Common.control.Search", key2: "There are no previous searches saved.", value: "Er zijn geen eerdere zoekopdrachten opgeslagen."},
        {key1: "Common.control.Signature", key2: "Clear", value: "Wissen"},
        {key1: "Common.control.Signature", key2: "Done", value: "Gereed"},
        {key1: "Common.control.Signature", key2: "Signature", value: "Handtekening"},
        {key1: "Common.controller.NavigationController", key2: "A mainView ref config must be provided when extending the Common.controller.NavigationController class", value: "Er moet een mainView-referentieconfiguratie worden verstrekt bij het uitbreiden van de Common.controller.NavigationController-klasse"},
        {key1: "Common.controller.NavigationController", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.controller.NavigationController", key2: "Save", value: "Opslaan"},
        {key1: "Common.controller.Registration", key2: "Do you want to continue?", value: "Doorgaan?"},
        {key1: "Common.controller.Registration", key2: "Error occured Un-Registering the device. <br>{0}", value: "Fout bij het ongedaan maken van de apparaatregistratie. <br>{0}"},
        {key1: "Common.controller.Registration", key2: "Logging out does not remove your application data.<br>You will need to re-register the device to access the apps.", value: "Door uit te loggen worden uw toepassingsgegevens niet verwijderd.<br>U moet het apparaat opnieuw registreren om toegang tot de apps te krijgen."},
        {key1: "Common.controller.Registration", key2: "Registration", value: "Registratie"},
        {key1: "Common.controller.Registration", key2: "Registration Failed", value: "Registratie is mislukt"},
        {key1: "Common.controller.Registration", key2: "The device registration service is not available. The Mobile services may not be enabled in the Web Central.", value: "De service voor apparaatregistratie is niet beschikbaar. De Mobiel-services zijn mogelijk niet ingeschakeld in Web Central."},
        {key1: "Common.data.ModelGenerator", key2: "Model with name [{0}] does not exist.", value: "Model met de naam [{0}] bestaat niet."},
        {key1: "Common.device.Barcode", key2: "Barcode scanning is not available", value: "Scannen van barcodes is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Permission to Access Location Information Denied", value: "Toestemming voor toegang tot locatiegegevens geweigerd"},
        {key1: "Common.device.Location", key2: "Position is not available", value: "Positie is niet beschikbaar"},
        {key1: "Common.device.Location", key2: "Position Timeout", value: "Time-out voor positie"},
        {key1: "Common.device.Location", key2: "Unknown Postion Error", value: "Fout onbekende positie"},
        {key1: "Common.document.DocumentManager", key2: "An error occured while displaying the document", value: "Er is een fout opgetreden tijdens het weergeven van het document"},
        {key1: "Common.document.DocumentManager", key2: "Document Display", value: "Documentweergave"},
        {key1: "Common.document.DocumentManager", key2: "Downloading Document", value: "Document downloaden"},
        {key1: "Common.document.DocumentManager", key2: "Feature not available in the desktop environment.", value: "Functie niet beschikbaar in de desktopomgeving."},
        {key1: "Common.document.DocumentManager", key2: "File does not exist", value: "Bestand bestaat niet"},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed on this device.", value: "Bestand {0} kan niet op dit apparaat worden weergegeven."},
        {key1: "Common.document.DocumentManager", key2: "File {0} cannot be displayed when in Desktop mode.", value: "Bestand {0} kan niet worden weergegeven in de Desktop-modus."},
        {key1: "Common.document.DocumentManager", key2: "Removing Document", value: "Document verwijderen"},
        {key1: "Common.form.FormPanel", key2: "Field Changed field: {0} newValue: {1} oldValue: {2}", value: "Veld met de naam Veld gewijzigd: {0} newValue: {1} oldValue: {2}"},
        {key1: "Common.form.FormPanel", key2: "Input", value: "Invoer"},
        {key1: "Common.form.FormPanel", key2: "Input for field {0} is limited to {1} characters", value: "Invoer voor veld {0} is beperkt tot {1} tekens"},
        {key1: "Common.lang.LocalizedStrings", key2: "Cancel", value: "Annuleren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Clear", value: "Wissen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Copy", value: "Kopiëren"},
        {key1: "Common.lang.LocalizedStrings", key2: "Done", value: "Gereed"},
        {key1: "Common.lang.LocalizedStrings", key2: "Error", value: "Fout"},
        {key1: "Common.lang.LocalizedStrings", key2: "No", value: "Nee"},
        {key1: "Common.lang.LocalizedStrings", key2: "Paste", value: "Plakken"},
        {key1: "Common.lang.LocalizedStrings", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Name", value: "Ruimtenaam"},
        {key1: "Common.lang.LocalizedStrings", key2: "Room Names", value: "Ruimtenamen"},
        {key1: "Common.lang.LocalizedStrings", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Common.lang.LocalizedStrings", key2: "Survey", value: "Survey"},
        {key1: "Common.lang.LocalizedStrings", key2: "Yes", value: "Ja"},
        {key1: "Common.plugin.DataViewListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.DataViewListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.plugin.ListPaging", key2: "Load More...", value: "Meer laden..."},
        {key1: "Common.plugin.ListPaging", key2: "No More Records", value: "Geen records meer"},
        {key1: "Common.scripts.ApplicationLoader", key2: "This application has been updated to the latest version. Reloading the application.", value: "Deze toepassing is bijgewerkt naar de laatste versie. De toepassing wordt opnieuw geladen."},
        {key1: "Common.scripts.ScriptManager", key2: "Error loading network services. The network connection may be slow or unavailable", value: "Fout bij laden van netwerkservices. De netwerkverbinding kan traag of niet beschikbaar zijn"},
        {key1: "Common.service.ExceptionTranslator", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.service.ExceptionTranslator", key2: "No data received from server", value: "Geen gegevens ontvangen van server"},
        {key1: "Common.service.ExceptionTranslator", key2: "Timeout", value: "Time-out"},
        {key1: "Common.service.ExceptionTranslator", key2: "Unknown Error", value: "Onbekende fout"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error Registering Device", value: "Fout bij registreren van apparaat"},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error retrieving User information.", value: "Fout tijdens ophalen van gebruikersinformatie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error setting Session Locale.", value: "Fout tijdens instellen van landinstellingen voor sessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Error starting User Session.", value: "Fout tijdens opstarten van gebruikerssessie."},
        {key1: "Common.service.MobileSecurityServiceAdapter", key2: "Single Sign On Error", value: "Fout bij eenmalige aanmelding"},
        {key1: "Common.service.MobileSyncServiceAdapter", key2: "Error retrieving TableDef.", value: "Fout bij ophalen van TableDef."},
        {key1: "Common.service.Session", key2: "Device is not registered.", value: "Apparaat is niet geregistreerd"},
        {key1: "Common.service.workflow.JsonUtil", key2: "Workflow toJSON. Date objects are not permitted to be marshalled using Workflow Rules.", value: "Werkstroom toJSON. Datumobjecten mogen niet worden gerangschikt aan de hand van Werkstroomregels."},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow Rule Executed", value: "Werkstroomregel uitgevoerd"},
        {key1: "Common.service.workflow.Workflow", key2: "Workflow rule failed:", value: "Werkstroomregel mislukt:"},
        {key1: "Common.store.AppPreferences", key2: "App Preferences", value: "App-voorkeuren"},
        {key1: "Common.store.Buildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "Common.store.Causes", key2: "Cause Types", value: "Types oorzaken"},
        {key1: "Common.store.Contacts", key2: "Contacts", value: "Contactpersonen"},
        {key1: "Common.store.Craftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Common.store.Departments", key2: "Departments", value: "Afdelingen"},
        {key1: "Common.store.Divisions", key2: "Divisions", value: "Divisies"},
        {key1: "Common.store.Employees", key2: "Employees", value: "Medewerkers"},
        {key1: "Common.store.EmployeeStandards", key2: "Employee Standards", value: "Personeelsstandaarden"},
        {key1: "Common.store.Equipments", key2: "Equipment", value: "Uitrusting"},
        {key1: "Common.store.EquipmentStandards", key2: "Equipment Standards", value: "Uitrustingsstandaarden"},
        {key1: "Common.store.Floors", key2: "Floors", value: "Verdiepingen"},
        {key1: "Common.store.IncidentInjuryAreas", key2: "Injury Areas", value: "Letsels"},
        {key1: "Common.store.IncidentInjuryCategories", key2: "Injury Categories", value: "Letselcategorieën"},
        {key1: "Common.store.IncidentTypes", key2: "Incident Types", value: "Incidenttypen"},
        {key1: "Common.store.PlanTypeGroups", key2: "Plan Type Groups", value: "Plantype Groepen"},
        {key1: "Common.store.PlanTypes", key2: "Plan Types", value: "Plantypen"},
        {key1: "Common.store.ProblemTypes", key2: "Problem Types", value: "Type problemen"},
        {key1: "Common.store.Projects", key2: "Projects", value: "Projecten"},
        {key1: "Common.store.Properties", key2: "Properties", value: "Eigenschappen"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Database error:", value: "Databasefout:"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No database table change applied. [{0}]", value: "Geen wijziging aan databasetabel toegepast. [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "No default value update for field: [{0}]", value: "Standaardwaarde niet bijgewerkt voor veld: [{0}]"},
        {key1: "Common.store.proxy.ChangeTableStructureOperation", key2: "Update default value: field [{0}]", value: "Standaardwaarde bijwerken: veld [{0}]"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error", value: "Fout Sqlite-proxy"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during create operation", value: "Fout Sqlite-proxy tijdens aanmaken"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during destroy operation", value: "Fout Sqlite-proxy tijdens vernietigen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during read operation", value: "Fout Sqlite-proxy tijdens lezen"},
        {key1: "Common.store.proxy.Sqlite", key2: "Sqlite Proxy error during update operation", value: "Fout Sqlite-proxy tijdens bijwerken"},
        {key1: "Common.store.proxy.SqliteConnectionManager", key2: "Error opening database: {0}", value: "Fout bij openen van database: {0}"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database Error [SqliteView]", value: "Databasefout [SqliteView]"},
        {key1: "Common.store.proxy.SqliteView", key2: "Database error in SqliteView proxy.", value: "Databasefout in SqliteView-proxy."},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support deleting records", value: "SqliteView is alleen-lezen; het verwijderen van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqliteView is read only and does not support updating records", value: "SqliteView is alleen-lezen; het bijwerken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "SqlliteView is read only and does not support creating records.", value: "SqliteView is alleen-lezen; het maken van records wordt niet ondersteund"},
        {key1: "Common.store.proxy.SqliteView", key2: "The database does not contain the required table definitions for Sqllite view {0}", value: "De database bevat niet de vereiste tabeldefinities voor Sqllite-weergave {0}"},
        {key1: "Common.store.RepairTypes", key2: "Repair Types", value: "Type reparaties"},
        {key1: "Common.store.RoomCategories", key2: "Room Categories", value: "Ruimtecategorieën"},
        {key1: "Common.store.Rooms", key2: "Rooms", value: "Ruimtes"},
        {key1: "Common.store.RoomStandards", key2: "Room Standards", value: "Ruimtestandaarden"},
        {key1: "Common.store.RoomTypes", key2: "Room Types", value: "Ruimte types"},
        {key1: "Common.store.RoomUses", key2: "Room Uses", value: "Ruimtefuncties"},
        {key1: "Common.store.Sites", key2: "Sites", value: "Sites"},
        {key1: "Common.store.sync.SchemaUpdaterStore", key2: "file_not_available", value: "bestand_niet_beschikbaar"},
        {key1: "Common.sycn.Manager", key2: "Syncing", value: "Synchroniseren"},
        {key1: "Common.sync.Manager", key2: "Downloading", value: "Downloaden"},
        {key1: "Common.sync.Manager", key2: "Error", value: "Fout"},
        {key1: "Common.type.Date", key2: "The input value cannot be converted to a Common.type.Date type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Date."},
        {key1: "Common.type.Integer", key2: "The input value cannot be converted to the Common.type.Integer type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Integer."},
        {key1: "Common.type.Time", key2: "The input value cannot be converted to a Common.type.Time type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Time."},
        {key1: "Common.type.Timestamp", key2: "The input value cannot be converted to a Common.type.Timestamp type.", value: "De invoerwaarde kan niet worden omgezet in het type Common.type.Timestamp."},
        {key1: "Common.util.ApplicationPreference", key2: "The Application Preferences have not been loaded", value: "De applicatievoorkeuren zijn niet geladen"},
        {key1: "Common.util.Environment", key2: "Running in Browser Mode. Filesystem access disabled", value: "Uitvoeren in browsermodus. Toegang tot bestandssysteem uitgeschakeld"},
        {key1: "Common.util.Environment", key2: "Running in Chrome or in WebView. Filesystem access enabled", value: "Uitvoeren in Chrome of in webweergave. Toegang tot bestandssysteem ingeschakeld"},
        {key1: "Common.util.FileManager", key2: "File access was aborted", value: "Toegang tot bestanden werd afgebroken"},
        {key1: "Common.util.FileManager", key2: "File already exists", value: "Bestand bestaat al"},
        {key1: "Common.util.FileManager", key2: "File encoding error", value: "Fout bij bestandscodering"},
        {key1: "Common.util.FileManager", key2: "File Error", value: "Bestandsfout"},
        {key1: "Common.util.FileManager", key2: "File is in an invalid state", value: "Bestand is in ongeldige toestand"},
        {key1: "Common.util.FileManager", key2: "File modification is not allowed", value: "Bestandswijziging is niet toegestaan"},
        {key1: "Common.util.FileManager", key2: "File quota exceeded", value: "Bestandsquotum is overschreden"},
        {key1: "Common.util.FileManager", key2: "File security error", value: "Fout bij bestandsbeveiliging"},
        {key1: "Common.util.FileManager", key2: "File type mismatch error", value: "Fout bij vergelijken bestandstype"},
        {key1: "Common.util.FileManager", key2: "File was not found", value: "Bestand is niet gevonden"},
        {key1: "Common.util.FileManager", key2: "File was not readable", value: "Bestand is niet leesbaar"},
        {key1: "Common.util.FileManager", key2: "Invalid file modification error", value: "Fout: ongeldige bestandswijziging"},
        {key1: "Common.util.Network", key2: "Network connection is not available", value: "Netwerkverbinding is niet beschikbaar"},
        {key1: "Common.util.Network", key2: "Network Unreachable", value: "Netwerk onbereikbaar"},
        {key1: "Common.util.SynchronizationManager", key2: "Downloading Background Data", value: "Basisgegevens downloaden"},
        {key1: "Common.util.SynchronizationManager", key2: "Error", value: "Fout"},
        {key1: "Common.util.Ui", key2: "The App Preferences store is not loaded. Cannot retrieve preferences", value: "Het toepassingsvoorkeurenarchief is niet geladen. Kan voorkeuren niet ophalen."},
        {key1: "Common.util.Units", key2: "ft", value: "ft"},
        {key1: "Common.util.Units", key2: "m", value: "L"},
        {key1: "Common.util.Units", key2: "sq ft", value: "sq ft"},
        {key1: "Common.util.Units", key2: "sq m", value: "vierkante meter"},
        {key1: "Common.util.UserProfile", key2: "The User Profile information is not available. Please Sync to retrieve the User Profile data.", value: "De gegevens van het gebruikersprofiel zijn niet beschikbaar. Synchroniseer om de gegevens van het gebruikersprofiel op te halen."},
        {key1: "Common.view.DocumentItem", key2: "Delete on Sync", value: "Verwijderen tijdens synchroniseren"},
        {key1: "Common.view.DocumentItem", key2: "Display", value: "Tonen"},
        {key1: "Common.view.DocumentList", key2: "Documents", value: "Documenten"},
        {key1: "Common.view.DocumentList", key2: "No documents available", value: "Geen documenten beschikbaar"},
        {key1: "Common.view.navigation.Carousel", key2: "{0} of {1}", value: "{0} of {1}"},
        {key1: "Common.view.navigation.CarouselIndicator", key2: "1 of x", value: "1 van x"},
        {key1: "Common.view.navigation.EditBase", key2: "The name of the Model class associated with this view must be supplied in the model property", value: "De naam van de Model-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de modeleigenschap"},
        {key1: "Common.view.navigation.EditBase", key2: "The store id of the Store class associated with this view must be supplied in the storeId property", value: "De opslag-id van de Opslag-klasse die aan deze weergave is gekoppeld, moet worden opgegeven in de storeId-eigenschap"},
        {key1: "Common.view.navigation.FilterForm", key2: "Clear", value: "Wissen"},
        {key1: "Common.view.navigation.FilterForm", key2: "Filter", value: "Filter"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Back", value: "Terug"},
        {key1: "Common.view.navigation.NavigationBar", key2: "Save", value: "Opslaan"},
        {key1: "Common.view.panel.SyncMessage", key2: "Field", value: "Veld"},
        {key1: "Common.view.panel.SyncMessage", key2: "Identifier", value: "Identifier"},
        {key1: "Common.view.panel.SyncMessage", key2: "Size (Bytes)", value: "Grootte (in bytes)"},
        {key1: "Common.view.panel.SyncMessage", key2: "Sync Messages", value: "Synchronisatieberichten"},
        {key1: "Common.view.panel.SyncMessage", key2: "Table", value: "Tabel"},
        {key1: "Common.view.Panel.SyncMessage", key2: "The following Web Central field values were not written to the client database because the data size exceeds the database limit", value: "De volgende Web Central-veldwaarden zijn niet naar de clientdatabase geschreven omdat de hoeveelheid gegevens de databaselimiet overschrijdt"},
        {key1: "Common.view.navigation.FilterForm", key2: "Set Filter", value: "Filter instellen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Assign the work request to you?", value: "De werkaanvraag aan u toewijzen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Cancel", value: "Annuleren"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Estimation", value: "Raming voltooien"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Complete Scheduling", value: "Planning voltooien"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete", value: "Verwijderen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Delete the craftsperson?", value: "De vakman verwijderen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate", value: "Schatting"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Estimate requests to more accurately budget, to schedule labor, and to reserve parts. You can change your estimates until you issue the request.<br/><br/>Complete the estimation of the work request?", value: "Aanvragen ramen voor nauwkeuriger begroten, plannen van werk en reserveren van onderdelen. U kunt uw schattingen wijzigen totdat u de aanvraag indient.<br/><br/>Wilt u de raming van de werkaanvraag afronden?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Forward", value: "Doorsturen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Map functionility can not run on Phone.", value: "Kaartfunctionaliteit is niet geschikt voor de telefoon."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Pending workflow step", value: "Werkstroomstap in behandeling"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please add your comments before rejecting the work request", value: "Voeg uw opmerkingen toe voordat de werkaanvraag wordt afgewezen."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Please complete the pending workflow step", value: "Rond de in behandeling zijnde werkstroomstap af"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Reject", value: "Afwijzen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Resume the work request to Issued?", value: "De werkaanvraag hervatten als Uitgegeven?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Return", value: "Terug"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Schedule requests to better plan and balance work for teams and craftspersons. You can change the schedule assignments until you issue the request.<br/><br/>Complete the scheduling of the work request?", value: "Plan aanvragen in om het werk beter te plannen en af te stemmen voor teams en vakmensen. U kunt de toewijzingen wijzigen totdat u de aanvraag indient.<br/><br/>Wilt u de planning van de werkaanvraag afronden?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Self Assign", value: "Zelftoewijzend"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Supervisor or Work Team Id must be completed before forwarding the request", value: "Teamleider of Werkteam-ID moeten worden ingevuld voordat de aanvraag wordt doorgestuurd"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The request will be automatically be sent back one step", value: "De aanvraag wordt automatisch één stap terug verzonden"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "The work request is already assigned to you", value: "De werkaanvraag is al aan u toegewezen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "There is another existing record with the same primary keys.", value: "Er is nog een record met dezelfde primaire sleutels."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action archives the request and prevents any further updates to it.<br/><br/>Close the work request?", value: "Met deze actie wordt de aanvraag gearchiveerd en kunnen er geen updates meer op worden toegepast.<br/><br/>De werkaanvraag sluiten?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Met deze actie wordt een aanvraag geannuleerd voordat met het werk is begonnen. Door een aanvraag te annuleren wordt de aanvraagwerkstroom beëindigd.<br/><br/>De werkaanvraag annuleren?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action issues the request to field personnel. Once you issue the request, it cannot be cancelled; it can be completed, put on hold, or stopped.<br/><br/>Issue the work request?", value: "Deze actie geeft de aanvraag door aan de medewerkers ter plaatse. Nadat de aanvraag is doorgegeven, kan deze niet meer worden geannuleerd; de aanvraag kan worden voltooid, in de wacht worden gezet of worden stopgezet.<br/><br/>De werkaanvraag indienen?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action marks the request as Completed. A Supervisor can update labor, parts, comments, and other work details until the request is Closed.<br/><br/>Complete the work request?", value: "Door deze actie wordt de aanvraag gemarkeerd als Voltooid. Een teamleider kan arbeid, onderdelen, opmerkingen en andere werkdetails bijwerken totdat de aanvraag wordt Gesloten.<br/><br/>De werkaanvraag voltooien?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action puts a request on hold while waiting for parts, the appropriate trade, or security access. You can stop or complete a request that is on hold.<br/><br/>Put on hold the work request?", value: "Door deze actie wordt een aanvraag in de wacht gezet terwijl op onderdelen, de juiste vakdiscipline of beveiligde toegang wordt gewacht. U kunt een wachtende aanvraag stoppen of voltooien.<br/><br/>De werkaanvraag in de wacht zetten?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "This action stops a request on which some work has already been performed and which may be billed. Stopping a request ends the request workflow.<br/><br/>Stop the work request?", value: "Met deze actie wordt een aanvraag stopgezet waarvoor al enig werk is verricht dat mogelijk kan worden gefactureerd. Door een aanvraag stop te zetten wordt de aanvraagwerkstroom beëindigd.<br/><br/>De werkaanvraag stopzetten?"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Two resource records of the same type can not be added for the same day.  Please edit the existing record to reflect the correct totals.", value: "Twee resourcerecords van hetzelfde type kunnen niet voor dezelfde dag worden toegevoegd.  Bewerk het bestaande record zodat de juiste totalen worden weergegeven."},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work Request", value: "Werkaanvraag"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work request assigned", value: "Werkaanvraag toegewezen"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You cannot select both Supervisor and Work Team Id before forwarding the request", value: "U kunt Teamleider en Werkteam-ID niet beide selecteren voordat u de aanvraag doorstuurt"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "You have changed the work request. Please sync before taking any further actions on it", value: "U hebt de werkaanvraag gewijzigd. Voer een synchronisatie uit voordat u hier verdere actie mee onderneemt"},
        {key1: "Maintenance.controller.manager.WorkRequestActionsMultiple", key2: "Please input the comments first", value: "Voer eerst de opmerkingen in"},
        {key1: "Maintenance.controller.manager.WorkRequestActions", key2: "Work requests assigned", value: "Werkaanvragen toegewezen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Other Cost", value: "Overige kosten toevoegen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Part", value: "Onderdeel toevoegen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Add Trade", value: "Vakdiscipline toevoegen"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Other Cost", value: "Overige kosten bewerken"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Part", value: "Onderdeel bewerken"},
        {key1: "Maintenance.controller.manager.WorkRequestListController", key2: "Edit Trade", value: "Vakdiscipline bewerken"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "All Work Request document fields are in use.<br>The photo cannot be attached to the Work Request", value: "Alle velden van het document Werkaanvragen zijn in gebruik.<br>De foto kan niet aan de werkaanvraag worden gekoppeld"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "Documents", value: "Documenten"},
        {key1: "Maintenance.controller.WorkRequestDocuments", key2: "This action will remove the document. Do you want to proceed?", value: "Met deze actie wordt het document verwijderd. Wilt u doorgaan?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Cancel", value: "Annuleren"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Complete", value: "Voltooien"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Craftsperson Labor", value: "Arbeidsuren vakman"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "One or more craftsperson entries are missing labor hours<br>Do you want to Complete the Work Request?", value: "In een of meer vermeldingen voor vakmensen ontbreken arbeidsuren<br>Wilt u de werkaanvraag voltooien?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Please input the comments first", value: "Voer eerst de opmerkingen in"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "Status", value: "Status"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "The Work Request status is Completed.<br>The status cannot be modified.", value: "De Werkaanvraag-status is Voltooid.<br>De status kan niet worden gewijzigd."},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action cancels a request before any work has begun. Canceling a request ends the request workflow.<br/><br/>Cancel the work request?", value: "Met deze actie wordt een aanvraag geannuleerd voordat met het werk is begonnen. Door een aanvraag te annuleren wordt de aanvraagwerkstroom beëindigd.<br/><br/>De werkaanvraag annuleren?"},
        {key1: "Maintenance.controller.WorkRequestForms", key2: "This action marks your assignment as Completed. Supervisors can update labor, parts, comments, and other work details until the request is Closed.<br>Complete your assignment?", value: "Met deze actie wordt uw toewijzing gemarkeerd als Voltooid. Supervisors kunnen arbeid, onderdelen, opmerkingen en andere werkdetails bijwerken totdat de aanvraag wordt gesloten.<br>Wilt u de toewijzing voltooien?"},
        {key1: "Maintenance.controller.FloorPlan", key2: "Locate Room", value: "Een ruimte zoeken"},
        {key1: "Maintenance.controller.FloorPlan", key2: "The work request is not assigned to a room and therefore cannot be located.", value: "De werkaanvraag is niet toegewezen aan een ruimte en kan daarom niet worden gelokaliseerd."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Craftsperson is required.", value: "Vakman is verplicht."},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "User Account", value: "Gebruikersaccount"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Validation", value: "Validatie"},
        {key1: "Maintenance.controller.WorkRequestNavigation", key2: "Your account does not have Craftsperson access. Submit Work Requests using the My Request tab.", value: "Uw account heeft geen Vakman-toegang. Dien werkaanvragen in via het tabblad Mijn aanvragen."},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Info", value: "Info"},
        {key1: "Maintenance.controller.WorkRequestSync", key2: "Updating Work Requests", value: "Bezig met bijwerken van werkaanvragen"},
        {key1: "Maintenance.model.manager.WorkRequestTool", key2: " {0} and {1} must be before {2} and {3}", value: "{0} en {1} moeten vallen voor {2} en {3}"},
        {key1: "Maintenance.model.PartStorageLocation", key2: "must be greater than 0.", value: "moet groter dan 0 zijn."},
        {key1: "Maintenance.model.WorkRequest", key2: " {0} is required", value: "{0} is vereist"},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be greater than or equal to 0.", value: "moet groter zijn dan of gelijk zijn aan 0."},
        {key1: "Maintenance.model.WorkRequestCost", key2: " must be less than or equal to 100,000,000.", value: "moet kleiner zijn dan of gelijk zijn aan 100.000.000."},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0} and {1} must be before {2} and {3}", value: "{0} en {1} moeten vallen voor {2} en {3}"},
        {key1: "Maintenance.model.WorkRequestCraftsperson", key2: " {0}, {1}, or {2} are required", value: "{0}, {1} of {2} zijn vereist"},
        {key1: "Maintenance.store.Accounts", key2: "Accounts", value: "Accounts"},
        {key1: "Maintenance.store.Buildings", key2: "Buildings", value: "Gebouwen"},
        {key1: "Maintenance.store.manager.Craftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.store.manager.CraftspersonWorkTeams", key2: "Craftsperson Work Teams", value: "Werkteams vakman"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Approved", value: "Goedgekeurd"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Completed", value: "Voltooid"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Issued", value: "Uitgegeven"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Requests", value: "Mijn aanvragen"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "My Work", value: "Mijn werk"},
        {key1: "Maintenance.store.manager.DropDownButtons", key2: "Requested", value: "Aangevraagd"},
        {key1: "Maintenance.store.manager.PartStorageLocations", key2: "Part Storage Locations", value: "Opslaglocaties voor onderdeel"},
        {key1: "Maintenance.store.manager.StorageLocations", key2: "Storage Locations", value: "Opslaglocaties"},
        {key1: "Maintenance.store.manager.Tools", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.store.manager.Trades", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve", value: "Goedkeuren"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Estimate", value: "Schatting goedkeuren"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Approve Schedule", value: "Planning goedkeuren"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Cancel", value: "Annuleren"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Close", value: "Sluiten"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Complete", value: "Voltooien"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Estimate", value: "Schatting"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Forward", value: "Doorsturen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Access", value: "Wacht op toegang"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Labor", value: "Wacht op vaklui"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Hold for Parts", value: "Wacht op onderdelen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Issue", value: "Uitgeven"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Link New", value: "Nieuwe koppelen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Resume To Issued", value: "Hervatten als Uitgegeven"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Return", value: "Terug"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Schedule", value: "Plannen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Self Assign", value: "Zelftoewijzend"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Stop", value: "Stoppen"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Update", value: "Bijwerken"},
        {key1: "Maintenance.store.manager.WorkRequestActions", key2: "Verify", value: "Verifiëren"},
        {key1: "Maintenance.store.manager.WorkRequestReferences", key2: "References", value: "Referenties"},
        {key1: "Maintenance.store.manager.WorkRequestTools", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.store.manager.WorkRequestTrades", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.store.OtherResources", key2: "Resources", value: "Resources"},
        {key1: "Maintenance.store.PmProcedures", key2: "PM Procedures", value: "PO-procedures"},
        {key1: "Maintenance.store.ProblemDescriptions", key2: "Problem Descriptions", value: "Probleemomschrijvingen"},
        {key1: "Maintenance.store.ProblemResolutions", key2: "Problem Resolutions", value: "Probleemoplossingen"},
        {key1: "Maintenance.store.WorkRequestCosts", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.store.WorkRequestCraftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.store.WorkRequestParts", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.store.WorkRequests", key2: "Due Today", value: "Moet vandaag"},
        {key1: "Maintenance.store.WorkRequests", key2: "On Hold", value: "In de wacht"},
        {key1: "Maintenance.store.WorkRequests", key2: "Other", value: "Andere"},
        {key1: "Maintenance.store.WorkRequests", key2: "Overdue", value: "Achterstallig"},
        {key1: "Maintenance.store.WorkRequests", key2: "Pending", value: "In behandeling"},
        {key1: "Maintenance.store.WorkRequests", key2: "Work Request", value: "Werkaanvraag"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Approved", value: "Goedgekeurd"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Completed", value: "Voltooid"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Issued", value: "Uitgegeven"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Requests", value: "Mijn aanvragen"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "My Work", value: "Mijn werk"},
        {key1: "Maintenance.util.WorkRequestListUtil", key2: "Requested", value: "Aangevraagd"},
        {key1: "Maintenance.view.FloorPlan", key2: "Floor Plans", value: "Verdiepingsplattegronden"},
        {key1: "Maintenance.view.FloorPlan", key2: "Site", value: "Site"},
        {key1: "Maintenance.view.Main", key2: "Add Purchased Parts", value: "Aangekochte onderdelen toevoegen"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Building Code:", value: "Gebouw:"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Code", value: "Onderdeelcode"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Part Storage Locations", value: "Opslaglocaties voor onderdeel"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Quantity Available", value: "Beschikbare aantal"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Code", value: "Code opslaglocatie"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Storage Location Name", value: "Naam opslaglocatie"},
        {key1: "Maintenance.view.manager.AddPartMap", key2: "Work Request Code", value: "Werkaanvraagcode"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account", value: "Account"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Account Code", value: "Accountnummer"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Add Purchased Parts to Inventory", value: "Aangekochte onderdelen toevoegen aan inventaris"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part", value: "Onderdeel"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Part Code", value: "Onderdeelcode"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Price", value: "Prijs"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Quantity (each)", value: "Aantal (elk)"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location", value: "Opslaglocatie"},
        {key1: "Maintenance.view.manager.AddPurchasedPartsToInventory", key2: "Storage Location Code", value: "Code opslaglocatie"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve", value: "Goedkeuren"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Request", value: "Aanvraag goedkeuren"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Cancel", value: "Annuleren"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Documents", value: "Documenten"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "References", value: "Referenties"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Reject", value: "Afwijzen"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Approve", value: "Goedkeuren"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.ApproveFormMultiple", key2: "Reject", value: "Afwijzen"},
        {key1: "Maintenance.view.manager.ApproveForm", key2: "Approve Requests", value: "Aanvragen goedkeuren"},
        {key1: "Maintenance.view.manager.EstimateApproveForm", key2: "Approve Request Estimation", value: "Aanvraagschatting goedkeuren"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Documents", value: "Documenten"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "References", value: "Referenties"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Complete Estimation", value: "Raming voltooien"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Estimate", value: "Schatting"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Actual Cost", value: "Werkelijke kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Add Other Cost", value: "Overige kosten toevoegen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Labor", value: "Kosten van arbeid"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Cost of Parts", value: "Kosten van onderdelen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Estimated Cost", value: "Geraamde kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Costs", value: "Overige kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Description", value: "Omschrijving van overige middelen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Other Resource Type", value: "Overige soort middelen"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Quantity Used", value: "Aantal gebruikt"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Actual Costs", value: "Samenvatting Werkelijke kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Summary of Estimated Costs", value: "Samenvatting van geraamde kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Total Cost", value: "Totale kosten"},
        {key1: "Maintenance.view.manager.EstimateFormCosts", key2: "Units", value: "Eenheden"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Complete Estimation", value: "Raming voltooien"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Estimate", value: "Schatting"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Requests to Estimate", value: "Aanvragen voor schattingen"},
        {key1: "Maintenance.view.manager.EstimateFormMultiple", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Part", value: "Onderdeel toevoegen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Add Purchased Parts", value: "Aangekochte onderdelen toevoegen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part", value: "Onderdeel"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Part Code", value: "Onderdeelcode"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Available", value: "Beschikbare aantal"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Estimated", value: "Geraamde hoeveelheid"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Quantity Used", value: "Aantal gebruikt"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Code", value: "Code opslaglocatie"},
        {key1: "Maintenance.view.manager.EstimateFormParts", key2: "Storage Location Name", value: "Naam opslaglocatie"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Email", value: "E-mail"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Employee Code", value: "Personeelscode"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Forward", value: "Doorsturen"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Supervisor", value: "Teamleider"},
        {key1: "Maintenance.view.manager.ForwardForm", key2: "Work Team Code", value: "Werkteam code"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Forward", value: "Doorsturen"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Requests to Forward", value: "Aanvragen voor doorsturen"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Supervisor", value: "Teamleider"},
        {key1: "Maintenance.view.manager.ForwardFormMultiple", key2: "Work Team Code", value: "Werkteam code"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Completer", value: "Voltooier"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Estimator", value: "Taxateur"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Issuer", value: "Uitgever"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject", value: "Afwijzen"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Reject Request", value: "Aanvraag afwijzen"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Requestor", value: "Aanvrager"},
        {key1: "Maintenance.view.manager.RejectOptionForm", key2: "Scheduler", value: "Planner"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Approver's Comments", value: "Opmerkingen van goedkeurder"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Building", value: "Gebouw"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Craftsperson Notes", value: "Opmerkingen van vakman"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Date Requested", value: "Datum aangevraagd"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Equipment Code", value: "Uitrusting"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Floor", value: "Verdieping"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Priority", value: "Prioriteit"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Location", value: "Probleem locatie"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Problem Type", value: "Type probleem"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Related Requests", value: "Gerelateerde aanvragen"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Requestor", value: "Aanvrager"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Room", value: "Ruimte"},
        {key1: "Maintenance.view.manager.RequestDetails", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return", value: "Terug"},
        {key1: "Maintenance.view.manager.ReturnCfForm", key2: "Return Work Request", value: "Werkaanvraag terugsturen"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Requests to Forward", value: "Aanvragen voor doorsturen"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return", value: "Terug"},
        {key1: "Maintenance.view.manager.ReturnCfFormMultiple", key2: "Return Work Request", value: "Werkaanvraag terugsturen"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Approved", value: "Goedgekeurd"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "by", value: "per"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Completed", value: "Voltooid"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Access", value: "Wacht op toegang"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Labor", value: "Wacht op vaklui"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Hold for Parts", value: "Wacht op onderdelen"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Issued", value: "Uitgegeven"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Rejected", value: "Afgekeurd"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Requested", value: "Aangevraagd"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return", value: "Terug"},
        {key1: "Maintenance.view.manager.ReturnOptionForm", key2: "Return Work Request", value: "Werkaanvraag terugsturen"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.EstimateForm", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.manager.ScheduleApproveForm", key2: "Approve Request Schedule", value: "Aanvraagplanning goedkeuren"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Add Trade", value: "Vakdiscipline toevoegen"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Estimated Hours", value: "Geraamde uren"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Hours", value: "Uren"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade", value: "Vakdiscipline"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Code", value: "Code van vakdiscipline"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trade Description", value: "Omschrijving van vakdiscipline"},
        {key1: "Maintenance.view.manager.ScheduleEstimateFormTrades", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Complete Scheduling", value: "Planning voltooien"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Documents", value: "Documenten"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Forward", value: "Doorsturen"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "References", value: "Referenties"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Schedule", value: "Plannen"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.manager.ScheduleForm", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Actual Hours", value: "Werkelijke uren"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Assign Craftsperson", value: "Vakman toewijzen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Copy", value: "Kopiëren"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson", value: "Vakman"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftsperson Code", value: "Code van vakman"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Finished", value: "Datum gereed"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Scheduled", value: "Datum gepland"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Date Started", value: "Datum begonnen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Doubletime Hours", value: "Uren dubbel uurtarief"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Overtime Hours", value: "150% Uurtarief uren"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Primary Trade", value: "Primaire vakdiscipline"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Scheduled Hours", value: "Geplande uren"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Start", value: "Start"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Stop", value: "Stoppen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Finished", value: "Tijdstip gereed"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Scheduled", value: "Geplande tijd"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Time Started", value: "Tijd begonnen"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Work Type", value: "Type werk"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Complete Scheduling", value: "Planning voltooien"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Forward", value: "Doorsturen"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Requests to Schedule", value: "Aanvragen voor plannen"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Schedule", value: "Plannen"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.manager.ScheduleFormMultiple", key2: "Trades", value: "Vakdisciplines"},
        {key1: "Maintenance.view.manager.ScheduleFormCraftspersons", key2: "Straight Time Hours Used", value: "100% Uurtarief uren gebruikt"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Assign Tool", value: "Gereedschap toewijzen"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Building Code", value: "Gebouwcode"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Finished", value: "Datum gereed"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Scheduled", value: "Datum gepland"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Date Started", value: "Datum begonnen"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Hours", value: "Uren"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Scheduled Hours", value: "Geplande uren"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Start", value: "Start"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Stop", value: "Stoppen"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Finished", value: "Tijdstip gereed"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Scheduled", value: "Geplande tijd"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Time Started", value: "Tijd begonnen"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool", value: "Gereedschap"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Code", value: "Gereedschapcode"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tool Type", value: "Types gereedschap"},
        {key1: "Maintenance.view.manager.ScheduleFormTools", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Complete", value: "Voltooien"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Mark only my assignment as Completed.", value: "Markeer alleen mijn toewijzing als Voltooid."},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Return Work Request", value: "Werkaanvraag terugsturen"},
        {key1: "Maintenance.view.manager.SupervisorCompleteOptions", key2: "Set all craftsperson assignments as Completed", value: "Stel alle toewijzingen voor vakmensen in op Voltooid"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Documents", value: "Documenten"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "References", value: "Referenties"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Update", value: "Bijwerken"},
        {key1: "Maintenance.view.manager.UpdateForm", key2: "Work Request Details", value: "Details werkaanvraag"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Update", value: "Aanvragen voor bijwerken"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Update", value: "Bijwerken"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Confirm", value: "Bevestig"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Return Incomplete", value: "Als niet compleet retourneren"},
        {key1: "Maintenance.view.manager.VerifyForm", key2: "Verify", value: "Verifiëren"},
        {key1: "Maintenance.view.manager.UpdateFormMultiple", key2: "Requests to Verify", value: "Te verifiëren aanvragen"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Confirm", value: "Bevestig"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Return Incomplete", value: "Als niet compleet retourneren"},
        {key1: "Maintenance.view.manager.VerifyFormMultiple", key2: "Verify", value: "Verifiëren"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "1", value: "1"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Nearing Escalation", value: "10 dichtst bij escalatie"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Newest Requests", value: "10 nieuwste verzoeken"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "10 Oldest Requests", value: "10 oudste aanvragen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "2", value: "2"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "3", value: "3"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "4", value: "4"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "5", value: "5"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "All", value: "Alle"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Any", value: "Willekeurig"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Both", value: "Beide"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftsperson", value: "Vakman"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested From", value: "Datum aanvraag vanaf"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date Requested To", value: "Datum aanvraag tot"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform From", value: "Datum van uitvoering vanaf"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Date To Perform To", value: "Datum van uitvoering tot"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Equipment", value: "Uitrusting"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated", value: "geëscaleerd"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Escalated ?", value: "Geëscaleerd?"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Approved Requests", value: "Mijn goedgekeurde aanvragen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "My Requests", value: "Mijn aanvragen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "On Demand", value: "Correctief onderhoud"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Part", value: "Onderdeel"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "PM", value: "PO"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Priority", value: "Prioriteit"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Problem Type", value: "Type probleem"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requestor", value: "Aanvrager"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Requests Requiring my Approval", value: "Aanvragen waarvoor mijn goedkeuring is vereist"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Set Filter", value: "Filter instellen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Show", value: "Tonen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Unassigned Requests", value: "Niet-toegewezen aanvragen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Request", value: "Werkaanvraag"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Requests", value: "Werkaanvragen"},
        {key1: "Maintenance.view.manager.WorkRequestFilter", key2: "Work Type", value: "Type werk"},
        {key1: "Maintenance.view.manager.WorkRequestManagerList", key2: "REQUESTED", value: "Aangevraagd"},
        {key1: "Maintenance.view.manager.WorkRequestManagerListItem", key2: "Assigned To:", value: "Toegewezen aan:"},
        {key1: "Maintenance.view.manager.WorkRequestSelection", key2: "Requests to Schedule", value: "Aanvragen voor plannen"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Hours", value: "Uren"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Job Setup or Prep.", value: "Opstelling of voorb. taak"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Material Pickup", value: "Ophalen van materiaal"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Travel Time", value: "Reistijd"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "UnSpecified", value: "Niet gespecificeerd"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Client", value: "Wacht op cliënt"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Wait for Security", value: "Wacht op bewakingsdienst"},
        {key1: "Maintenance.view.manager.WRCraftspersonListItem", key2: "Work", value: "Werkzaamheid"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "No Status Change", value: "Geen statuswijziging"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Access", value: "Wacht op toegang"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold for Labor", value: "Wacht op vaklui"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "On Hold For Parts", value: "Wacht op onderdelen"},
        {key1: "Maintenance.view.overlay.HoldAction", key2: "Resume To Issued", value: "Hervatten als Uitgegeven"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Actual Hours", value: "Werkelijke uren"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Cancel", value: "Annuleren"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Doubletime Hours", value: "Uren dubbel uurtarief"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Overtime Hours", value: "150% Uurtarief uren"},
        {key1: "Maintenance.view.overlay.QuickComplete", key2: "Save", value: "Opslaan"},
        {key1: "Maintenance.view.phone.Main", key2: "Apps", value: "Apps"},
        {key1: "Maintenance.view.phone.QuickComplete", key2: "Complete Request", value: "Aanvraag voltooien"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cancel", value: "Annuleren"},
        {key1: "Maintenance.view.SiteMap", key2: "Buildings", value: "Gebouwen"},
        {key1: "Maintenance.view.tablet.Main", key2: "Apps", value: "Apps"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Actual Cost", value: "Werkelijke kosten"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Add Cost", value: "Kosten toevoegen"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Date Used", value: "Datum gebruikt"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Edit Cost", value: "Kosten bewerken"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Quantity Used", value: "Aantal gebruikt"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Resource Type", value: "Type resource"},
        {key1: "Maintenance.view.WorkRequestCostEdit", key2: "Units", value: "Eenheden"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Cost:", value: "Kosten:"},
        {key1: "Maintenance.view.WorkRequestCostList", key2: "Other Costs", value: "Overige kosten"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Actual Hours", value: "Werkelijke uren"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Add Craftsperson", value: "Vakman toevoegen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Craftsperson", value: "Vakman"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Finished", value: "Datum gereed"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Date Started", value: "Datum begonnen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Doubletime Hours", value: "Uren dubbel uurtarief"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Edit Craftsperson", value: "Vakman bewerken"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Overtime Hours", value: "150% Uurtarief uren"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Start", value: "Start"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Stop", value: "Stoppen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Finished", value: "Tijdstip gereed"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Time Started", value: "Tijd begonnen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonEdit", key2: "Work Type", value: "Type werk"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.WorkRequestCraftspersonList", key2: "Hours", value: "Uren"},
        {key1: "Maintenance.view.manager.WorkRequestEdit", key2: "References", value: "Referenties"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Assigned Date", value: "Datum toegewezen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Cause Type", value: "Type oorzaak"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Code", value: "Code"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Costs", value: "Kosten"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftsperson Notes", value: "Opmerkingen van vakman"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Craftspersons", value: "Vaklui"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Related Work Request", value: "Gerelateerde werkaanvraag aanmaken"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Create Work Request", value: "Werkaanvraag aanmaken"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Description", value: "Omschrijving"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Documents", value: "Documenten"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 1", value: "Foto 1"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 2", value: "Foto 2"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 3", value: "Foto 3"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Photo 4", value: "Foto 4"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "PM Procedure", value: "PO-procedure"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Description", value: "Omschrijving van probleem"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Location", value: "Probleem locatie"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Problem Type", value: "Type probleem"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Repair Type", value: "Type reparatie"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested", value: "Aangevraagd"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Requested By", value: "Aangevraagd door"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Scheduled Date", value: "geplande datum"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Tools", value: "Gereedschappen"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Update", value: "Bijwerken"},
        {key1: "Maintenance.view.WorkRequestEdit", key2: "Work Request Details", value: "Details werkaanvraag"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Escalation", value: "Escalatie"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Loading...", value: "Bezig met laden..."},
        {key1: "Maintenance.view.WorkRequestList", key2: "Location", value: "Locatie"},
        {key1: "Maintenance.view.WorkRequestList", key2: "My Work", value: "Mijn werk"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Problem Type", value: "Type probleem"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search", value: "Zoeken"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Search Work Requests", value: "In werkaanvragen zoeken"},
        {key1: "Maintenance.view.WorkRequestList", key2: "Status", value: "Status"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Add Part", value: "Onderdeel toevoegen"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Assigned", value: "toegewezen"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Comments", value: "Opmerkingen"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Edit Part", value: "Onderdeel bewerken"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Part", value: "Onderdeel"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.WorkRequestPartEdit", key2: "Quantity", value: "Aantal"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Parts", value: "Onderdelen"},
        {key1: "Maintenance.view.WorkRequestPartList", key2: "Quantity", value: "Aantal"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "OpenURL", value: "URL openen"},
        {key1: "Maintenance.view.WorkRequestReferenceListsItems", key2: "URL does not exsits", value: "URL bestaat niet"},
        {key1: "Maintenance.view.WorkRequestReferencesLists", key2: "References", value: "Referenties"},
        {key1: "Floorplan.component.Legend", key2: "Are you sure you want to delete this object?", value: "Weet u zeker dat u dit object wilt verwijderen?"},
        {key1: "Floorplan.component.Legend", key2: "Please enter the text box content:", value: "Voer de inhoud voor het tekstvak in:"},
        {key1: "Floorplan.component.Svg", key2: "Floor Plan is not available", value: "Plattegrond is niet beschikbaar"},
        {key1: "Floorplan.control.Legend", key2: "Copy", value: "Kopiëren"},
        {key1: "Floorplan.control.Legend", key2: "Paste", value: "Plakken"},
        {key1: "Floorplan.control.Legend", key2: "Reload", value: "Opnieuw laden"},
        {key1: "Floorplan.control.Legend", key2: "Save Image", value: "Afbeelding opslaan"},
        {key1: "Floorplan.controller.Marker", key2: "Are you sure you want to delete this item?", value: "Weet u zeker dat u dit item wilt verwijderen?"},
        {key1: "Floorplan.controller.Marker", key2: "Edit", value: "Bewerken"},
        {key1: "Floorplan.controller.Redline", key2: "There is no Floor Plan available to Redline", value: "Er is geen verdiepingplattegrond beschikbaar voor Rode lijn"},
        {key1: "Floorplan.store.PublishDates", key2: "Publish Dates", value: "Datums publiceren"},
        {key1: "Floorplan.store.SiteDrawings", key2: "Site Maps", value: "Locatieplattegronden"},
        {key1: "Floorplan.view.FloorPlan", key2: "Floor Plan", value: "Verdiepingplattegrond"},
        {key1: "Floorplan.view.Redline", key2: "Redline", value: "Rode lijn"},
        {key1: "Common.store.Buildings", key2: "Building Codes", value: "Gebouwcodes"},
    ]
};
