BEGIN EXECUTE IMMEDIATE 'DROP INDEX RM_TEAM_DATE_START_DATE_END'; EXCEPTION WHEN OTHERS THEN null; END;;
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX rm_team_date_start_date_end ON rm_team(date_start, date_end)'; EXCEPTION WHEN OTHERS THEN null; END;;
BEGIN EXECUTE IMMEDIATE 'DROP INDEX TEAM_DATE_START_DATE_END'; EXCEPTION WHEN OTHERS THEN null; END;;
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX team_date_start_date_end ON team(date_start, date_end)'; EXCEPTION WHEN OTHERS THEN null; END;;
