IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'gpc' AND type = 'V') DROP VIEW gpc

CREATE VIEW gpc AS SELECT gp.gp_id AS gp_id, fl.fl_id AS fl_id, bl.bl_id AS bl_id, site.site_id AS site_id, ( gp.area * fl.area_fl_comn_gp /  IF fl.area_gp_dp = 0 THEN 9999999999 ELSE fl.area_gp_dp ENDIF ) AS flcomgp, ( gp.area * bl.area_bl_comn_gp /  IF bl.area_gp_dp = 0 THEN 9999999999 ELSE bl.area_gp_dp ENDIF ) AS blcomgp, ISNULL( ( gp.area * site.area_st_comn_gp /  IF site.area_gp_dp = 0 THEN 9999999999 ELSE site.area_gp_dp ENDIF ),0) AS stcomgp, ( gp.area * fl.area_fl_comn_serv /  IF fl.area_gp_dp = 0 THEN 9999999999 ELSE fl.area_gp_dp ENDIF ) AS flcomsrv, ( gp.area * bl.area_bl_comn_serv /  IF bl.area_gp_dp = 0 THEN 9999999999 ELSE bl.area_gp_dp ENDIF ) AS blcomsrv, ISNULL( ( gp.area * site.area_st_comn_serv /  IF site.area_gp_dp = 0 THEN 9999999999 ELSE site.area_gp_dp ENDIF ),0) AS stcomsrv FROM gp, fl, bl KEY LEFT OUTER JOIN site WHERE gp.dp_id IS NOT NULL AND gp.fl_id = fl.fl_id AND gp.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'rmc' AND type = 'V') DROP VIEW rmc;

CREATE VIEW rmc AS SELECT rm.rm_id AS rm_id, rm.fl_id AS fl_id, rm.bl_id AS bl_id, site.site_id AS site_id, ( rm.area * fl.area_fl_comn_rm /  IF fl.area_rm_dp = 0 THEN 9999999999 ELSE fl.area_rm_dp ENDIF ) AS flcomrm, ( rm.area * bl.area_bl_comn_rm /  IF bl.area_rm_dp = 0 THEN 9999999999 ELSE bl.area_rm_dp ENDIF ) AS blcomrm, ISNULL( ( rm.area * site.area_st_comn_rm /  IF site.area_rm_dp = 0 THEN 9999999999 ELSE site.area_rm_dp ENDIF ),0) AS stcomrm, ( rm.area * fl.area_fl_comn_serv /  IF fl.area_rm_dp = 0 THEN 9999999999 ELSE fl.area_rm_dp ENDIF ) AS flcomsrv, ( rm.area * bl.area_bl_comn_serv /  IF bl.area_rm_dp = 0 THEN 9999999999 ELSE bl.area_rm_dp ENDIF ) AS blcomsrv, ISNULL( ( rm.area * site.area_st_comn_serv /  IF site.area_rm_dp = 0 THEN 9999999999 ELSE site.area_rm_dp ENDIF ),0) AS stcomsrv FROM rm, fl, bl KEY LEFT OUTER JOIN site WHERE rm.dp_id IS NOT NULL AND rm.fl_id = fl.fl_id AND rm.bl_id = fl.bl_id AND rm.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'rmpctc' AND type = 'V') DROP VIEW rmpctc;

CREATE VIEW rmpctc AS SELECT rmpct.pct_id AS pct_id, rmpct.rm_id AS rm_id, fl.fl_id AS fl_id, bl.bl_id AS bl_id, site.site_id AS site_id, ( rmpct.area_rm * fl.area_fl_comn_rm /  IF fl.area_rm_dp = 0 THEN 9999999999 ELSE fl.area_rm_dp ENDIF ) AS flcomrm, ( rmpct.area_rm * bl.area_bl_comn_rm /  IF bl.area_rm_dp = 0 THEN 9999999999 ELSE bl.area_rm_dp ENDIF ) AS blcomrm, ISNULL((rmpct.area_rm * site.area_st_comn_rm /  IF site.area_rm_dp = 0 THEN 9999999999 ELSE site.area_rm_dp ENDIF ),0) AS stcomrm, ( rmpct.area_rm * fl.area_fl_comn_serv /  IF fl.area_rm_dp = 0 THEN 9999999999 ELSE fl.area_rm_dp ENDIF ) AS flcomsrv, ( rmpct.area_rm * bl.area_bl_comn_serv /  IF bl.area_rm_dp = 0 THEN 9999999999 ELSE bl.area_rm_dp ENDIF ) AS blcomsrv, ISNULL((rmpct.area_rm * site.area_st_comn_serv/ IF site.area_rm_dp = 0 THEN 9999999999 ELSE site.area_rm_dp ENDIF ),0) AS stcomsrv FROM rmpct, fl, bl KEY LEFT OUTER JOIN site WHERE rmpct.dp_id IS NOT NULL AND rmpct.fl_id = fl.fl_id AND rmpct.bl_id = fl.bl_id AND rmpct.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'alrmc' AND type = 'V') DROP VIEW alrmc;

CREATE VIEW alrmc AS SELECT rm.rm_id AS rm_id, rm.fl_id AS fl_id, rm.bl_id AS bl_id, site.site_id AS site_id, ( rm.area * fl.area_fl_comn_ocup /  IF fl.area_ocup_dp = 0 THEN 9999999999 ELSE fl.area_ocup_dp ENDIF ) AS flcomocup, ( rm.area * bl.area_bl_comn_ocup /  IF bl.area_ocup_dp = 0 THEN 9999999999 ELSE bl.area_ocup_dp ENDIF ) AS blcomocup, ISNULL( ( rm.area * site.area_st_comn_ocup /  IF site.area_ocup_dp = 0 THEN 9999999999 ELSE site.area_ocup_dp ENDIF ),0) AS stcomocup, ( rm.area * fl.area_fl_comn_nocup /  IF fl.area_ocup_dp = 0 THEN 9999999999 ELSE fl.area_ocup_dp ENDIF ) AS flcomnocup, ( rm.area * bl.area_bl_comn_nocup /  IF bl.area_ocup_dp = 0 THEN 9999999999 ELSE bl.area_ocup_dp ENDIF ) AS blcomnocup, ISNULL( ( rm.area * site.area_st_comn_nocup /  IF site.area_ocup_dp = 0 THEN 9999999999 ELSE site.area_ocup_dp ENDIF ),0) AS stcomnocup FROM rm, rmcat, fl, bl KEY LEFT OUTER JOIN site WHERE rm.dp_id IS NOT NULL AND rmcat.occupiable = 1 AND rm.rm_cat = rmcat.rm_cat AND rm.fl_id = fl.fl_id AND rm.bl_id = fl.bl_id AND rm.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'alrmpctc' AND type = 'V') DROP VIEW alrmpctc;

CREATE VIEW alrmpctc AS SELECT rmpct.pct_id AS pct_id, rmpct.rm_id AS rm_id, rmpct.fl_id AS fl_id, rmpct.bl_id AS bl_id, site.site_id AS site_id, ( rmpct.area_rm * fl.area_fl_comn_ocup /  IF fl.area_ocup_dp = 0 THEN 9999999999 ELSE fl.area_ocup_dp ENDIF ) AS flcomocup, ( rmpct.area_rm * bl.area_bl_comn_ocup /  IF bl.area_ocup_dp = 0 THEN 9999999999 ELSE bl.area_ocup_dp ENDIF ) AS blcomocup, ISNULL((rmpct.area_rm * site.area_st_comn_ocup/ IF site.area_ocup_dp = 0 THEN 9999999999 ELSE site.area_ocup_dp ENDIF ),0) AS stcomocup, ( rmpct.area_rm * fl.area_fl_comn_nocup /  IF fl.area_ocup_dp = 0 THEN 9999999999 ELSE fl.area_ocup_dp ENDIF ) AS flcomnocup, ( rmpct.area_rm * bl.area_bl_comn_nocup /  IF bl.area_ocup_dp = 0 THEN 9999999999 ELSE bl.area_ocup_dp ENDIF ) AS blcomnocup, ISNULL((rmpct.area_rm *site.area_st_comn_nocup/ IF site.area_ocup_dp = 0 THEN 9999999999 ELSE site.area_ocup_dp ENDIF ),0) AS stcomnocup FROM rmpct, rmcat, fl, bl KEY LEFT OUTER JOIN site WHERE rmpct.dp_id IS NOT NULL AND rmcat.occupiable = 1 AND rmpct.rm_cat = rmcat.rm_cat AND rmpct.fl_id = fl.fl_id AND rmpct.bl_id = fl.bl_id AND rmpct.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'emcic' AND type = 'V') DROP VIEW emcic;

CREATE VIEW emcic AS SELECT rm.rm_id AS rm_id, rm.fl_id AS fl_id, rm.bl_id AS bl_id, site.site_id AS site_id, ( rm.area * fl.area_fl_comn_rm /  IF fl.area_em_dp = 0 THEN 9999999999 ELSE fl.area_em_dp ENDIF ) AS flcomrm, ( rm.area * bl.area_bl_comn_rm /  IF bl.area_em_dp = 0 THEN 9999999999 ELSE bl.area_em_dp ENDIF ) AS blcomrm, ( rm.area * site.area_st_comn_rm /  IF site.area_em_dp = 0 THEN 9999999999 ELSE site.area_em_dp ENDIF ) AS stcomrm, ( rm.area * fl.area_fl_comn_serv /  IF fl.area_em_dp = 0 THEN 9999999999 ELSE fl.area_em_dp ENDIF ) AS flcomsrv, ( rm.area * bl.area_bl_comn_serv /  IF bl.area_em_dp = 0 THEN 9999999999 ELSE bl.area_em_dp ENDIF ) AS blcomsrv, ( rm.area * site.area_st_comn_serv /  IF site.area_em_dp = 0 THEN 9999999999 ELSE site.area_em_dp ENDIF ) AS stcomsrv FROM rm,fl,bl,site WHERE rm.count_em > 0 AND rm.fl_id = fl.fl_id AND rm.bl_id = fl.bl_id AND rm.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id AND bl.site_id = site.site_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'emarc' AND type = 'V') DROP VIEW emarc;

CREATE VIEW emarc AS SELECT rm.rm_id AS rm_id, rm.fl_id AS fl_id, rm.bl_id AS bl_id, site.site_id AS site_id, ( rm.area * fl.area_fl_comn_ocup /  IF fl.area_em_dp = 0 THEN 9999999999 ELSE fl.area_em_dp ENDIF ) AS flcomocup, ( rm.area * bl.area_bl_comn_ocup /  IF bl.area_em_dp = 0 THEN 9999999999 ELSE bl.area_em_dp ENDIF ) AS blcomocup, ( rm.area * site.area_st_comn_ocup /  IF site.area_em_dp = 0 THEN 9999999999 ELSE site.area_em_dp ENDIF ) AS stcomocup, ( rm.area * fl.area_fl_comn_nocup /  IF fl.area_em_dp = 0 THEN 9999999999 ELSE fl.area_em_dp ENDIF ) AS flcomnocup, ( rm.area * bl.area_bl_comn_nocup /  IF bl.area_em_dp = 0 THEN 9999999999 ELSE bl.area_em_dp ENDIF ) AS blcomnocup, ( rm.area * site.area_st_comn_nocup /  IF site.area_em_dp = 0 THEN 9999999999 ELSE site.area_em_dp ENDIF ) AS stcomnocup FROM rm,fl,bl,site WHERE rm.count_em > 0 AND rm.fl_id = fl.fl_id AND rm.bl_id = fl.bl_id AND rm.bl_id = bl.bl_id AND fl.bl_id = bl.bl_id AND bl.site_id = site.site_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'rmpctbdd' AND type = 'V') DROP VIEW rmpctbdd;

CREATE VIEW rmpctbdd AS SELECT DISTINCT site_id,rmpct.bl_id,rmpct.fl_id,rmpct.rm_id,rmpct.dv_id,rmpct.dp_id,rm_std FROM rmpct,rm,bl WHERE rmpct.bl_id = bl.bl_id AND rmpct.bl_id = rm.bl_id AND rmpct.fl_id = rm.fl_id AND rmpct.rm_id = rm.rm_id;

IF EXISTS (SELECT 1 FROM sysobjects WHERE name = 'rmpcttc' AND type = 'V') DROP VIEW rmpcttc;

CREATE VIEW rmpcttc AS SELECT DISTINCT site_id,rmpct.bl_id,fl_id,rm_id,rm_cat,rm_type  FROM rmpct,bl WHERE rmpct.bl_id = bl.bl_id;